open-telemetry/opentelemetry-java

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractDoubleAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractLongAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrument.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulator.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
The code already existed as part of the instrument, but it was extracted in a separate concept,
and all Sync/Async instruments look very similar: Descriptor + Accumulator.
I will work to improve the initialization story in a followup PR, but current code is good enough to introduce the new concept.
> Introduce accumulator concept

- sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
To better see the effect of proposed changes
> Some example of possible SDK configuration

- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorMultipleHeaders.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorSingleHeader.java
> Make imports consistent with other files in this package.

- api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java
> Small nit in internal members order

- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/2270](https://github.com/open-telemetry/opentelemetry-java/issues/2270)
> Fix comment and remove import

- api/trace/src/main/java/io/opentelemetry/api/trace/attributes/SemanticAttributes.java
- buildscripts/semantic-convention/generate.sh
This release includes lots of new cassandra attributes.
> fix(semantic-attributes): update to dec 14 2020 master

- CHANGELOG.md
I fell behind by a week. So many changes!
> changelog updates for Dec 15 2020

- perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java
- sdk/all/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java
- sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java
- sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java
- sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdkBuilder.java
- sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/package-info.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/spi/MeterProviderFactorySdk.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterRegistryTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/spi/MeterProviderFactorySdkTest.java
> Consistent naming for metrics SDK implementations with trace

- exporters/jaeger-thrift/README.md
- exporters/jaeger/README.md
fix #2331  ref https://github.com/open-telemetry/opentelemetry-java/issues/2331#issuecomment-747217094
> fix jaeger exporter readme

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java
> Move SdkMeterProvider builder to top level

- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
> Fix flappy IntervalMetricReaderTest

- api/metrics/src/main/java/io/opentelemetry/api/metrics/AsynchronousInstrument.java
> Remove unnecessary interface

- api/common/src/main/java/io/opentelemetry/api/common/AttributeKeyImpl.java
Was trying my hand at an interface bridge for this in agent and found this.
/cc @trask
> Return interface from AttributeKeyImpl.create

- exporters/logging/build.gradle
- exporters/otlp/metrics/build.gradle
- exporters/otlp/trace/build.gradle
- exporters/prometheus/build.gradle
- opencensus-shim/build.gradle
- sdk-extensions/logging/build.gradle
- sdk-extensions/otproto/build.gradle
- sdk/all/build.gradle
- sdk/testing/build.gradle
> Remove dependency on metrics from sdk:all

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
> Simplify logic in AsynchronousInstrumentAccumulator

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/Aggregations.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/CountAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/LastValueAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/MetricDataUtils.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/MinMaxSumCountAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/SumAggregation.java
> Split different aggregations in their own files

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactory.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/CountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
This way the Accumulator will produce the right accumulations, for example in case of count. Added tests for all instrument types.
> Add ability to create accumulation to the Aggregator

- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/MetricInteroperabilityTest.java
I tried various invocations with `AggregationWindow.Interval` but could not get a summary to be exported. Since summaries are deprecated in OC anyways, I wonder if we can just remove their conversion code and consider them unsupported? Or if anyone can tell me how to add coverage for them would be nice.
> Add some metric types to ocshim tests

- CONTRIBUTING.md
> Add point to contributor document about preserving semantic versioning.

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/Aggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/CountAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/LastValueAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/MinMaxSumCountAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/SumAggregation.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/CountAggregationTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/LastValueAggregationTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/MinMaxSumCountAggregationTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/SumAggregationTest.java
> Make the toMetricsData to use generic map of labels to accumulations

- exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java
- exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
fixes [https://github.com/open-telemetry/opentelemetry-java/issues/2399](https://github.com/open-telemetry/opentelemetry-java/issues/2399)
Signed-off-by: dengliming <liming.d.pro@gmail.com>
> Fix parsing the exporter headers via environment variables

- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricsExporter.java
- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/MetricInteroperabilityTest.java
- perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java
- sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/MetricAdapter.java
- sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/DoubleLastValueAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/DoubleSumAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/ImmutableAggregationFactory.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/LongLastValueAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/LongSumAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/MetricDataUtils.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregation/MinMaxSumCountAggregation.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/LastValueAggregationTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregation/SumAggregationTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/data/MetricDataTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/2412
> Change MetricData to expose the Point type that is expected for each data type

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerManagement.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java
> Deprecate addSpanProcessor mutator

- api/context/src/strictContextEnabledTest/java/io/opentelemetry/context/StrictContextEnabledTest.java
- api/context/src/test/java/io/opentelemetry/context/ContextTest.java
- build.gradle
- exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporter.java
- exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporter.java
- exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporterTest.java
- exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporterTest.java
- exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java
- exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingMetricExporterTest.java
- exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingSpanExporterTest.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/context/StrictContextStorageTest.java
Been looking for this and finally found it!
> Use logunit instead of tedious jul handler modifications for testing

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerTest.java
> Have a default span name in case instrumentation sends in a blank/empty/null name

- sdk-extensions/build.gradle
Had just forgotten for this folder
> Set archiveBaseName pattern for sdk-extensions too

- build.gradle
- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterBuilder.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java
- exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
- exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java
- sdk-extensions/async-processor/src/main/java/io/opentelemetry/sdk/extension/trace/export/DisruptorAsyncSpanProcessor.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessor.java
- sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanProcessor.java
- sdk/common/src/main/java/io/opentelemetry/sdk/common/export/ConfigBuilder.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/EnvAutodetectResource.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourcesConfig.java
- sdk/common/src/test/java/io/opentelemetry/sdk/common/export/ConfigBuilderTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfigBuilder.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorBuilder.java
Autoconfiguration now job of autoconfigure module
> Deprecate ConfigBuilder.

- exporters/prometheus/gradle.properties
> Mark prometheus exporter as alpha.

- proto/build.gradle
> Update proto library to v0.7.0

- opencensus-shim/gradle.properties
- opentracing-shim/gradle.properties
- sdk-extensions/async-processor/gradle.properties
- sdk-extensions/jfr-events/gradle.properties
- sdk-extensions/logging/gradle.properties
- sdk-extensions/tracing-incubator/gradle.properties
- sdk-extensions/zpages/gradle.properties
I got 2 more here that I don't think we should declare as stable for 1.0. Any others that people think we aren't ready to support forever yet?
> Mark a few more modules as alpha release status

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractDoubleAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractLongAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulatorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewRegistryTest.java
> Cleanup ViewRegistry, move processor creation to InstrumentProcessor

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderBuilder.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
> Extract IntervalMetricReaderBuilder as a top-level class

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractDoubleAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractLongAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulator.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulatorTest.java
> Some small fixes in the metrics

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractDoubleAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractLongAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactory.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/ImmutableAggregatorFactory.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulatorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactoryTest.java
> Pass the whole instrument descriptor to the Aggregator factory

- README.md
- build.gradle
- sdk-extensions/zpages/build.gradle
This updates the README to use boms as we recommend. It also updates the versions to properly have the alpha suffix where appropriate.
> Update the README

- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorMultipleHeaders.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorSingleHeader.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/StringUtils.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/StringUtilsTest.java
Found this presumably mistakenly public class.
> Deprecate trace-propagators StringUtils to make package private.

- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
- sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/SpanAdapter.java
- sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtils.java
- sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtilsTest.java
Realized we have this class we probably don't want to release as a stable artifact, at least for now.
> Deprecate TraceProtoUtils

- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
> Create SdkMeter via provider, simplifies initialization logic

- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
> Rename testSdk with sdkMeter to match the class name

- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
> Add tests for the default meter name

- perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterRegistryTest.java
> Implement MetricProducer directly by the SdkMeterProvider

- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/2489
> Avoid passing the time to collect by calling the producer public method

- api/context/build.gradle
- exporters/otlp/trace/build.gradle
- exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
autoconfigure ones I added in #2499
> Add test-sets tests to check which was forgotten.

- sdk-extensions/autoconfigure/build.gradle
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/testConfigError/java/io/opentelemetry/sdk/autoconfigure/ConfigErrorTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java
- sdk-extensions/autoconfigure/src/testJaeger/java/io/opentelemetry/sdk/autoconfigure/JaegerConfigTest.java
- sdk-extensions/autoconfigure/src/testZipkin/java/io/opentelemetry/sdk/autoconfigure/ZipkinConfigTest.java
> Update exporter environment variable to latest spec's singular forms.

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactory.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/CountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java
> Remove public from classes/methods that don't need to be

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java
> Remove deprecated methods from metrics

- .github/workflows/patch-release-build.yml
- README.md
- sdk-extensions/zpages/README.md
- sdk-extensions/zpages/build.gradle
and remove the readme updating step from the patch release action
> Update the READMEs for 0.14.1

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/CountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/MetricDataUtils.java
> Update metric data util in the aggregator, remove unnecessary helpers

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractDoubleAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractLongAsynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulator.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulatorTest.java
> Move InstrumentProcessor initialization in the Accumulator

- exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java
- exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
- exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/ExportTest.java
- exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/TlsExportTest.java
- exporters/otlp/trace/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/trace/TlsExportTest.java
- exporters/otlp/trace/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/trace/ExportTest.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
> Use endpoint scheme in OTLP exporters

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java
- exporters/jaeger/build.gradle
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
> Update the Jaeger exporters to properly use the service name from the Resource

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java
- sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
This is the implementation of pending spec change here: https://github.com/open-telemetry/opentelemetry-specification/pull/1345
> Reverse the direction of the Resource.merge

- CHANGELOG.md
Note: this includes a few pending PRs that I think will make it in.
> Changelog updates for Jan 19, 2021

- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
non-scheme'd endpoints would blow up before this change.
> Handle old-style otlp endpoints properly.

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterBuilder.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftIntegrationTest.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerIntegrationTest.java
- exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java
- exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java
- exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java
- exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
- integration-tests/src/main/java/io/opentelemetry/SendTraceToJaeger.java
> Deprecate the service name configuration options for exporters

- build.gradle
- examples/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
Take 2 - POMs look ok.
Also removed task setting which we don't really use / need.
> Update to Gradle 6.8.1

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java
I think this was the only thing we weren't doing from the newly hatched spec.
> tweak the jaeger exporters to not set internal span kind

- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagatorTest.java
> OtTracerPropagator: send only 64 bits for trace id

- build.gradle.kts
I think this fixes the issue with the bom not being published (at least it did locally)
> apply the publishing configuration directly, rather than inside the java plugin config

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
> Use duration parser in autoconfiguration.

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java
> Remove reference to not public class MultiSpanExporter

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatusData.java
> Remove unnecessary public method

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/SamplingResult.java
> Mark SamplingResult as immutable

- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
> Remove unnecessary class

- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
> Remove unnecessary private method in ImmutableKeyValuePairs

- api/all/src/test/java/io/opentelemetry/api/trace/DefaultTracerTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanContextTest.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/TraceMarshaler.java
> Fix small nits in tests

- api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/2658
I was expecting a one-word change, woah!
> Have w3ctracecontextpropagator actually implement textmappropagator.

- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
> Remove unused public method in TraceId

- api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java
- api/all/src/main/java/io/opentelemetry/api/baggage/BaggageBuilder.java
- api/all/src/main/java/io/opentelemetry/api/baggage/BaggageEntryMetadata.java
- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableEntry.java
- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableEntryMetadata.java
- api/all/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java
- api/all/src/test/java/io/opentelemetry/api/baggage/ImmutableEntryTest.java
- api/all/src/test/java/io/opentelemetry/api/baggage/ScopedBaggageTest.java
> Use consistent name for private classes in the baggage package

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
> Fix more comments in TraceId/SpanId

- sdk-extensions/autoconfigure/build.gradle
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/testConfigError/java/io/opentelemetry/sdk/autoconfigure/ConfigErrorTest.java
> update the trace-related env vars to match the spec

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java
> [BREAKING CHANGE] Remove bytes size from TraceId/SpanId

- api/all/src/main/java/io/opentelemetry/api/trace/TraceFlags.java
- api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceFlagsTest.java
> [BREAKING CHANGE] Remove unused method, cleanup comments in TraceFlags

- api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java
- api/all/src/test/java/io/opentelemetry/api/baggage/BaggageContextTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanTest.java
> Fix consistency between implementation/test of fromContextOrNull

- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
> Mark sortAndFilter methods as protected, reduce public API

- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
- api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java
- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/common/ArrayBackedLabels.java
> Extract foreach implementation in the super class

- api/all/src/main/java/io/opentelemetry/api/baggage/BaggageEntry.java
- api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java
- api/all/src/test/java/io/opentelemetry/api/baggage/ImmutableEntryTest.java
> [BREAKING CHANGE] Rename getEntryMetadata to getMetadata

- api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java
- api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanContextTest.java
- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagator.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorMultipleHeaders.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java
- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/InteroperabilityTest.java
- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java
- sdk-extensions/jfr-events/src/main/java/io/opentelemetry/sdk/extension/jfr/ScopeEvent.java
- sdk-extensions/jfr-events/src/test/java/io/opentelemetry/sdk/extension/jfr/JfrSpanProcessorTest.java
- sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanProcessor.java
- sdk-extensions/zpages/src/test/java/io/opentelemetry/sdk/extension/zpages/TracezZPageHandlerTest.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
> [BREAKING CHANGE] Remove AsHexString suffix from ids getters.

- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
- api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java
- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
- api/all/src/test/java/io/opentelemetry/api/internal/ImmutableKeyValuePairsTest.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/common/ArrayBackedLabels.java
> Implement ImmutableKeyValuePairs to avoid unnecessary autovalue

- sdk/common/src/main/java/io/opentelemetry/sdk/common/Clock.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/IdGenerator.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProviderBuilder.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerProviderTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2627
> Clarify thread-safety requirements for SDK components, fix small issues

- buildscripts/checkstyle-suppressions.xml
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sampler.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/package-info.java
and update some javadoc for parent-based Samplers.
resolves #2632 
resolves #2644
> Add javadoc to the package-info.java for Sampling

- api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java
> Cleanup javadoc in SpanContext

- api/all/src/main/java/io/opentelemetry/api/trace/BigendianEncoding.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceFlags.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/BigendianEncodingTest.java
> Better document exceptions that could happen when parsing Span/Trace ids

- api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java
- api/all/src/main/java/io/opentelemetry/api/trace/ImmutableTraceFlags.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceFlags.java
> Make TraceFlags interface to allow agent to re-implement it

- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorMultipleHeaders.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/StringUtils.java
> Small cleanups in the propagators extension

- api/all/src/jmh/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorBenchmark.java
> Add a benchmark that test extract, create client span, inject

- api/context/src/main/java/io/opentelemetry/context/internal/shaded/AbstractWeakConcurrentMap.java
> Mark AbstractWeakConcurrentMap as package protected, no usage

- exporters/jaeger-thrift/build.gradle
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java
- exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporterTest.java
- exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingSpanExporterTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/JaegerPropagatorTest.java
- sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSamplerTest.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
- sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
> Remove trivial usage of fromLong[s] methods

- api/all/src/main/java/io/opentelemetry/api/trace/BigendianEncoding.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
- exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/TraceMarshalerTest.java
- sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/SpanAdapterTest.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
> Remove helper methods fromBytes from Trace/Span Id

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/EventData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableEventData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableLinkData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/LinkData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/StatusData.java
> Mark interfaces in trace/data immutable

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
> Remove helper methods asBytes from Trace/Span Id

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java
- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java
> Remove helper methods for as longs

- api/all/src/main/java/io/opentelemetry/api/trace/BigendianEncoding.java
- api/all/src/test/java/io/opentelemetry/api/trace/BigendianEncodingTest.java
> Remove unused code in BigendianEncoding

- CHANGELOG.md
we can keep this open until we've got all the pre-1.0 breaking stuff in.
> CHANGELOG entries for today

- api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java
https://github.com/open-telemetry/opentelemetry-java/issues/2724
> Remove one level of indirection, and checks for bytes ids

- exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/TraceMarshalerTest.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
Partially reverts open-telemetry/opentelemetry-java#2750
> Partially reverts "Restore Trace/SpanId.fromBytes"

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
In the revert PR the author did actually change the code (which usually should not be done when calling something a revert),
> Fix comments after revert PR did actually more than just revert

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java
> Do not throw NPE if span/trace ids are null in isValid

- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
> Small javadoc fix for SpanId.fromLong

- api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java
> ArrayBasedTraceStateBuilder:Remove obsolete comment, remove unnecessary null check

- api/metrics/src/main/java/io/opentelemetry/api/metrics/common/ArrayBackedLabels.java
- api/metrics/src/test/java/io/opentelemetry/api/metrics/common/LabelsTest.java
> Null label values means label is not present

- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
- api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java
- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/common/ArrayBackedLabels.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2657
> Remove filterNullValues property from sortAndFilter

- api/context/build.gradle.kts
- api/context/src/main/java/io/opentelemetry/context/StrictContextStorage.java
- api/context/src/strictContextEnabledTest/java/io/opentelemetry/context/StrictContextStorageTest.java
- extensions/kotlin/build.gradle
- extensions/kotlin/src/testStrictContext/kotlin/io/opentelemetry/extension/kotlin/StrictContextWithCoroutinesTest.kt
> Make StrictContextStorage package-private

- api/context/src/main/java/io/opentelemetry/context/internal/shaded/WeakConcurrentMap.java
> Remove comment about internal backwards compatibility guarantees

- api/all/src/jmh/java/io/opentelemetry/api/common/AttributesBenchmark.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/2765
> Add benchmark for attributes

- api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java
> Avoid duplicate copy of the data list in Baggage.toBuilder

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sampler.java
Per https://github.com/open-telemetry/opentelemetry-specification/pull/1414/files
> Add docs about recommendations regarding traceidratiobased sampler

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
This also addresses a possible race condition in the forceFlush() implementation.
> Clarify the implementation of the BatchSpanProcessor forceFlush implementation

- api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java
> Add documentation about invalid SpanContext inputs.

- dependencyManagement/build.gradle.kts
- sdk-extensions/resources/build.gradle.kts
- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ProcessResource.java
> Enable animal sniffer for resources artifact.

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
> Use empty default for null attributes and discard for null unit

- QUICKSTART.md
- sdk-extensions/autoconfigure/README.md
Reflects #2811 #2813
Almost verbatim from https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md
> Add docs for autoconfiguration options.

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfigurationTest.java
> Set the default propagators if none are specified.

- api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleSumObserver.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleUpDownSumObserver.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleValueObserver.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/LongSumObserver.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/LongUpDownSumObserver.java
- api/metrics/src/main/java/io/opentelemetry/api/metrics/LongValueObserver.java
- sdk-extensions/tracing-incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/data/DelegatingSpanData.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRule.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java
> clean up the javadoc and make examples pasteable

- api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceStateBuilder.java
- api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanContextTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorTest.java
- extensions/aws/src/test/java/io/opentelemetry/extension/aws/AwsXrayPropagatorTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/JaegerPropagatorTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracePropagatorTest.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java
- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/SpanConverterTest.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
Provisionally resolves #2746
Do not merge unless we agree to resolve #2746 before 1.0.0 is released.
> [Breaking Change] Rename TraceStateBuilder.set() to put()

- examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClient.java
- examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClientStream.java
- examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java
- examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java
- examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java
- examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java
- examples/logging/src/main/java/io/opentelemetry/example/logging/ExampleConfiguration.java
- examples/logging/src/main/java/io/opentelemetry/example/logging/LoggingExporterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongValueObserverExample.java
- examples/otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java
- examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java
- examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/ExampleConfiguration.java
- examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java
- examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java
- examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ExampleConfiguration.java
- examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ZipkinExample.java
> Mark all public classes as final in the examples

- sdk/common/src/main/java/io/opentelemetry/sdk/internal/TestClock.java
> Mark public class TestClock as final

- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java
> Remove public from methods of not public class in opentracing-shim

- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryContextManager.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricsExporter.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java
> Avoid public unnecessary constants, mark classes final in opencensus-shim/

- api/metrics/src/main/java/io/opentelemetry/api/metrics/GlobalMetricsProvider.java
> Mark GlobalMetricsProvider as final

- extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsConfigurablePropagator.java
> Mark public classes as final in extensions/aws

- sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java
> Mark public classes as final in sdk-extensions/jaeger-remote-sampler

- integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java
- integration-tests/tracecontext/src/main/java/io/opentelemetry/Request.java
> Mark public classes as final in intergration-tests/

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ConfigProperties.java
> Mark public classes as final in sdk-extensions/autoconfigure

- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessor.java
> Mark public classes as final in sdk-extensions/logging

- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/LogSinkSdkProvider.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/LogSinkSdkProviderBuilder.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/data/LogRecord.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/data/LogRecordBuilder.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessor.java
- sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessorBuilder.java
- sdk-extensions/logging/src/test/java/io/opentelemetry/sdk/logging/LogSinkSdkProviderTest.java
> Move Builders as non inner classes in sdk-extension/logging

- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertions.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TraceAssert.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TracesAssert.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/trace/TestSpanData.java
> Mark classes final, or hide ctor for testing classes

- api/all/src/main/java/io/opentelemetry/api/common/AttributeKey.java
- api/all/src/main/java/io/opentelemetry/api/trace/Span.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java
> Remove Nonnull annotations, we use package default Nonnull

- api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java
- api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java
- api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java
- api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java
- api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java
> Do not throw exception if byte array too short for fromBytes

- extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextExtractBenchmark.java
- extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextInjectBenchmark.java
- extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryPropagationComponentImpl.java
- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/OpenTelemetryTextFormatImplTest.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
> [Breaking Change] Remove B3Propagator.Builder, add static methods to access possible instances

- all/build.gradle.kts
Removed already removed path pre-deprecation too
> Exclude all, not just span, generated semconv from coverage

- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusCollector.java
- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusCollectorBuilder.java
> Move Builder as non inner class in prometheus exporter

- sdk-extensions/async-processor/src/main/java/io/opentelemetry/sdk/extension/trace/export/DisruptorAsyncSpanProcessor.java
- sdk-extensions/async-processor/src/main/java/io/opentelemetry/sdk/extension/trace/export/DisruptorAsyncSpanProcessorBuilder.java
> Move Builder as non inner class in async-processor

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/package-info.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/package-info.java
- exporters/logging/src/main/java/io/opentelemetry/exporter/logging/package-info.java
- exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/package-info.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/package-info.java
- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/package-info.java
- exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/package-info.java
- integration-tests/src/test/java/io/opentelemetry/package-info.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/package-info.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/package-info.java
> Ensure ParametersAreNonnullByDefault is present in all packages

- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResource.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/OsResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/SecurityManagerExtension.java
Saw these in coverage reports and have never actually used a security manager before so was a good opportunity to try it out.
> Add tests for resources with securitymanager enabled.

- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/package-info.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/package-info.java
See https://github.com/open-telemetry/opentelemetry-java/tree/main/semconv/src/main/java/io/opentelemetry/api/trace/attributes
> Fix package info in semconv, move from empty package to resource

- README.md
- build.gradle.kts
and fix the script that should have caught it.
> update a version that got missed in the README

- exporters/jaeger/build.gradle.kts
- sdk-extensions/jaeger-remote-sampler/build.gradle.kts
> Remove unnecessary dependencies on alpha artifacts

- extensions/kotlin/src/main/java/io/opentelemetry/extension/kotlin/package-info.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/testing/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/context/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/package-info.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/trace/package-info.java
> Add package-info for all packages

- api/all/src/main/java/io/opentelemetry/api/trace/Span.java
- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/SpanAdapter.java
- exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatusData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/StatusData.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusDataTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2894
> Do not allow null description in the StatusData

- sdk/trace/build.gradle.kts
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2917
> Move semconv dependency as implementation, not exposed in the API

- exporters/jaeger-thrift/build.gradle.kts
- exporters/zipkin/build.gradle.kts
- integration-tests/build.gradle.kts
- perf-harness/build.gradle.kts
- sdk-extensions/autoconfigure/build.gradle.kts
- sdk-extensions/aws/build.gradle.kts
- sdk-extensions/resources/build.gradle.kts
- sdk-extensions/tracing-incubator/build.gradle.kts
- sdk/common/build.gradle.kts
> Fix more api dependencies which should be implementation

- api/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2737
> Move c-like comment to javadoc in TextMapPropagator

- api/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java
> Update the docs on the TextMapPropagator to be closer to the specification

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
Went through the API for #2623 and couldn't find anything other than this one. Though don't know of an automated way of doing it, always possible to have missed something, but I think we're in ok of a position to fix forward in the off chance.
> Pass unmodifiable list to exporters

- api/all/src/main/java/io/opentelemetry/api/trace/propagation/TemporaryBuffers.java
> Small nit fix in propagation TemporaryBuffers

- api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java
- api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java
> Remove usage of not well defined fromHex in w3c context

- CHANGELOG.md
Also, a bit of cleanup to add separators between each release
> Update the CHANGELOG.md for unreleased changes

- sdk-extensions/autoconfigure/README.md
> Add some notes to the autoconfigure README about shutdown hooks and JUL.

- sdk-extensions/autoconfigure/README.md
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/EndpointConfigurationTest.java
> Support OTEL_EXPORTER_OTLP_METRICS/TRACES_ENDPOINT

- examples/autoconfigure/README.md
- examples/autoconfigure/build.gradle
- examples/autoconfigure/src/main/java/io/opentelemetry/example/autoconfigure/AutoConfigExample.java
- examples/settings.gradle
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/2999
> Add an example that uses auto-configuration

- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/BeanstalkResource.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/Ec2Resource.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EcsResource.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EksResource.java
Currently some will NPE, others just don't work. The order of static initialization is something that continues to surprise / bite me :(
> Fix AWS detectors to initialize singleton after statics

- buildscripts/semantic-convention/generate.sh
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/Ec2Resource.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/Ec2ResourceTest.java
- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
Note: this contains breaking changes to ResourceAttributes.
> Update the SemanticAttributes and ResourceAttributes for specification v1.1.0

- exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java
- exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java
- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java
- exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
> Log clearer messages when the collector responds with UNIMPLEMENTED

- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java
- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java
> Implement OpenTracing Shim methods taking timestamp

- api/all/src/main/java/io/opentelemetry/api/trace/TracerProvider.java
> Add a note to the TracerProvider javadoc about instrumentation name.

- build.gradle.kts
I think I copy-pasted a similar snippet from agent but didn't update an important parameter 😱 
Fixes #3058
> Fix testJava8

- api/all/src/main/java/io/opentelemetry/api/trace/PropagatedSpan.java
- api/all/src/test/java/io/opentelemetry/api/trace/PropagatedSpanTest.java
> Better PropagatedSpan.toString

- context/src/main/java/io/opentelemetry/context/propagation/ContextPropagators.java
> Fix leftover occurence of Span.Kind

- exporters/jaeger-thrift/README.md
- exporters/jaeger/README.md
> cleanup the out-of-date Jaeger exporter docs

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulatorTest.java
> Fix bug where AsynchronousInstrumentAccumulator does not call configured LabelProcessorFactory. (#3085)

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricAdapter.java
- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/MetricAdapterTest.java
> Convert DoubleSummaryData to DoubleSummary protos. (#3066)

- .github/workflows/main-build.yml
- .github/workflows/patch-release-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-examples-build.yml
- .github/workflows/release-build.yml
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
Guess my PR had already been incoprorated into another PR
> Fix merge and pin ubuntu to 18.04 to workaround SSL issue

- .github/workflows/build-tracecontext-testsuite.yml
- integration-tests/tracecontext/docker/Dockerfile
It'll be nice to run this with testcontainers.
> Add docker build for tracecontext testsuite.

- integration-tests/tracecontext/build.gradle.kts
- integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java
This simplifies the code a bit by having classes available more convenient than just the servlet API. Will follow up with seeing if it can make it easier to pass more tests. I confirmed that this fails the same tests as current code.
> Migrate tracecontext test app to Armeria.

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java
> set the parentId in the JaegerThriftSpanExporter when span has a parent

- .github/workflows/docs-update.yml
This PR adds a Github Action to allow for updating the documentation on-demand.
> Add automation for updating documentation

- examples/build.gradle
- examples/gradle.properties
- examples/logging/src/main/java/io/opentelemetry/example/logging/LoggingExporterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java
- examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongValueObserverExample.java
also, exclude generated files from spotless
> Update the example code for the 1.1.0 release

- website_docs/_index.md
/cc @austinlparker 
Should we get these pushed to the website manually, rather than waiting for automated solutions?
> update the website docs for the 1.1.0 release

- api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java
> Improve key validity code documentation for trace state

- buildscripts/semantic-convention/generate.sh
> Semantic Conventions: use only a compatible version of the tools image

- CONTRIBUTING.md
- buildscripts/semantic-convention/templates/SemanticAttributes.java.j2
- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/3006
> Modification of enum semantic attributes 

- opentracing-shim/build.gradle.kts
- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceBuilder.java
Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#log
> Implement OpenTracing Shim error logging translation

- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/testbed/clientserver/TestClientServerTest.java
The above PR resolves https://github.com/open-telemetry/opentelemetry-java/issues/3062 on windows with Java 8
> Updated TestClientServer timer execution in Java8

- examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java
- examples/logging/src/main/java/io/opentelemetry/example/logging/LoggingExporterExample.java
> Remove credential info from url in example 

- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/HostResource.java
- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/HostResourceProvider.java
- sdk-extensions/resources/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/HostResourceTest.java
> add host.name as default attribute by add HostResourceProvider 

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactory.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/SumAggregatorFactory.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactoryTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregatorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregatorTest.java
> Add full delta support for sum aggregator

- docs/sdk-configuration.md
Several of the example snippets in the SDK configuration documentation were outdated. I went ahead and updated them.
There are several other chunks of text that are no longer accurate, but I held off on fixing them because they discuss philosophies and future direction which I'm not familiar enough with to represent. But it'd be great if someone could do a read through and update the text as well.
> Fix SDK Config documentation

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricAdapter.java
- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/MetricAdapterTest.java
> Fix otlp metric proto summary quantile conversion bug.

- buildscripts/semantic-convention/generate.sh
- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/OsResource.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/OsResourceTest.java
- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
> Update the semantic convention classes for spec v1.3.0

- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java
- exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java
- exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java
- exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
> Add dropped attribute/event counts to jaeger and zipkin exporters.

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java
> clean up the package-level docs for the sdk trace export package.

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/EnvironmentResource.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/EnvironmentResourceTest.java
- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/HostResource.java
resolves #2858 
Open question: is this in a good package?
> Make the EnvironmentResource public.

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt
- sdk-extensions/autoconfigure/build.gradle.kts
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/EnvironmentResource.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/EnvironmentResourceTest.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
> Implement handling the OTEL_SERVICE_NAME env var.

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/SpanAdapter.java
@iNikem doesn't like these copies :)
> Wrap instead of copy IDs since they are already copies.

- sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java
- sdk/trace/src/jmh/resources/otel.yaml
I also updated it to create 100 spans, rather than just a single span, so we can amortize the cost of the Resource, etc.
> Fix the SpanPipelineBenchmark so that it runs.

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java
While examining this code, I found AutoValue seems to make it much more confusing than the code reduction benefit, it's just supposed to be one field, something our equals / hashcode can take advantage of to keep things small.
> Don't use AutoValue for TraceIdRatio sampler

- docs/apidiffs/current_vs_latest/opentelemetry-extension-trace-propagators.txt
Ended up not calling this locally since I was running the autoconfigure tests, not these ones
> Update API diffs

- CONTRIBUTING.md
Based on https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3206, I'd like to see what people think in this repo as well, and we can adjust one or the other as needed so that they are the same.
> Minor changes to class member ordering

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java
I could also remove the now useless `setNoParent().setParent()` sequences from the unit test if you want.
> SdkSpanBuilder: Use Context.root() to simplify logic.

- .github/workflows/main-build.yml
- .github/workflows/patch-release-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-examples-build.yml
- .github/workflows/release-build.yml
> revert our CI to use ubuntu 18.04

- sdk-extensions/aws/build.gradle.kts
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/internal/JdkHttpClient.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/Ec2Resource.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EksResource.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/GetSamplingRulesRequest.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/GetSamplingRulesResponse.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/XraySamplerClient.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/internal/JdkHttpClientTest.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/EksResourceTest.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/trace/XraySamplerClientTest.java
- sdk-extensions/aws/src/test/resources/get-sampling-rules-response.json
- sdk-extensions/aws/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Add support for fetching xray sampling rules.

- sdk-extensions/aws/build.gradle.kts
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/GetSamplingTargetsRequest.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/GetSamplingTargetsResponse.java
- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/XraySamplerClient.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/trace/XraySamplerClientTest.java
- sdk-extensions/aws/src/test/resources/get-sampling-targets-request.json
- sdk-extensions/aws/src/test/resources/get-sampling-targets-response.json
> Add support for fetching xray sampling targets.

- sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/trace/SamplingRuleApplier.java
- sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/trace/SamplingRuleApplierTest.java
- sdk-extensions/aws/src/test/resources/sampling-rule-awslambda.json
- sdk-extensions/aws/src/test/resources/sampling-rule-exactmatch.json
- sdk-extensions/aws/src/test/resources/sampling-rule-wildcards.json
#3328
Real logic, not just plumbing!
> Add logic for processing a xray remote SamplingRule

- .github/CODEOWNERS
- README.md
Jakub Wach has been doing very good reviews for the project lately and I'd like to nominate him as an Approver.
> Add @kubawach as an Approver

- .github/workflows/main-build.yml
- .github/workflows/pr-build.yml
- dependencyManagement/build.gradle.kts
- exporters/otlp/trace/build.gradle.kts
- sdk-extensions/aws/build.gradle.kts
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/HostResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/OsResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessResourceTest.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResourceTest.java
Netty issue means we need bouncycastle for tests that use SSL https://github.com/netty/netty/issues/10317
Fixes #3361
> Fix tests on Java 16+ and add 16/17-ea to CI.

- CHANGELOG.md
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceBuilder.java
Also added a couple of missing `@since` tags.
> Updates for the CHANGELOG as of July 8, 2021

- buildscripts/checkstyle-suppressions.xml
- buildscripts/checkstyle.xml
- buildscripts/semantic-convention/generate.sh
- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
Also, tweak our checkstyle settings to allow long markdown-style links.
> Update the semconv constants to v1.5.0

- sdk-extensions/autoconfigure/README.md
> Add documentation for OTEL_SERVICE_NAME

- buildscripts/checkstyle-suppressions.xml
- buildscripts/semantic-convention/templates/SemanticAttributes.java.j2
- semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
- semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
> Further work on cleaning up the auto-generated javadoc for SemanticAtttributes

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
Similar to what we do for `put`
> Add containsEntry overload that accepts int

- buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts
- docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-http-trace.txt
- exporters/otlp-http/trace/build.gradle.kts
> Publish the otlp-http-trace exporter.

- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
One of the tests doesn't mock out `shutdown` which can result in flakes. But there doesn't seem to be a need for the test-specific mocks in this file anyways.
```
BatchSpanProcessorTest > exporterThrowsException() FAILED
java.lang.NullPointerException: Cannot invoke "io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(java.lang.Runnable)" because "code" is null
at io.opentelemetry.sdk.common.CompletableResultCode.ofAll(CompletableResultCode.java:48)
at io.opentelemetry.sdk.trace.export.MultiSpanExporter.shutdown(MultiSpanExporter.java:94)
```
> Don't create test-specific mocks in BSPTest.

- context/README.md
- exporters/otlp/all/README.md
- extensions/aws/README.md
- extensions/incubator/README.md
- extensions/kotlin/README.md
- extensions/noop-api/README.md
- opencensus-shim/README.md
- opentracing-shim/README.md
- sdk-extensions/autoconfigure/README.md
- sdk-extensions/aws/README.md
- sdk-extensions/jaeger-remote-sampler/README.md
- sdk-extensions/jfr-events/README.md
- sdk-extensions/logging/README.md
- sdk-extensions/resources/README.md
- sdk-extensions/tracing-incubator/README.md
- sdk-extensions/zpages/README.md
- sdk/common/README.md
- sdk/metrics-testing/README.md
- sdk/metrics-testing/build.gradle.kts
- sdk/metrics/README.md
- sdk/testing/README.md
- sdk/trace/README.md
> Add missing readmes and missing javadoc links

- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/MarshalerInputStream.java
This copies the logic from `AbstractMessageLite` in the proto library. We may look into potential optimization on top of it but this is good to baseline with protobuf.
Thanks for the callout @jsuereth
> Compute buffer size for grpc marshaler

- exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/AttributeMarshaler.java
> Remove comment that isn't valid

- exporters/otlp-http/trace/src/test/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterTest.java
Just wanted to add these assertions to demonstrate our current restrictions. Unfortunately, OkHttp doesn't, and won't, support HTTP/2 upgrade on cleartext. Armeria does, but it's a 8.7MB JAR since it's meant for servers, not embedded libraries :) Apache httpclient5 doesn't, unclear about Jetty - but I'd suspect them to have their own performance issues anyways. 
An option would be to add a recognized scheme like `h2c://` and enable OkHttp in forced cleartext HTTP/2 mode (it doesn't do an upgrade, just assumes it will work) - but I guess it's not a huge deal either since HTTP/2 doesn't provide much benefit when using the BatchSpanProcessor, so only one concurrent export.
> Add assertions for HTTP/2 behavior of OkHttp

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
The refactor portion of Issue #3522.
> Extract common OTLP config logic to utility function

- sdk-extensions/autoconfigure/README.md
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java
- sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
> Add autoconfigure support for OTLP gzip compression

- dependencyManagement/build.gradle.kts
- exporters/jaeger-thrift/build.gradle.kts
- exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
- exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftIntegrationTest.java
> Use Jackson to encode arrays in jaeger-thrift exporter.

- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/traces/TraceRequestMarshalerTest.java
Currently we miss coverage of several, especially array, types
https://app.codecov.io/gh/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/KeyValueMarshaler.java
> Add all attribute types to trace marshaler test.

- sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceBuilder.java
- sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
> Test ResourceBuilder with null inputs

- buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
- integration-tests/tracecontext/src/main/java/io/opentelemetry/Request.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricsExporter.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryTextFormatImpl.java
- opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java
- sdk/metrics/build.gradle.kts
Will enable for metrics after #3578
> Enable nullaway except for metrics.

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/CodedOutputStream.java
The only unused methods remaining are for types that we don't use yet, such as `sfixed32`, though we would want to make it easy to add these fields to the protocol and leave them. There is no possible future use case for these other removed methods, without bigger changes, especially the out of space stuff that doesn't apply to output stream encoding.
> Remove unused CodedOutputStream methods.

- integration-tests/build.gradle.kts
- integration-tests/src/test/java/io/opentelemetry/OtlpExporterIntegrationTest.java
- integration-tests/src/test/resources/otel-config.yaml
Add integration test for new otlp grpc log exporter.
> Add otlp grpc log integration test

- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java
No big deal but just happened to be looking at the file
> Remove final from methods on final class.

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporter.java
> Close response on successful response in HTTP exporter.

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpiUtil.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfigurationTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSamplerTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java
> Allow specifying SPI classloader during autoconfiguration.

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageUtils.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageUtilsTest.java
While reviewing #3831 I was thinking about the `MetricStorageUtils` implementation and couldn't find any tests so I made some.
> Backfill test coverage for MetricStorageUtils

- website_docs/manual_instrumentation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/908
/cc @austinlparker
> [website_docs] Link to website spec pages

- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-api.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-context.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-jaeger-proto.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-jaeger-thrift.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-jaeger.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-logging-otlp.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-logging.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-otlp-common.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-otlp-http-trace.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-otlp-trace.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-otlp.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-exporter-zipkin.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-extension-annotations.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-extension-aws.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-extension-kotlin.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-extension-trace-propagators.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-common.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-extension-autoconfigure-spi.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-extension-aws.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-extension-jaeger-remote-sampler.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-extension-resources.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-testing.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk-trace.txt
- docs/apidiffs/1.9.0_vs_1.7.0/opentelemetry-sdk.txt
Looks like I forgot to `git add` these
> Add apidiffs for 1.9

- website_docs/manual_instrumentation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/922. /cc @austinlparker
> [website_docs] Drop unused link definition

- website_docs/_index.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/905. /cc @austinlparker
> [website_docs] Rework releases and other info

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java
> Wrap async callbacks in try catch

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/InstrumentSelector.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java
> Make InstrumentSelect#getInstrumentType() nullable

- website_docs/instrumentation_examples.md
Contributes https://github.com/open-telemetry/opentelemetry.io/issues/949. /cc @austinlparker
Corresponding website PR: https://github.com/open-telemetry/opentelemetry.io/pull/950
> [website_docs] Use console code-block style, and copyedits

- api/all/src/main/java/io/opentelemetry/api/metrics/ObservableDoubleMeasurement.java
- api/all/src/main/java/io/opentelemetry/api/metrics/ObservableLongMeasurement.java
- api/all/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java
- docs/apidiffs/current_vs_latest/opentelemetry-api.txt
- exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/GrpcGzipBenchmark.java
- exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/MetricsRequestMarshalerBenchmark.java
- exporters/prometheus/src/integrationTest/java/io/opentelemetry/exporter/prometheus/PrometheusIntegrationTest.java
- sdk-extensions/autoconfigure/src/testPrometheus/java/io/opentelemetry/sdk/autoconfigure/PrometheusTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleSumObserverTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownSumObserverTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongGaugeBuilderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongSumObserverTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongUpDownSumObserverTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
Also removed MUST be non-negative from docs, this is true only of Counter instruments I think.
Fixes #3914
> Rename .observe to .record

- dependencyManagement/build.gradle.kts
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporterBuilder.java
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporterBuilder.java
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpUtil.java
> Update to OkHttp 4 and use daemon threads in dispatcher.

- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java
> Set OT Shim's SpanBuilder attributes before the Span is created.

- README.md
metrics api was removed, update documentation
> update the readme document

- sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoubleHistogramPointDataAssert.java
- sdk/metrics-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java
I really needed this assertion when I was working on the micrometer bridge PR.
> Add DoubleHistogramPointData assertion: hasSumGreaterThan()

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
> Use configured classloader for resource SPI.

- docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger.txt
- exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
> Expose setTrustedCertificates in JaegerGrpcSpanExporterBuilder for mTLS Support 

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure-spi.txt
- sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
> Customizer for SdkTracerProviderBuilder

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
> Provide a way to register / skip the shutdown hook in AutoConfiguredOpenTelemetrySdkBuilder

- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusCollector.java
- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusCollectorTest.java
> Fix bug where PrometheusCollector can't be registered

- CHANGELOG.md
- README.md
- RELEASING.md
- Add notes to release documentation
- Update version in docs
- Update changelog
> Docs for 1.10.1 relesae

- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
After #4112, we may run our assertions with BSP metrics in but not the test ones yet.
> Fix flaky FullConfigTest

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
Adjust tracer and meter provider customizer execution order to the last step. 
close #4121
> refactor: adjust tracer and meter provider customizer execution order

- api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java
- context/src/main/java/io/opentelemetry/context/propagation/ContextPropagators.java
- sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java
For example `OpenTelemetry.get()`
> Javadoc code snippets use methods that don't exist

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure-spi.txt
- sdk-extensions/autoconfigure-spi/build.gradle.kts
- sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfiguration.java
- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogExporterConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LogExporterConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfigurationTest.java
- sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LogExporterCustomizer.java
- sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider
Resolves #4095. Mirrors #4127 for logs.
> Logs customizer

- README.md
> [FEATURE] Android desugaring warning

- sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java
- sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
Updated Resource.toBuilder to copy schema URL (#4176)
> Copy schema URL during Resource.toBuilder

- api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java
> Add scare text to the javadoc for GlobalOpenTelemetry

- sdk-extensions/metric-incubator/src/main/java/io/opentelemetry/sdk/viewconfig/ViewConfig.java
- sdk-extensions/metric-incubator/src/test/java/io/opentelemetry/sdk/viewconfig/ViewConfigTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/InstrumentSelector.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/InstrumentSelectorBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/MeterSelector.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/MeterSelectorBuilder.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/InstrumentSelectorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/MeterSelectorTest.java
A strawmans proposal, don't have to merge it but I feel like the extra class makes the API more complicated without much user benefit.
> Inline MeterSelector into InstrumentSelector

- exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogExporterTest.java
- exporters/otlp-http/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterTest.java
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java
- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/logs/LogsRequestMarshalerTest.java
- exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterTest.java
- exporters/otlp/logs/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyLogExporterTest.java
- exporters/otlp/logs/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyShadedLogExporterTest.java
- exporters/otlp/logs/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyOkHttpLogExporterTest.java
- integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java
- sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogDataAssert.java
- sdk/logs-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogBuilder.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogBuilder.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogData.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogDataBuilder.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogDataImpl.java
- sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogBuilderTest.java
Drop the deprecated log name field.
> Remove log name field

- .github/workflows/docker-test-containers.yml
- .github/workflows/main-build.yml
- .github/workflows/patch-release-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/release-build.yml
I'm planning to do some work on sync'ing up workflow configurations between the 3 repos, starting small 😄
> Add newlines between yml steps

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java
- sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceBuilder.java
- sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
This PR is related to #4175 .
The changes included are the following：
- add shortcut of removeif in ResourceBuilder;
- optimize the code in ResourceConfiguration.
> feat:add the shortcut of removeif in ResourceBuilder

- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
to be able to assert a single attribute in a fluent way
> Add SpanDataAssert.hasAttribute

- .github/workflows/docker-test-containers.yml
Updates jaeger and adds in a java 17 image to replace our current java 8 usage
> Update docker test containers

- .github/scripts/markdown-link-check-config.json
- .github/workflows/main-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/reusable-markdown-link-check.yml
- .github/workflows/reusable-misspell-check.yml
- CHANGELOG.md
- RELEASING.md
- docs/common-github-actions-practices.md
A couple of other changes in this PR:
* Update CI build to run on release branches
* Some refinements to the github action doc
* Fix two misspellings that must have just been added to the misspell dictionary(?)
> Better link checking

- .github/workflows/build-pull-request.yml
- .github/workflows/build-tracecontext-testsuite.yml
- .github/workflows/build.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/patch-release-build.yml
- .github/workflows/reusable-create-issue-for-failure.yml
- .github/workflows/reusable-misspell-check.yml
- docs/common-github-actions-practices.md
See also https://github.com/open-telemetry/opentelemetry-java-contrib/pull/274 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5695.
Also several updates to the github actions doc.
> Sync GitHub actions, other than release actions

- sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/SamplingStrategyResponse.java
- sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java
- sdk-extensions/jaeger-remote-sampler/src/test/resources/sampling.json
> Do not rely on samplingType provided by Jaeger (#4319)

- exporters/prometheus/build.gradle.kts
Forgot to remove these when removing the usage
> Remove unused transitive prometheus deps

- .github/workflows/backport.yml
- .github/workflows/merge-change-log-to-main.yml
- .github/workflows/prepare-release-branch.yml
- .github/workflows/release.yml
- CHANGELOG.md
- RELEASING.md
- docs/common-github-actions-practices.md
see RELEASING.md updates for overview of change
> Release workflow improvement

- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java
- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java
> Fix Prometheus export of histogram data points without attributes

- .github/workflows/prepare-release-branch.yml
- docs/common-github-actions-practices.md
- version.gradle.kts
~will rebase this once #4357 is merged~
> Fix prepare release branch workflow

- micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryMeterRegistryBuilder.java
to match the module name, and to differentiate it from upcoming micrometer2shim
> Update micrometer1shim instrumentation scope name

- .github/scripts/markdown-link-check-config.json
- .github/workflows/build.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/merge-change-log-to-main.yml
- .github/workflows/prepare-patch-release.yml
- .github/workflows/prepare-release-branch.yml
- .github/workflows/release.yml
- RELEASING.md
- docs/common-github-actions-practices.md
A bunch of random workflow changes/fixes I've been accumulating...
> Sync'ing workflow changes/fixes

- api/all/src/main/java/io/opentelemetry/api/internal/ValidationUtil.java
- api/all/src/main/java/io/opentelemetry/api/metrics/DefaultMeter.java
- api/all/src/test/java/io/opentelemetry/api/internal/ValidationUtilTest.java
- api/all/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
> Set unit to 1 if invalid

- .github/workflows/merge-change-log-to-main.yml
- docs/common-github-actions-practices.md
this would have made this succeed: https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/6133898396
> More resilient change log merging

- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryInterceptorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/IdentityTest.java
> Flaky retry interceptor test

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/IdentityTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
> Default unit is blank instead of 1

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt
- sdk/testing/build.gradle.kts
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRule.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRuleTest.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
Still need to find a way to clear metrics between tests to make metrics testing practical.
> Add metrics to OpenTelemetryRule and OpenTelemetryExtension

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt
- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java
- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
- sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java
- sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentSelector.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/View.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MeterProviderSharedState.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/NoopAttributesProcessor.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/RegisteredView.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/InstrumentSelectorTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReaderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/RegisteredViewTest.java
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricReader.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricReaderTest.java
Will likely followup with sdklogemiterprovider, and propagators.
> Add SdkMeterProvider toString method

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/retry/RetryInterceptor.java
- exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryInterceptorTest.java
> RetryInterceptor retries on SocketTimeoutException with no message

- context/src/test/java/io/opentelemetry/context/propagation/MultiTextMapPropagatorTest.java
- exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
- extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/SpiUtilTest.java
- sdk-extensions/jfr-events/src/test/java/io/opentelemetry/sdk/extension/jfr/JfrSpanProcessorTest.java
- sdk/logs/src/test/java/io/opentelemetry/sdk/logs/data/LogDataBuilderTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBucketsTest.java
Follow up from #4500 -- picking up a few remaining log4j assertions and migrating them to assertj.
> Migrate to assertj 

- sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ContainerResource.java
- sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ContainerResourceTest.java
> Handle ContainerResource edge case

- .github/workflows/build.yml
- api/all/src/main/java/io/opentelemetry/api/common/Attributes.java
Resolves #4516.
Tested locally and works.
> Add build step to check for diff

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/DefaultConfigProperties.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
> Handle non-String system properties (#4543)

- .github/workflows/stale-pr.yml
Close #4497 
Signed-off-by: Cuichen Li <cuichli@cisco.com>
> add github action to autoclose old pr/issues

- RELEASING.md
- sdk-extensions/metric-incubator/README.md
- sdk-extensions/metric-incubator/src/main/java/io/opentelemetry/sdk/viewconfig/ViewConfig.java
These docs have been incorrect since the InstrumentSelector and View APIs were updated.
> Fix metrics incubator docs

- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
> Fix ConcurrencModificationException in BatchSpanProcessorTest

- opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java
- opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
OpenTracing shim: baggage of active span was not used
> OpenTracing shim: baggage of active span was not used

- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/internal/metrics/MetricAdapterTest.java
> Fix typo in MetricAdapterTest#convertHistogram

- README.md
Fixes: https://github.com/open-telemetry/opentelemetry-java/issues/4611
> Add Project Status in README

- .github/scripts/set-git-user.sh
- .github/scripts/use-cla-approved-github-bot.sh
- .github/workflows/backport.yml
- .github/workflows/prepare-patch-release.yml
- .github/workflows/prepare-release-branch.yml
- .github/workflows/release.yml
Feel free to merge this before or after the release, the existing bot account is still live and kicking.
> Switch to opentelemetrybot account

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/OkHttpGrpcExporter.java
- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporter.java
- sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/OkHttpGrpcService.java
- sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProviderTest.java
> Cache HttpUrl for exporters that use OkHttp

- .github/scripts/generate-release-contributors.sh
- .github/workflows/release.yml
> Fix release notes generation

- sdk-extensions/metric-incubator/README.md
- sdk-extensions/metric-incubator/src/main/java/io/opentelemetry/sdk/viewconfig/ViewConfig.java
- sdk-extensions/metric-incubator/src/main/java/io/opentelemetry/sdk/viewconfig/ViewSpecification.java
- sdk-extensions/metric-incubator/src/test/java/io/opentelemetry/sdk/viewconfig/ViewConfigTest.java
- sdk-extensions/metric-incubator/src/test/resources/aggregation-args.yaml
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/AggregationUtil.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/AggregationUtilTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java
> Support aggregation arguments for view file configuration

- buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts
- docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt
- docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/trace/TestSpanData.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java
> Add default implementations for getInstrumentationScopeInfo methods

- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java
The current example is out of date and does not compile.
> Update example in `InMemorySpanExporter`

- opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricExporterTest.java
> Fix OpenTelemetryMetricExporterTest flake

- buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
- buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Syncing across the 3 Java repos
> Sync errorprone conventions

- sdk-extensions/autoconfigure/README.md
> Fix autoconfigure documentation

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java
> Remove unnecessary code from metrics sdk

- sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/internal/aggregator/HistogramScaleBenchmark.java
> Fix HistogramScaleBenchmark, use the right ThreadState, clarify difference

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt
- sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationScopeInfo.java
- sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationScopeInfoBuilder.java
- sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java
- sdk/common/src/test/java/io/opentelemetry/sdk/common/InstrumentationScopeInfoTest.java
- sdk/common/src/test/java/io/opentelemetry/sdk/internal/ComponentRegistryTest.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogEmitterBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterBuilder.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerBuilder.java
- sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
> Extend InstrumentationScopeInfo with scope attributes

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExplicitBucketHistogramUtils.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
> Update bucket hist defaults to match spec

- docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt
- sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java
- sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/TraceAssertionsTest.java
I needed something like that in the javaagent tests
> Add AttributesAssert#doesNotContainKey()

- api/all/src/test/java/io/opentelemetry/api/common/AttributesTest.java
Simplified the assertions to fix the IntelliJ warnings.
> AttributesTest | Simplified the assertions to fix the warnings

- dependencyManagement/build.gradle.kts
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6592#issuecomment-1248298564
> Update snakeyaml dependency

- .github/dependabot.yml
> Ignore updates to jqf-fuzz

- .github/scripts/get-version.sh
Same as https://github.com/open-telemetry/opentelemetry-java-contrib/pull/538
> Fix patch release process

- README.md
https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#project-naming
> Align project names

- api/all/src/main/java/io/opentelemetry/api/internal/ImmutableSpanContext.java
`skipIdValidation` was missing from javadoc.
> Add missing javadoc param to ImmutableSpanContext.create()

- sdk/logs/src/jmh/java/io/opentelemetry/sdk/logs/LogsBenchmarks.java
Fixes the build, which is broken because of a bad merge.
> Fix LogsBenchmarks

- README.md
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-api.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-context.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-common.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-jaeger-thrift.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-jaeger.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-logging-otlp.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-logging.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-otlp-common.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-otlp.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-exporter-zipkin.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-extension-kotlin.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-extension-trace-propagators.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-common.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-extension-autoconfigure-spi.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-extension-jaeger-remote-sampler.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-metrics.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-testing.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk-trace.txt
- docs/apidiffs/1.22.0_vs_1.21.0/opentelemetry-sdk.txt
Update version in docs, update japicmp.
> Post release 1.22.0

- dependencyManagement/build.gradle.kts
This will help dependabot detect and update more libraries, see also https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7176
> More dependabot

- gradle.properties
same as https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7533
> Remove workaround

- opentracing-shim/README.md
- opentracing-shim/src/main/resources/simplelogger.properties
Fixing incorrect docs left floating around after a recent change I made to the API.
> Fix opentracing docs

- dependencyManagement/build.gradle.kts
- sdk-extensions/incubator/build.gradle.kts
- sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfig.java
> Switch from snakeyaml to snakeyaml-engine

- dependencyManagement/build.gradle.kts
Resolves https://github.com/open-telemetry/opentelemetry-java/actions/runs/4120053689
> Use latest netty

- .github/workflows/reusable-open-issue-on-failure.yml
Noticed this in the workflow I got a notification about the other day
https://github.com/open-telemetry/opentelemetry-java/actions/runs/4339199441/jobs/7576577037
> Fix case of bug label in open issue workflow

- .github/workflows/codeql-daily.yml
See similar fix in [contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/772).
> Fix code ql

- .github/workflows/release.yml
Revert #5283 now that release is finished.
> Revert change to release

- .github/workflows/reusable-markdown-link-check.yml
> Use markdown-link-check@3.10.3

- exporters/otlp/all/src/jmh/java/io/opentelemetry/exporter/otlp/trace/OltpExporterBenchmark.java
The benchmark currently tests the okhttp and grpc managed channel versions of the grpc exporters. Extending to include the http/protobuf exporter.
> Expand otlp benchmark to include otlp http case

- .github/repository-settings.md
Just in case you want to be the same as the -instrumentation and -contrib repos 😄
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6624
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8229
> Update squash merge commit message

- .github/repository-settings.md
> Add new branch rule for gradlew-update-*

- exporters/otlp/all/build.gradle.kts
- sdk-extensions/jaeger-remote-sampler/build.gradle.kts
> Fix more gradle warnings

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java
> fix comment for registerView

- README.md
Thanks @zeitlinger for the help you've been providing!
> Add Gregor Zeitlinger as triager

- .github/workflows/build.yml
See comments on `semantic-conventions-java`:
- https://github.com/open-telemetry/semantic-conventions-java/pull/1#discussion_r1291735229
- https://github.com/open-telemetry/semantic-conventions-java/pull/1#discussion_r1291735546
> Update build to use ubuntu-latest, java 20

- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
> Retry requests in PrometheusHttpServerTest

- .github/workflows/build-tracecontext-testsuite.yml
> Less renovate (pin docker/build-push-action@v4)

- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java
- sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
> Allow instrument names to contain a forward slash

- .github/config/markdown-link-check-config.json
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/5884
> Enable checking javadoc.io links

- sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java
- sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
> Stop setting Resource schemaUrl in autoconfigure

- .github/workflows/release.yml
- README.md
> Stop publishing announcement on release

- CHANGELOG.md
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
Still need to make a decision on #5976.
> Prepare 1.32.0

- RELEASING.md
this should fix the build cc @jack-berg
> fixes link drift in sonatype

- buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Accidentally removed this in #6322.
> Restore build fail on warning

- README.md
Thanks for everything @mateuszrzeszutek. Hope to see you around!
> Move mateusz to emeritus

- exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverter.java
- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverterTest.java
> Use getPrometheusName for Otel2PrometheusConverter map keys

- .github/workflows/build.yml
> Run build on java 21

- exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanStatusStatelessMarshaler.java
Related to https://github.com/open-telemetry/opentelemetry-java/pull/6410
> Marshal span status description without allocation

- README.md
In addition to being a valued maintainer for `opentelemetry-java-instrumentation`, @laurit has contributed many PRs and provided valuable feedback to `opentelemetry-java` over the last couple of years. Most recently, Lauri has driven an effort to optimize the memory usage of OTLP serialization - very tricky work which stands to be highly impactful. 
Thanks for all your work @laurit!
> Add Lauri to approvers

- api/incubator/README.md
Remove remnant now that synchronous gauge is stable.
> Fix incubator docs

- sdk/trace/build.gradle.kts
- sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/ExporterBenchmark.java
- sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java
fix issue: https://github.com/open-telemetry/opentelemetry-java/issues/6409
> Fix the JMH task execution failure.

- integration-tests/tracecontext/build.gradle.kts
- sdk/trace-shaded-deps/build.gradle.kts
- settings.gradle.kts
> New gradle shadow plugin location

- README.md
now #6471 has fully solved every issue, let's celebrate success! :)
> add Reproducible Builds badge

- CHANGELOG.md
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/View.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewBuilder.java
- sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/CardinalityLimitSelector.java
- sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ExceptionEventData.java
- Related PR to update `opentelemetry-java-examples`: https://github.com/open-telemetry/opentelemetry-java-examples/pull/520
- Related PR to update `opentelemetry.io`: https://github.com/open-telemetry/opentelemetry.io/pull/5566
> Prepare 1.44.0

- .github/repository-settings.md
- .github/workflows/benchmark-tags.yml
- .github/workflows/benchmark.yml
- .github/workflows/build.yml
- settings.gradle.kts
> Update develocity configuration

- .codecov.yaml
At least for now in order to get PRs passing again.
> Reduce codecov target from 90 to 89

- .github/workflows/build.yml
- .github/workflows/generate-post-release-pr.yml
- .github/workflows/prepare-patch-release.yml
- .github/workflows/prepare-release-branch.yml
- .github/workflows/release.yml
- .github/workflows/reusable-open-issue-on-failure.yml
Continuation of #7072, which should cover all the workflows: https://scorecard.dev/viewer/?uri=github.com/open-telemetry/opentelemetry-java
> Continue limiting workflow permissions

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Let's try this instead of #7086. 
Thanks for the [tip](https://github.com/open-telemetry/opentelemetry-java/pull/7086#issuecomment-2648871293) @trask
> Retry tests in CI

- docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt
- exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java
- exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java
- exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java
- exporters/otlp/testing-internal/build.gradle.kts
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcLogRecordExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcMetricExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcSpanExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpLogRecordExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpMetricExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpSpanExporterBuilderWrapper.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java
- exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/TelemetryExporterBuilder.java
> Add support for setting OTLP exporter service class loader

- sdk/metrics/src/testIncubating/java/io/opentelemetry/sdk/metrics/AttributesAdviceTest.java
> Add more attribute advice tests to show interaction with views

- docs/jmh.md
> Fix jmh link

- .clomonitor.yml
- README.md
along with selective reordering and pruning, let me know if you have any preferences
> Add FOSSA badges

- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ExtendedSdkLogger.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogger.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLoggerProvider.java
- sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkLoggerProviderUtil.java
- sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerProviderTest.java
- sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerTest.java
- sdk/logs/src/testIncubating/java/io/opentelemetry/sdk/logs/LoggerConfigTest.java
> Add `setLoggerConfigurator` support to `LoggerProvider`

- context/src/main/java/io/opentelemetry/context/ContextKey.java
> ContextKey update example code

- .github/renovate.json5
See #7319 and comments in #7415.
> Prevent major version bump in equalsverifier.

- sdk/common/src/main/java/io/opentelemetry/sdk/internal/ThrottlingLogger.java
- sdk/common/src/test/java/io/opentelemetry/sdk/internal/ThrottlingLoggerTest.java
Modified the ThrottlingLogger.java to be able to take in a time interval and time unit.
> added new constructor and tests

- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java
> Fix collector integration test

- exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java
(cherry picked from commit 7b72a52620b81461c53e69b034c57298dd470abf)
> Fix collector integration test (#7545)

- CHANGELOG.md
- version.gradle.kts
> [release/v1.53.x] Prepare release 1.53.0

- .github/workflows/reusable-markdown-link-check.yml
Matching max_concurrency used in other Java repos
> Speed up link checking

- .github/workflows/build.yml
This is definitely not an important change but randomly found it when reading the file so sent a PR
> Remove extra space in a comment
