open-telemetry/opentelemetry-java

api/src/main/java/openconsensus/trace/BlankSpan.java, api/src/main/java/openconsensus/trace/EndSpanOptions.java, api/src/main/java/openconsensus/trace/Span.java, api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/data/Event.java
=> Annotation -> Event

api/src/main/java/openconsensus/trace/Span.java, api/src/main/java/openconsensus/trace/SpanBuilder.java
#17
I also introduced undefined to match proto definition for span kind in Open Census. And also remove nullable attribute from the span kind attribute
=> producer and consumer span kinds

api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/Tracer.java, api/src/main/java/openconsensus/trace/propagation/BinaryFormat.java
=> Remove SpanBuilder.startScopedSpan().

api/README.md, api/build.gradle, api/src/main/java/openconsensus/common/ExperimentalApi.java, api/src/main/java/openconsensus/common/Internal.java, api/src/main/java/openconsensus/internal/package-info.java, api/src/main/java/openconsensus/metrics/data/AttachmentValue.java, api/src/main/java/openconsensus/metrics/package-info.java, api/src/main/java/openconsensus/resource/package-info.java, api/src/main/java/openconsensus/stats/data/Measure.java, api/src/main/java/openconsensus/tags/package-info.java, api/src/main/java/openconsensus/tags/propagation/TagContextBinarySerializer.java, api/src/main/java/openconsensus/tags/unsafe/ContextUtils.java, api/src/main/java/openconsensus/trace/package-info.java, api/src/main/java/openconsensus/trace/unsafe/ContextUtils.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/61.
=> Remove all reference to opencensus.

CONTRIBUTING.md, README.md
=> readme and contributing

api/src/main/java/openconsensus/metrics/data/Distribution.java, api/src/main/java/openconsensus/metrics/data/Value.java, api/src/main/java/openconsensus/stats/data/Measurement.java, api/src/main/java/openconsensus/stats/view/data/Aggregation.java, api/src/main/java/openconsensus/trace/data/AttributeValue.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/70.
=> Use getX() to get values from subclasses instead of cast.

api/src/main/java/openconsensus/trace/BlankSpan.java, api/src/main/java/openconsensus/trace/Span.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/TracerShim.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/18
=> Specialized the setAttribute to avoid one allocation.

api/src/main/java/openconsensus/tags/NoopTags.java, api/src/main/java/openconsensus/tags/Tagger.java, api/src/main/java/openconsensus/tags/propagation/TagMapBinarySerializer.java, api/src/main/java/openconsensus/tags/propagation/TagMapDeserializationException.java, api/src/main/java/openconsensus/tags/propagation/TagMapSerializationException.java, api/src/main/java/openconsensus/tags/propagation/TagPropagationComponent.java, api/src/main/java/openconsensus/tags/unsafe/ContextUtils.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/89.
=> Rename all TagContext* to TagMap*.

api/src/main/java/openconsensus/internal/Utils.java, api/src/main/java/openconsensus/metrics/MetricOptions.java, api/src/main/java/openconsensus/metrics/MetricRegistry.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/86.
Identical PR to https://github.com/census-instrumentation/opencensus-java/pull/1814.
=> Add MetricOptions to build Double/Long Gauge.

api/src/main/java/openconsensus/trace/NoopTrace.java, api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/TraceComponent.java, api/src/main/java/openconsensus/trace/Tracer.java, api/src/main/java/openconsensus/trace/Tracing.java, api/src/main/java/openconsensus/trace/propagation/BinaryFormat.java, api/src/main/java/openconsensus/trace/propagation/PropagationComponent.java, api/src/main/java/openconsensus/trace/propagation/TextFormat.java
Updates https://github.com/bogdandrutu/openconsensus/issues/65.
=> Move Noop Trace implementation to one class.

api/src/main/java/openconsensus/tags/NoopTags.java
To make it consistent with NoopStats and NoopTrace.
=> Remove singleton in NoopTags.

api/src/main/java/openconsensus/metrics/DerivedDoubleGauge.java, api/src/main/java/openconsensus/metrics/DerivedLongGauge.java, api/src/main/java/openconsensus/metrics/DoubleGauge.java, api/src/main/java/openconsensus/metrics/LongGauge.java, api/src/main/java/openconsensus/metrics/MetricRegistry.java, api/src/main/java/openconsensus/metrics/Metrics.java, api/src/main/java/openconsensus/metrics/MetricsComponent.java, api/src/main/java/openconsensus/metrics/NoopMetrics.java
Similar to ~~https://github.com/bogdandrutu/openconsensus/pull/91~~ #88 .
=> Move Noop Metrics implementation to one class.

api/src/main/java/openconsensus/tags/NoopTags.java, api/src/main/java/openconsensus/tags/propagation/TagMapTextFormat.java, api/src/main/java/openconsensus/tags/propagation/TagPropagationComponent.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/99.
Import changes from https://github.com/census-instrumentation/opencensus-java/pull/1800.
=> Add HTTP text serializer API for TagMap.

api/src/main/java/openconsensus/trace/data/Link.java
Updates https://github.com/bogdandrutu/openconsensus/issues/14
In a followup PR will rename to Reference, update comments and SpanBuilder.
=> Remove the type from links, and add SpanContext.

api/src/main/java/openconsensus/trace/SpanBuilder.java
=> Clarify that sampling on Span is merely a hint.

opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java
Use this later, when the actual Span gets built.
Addresses #41
=> Stash the error value for SpanBuilder.

api/src/main/java/openconsensus/trace/data/SpanData.java
Updates https://github.com/bogdandrutu/openconsensus/issues/74
=> Remove notion about dropped events, links, attributes from SpanData.

api/src/main/java/openconsensus/metrics/NoopMetrics.java, api/src/main/java/openconsensus/stats/NoopStats.java, api/src/main/java/openconsensus/tags/NoopTags.java, api/src/main/java/openconsensus/trace/NoopTrace.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/65.
=> Expose noop implementations.

api/build.gradle, build.gradle, contrib/build.gradle, sdk/README.md, sdk/build.gradle, sdk/src/main/proto/agent/README.md, sdk/src/main/proto/agent/common/v1/common.proto, sdk/src/main/proto/agent/metrics/v1/metrics_service.proto, sdk/src/main/proto/agent/trace/v1/trace_service.proto, sdk/src/main/proto/agent/trace/v1/trace_service_http.yaml, sdk/src/main/proto/metrics/v1/metrics.proto, sdk/src/main/proto/resource/v1/resource.proto, sdk/src/main/proto/trace/v1/trace.proto, sdk/src/main/proto/trace/v1/trace_config.proto, settings.gradle
* This PR only modifies the packages, copyright and authors from the initial files.
* Follow up PRs will update the protos in order to keep a history.
* In the final state the protos will be moved to a different repo and a Java artifact will be generated from there, but for the moment we keep them here.
=> Copy the current OpenCensus protos.

sdk/src/main/proto/agent/README.md, sdk/src/main/proto/agent/common/v1/common.proto, sdk/src/main/proto/agent/metrics/v1/metrics_service.proto, sdk/src/main/proto/agent/trace/v1/trace_service.proto, sdk/src/main/proto/agent/trace/v1/trace_service_http.yaml, sdk/src/main/proto/metrics/v1/metrics.proto, sdk/src/main/proto/resource/v1/resource.proto, sdk/src/main/proto/trace/v1/trace.proto, sdk/src/main/proto/trace/v1/trace_config.proto
I broke something in https://github.com/bogdandrutu/openconsensus/pull/134 and this changes did not get merged.
=> Cleanup copyright and package.

opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java
Had forgotten to update the OT shim after the respective change was merged.
=> Do set the Span name for the OT shim.

api/src/main/java/openconsensus/context/propagation/TextFormat.java, api/src/main/java/openconsensus/tags/propagation/TextFormat.java, api/src/main/java/openconsensus/trace/propagation/BinaryFormat.java, api/src/main/java/openconsensus/trace/propagation/TextFormat.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/Propagation.java
Updates https://github.com/bogdandrutu/openconsensus/issues/128
=> Move TextFormat in the context.

schemas/opencensus/HTTP.md, schemas/opencensus/StandardResources.md, schemas/opencensus/gRPC.md, schemas/opencensus/http-out-test-cases.json, schemas/opentracing/semantic_conventions.md
This is the copy of metadata-related files from OC and OT. Copying as is so changes would be an atomic PRs
#17
=> raw copies of metadata docs

api/src/main/java/openconsensus/trace/NoopTrace.java, api/src/main/java/openconsensus/trace/SpanData.java, api/src/main/java/openconsensus/trace/Tracer.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/82
=> Move SpanData to main API and add Resource.

schemas/opencensus/HTTP-stats.md, schemas/opencensus/gRPC-stats.md
So I can make atomic changes...
=> raw files from opencensus regarding stats from rpc

api/src/main/java/openconsensus/stats/view/data/View.java, api/src/main/java/openconsensus/tags/EmptyTagMap.java, api/src/main/java/openconsensus/tags/NoopTags.java, api/src/main/java/openconsensus/tags/Tag.java, api/src/main/java/openconsensus/tags/TagKey.java, api/src/main/java/openconsensus/tags/TagMap.java, api/src/main/java/openconsensus/tags/TagMapBuilder.java, api/src/main/java/openconsensus/tags/TagMetadata.java, api/src/main/java/openconsensus/tags/TagValue.java, api/src/main/java/openconsensus/tags/package-info.java, api/src/main/java/openconsensus/tags/unsafe/ContextUtils.java
* EmtpyTagMap is not exposed, we will do that in a separate PR and remove the duplicate code from the unsafe directory.
=> Add getter on the TagMap.

api/src/main/java/openconsensus/metrics/DerivedDoubleCumulative.java, api/src/main/java/openconsensus/metrics/DoubleCumulative.java, api/src/main/java/openconsensus/metrics/MetricRegistry.java, api/src/main/java/openconsensus/metrics/NoopMetrics.java
Because of https://github.com/bogdandrutu/openconsensus/pull/155 I only added Double cumulative APIs.
=> Metrics: Add cumulative API.

api/src/main/java/openconsensus/trace/SpanData.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/156
=> Remove child count from the SpanData.

sdk/src/main/proto/metrics/v1/metrics.proto
Fixes https://github.com/bogdandrutu/openconsensus/issues/112
=> Rename Distribution to Histogram, remove sum of squares.

api/src/main/java/openconsensus/resource/Resource.java, api/src/main/java/openconsensus/trace/NoopTrace.java, api/src/main/java/openconsensus/trace/Tracer.java
=> add resource on tracer

api/src/main/java/openconsensus/metrics/DerivedLongCumulative.java, api/src/main/java/openconsensus/metrics/LongCumulative.java, api/src/main/java/openconsensus/metrics/MetricRegistry.java, api/src/main/java/openconsensus/metrics/NoopMetrics.java
In observance of https://github.com/bogdandrutu/openconsensus/issues/185 and https://github.com/bogdandrutu/openconsensus/pull/155.
=> Metrics: Add LongCumulative.

README.md
Signed-off-by: Yuri Shkuro <ys@uber.com>
=> Rename & test CLA

.travis.yml, all/build.gradle, settings.gradle
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/196
=> Add an all gradle module that reports coverage and builds all javadoc.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanInterceptor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/276
=> SDK: Add SpanProcessor as an interface to process Spans when start/end.

api/src/main/java/io/opentelemetry/trace/NoopTrace.java, api/src/test/java/io/opentelemetry/trace/TracerTest.java
=> Use w3c tracecontext in noop tracer

api/src/main/java/io/opentelemetry/trace/NoopTrace.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/trace/TracerTest.java
=> Propagate span context in noop

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/spi/TaggerProvider.java, api/src/main/java/io/opentelemetry/tags/Tagger.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/tags/TagsTest.java, docs/io/opentelemetry/tags/Tagger.html, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/tags/propagation/TagContextTextFormat.java
=> Add tagger to global registry

api/src/main/java/io/opentelemetry/trace/Link.java
=> Clarify Link javadoc

api/src/main/java/io/opentelemetry/tags/unsafe/ContextUtils.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/tags/unsafe/ContextUtilsTest.java, sdk/src/main/java/io/opentelemetry/sdk/tags/internal/CurrentTagMapUtils.java, sdk/src/test/java/io/opentelemetry/sdk/tags/TaggerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/tags/internal/CurrentTagMapUtilsTest.java
=> Add support to directly interact with current Context in the unsafe for tags.

api/src/main/java/io/opentelemetry/trace/spi/TracerProvider.java
=> Fix tracer provider javadoc

api/src/main/java/io/opentelemetry/context/propagation/HttpTextFormat.java
=> Prohibit returning null in extract javadoc

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/context/NoopScope.java, api/src/main/java/io/opentelemetry/metrics/NoopMeter.java, api/src/main/java/io/opentelemetry/tags/NoopTagger.java, api/src/main/java/io/opentelemetry/trace/NoopTracer.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/MeasureTest.java, api/src/test/java/io/opentelemetry/metrics/NoopMeterTest.java, api/src/test/java/io/opentelemetry/tags/NoopTaggerTest.java, api/src/test/java/io/opentelemetry/trace/NoopTracerTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java
Resolves #253 
Related to #309 
=> Define noop tracer/metrer/tagger as singletons

.github/CODEOWNERS
As this is part of the process for new Approvers.
=> Add @tylerbenson as CODEOWNER

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/tags/DefaultTagger.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, api/src/test/java/io/opentelemetry/metrics/MeasureTest.java, api/src/test/java/io/opentelemetry/tags/DefaultTaggerTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/285
=> Rename Noop[Tracer|Tagger|Meter] to Default[Tracer|Tagger|Meter].

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/main/resources/META-INF/services/io.opentelemetry.trace.spi.TracerProvider, sdk/src/test/java/io/opentelemetry/sdk/OpenTelemetryTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkProviderTest.java
=> Implement tracer provider in SDK

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/tags/TaggerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
=> Add empty implementation of Meter to SDK

sdk/src/main/java/io/opentelemetry/sdk/tags/TaggerSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/main/resources/META-INF/services/io.opentelemetry.tags.spi.TaggerProvider, sdk/src/test/java/io/opentelemetry/sdk/tags/TaggerSdkProviderTest.java
=> Implement tagger provider in SDK

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/resources/META-INF/services/io.opentelemetry.metrics.spi.MeterProvider, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkProviderTest.java
=> Implement meter provider in SDK

sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/Aggregation.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/BucketBoundaries.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/View.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/ViewManager.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/impl/MeasurementImpl.java
=> Move SDK stats to metrics

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
=> Use tracecontext format in tracer SDK

api/src/main/java/io/opentelemetry/tags/DefaultTagger.java, api/src/main/java/io/opentelemetry/tags/TagMap.java, api/src/main/java/io/opentelemetry/tags/Tagger.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/tags/DefaultTaggerTest.java, sdk/src/main/java/io/opentelemetry/sdk/tags/TaggerSdk.java
Addresses #312 
I haven't included (on purpose) any details about logic mentioned by @bogdandrutu as we will know better once we implement that in the SDK.
=> Apply same logic for parent to TagMap as we do for Span.

api/src/main/java/io/opentelemetry/trace/SpanData.java
See https://github.com/open-telemetry/opentelemetry-java/pull/355#issuecomment-496930157.
=> Add a note in SpanData documentation.

CODEOWNERS
https://github.com/open-telemetry/community/blob/master/community-members.md
=> Updating according to the list in community repo

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Metric.java, api/src/main/java/io/opentelemetry/resources/Resource.java, api/src/main/java/io/opentelemetry/resources/package-info.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/SpanData.java, api/src/main/java/io/opentelemetry/trace/Tracer.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/resources/ResourceTest.java, sdk/src/main/java/io/opentelemetry/sdk/resources/EnvVarResource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
=> Rename package resource to resources.

api/src/main/java/io/opentelemetry/trace/Span.java
Addresses #369 
Changing the case to singular seems enough to fix this.
=> Fix comment for addEvent() as there is no setAttributes() anymore.

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java
* Make the public methods static.
* Update the documentation.
=> OT Shim: Small cleanup of the public TraceShim class.

api/src/main/java/io/opentelemetry/context/propagation/TraceContextFormat.java, api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/SpanContext.java, api/src/main/java/io/opentelemetry/trace/SpanId.java, api/src/main/java/io/opentelemetry/trace/TraceId.java, api/src/main/java/io/opentelemetry/trace/TraceOptions.java, api/src/main/java/io/opentelemetry/trace/Tracestate.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/context/propagation/TraceContextFormatTest.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, api/src/test/java/io/opentelemetry/trace/LinkTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, api/src/test/java/io/opentelemetry/trace/SpanContextTest.java, api/src/test/java/io/opentelemetry/trace/SpanIdTest.java, api/src/test/java/io/opentelemetry/trace/TraceIdTest.java, api/src/test/java/io/opentelemetry/trace/TraceOptionsTest.java, api/src/test/java/io/opentelemetry/trace/samplers/SamplersTest.java, contrib/src/test/java/io/opentelemetry/contrib/trace/CurrentSpanUtilsTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySamplerTest.java
=> Use static methods instead of variables.

api/src/main/java/io/opentelemetry/trace/Span.java
Additional cleanup after https://github.com/open-telemetry/opentelemetry-java/pull/296
=> Fix comment in startSpan method

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, sdk/src/test/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySamplerTest.java
=> Clean up the Link handling in Span.

api/src/main/java/io/opentelemetry/trace/SpanContext.java
As a follow-up of https://github.com/open-telemetry/opentelemetry-java/pull/383#issuecomment-499525065.
=> Make invalid SpanContext package-private.

api/src/main/java/io/opentelemetry/trace/Link.java, api/src/main/java/io/opentelemetry/trace/SpanData.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/LinkTest.java, api/src/test/java/io/opentelemetry/trace/SpanDataLinkTest.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java
=> Make Link an interface.

api/src/main/java/io/opentelemetry/context/NoopScope.java, api/src/main/java/io/opentelemetry/tags/DefaultTagger.java, api/src/main/java/io/opentelemetry/tags/EmptyTagMap.java, api/src/main/java/io/opentelemetry/tags/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/tags/DefaultTaggerTest.java, sdk/src/test/java/io/opentelemetry/sdk/tags/TaggerSdkTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/309.
=> More cleanup on static variables.

api/src/main/java/io/opentelemetry/trace/util/Samplers.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, api/src/test/java/io/opentelemetry/trace/samplers/SamplersTest.java, api/src/test/java/io/opentelemetry/trace/util/SamplersTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
=> Move samplers to util package

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/SpanId.java, api/src/main/java/io/opentelemetry/trace/TraceId.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/TestUtils.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/392.
=> Use random IDs instead of invalid in default span.

api/src/main/java/io/opentelemetry/tags/TagMap.java, sdk/src/main/java/io/opentelemetry/sdk/tags/TagMapSdk.java, sdk/src/main/java/io/opentelemetry/sdk/tags/TaggerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/tags/ScopedTagMapTest.java, sdk/src/test/java/io/opentelemetry/sdk/tags/TagMapSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/tags/TagMapTestUtil.java
Implementation and tests mostly taken from OpenCensus.
Updates #284
=> Initial implementation for TagMapSdk and Builder.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
Updates #280 
Adding an empty implementation. More will come once Span class is defined.
=> Add span builder to SDK

api/src/main/java/io/opentelemetry/trace/Tracer.java
=> Tracer API: Fix doc regarding default propagation formats

api/src/main/java/io/opentelemetry/trace/util/Samplers.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, build.gradle, sdk/src/main/java/io/opentelemetry/sdk/distributedcontext/DistributedContextManagerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySampler.java
=> Fix all errorprone warnings, ignore genproto files.

sdk/src/main/java/io/opentelemetry/sdk/trace/TraceProtoUtils.java, sdk/src/main/proto/trace/v1/trace.proto, sdk/src/test/java/io/opentelemetry/sdk/trace/TraceProtoUtilsTest.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/279.
=> Add utilities to convert to Trace Protos in SDK.

api/src/main/java/io/opentelemetry/trace/Link.java
=> Remove public abstract from interface

api/src/main/java/io/opentelemetry/distributedcontext/DefaultDistributedContextManager.java, api/src/main/java/io/opentelemetry/distributedcontext/DistributedContext.java, sdk/src/main/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdk.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/ScopedDistributedContextTest.java
=> Remove DistributedContext.Builder.buildScoped()

api/src/main/java/io/opentelemetry/trace/SpanId.java, api/src/main/java/io/opentelemetry/trace/TraceId.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanImpl.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanImplTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
Resolves #280 
Resolves #431 
TODOs:
- Pass links from builder to span (can be done in a separate PR)
- return `DefaultSpan` if recording events is set to false.
=> Connect span builder and span in SDK

api/src/main/java/io/opentelemetry/distributedcontext/DistributedContext.java, api/src/main/java/io/opentelemetry/distributedcontext/EmptyDistributedContext.java, api/src/test/java/io/opentelemetry/distributedcontext/DefaultDistributedContextManagerTest.java, api/src/test/java/io/opentelemetry/distributedcontext/unsafe/ContextUtilsTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, sdk/src/main/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdk.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextManagerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextTestUtil.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/ScopedDistributedContextTest.java
=> Replace DistributedContext.getIterator with getEntries.

sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpanData.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TraceProtoUtils.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/ReadableSpanDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TraceProtoUtilsTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
=> Implement ReadableSpanData

api/src/main/java/io/opentelemetry/trace/Sampler.java, api/src/main/java/io/opentelemetry/trace/util/Samplers.java, api/src/test/java/io/opentelemetry/trace/util/SamplersTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySampler.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySamplerTest.java
=> Change Sampler.shouldSample to accept list of Link.

api/src/main/java/io/opentelemetry/metrics/Measure.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/410.
=> Change the order of measure type enum to match specs.

api/src/main/java/io/opentelemetry/trace/Span.java
=> Fix typo in isRecordingEvents

.travis.yml
Use the trusty distro, to make the environment safer (and have Travis back to green).
=> Make Travis use the trusty distro.

api/src/main/java/io/opentelemetry/trace/Span.java, sdk/src/main/proto/trace/v1/trace.proto
Changes are generated with
$ misspell -w .
See https://github.com/client9/misspell
=> Fix all typos

sdk/src/main/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSampledSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessorTest.java
Based on the specification https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-exporter.md
/cc @tigrannajaryan
=> Add ResultCode to the SpanExporter interface.

.circleci/config.yml, README.md
Resolves #466 
The passed CI can be seen on my fork https://circleci.com/gh/pavolloffay/openconsensus
=> Add CircleCI support

api/src/main/java/io/opentelemetry/OpenTelemetry.java
Fix service provider not found exception message.
=> Fix service provider not found exception message

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/context/Scope.java, api/src/main/java/io/opentelemetry/context/propagation/BinaryFormat.java, api/src/main/java/io/opentelemetry/context/propagation/HttpTextFormat.java, api/src/main/java/io/opentelemetry/distributedcontext/DistributedContextManager.java, api/src/main/java/io/opentelemetry/distributedcontext/spi/DistributedContextManagerProvider.java, api/src/main/java/io/opentelemetry/distributedcontext/unsafe/ContextUtils.java, api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/internal/Utils.java, api/src/main/java/io/opentelemetry/metrics/MeasureBatchRecorder.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/main/java/io/opentelemetry/metrics/spi/MeterProvider.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Link.java, api/src/main/java/io/opentelemetry/trace/Sampler.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/main/java/io/opentelemetry/trace/Tracer.java, api/src/main/java/io/opentelemetry/trace/propagation/BinaryTraceContext.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/main/java/io/opentelemetry/trace/spi/TracerProvider.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/main/java/io/opentelemetry/trace/util/Events.java, api/src/main/java/io/opentelemetry/trace/util/Links.java, api/src/main/java/io/opentelemetry/trace/util/Samplers.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/402
=> Add thread safe annotations for the public API.

api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextManagerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
This fixes the build for the #504, I am not sure why this was not the case before.
=> Fix android 14 build for sdk.

CONTRIBUTING.md
Follow up of https://github.com/open-telemetry/opentelemetry-java/pull/504#issuecomment-524002145.
=> Update CONTRIBUTING.md after using git submodule and make

.gitmodules
=> Set proto submodule to upstream repository

build.gradle, opentracing_shim/build.gradle, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/actorpropagation/ActorPropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/promisepropagation/PromisePropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/suspendresumepropagation/SuspendResumePropagationTest.java
=> replace assertj with Truth

api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/CounterLong.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Gauge.java, api/src/main/java/io/opentelemetry/metrics/Metric.java, api/src/main/java/io/opentelemetry/metrics/Observer.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java
In a future PR will add Negative/NonNegative support for Measure.
=> Add monotonic option for Gauge/Observer/Counter

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
Implement the latest update about links from the specs.
=> Remove addLink API from the Span

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java
=> Small cleanup to remove some duplicate code.

sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricData.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricDescriptor.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDescriptorTest.java
After this PR will add the builders for all metric types.
=> Add metrics data and metric descriptor, to avoid using proto

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanDataTest.java
this fixes the broken master build.
=> Timestamp moved underneath the SpanData PR.

api/src/main/java/io/opentelemetry/metrics/Meter.java, build.gradle, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/TestUtils.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/promisepropagation/PromisePropagationTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessorTest.java, sdk_contrib/testbed/src/test/java/io/opentelemetry/sdk/contrib/trace/testbed/TestUtils.java
=> Update errorprone, remove stale disabled checks.

proto/build.gradle
=> Remove unnecessary dependency in proto on API.

opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/TestUtils.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java, sdk_contrib/inmemory_export/src/main/java/io/opentelemetry/sdk/contrib/trace/export/InMemoryTracing.java, sdk_contrib/testbed/src/test/java/io/opentelemetry/sdk/contrib/trace/testbed/TestUtils.java
Indirectly related to https://github.com/open-telemetry/opentelemetry-specification/pull/205#discussion_r315617112
=> Report span which is recording events

opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java
whoops! this got mangled when switching over to use JUL.
/cc @carlosalberto
=> Fix the logging of the error message to use the JUL proper formatting.

exporters/logging/build.gradle, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingExporterTest.java, settings.gradle
=> Create a Logging span exporter

exporters/jaeger/build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otprotocol/README.md, exporters/otprotocol/build.gradle, exporters/otprotocol/src/main/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtils.java, exporters/otprotocol/src/test/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtilsTest.java, settings.gradle
=> Move TraceProtoUtils to otprotocol artifact.

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
This implements https://github.com/open-telemetry/opentelemetry-specification/pull/290
=> Rename isRecordingEvents to isRecording

settings.gradle
=> Restore gradle modules deleted when rebase

exporters/otprotocol/src/main/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtils.java, exporters/otprotocol/src/test/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtilsTest.java, sdk/build.gradle, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java
=> Move traceconfig proto helper out of SDK and remove protobuf dependency

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
=> Remove setRecordEvents option from the Span.Builder

sdk/src/main/java/io/opentelemetry/sdk/distributedcontext/DistributedContextManagerSdk.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/605
=> Fix OpenTracingShim to run with SDK without baggages.

opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/TraceShimTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
Although we have the extensive testbed section,
we need some basic tests for non-exotic scenarios,
and this is part of that intention.
=> Add tests for TraceShim/TracerShim.

all/build.gradle, api/src/main/java/io/opentelemetry/distributedcontext/EmptyDistributedContext.java, api/src/main/java/io/opentelemetry/distributedcontext/EntryMetadata.java, api/src/main/java/io/opentelemetry/trace/Status.java, api/src/main/java/io/opentelemetry/trace/TraceFlags.java, api/src/main/java/io/opentelemetry/trace/Tracestate.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, exporters/jaeger/build.gradle, proto/build.gradle, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Some minor cleanups

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Span.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemoryTracingTest.java, exporters/otprotocol/src/main/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtils.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
=> Move sampler to the SDK

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java
=> Set default binary propagator.

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TimedEvent.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TimedEventTest.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/633
=> Implement support for epoch timestamps for events

sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricData.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDataTest.java
=> Remove usage of Timestamp in metrics

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkFactory.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkFactoryTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/640
Also this PR moves the setters/getters for config, processors to the factory which owns the shared state.
=> Extract the shared state between Tracers in TracerSharedState.

README.md, build.gradle
=> Increase version to 0.2.0-SNAPSHOT

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkFactory.java
=> Ensure that only one tracer is created

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java
=> Fix NPE when using non-OK status with a null description

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java
The tag types were not being set.
Resolves #665 
Signed-off-by: Gary Brown <gary@brownuk.com>
=> Set the type of the tags within the Jaeger exporter

sdk/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java, sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkFactory.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkFactoryTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/670
=> Move InstrumentationLibraryInfo to common to be shared with metrics.

api/src/main/java/io/opentelemetry/metrics/CounterDouble.java, api/src/main/java/io/opentelemetry/metrics/CounterLong.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/GaugeDouble.java, api/src/main/java/io/opentelemetry/metrics/GaugeLong.java, api/src/main/java/io/opentelemetry/metrics/MeasureDouble.java, api/src/main/java/io/opentelemetry/metrics/MeasureLong.java, api/src/main/java/io/opentelemetry/metrics/Metric.java, api/src/main/java/io/opentelemetry/metrics/ObserverDouble.java, api/src/main/java/io/opentelemetry/metrics/ObserverLong.java, api/src/test/java/io/opentelemetry/metrics/CounterDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/CounterLongTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeLongTest.java, api/src/test/java/io/opentelemetry/metrics/ObserverDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/ObserverLongTest.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMetricBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
=> rename getBound/removeBound to bind/unbind

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Demonstrates the error that #699 describes.
I plan to add a fix too. EDIT: Fix added in f09caa34b78f941926e3e05bad5a5e7ba258dc0e.
=> Synchronize toSpanData properly for un-ended Span.

api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleGauge.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/DoubleObserver.java, api/src/main/java/io/opentelemetry/metrics/Gauge.java, api/src/main/java/io/opentelemetry/metrics/Instrument.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongGauge.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, api/src/main/java/io/opentelemetry/metrics/LongObserver.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/main/java/io/opentelemetry/metrics/Observer.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMetricBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricData.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/stats/Aggregation.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/InstrumentDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/InstrumentDescriptorTest.java
Resolves #714 
This also does some javadoc cleanup that is related.
=> Rename Metric to Instrument

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilder.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
I missed these classes the first time around.
=> More renaming of Metric to Instrument

sdk/src/main/java/io/opentelemetry/sdk/trace/RandomIdsGenerator.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkRegistry.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java
=> Use a thread local to hold random instances to avoid thread contention.

api/src/main/java/io/opentelemetry/trace/SpanContext.java, api/src/test/java/io/opentelemetry/trace/SpanContextTest.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java
=> convert the SpanContext to use Autovalue

api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleGaugeTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongGaugeTest.java, api/src/test/java/io/opentelemetry/metrics/LongObserverTest.java
resolves #705 
@Oberon00 I think I got the rest of them with this. If we find any more, we can clean them up as we go along.
=> remove some more usages of the bare word "bound"

sdk/src/main/java/io/opentelemetry/sdk/resources/ResourceConstants.java
=> Add constants for resource label semantic conventions

sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
=> Implement a timeout on batch exports.

sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java
=> Fix build after merging race condition

README.md
=> Move the list of approvers/maintainers in the repo.

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkLongMeasure.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkLongMeasureTest.java
=> Add Measure metrics

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkLongMeasure.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
=> Fixing naming convention for boolean getter

sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricData.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDataDescriptorTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDataTest.java
=> Rename Int64 to Long in metrics data.

sdk/src/main/java/io/opentelemetry/sdk/metrics/LabelSetSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java
=> Rename SdkLabelSet to LabelSetSdk

sdk/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java
This improves the performance by avoiding on map lookup.
=> Use a more clean pattern for putIfAbsent

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java
Split from https://github.com/open-telemetry/opentelemetry-java/pull/831
=> Add getters and tests for AbstractInstrument

sdk/src/main/java/io/opentelemetry/sdk/trace/RandomIdsGenerator.java
Now that we can use all java7 capabilities it is time to clean some hacks :)
=> Use ThreadLocalRandom insted of our own class.

sdk/src/test/java/io/opentelemetry/sdk/correlationcontext/CorrelationContextManagerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
Now that we can use all java7 capabilities it is time to clean some hacks :)
=> Use try-with-resource in SDK where possible

sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java
Also copy MetricExporter, MetricProducerManager
and MetricProducer interfaces from OpenCensus.
=> Add metric.export package to SDK

sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AggregatorFactory.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/NoopAggregator.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregatorTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregatorTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/NoopAggregatorTest.java
=> Add AggregatorFactory and tests for aggregators

sdk/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/data/MetricDataTest.java
=> Add Resource and InstrumentationLibraryInfo to metrics

sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricProducer.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/README.md
=> Add MetricProducer interface and explain how to use

.circleci/config.yml, build.gradle
=> switch CI to use java11, rather than java9

build.gradle
=> Add compileJmhJava to the errorprone configuration

all/build.gradle, sdk_contrib/auto_config/README.md, sdk_contrib/auto_config/build.gradle, settings.gradle
@prydin Here's where we can start building stuff.
related to #849
=> Add a module for auto-instrumentation agent configuration bridge code.

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserver.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverTest.java
Next PR:
* Move Abstract{$INSTRUMENT}Builder as an inner class to Abstract{$INSTRUMENT}
=> Add abstract methods for every instrument type

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeterProvider.java, api/src/main/java/io/opentelemetry/metrics/DefaultMetricsProvider.java, api/src/main/java/io/opentelemetry/metrics/MeterProvider.java, api/src/main/java/io/opentelemetry/metrics/spi/MetricsProvider.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, sdk/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/spi/MetricsProviderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/spi/MetricsProviderSdkTest.java
This addresses #794 
Specification: [link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-metrics-user.md#obtaining-a-meter)
=> Rename MeterRegistry -> MeterProvider

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java
=> Align valid metric names with spec

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentWithBinding.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserver.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/ActiveBatcher.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/Batcher.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/Batchers.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java
Split from https://github.com/open-telemetry/opentelemetry-java/pull/831 with a no-op batcher for all the instruments.
=> Add an abstract helper class for all instruments with bindings

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongObserverTest.java
Follow up PR to address https://github.com/open-telemetry/opentelemetry-java/pull/877#discussion_r381136475
=> Move all metric name checks into StringUtils

sdk/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
Fixes #880 changing the signature of `io.opentelemetry.sdk.trace.Sampler#shouldSample`
=> Change Sampler interface

api/src/test/java/io/opentelemetry/trace/propagation/BinaryTraceContextTest.java, build.gradle, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/TraceShimTest.java
See more details about the error pattern here:
https://github.com/google/error-prone/blob/master/docs/bugpattern/TestExceptionChecker.md
=> Remove the exclusion of TestExceptionRefactoring from errorprone config.

sdk/src/main/java/io/opentelemetry/sdk/metrics/InstrumentRegistry.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSharedState.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/InstrumentRegistryTest.java
Few TODOs left in the registry, but this is a first naive implementation.
=> Add an InstrumentRegistry that tracks all created Instruments

QUICKSTART.md, README.md
I have added a Quick Start Markdown file that describes how to configure the SDK and how to use the OTel API to create Spans. 
This addresses #798 and #795
=> Quick Start guide

sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java, sdk_contrib/async_processor/src/test/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorAsyncSpanProcessorTest.java
=> Block Disruptor until flush is performed

build.gradle, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkBenchmark.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/LongCounterSdkBenchmark.java
=> Add minimal benchmarks for Counter instruments

sdk/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/data/MetricDataTest.java
Step one in adding the MinMaxSumCount aggregation
=> Add summary metric data type

sdk_contrib/auto_config/src/main/java/io/opentelemetry/sdk/contrib/auto/config/Config.java, sdk_contrib/auto_config/src/main/java/io/opentelemetry/sdk/contrib/auto/config/SpanExporterFactory.java
Added interfaces for creating SpanExporters from auto instrumentation agents according to discussion in  #849.
=> Added SpanExporterFactory and Config

sdk/src/jmh/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountBenchmark.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCount.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCount.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountTest.java
And, simple benchmarks for them.
=> Add aggregators for double & long MinMaxSumCount aggregations

sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java
=> Make sure to shutdown the exporter when the processor is shut down.

api/src/main/java/io/opentelemetry/correlationcontext/DefaultCorrelationContextManagerProvider.java, api/src/main/java/io/opentelemetry/correlationcontext/unsafe/CorrelationContextInScope.java, api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeterProvider.java, api/src/main/java/io/opentelemetry/metrics/DefaultMetricsProvider.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBinding.java, api/src/main/java/io/opentelemetry/metrics/LabelSet.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, api/src/main/java/io/opentelemetry/metrics/Observer.java, api/src/main/java/io/opentelemetry/trace/BigendianEncoding.java, api/src/main/java/io/opentelemetry/trace/DefaultTraceProvider.java, api/src/main/java/io/opentelemetry/trace/DefaultTracerProvider.java, api/src/main/java/io/opentelemetry/trace/unsafe/SpanInScope.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LabelSetSdk.java
=> Add missing thread safety & immutable annotations in the API.

exporters/jaeger/build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java
=> Small fixes in Jaeger exporter.

exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java, sdk/src/test/java/io/opentelemetry/sdk/trace/data/SpanDataTest.java
=> Remove the child count from the SpanData, and callers.

exporters/jaeger/README.md, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/spi/TraceProviderSdk.java
=> Add create Jaeger exporter with default settings and from environment settings

exporters/otlp/build.gradle, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/CommonAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/ResourceAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/CommonAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/ResourceAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, proto/build.gradle
Updates https://github.com/open-telemetry/opentelemetry-java/issues/793
=> Add OTLP trace implementation

sdk/src/main/java/io/opentelemetry/sdk/resources/EnvVarResource.java, sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/src/main/java/io/opentelemetry/sdk/resources/package-info.java, sdk/src/test/java/io/opentelemetry/sdk/resource/ResourceTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk_contrib/aws_v1_support/src/test/java/io/opentelemetry/sdk/contrib/trace/aws/Ec2ResourceTest.java
=> Rename resource labels to attributes

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/trace/propagation/B3Propagator.java, api/src/test/java/io/opentelemetry/internal/StringUtilsTest.java, api/src/test/java/io/opentelemetry/trace/propagation/B3PropagatorTest.java
Fixes #853.
Adds support for B3 propagation, including both single and multi header formats.
=> Add B3 propagator

api/src/main/java/io/opentelemetry/internal/Utils.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkBenchmark.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/LongCounterSdkBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
=> Remove LabelSet from non-bound instrument usage

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/CommonAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/ResourceAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/CommonAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/ResourceAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
@bogdandrutu looks like master got race-conditioned.
=> fix some broken imports

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/BatchRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LabelSetSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
The next step in making #992 a reality.
=> Remove batch recorder LabelSet usage

api/src/main/java/io/opentelemetry/metrics/DoubleObserver.java, api/src/main/java/io/opentelemetry/metrics/LongObserver.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentWithBinding.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/ActiveBatcher.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/Batcher.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/Batchers.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongObserverSdkTest.java
=> Remove LabelSet from Observer API

sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricsReader.java
This is a final bit of clean up from @bogdandrutu's work in #944
=> Add a helper class that reads metrics every X seconds.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/CommonAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/MetricAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/ResourceAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/793
=> Add OtlpMetricExporter, fix copyright years.

sdk/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java
=> Add a very basic benchmark for the span implementation

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBinding.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleMeasureTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongMeasureTest.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkBenchmark.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/LongCounterSdkBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java
=> remove LabelSet from the Instrument binding API

QUICKSTART.md
Create basic span example should be with try with resources
=> Try with resources in example

exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
=> Add a shutdown method on the metric exporter interface.

examples/jaeger/build.gradle, examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java
=> feat: update example for OT 0.2.4

settings.gradle
Set the projectDir from the project name with a few String.replace calls instead of manually.
=> Reduce repetitions in settings.gradle

build.gradle
=> Update grpc, protobuf, and few test dependencies

.circleci/config.yml, build.gradle, exporters/jaeger/build.gradle, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, exporters/jaeger/src/test/resources/logback-test.xml
End to end test with Jaeger all in one
Should solve https://github.com/open-telemetry/opentelemetry-java/issues/498
=> test: end to end opentelemetry test with jaeger exporter

QUICKSTART.md
Updates #1002 
Some copy paste from Python's guide https://github.com/open-telemetry/opentelemetry-python/blob/master/docs/getting-started.rst#adding-metrics
with Java example
=> Fill in the Metrics details in the Getting Started guide.

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java
=> Add more documentation on updating the TraceConfig on the TracerProvider

README.md
including updating one of the maintainers' corporate affiliation
resolves #1069
=> update README with latest information

api/src/main/java/io/opentelemetry/OpenTelemetry.java
=> use a reentrant lock as the mutex for initializing/reading the global instance

sdk/src/test/java/io/opentelemetry/sdk/trace/StressTestRunner.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
=> A simple stress-test for the TracerSdk.

contrib/trace_propagators/build.gradle, contrib/trace_propagators/src/jmh/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagatorContextExtractBenchmark.java, contrib/trace_propagators/src/jmh/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagatorContextInjectBenchmark.java
Bring the build back to green.
=> Update the Jaeger benchmarks code.

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingMetricExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingSpanExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingMetricExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, sdk/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java
=> Add flush method to [Span|Metric] Exporters

exporters/prometheus/src/main/java/io/opentelemetry/exporters/prometheus/PrometheusCollector.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java, sdk/src/main/java/io/opentelemetry/sdk/correlationcontext/CorrelationContextSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessor.java
Inspired by https://github.com/open-telemetry/opentelemetry-java/pull/1128
=> Use java Objects.requireNotNull

api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextExtractBenchmark.java, api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextInjectBenchmark.java
Should solve https://github.com/open-telemetry/opentelemetry-java/issues/933
=> Iterations benchmark

sdk/src/main/java/io/opentelemetry/sdk/common/export/ConfigBuilder.java
=> Add some clarifying javadoc to the ConfigBuilder class.

contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3Propagator.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorExtractor.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjector.java
=> Extracted Extractor and Injector code from B3Propagator

CHANGELOG.md
In a followup PR we need to add things to the changelog for this release, also we should start asking for changelog changes for major PRs.
=> Update changlog to reflect already released changes

QUICKSTART.md
Fixes the remaining parts of #1002
=> Update the QUICKSTART with more metrics.

.github/ISSUE_TEMPLATE/feature_request.md
I know that I did create a branch on this repo, but the github UI helped me created this template and I did not have other option. Thanks for understanding.
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/493
=> Add template for feature request

build.gradle
https://github.com/open-telemetry/opentelemetry-java/issues/1111
=> build: using external boms

build.gradle
Do NOT use merge from the UI to merge this PR because it squashes the commits and does not push the tag. I will manually merge once approved.
=> Add 2 individual commits and a tag to the first commit for release

.github/ISSUE_TEMPLATE/bug_report.md
Follow up from https://github.com/open-telemetry/opentelemetry-java/pull/1170#pullrequestreview-405111875 (race condition when merging).
Updates #493.
=> Extend bug report template

api/src/main/java/io/opentelemetry/OpenTelemetry.java
I think that's the smallest PR I've ever created but I couldn't just leave it there after I saw it 😄
=> Fix typo in OpenTelemetry.getTracerProvider

sdk_contrib/auto_config/src/main/java/io/opentelemetry/sdk/contrib/auto/config/MetricExporterFactory.java
=> Add a MetricExporterFactory so auto-instrumentation can use SPI to load an exporter

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Fix remove attributes from span after termination

api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeterProvider.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, api/src/main/java/io/opentelemetry/metrics/SyncInstrument.java, api/src/main/java/io/opentelemetry/metrics/SynchronousInstrument.java, api/src/test/java/io/opentelemetry/metrics/BatchRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleMeasureTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongMeasureTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractSyncInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java
Split from https://github.com/open-telemetry/opentelemetry-java/pull/1201
=> Cleanup names in metrics and ensure consistency with specs

examples/build.gradle, examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldClient.java, examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldClientStream.java, examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldServer.java, examples/http/build.gradle, examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java, examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java, examples/sdk-usage/build.gradle, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
Note: In a couple cases I had to add the grpc-context dependency explicitly to the build.gradle. I suspect something isn't working quite right with the publishing or consumption of the boms.
=> Update the examples to work with 0.5.0-SNAPSHOT

sdk/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
This PR will be split into smaller PRs:
* #1202 
* #1200 
* #1208 
* #1210
=> Add CounterUpDown implementation in the SDK

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
=> Unify config api

README.md
=> Update owners in readme

build.gradle
There are 2 commits that will be merged as separate commits.
=> Release v0.4.1

sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/1220
=> Add implementation for UpDownSumObservers

QUICKSTART.md, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/1234
=> Rename [Batch|Simple]SpansProcessor to [Batch|Simple]SpanProcessor

api/src/main/java/io/opentelemetry/metrics/BatchRecorder.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleValueRecorder.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/LongValueRecorder.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/BatchRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleValueRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/LongValueRecorderTest.java, sdk/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
TODO: In a separate PR https://github.com/open-telemetry/opentelemetry-java/issues/1244
=> Rename Measure to ValueRecorder, fix comments and javadoc

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/test/java/io/opentelemetry/metrics/DoubleValueRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/LongValueRecorderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/1244
=> Remove check for non-negative values in ValueRecorder

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanWrapper.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
And, remove an extra wrapping of links which wasn't needed.
=> Add tests to verify immutability of the SpanData representation

sdk/src/main/java/io/opentelemetry/sdk/resources/EnvVarResource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/resources/EnvVarResourceTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
In this case, for the EnvVarResource and the SimpleSpanProcessor
=> Add a few missing unit tests

sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
=> Fix Jaeger remote sampler flaky test

api/src/main/java/io/opentelemetry/trace/Span.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Do not allow adding attributes, links after startSpan.

build.gradle, exporters/jaeger/build.gradle, exporters/otlp/build.gradle, exporters/prometheus/build.gradle, exporters/zipkin/build.gradle, proto/build.gradle, sdk/build.gradle, sdk_contrib/async_processor/build.gradle, sdk_contrib/jaeger_remote_sampler/build.gradle, sdk_contrib/otproto/build.gradle, sdk_contrib/testbed/build.gradle
=> Apply bom imports only if needed

exporters/zipkin/README.md
=> Update Zipkin readme

sdk/src/main/java/io/opentelemetry/sdk/metrics/Batchers.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
Currently we use a delta batcher with MinMaxSumCount as the default batcher for this. There are some questions about what should be the start time for this points. We can address this later.
=> Add implementation for value observers

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/common/export/ConfigBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes useless code and adds more tests for `ConfigBuilder` classes
=> Cleanup and additional tests for ConfigBuilder

api/src/main/java/io/opentelemetry/metrics/AsynchronousInstrument.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleSumObserver.java, api/src/main/java/io/opentelemetry/metrics/DoubleUpDownSumObserver.java, api/src/main/java/io/opentelemetry/metrics/DoubleValueObserver.java, api/src/main/java/io/opentelemetry/metrics/LongSumObserver.java, api/src/main/java/io/opentelemetry/metrics/LongUpDownSumObserver.java, api/src/main/java/io/opentelemetry/metrics/LongValueObserver.java, api/src/test/java/io/opentelemetry/metrics/DoubleSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleUpDownSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleValueObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongUpDownSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongValueObserverTest.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/1230
=> Remove duplicate Result interfaces

sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
=> Make the IntervalMetricReader robust to exporter failures

exporters/prometheus/src/main/java/io/opentelemetry/exporters/prometheus/MetricAdapter.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/1341
=> Simplify prometheus metrics adapter

build.gradle, buildscripts/checkstyle.xml, settings.gradle
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/1350
=> Update animalsniffer and disable for tests

api/src/main/java/io/opentelemetry/OpenTelemetry.java
These API's weren't added until 0.5.0.
=> Fix OpenTelemetry since versions.

examples/settings.gradle, examples/zipkin/README.md, examples/zipkin/build.gradle, examples/zipkin/src/main/java/io/opentelemetry/example/ZipkinExample.java
Fixes #1137 
Added example module for Zipkin ( issue #1137 ). This module looks a lot like jaeger example.
Also used shutdown( ) on TracerSdkProvider ( issue #1382) in zipkin example module only.
=> Added example module for zipkin trace exporter

CHANGELOG.md, QUICKSTART.md, README.md
=> Update the docs for the 0.6.0 release.

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
=> Add semantic attributes for messaging

sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregator.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageServer.java
These got merged from a branch without the errorprone update.
=> Fix errorprone errors.

sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/IndexZPageHandler.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandler.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageHandler.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageServer.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageStyle.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/IndexZPageHandlerTest.java
Implemented an index page for zPages that includes links to available zPages.
This PR addresses [issue #1416 ](https://github.com/open-telemetry/opentelemetry-java/issues/1416)
=> Implemented index page for zPages

sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/SpanBucketTest.java
=> Added unit tests for SpanBucket

sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/IndexZPageHandler.java
As discussed in https://github.com/open-telemetry/opentelemetry-java/pull/1423#discussion_r456149818
=> Removed nullable annotation for ZPagesHandlers container in IndexZPageHandler

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
=> Change numeric attributes to be numeric

sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandler.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageHttpHandler.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandlerTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/ZPageHttpHandlerTest.java
=> Removed URLEncoder from TracezZPageHandler

api/src/main/java/io/opentelemetry/common/ImmutableKeyValuePairs.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
=> Forbid empty/null keys

sdk/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/PerOperationSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSampler.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSamplerTest.java, sdk_extensions/otproto/src/main/java/io/opentelemetry/sdk/extensions/otproto/TraceProtoUtils.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/962
=> Refactor decision to sampling result

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
Fix [#1456](https://github.com/open-telemetry/opentelemetry-java/issues/1456)
=> Update database attributes

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/resources/EnvAutodetectResource.java, sdk/src/main/java/io/opentelemetry/sdk/resources/EnvVarResource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/test/java/io/opentelemetry/sdk/resources/EnvAutodetectResourceTest.java, sdk/src/test/java/io/opentelemetry/sdk/resources/EnvVarResourceTest.java
for [https://github.com/open-telemetry/opentelemetry-java/issues/1462](https://github.com/open-telemetry/opentelemetry-java/issues/1462)
=> Support system property otel.resource.attributes corresponding to OTEL_RESOURCE_ATTRIBUTES

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/resources/EnvAutodetectResource.java, sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java
for [https://github.com/open-telemetry/opentelemetry-java/issues/1472](https://github.com/open-telemetry/opentelemetry-java/issues/1472)  
@carlosalberto @anuraaga Please take a look.
=> Hide EnvAutodetectResource ro reduce public classes

.github/CODEOWNERS, README.md
Will be merged only if @anuraaga approves it.
=> Propose @anuraaga as approver

examples/grpc/build.gradle, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
looks like sampling changes didn't make it into the examples. And, some grpc issues with building the grpc examples.
=> Fix examples from the latest updates.

build.gradle
for [https://github.com/open-telemetry/opentelemetry-java/issues/1483](https://github.com/open-telemetry/opentelemetry-java/issues/1483)
@jkwatson @iNikem @carlosalberto @Oberon00 Would you mind checking to see if it works?
=> Remove javadoc warnings

extensions/logging/log4j2_extensions/src/test/java/io/opentelemetry/contrib/logging/log4j2/TraceContextDataProviderTest.java
for [https://github.com/open-telemetry/opentelemetry-java/issues/1506](https://github.com/open-telemetry/opentelemetry-java/issues/1506)
@jkwatson Can you help to review if that makes sense?
=> Fix possible test failure

build.gradle, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, integration_tests/src/test/java/io/opentelemetry/JavaSevenCompatibilityIntegrationTest.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
Last ones are complicated extensions with no jupiter support yet will work upstream with them to get it.
=> Migrate most remaining tests to JUnit5.

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
=> Update to latest RPC semantic attributes.

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
This would be very helpful for debugging our sporadic test failures in opentelemetry-java-instrumentation.
Let me know if there are other fields you'd like included. I just included the ones I thought would be most useful.
=> Add RecordEventsReadableSpan toString

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
This is in order to do a patch release with this fix for the 0.7.x series.
PS - After this is merged, I will issue a patch release ;)
=> Cherry-pick commit 6c31db4521c3c0f78a62ec061efd0ce3ae3b8513

api/src/main/java/io/opentelemetry/trace/Span.java
I think this captures the thoughts in https://github.com/open-telemetry/opentelemetry-specification/issues/796 let me know
=> Clarify timestamps of events in javadoc.

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleValueRecorder.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/LongValueRecorder.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleUpDownCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleValueRecorderTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongUpDownCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongValueRecorderTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
for [https://github.com/open-telemetry/opentelemetry-java/issues/1533](https://github.com/open-telemetry/opentelemetry-java/issues/1533)
cc @kenfinnigan @jkwatson
=> Add convenience methods for when empty labels are used.

api/README.md
=> Update android API text

examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java
=> instead of waiting use TracerSdkProvider.shutdown() in examples

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
=> BatchSpanProcessor now starts daemon timer thread

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
=> Export InstrumentationLibraryInfo to Zipkin and Jaeger

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/PerOperationSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSampler.java
=> prevent parent spanContext from being null in Samplers

api/src/main/java/io/opentelemetry/common/Attributes.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1553](https://github.com/open-telemetry/opentelemetry-java/issues/1553)
=> Create a static method on Attributes to create an Attributes builder from ReadableAttributes

api/src/main/java/io/opentelemetry/trace/SpanId.java, api/src/main/java/io/opentelemetry/trace/TraceId.java
=> Remove two unused internal methods.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigSystemPropertiesTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
Github wasn't smart enough to detect this conflict. This should fix it up!
=> Fix for a mashed up PR merge.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Remove link and parent sampling decision from Probability sampler

exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java
fixes #1608 
I had originally tried to add a ```.join``` to the result returned from ```exporter.export()``` in the test but the error still occurred as the ```deadlineMs``` was low enough for gRPC DEADLINE_EXCEEDED to happen before the result was returned to the test.  The Future to execute the gRPC call export was on occasions not completing before the original deadline (500ms) is breached so I have doubled this to 1000ms and I've not experienced this failure locally since.
I've also tidied up ```testExport_DeadlineSetPerExport```.   The sleeps in the Test were not neccessary so I removed them.  I also added a mechanism to simulate a big export in the ```FakeCollector``` and check that this fails as well as successful export.
=> fix for OtlpGrpcMetricExporterTest 

CHANGELOG.md, api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextExtractBenchmark.java, api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextInjectBenchmark.java, api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, extensions/trace_propagators/src/jmh/java/io/opentelemetry/extensions/trace/propagation/PropagatorContextExtractBenchmark.java, extensions/trace_propagators/src/jmh/java/io/opentelemetry/extensions/trace/propagation/PropagatorContextInjectBenchmark.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/AwsXRayPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagator.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/AwsXRayPropagatorTest.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagatorTest.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/TraceMultiPropagatorTest.java
=> Have Propagators expose only a singleton instance

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporter.java, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java
=> add javadoc to InMemorySpanExporter shutdown() method

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigSystemPropertiesTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/PerOperationSampler.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerTest.java, sdk_extensions/otproto/src/main/java/io/opentelemetry/sdk/extensions/otproto/TraceProtoUtils.java, sdk_extensions/otproto/src/test/java/io/opentelemetry/sdk/extensions/otproto/TraceProtoUtilsTest.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TraceConfigzZPageHandler.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TraceConfigzZPageHandlerTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1573](https://github.com/open-telemetry/opentelemetry-java/issues/1573)
=> Rename ProbabilitySampler to TraceIdRatioBased

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/CommonProperties.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/package-info.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
=> Update env var names

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java
=> Change built-in SpanProcessor implementations to ignore more than one shutdown call

context_prop/src/main/java/io/opentelemetry/context/propagation/DefaultContextPropagators.java, context_prop/src/test/java/io/opentelemetry/context/propagation/DefaultPropagatorsTest.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/TraceMultiPropagator.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/TraceMultiPropagatorTest.java
=> de-duplicate fields in TraceMultiPropagator

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
See this change: https://github.com/open-telemetry/opentelemetry-specification/pull/972
=> Remove the obsolete HTTP_STATUS_TEXT semantic attribute.

exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
=> Update zipkin attribute names to match the spec.

sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/AwsResourceConstants.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/BeanstalkResource.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/Ec2Resource.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/EcsResource.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/resource/BeanstalkResourceTest.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/resource/Ec2ResourceTest.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/resource/EcsResourceTest.java
Need to set in SDK or the span looks like it could be from any cloud.
=> Fill cloud.provider for AWS resources.

opentracing_shim/README.md
=> add OpenTracing Shim usage

api/src/main/java/io/opentelemetry/OpenTelemetry.java, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java
=> Change the default Propagator in the API to be a no-op

api/src/main/java/io/opentelemetry/common/Attributes.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
=> Add overrides to allow using a long key with an int value.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/CommonProperties.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
=> fix the backwards TLS/insecure config options

sdk/tracing/build.gradle
=> Fix wrong usage of tracing in the sdk's module name trace package

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
=> update the zipkin and jaeger attributes for the instrumentation library info

exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableEvent.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, testing_internal/src/test/java/io/opentelemetry/sdk/trace/TestSpanDataTest.java
=> Rename EventImpl to ImmutableEvent

README.md
Also fix the README components list to use English sentences.
=> Fix reference to correlation context

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/baggage/DefaultBaggageManager.java, api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/internal/Utils.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Status.java, api/src/main/java/io/opentelemetry/trace/TraceId.java, api/src/main/java/io/opentelemetry/trace/TraceState.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/internal/UtilsTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/StringUtils.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessor.java, sdk_extensions/logging/src/main/java/io/opentelemetry/sdk/logging/LogSinkSdkProvider.java, sdk_extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessor.java
=> Remove unnecessary methods from api/internal

exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatus.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk_extensions/tracing_incubator/src/test/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilderTest.java
=> Remove helper method withDescription from ImmutableStatus

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk_extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/errorreporting/ErrorReportingTest.java, sdk_extensions/zpages/src/jmh/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorBenchmark.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandlerTest.java
=> Add overload for setStatus without description, fix usages

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatus.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusTest.java
=> Avoid creating new status objects when null description

exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableEvent.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableLink.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatus.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusTest.java, sdk_extensions/tracing_incubator/src/test/java/io/opentelemetry/sdk/extensions/incubator/trace/data/DelegatingSpanDataTest.java, sdk_extensions/tracing_incubator/src/test/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilderTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessorTest.java, testing_internal/src/test/java/io/opentelemetry/sdk/trace/TestSpanDataTest.java
=> Remove SpanData implementation classes from public API.

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1757](https://github.com/open-telemetry/opentelemetry-java/issues/1757)
=> Fix specification link in SemanticAttributes.java

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
=> Make the RERS return isRecording=false after it has ended.

all/build.gradle, context/build.gradle
Forgot to add the line of magic, noticed when trying to depend on the snapshots.
=> Publish -context package

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/PerOperationSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSampler.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
=> toString calls through getDescription

api/src/main/java/io/opentelemetry/trace/PropagatedSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/main/java/io/opentelemetry/trace/StatusCode.java, api/src/test/java/io/opentelemetry/trace/PropagatedSpanTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, extensions/trace_utils/src/main/java/io/opentelemetry/extensions/trace/CurrentSpanUtils.java, extensions/trace_utils/src/test/java/io/opentelemetry/extensions/trace/CurrentSpanUtilsTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatus.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusTest.java, sdk_extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/errorreporting/ErrorReportingTest.java, sdk_extensions/tracing_incubator/src/test/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilderTest.java, sdk_extensions/zpages/src/jmh/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorBenchmark.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregator.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanBuckets.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandler.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandlerTest.java
=> rename  StatusCanonicalCode to StatusCode

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/MetricAdapterTest.java, exporters/prometheus/src/main/java/io/opentelemetry/exporters/prometheus/MetricAdapter.java, exporters/prometheus/src/test/java/io/opentelemetry/exporters/prometheus/MetricAdapterTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/Aggregations.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
=> Add Gauge metrics and hook them up to the LastValue aggegrator and the OTLP and Prometheus exporters.

context/src/main/java/io/opentelemetry/context/LazyStorage.java, context/src/test/java/io/opentelemetry/context/LazyStorageTest.java
fixes [https://github.com/open-telemetry/opentelemetry-java/issues/1819](https://github.com/open-telemetry/opentelemetry-java/issues/1819)
=> Fix using default context storage implemenation in LazyStorage

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java
resolves [https://github.com/open-telemetry/opentelemetry-java/issues/1812](https://github.com/open-telemetry/opentelemetry-java/issues/1812)
=> Update Jaeger exporter to conform to updated specification

sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSamplerTest.java
=> Fix build breakage due to conflicting merges.

api/src/main/java/io/opentelemetry/baggage/Baggage.java, api/src/main/java/io/opentelemetry/baggage/BaggageUtils.java, api/src/main/java/io/opentelemetry/baggage/propagation/W3CBaggagePropagator.java, api/src/test/java/io/opentelemetry/baggage/propagation/W3CBaggagePropagatorTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/BaggageManagerSdkTest.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/ImmutableBaggageTest.java
and make `BaggageUtils.withBaggage` non-public.
=> Make Baggage implement ImplicitContextKeyed

.github/workflows/continuous-build.yml
=> Add secrets to environment for publishing.

examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java
Resolves #1826 
I'm not really sure why the single span wasn't making it through the pipeline, but 10 make it through just fine.
=> Make the jaeger example send more spans to make sure that they get properly exported

integration_tests/src/test/java/io/opentelemetry/JaegerExporterIntegrationTest.java
This flaky test I actually saw locally too, not just GitHub :) For now a random attempt of increasing the timeout to see what happens.
=> Increase Jaeger container timeout

api/src/main/java/io/opentelemetry/trace/TracingContextUtils.java
=> Simplify a call so that we don't have cycles in the TCU->Span call chain

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessor.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorEventQueue.java, sdk_extensions/async_processor/src/test/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessorTest.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessor.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessorTest.java
=> Nit: move Context as first argument to SpanProcessor.onStart

api/src/main/java/io/opentelemetry/trace/SpanContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java
=> Serialize the entire trace flags not only the sample bit

api/src/main/java/io/opentelemetry/trace/PropagatedSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
resolves [https://github.com/open-telemetry/opentelemetry-java/issues/1864](https://github.com/open-telemetry/opentelemetry-java/issues/1864)
=> Span return `this` to enable chain calls

.editorconfig
=> Disable inner class imports to avoid errorprone BadImport error

context/src/otelInGrpcTest/java/io/opentelemetry/context/GrpcContextStorageProvider.java, context/src/otelInGrpcTest/java/io/opentelemetry/context/OtelInGrpcTest.java
=> Fix propagating Otel context to propagate gRPC context

build.gradle, settings.gradle
=> Set plugin versions in only one place

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/IdGenerator.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RandomIdGenerator.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/ParentBasedSamplerTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RandomIdGeneratorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkProviderTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/samplers/AlwaysOffSamplerTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/samplers/AlwaysOnSamplerTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/AwsXrayIdGenerator.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/AwsXRayIdGeneratorTest.java
=> Rename IdsGenerator to IdGenerator

api/src/main/java/io/opentelemetry/api/baggage/BaggageUtils.java, api/src/main/java/io/opentelemetry/api/trace/TracingContextUtils.java
=> Make BaggageUtils and TracingContextUtils package protected

sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/ZPageServerTest.java
and be sure to shut it down at the end of the test
I had a local failure since I was running something else on the non-random port.
=> start up the test zpages server on a random port

integration_tests/tracecontext/src/main/java/io/opentelemetry/Application.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/TraceShimTest.java
Also, update the TraceContext integration test to use an OTel instance.
=> Add a creation method to the TraceShim that takes an OTel instance.

api/build.gradle, api/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorFuzzTest.java, api/src/test/java/io/opentelemetry/api/trace/propagation/HttpTraceContextFuzzTest.java, build.gradle
=> Add some simplistic fuzz-based tests for the 2 built-in W3C propagators.

api/src/test/java/io/opentelemetry/api/common/AttributesTest.java
Don't think I saw tests for this but they're worth special care.
=> Add test cases for array attributes with null inside.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1912](https://github.com/open-telemetry/opentelemetry-java/issues/1912)
=> Update opentelemetry-proto to latest version.

CONTRIBUTING.md
=> Fix small nit in readme

examples/grpc/README.md, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClient.java, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClientStream.java, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java, examples/jaeger/README.md, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java, examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java, examples/prometheus/README.md, examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java, examples/zipkin/README.md, examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ZipkinExample.java
=> Rename all packages to follow the module name definition

examples/build.gradle, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
=> Update to use google java format 1.9 in the examples

examples/build.gradle, examples/grpc/build.gradle, examples/http/build.gradle, examples/jaeger/build.gradle, examples/metrics/build.gradle, examples/otlp/build.gradle, examples/prometheus/build.gradle, examples/sdk-usage/build.gradle, examples/zipkin/build.gradle
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/1950
=> Use boms for grpc and opentelemetry in the examples

.github/workflows/pr-examples-build.yml, examples/build.gradle, examples/grpc/src/main/proto/helloworld.proto
Some fixes:
1. Update grpc version to match the core version.
2. Fix build after grpc examples were moved to `.grpc` package, but proto package was not updated.
=> Add github action to build examples when changes are identified in example directory

context/build.gradle, context/src/otelInBraveTest/java/io/opentelemetry/context/BraveContextStorageProvider.java, context/src/otelInBraveTest/java/io/opentelemetry/context/OtelInBraveTest.java, context/src/otelInBraveTest/resources/META-INF/services/io.opentelemetry.context.ContextStorageProvider
=> Add test for otel in brave

api/src/main/java/io/opentelemetry/api/trace/PropagatedSpan.java, context/src/main/java/io/opentelemetry/context/DefaultContext.java, context/src/main/java/io/opentelemetry/context/LazyStorage.java
per @bogdandrutu request https://github.com/open-telemetry/opentelemetry-java/pull/1888#issuecomment-720712989
=> Add doc explaining the restriction on return type

sdk-extensions/testbed/build.gradle, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/TestUtils.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/activespanreplacement/ActiveSpanReplacementTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/actorpropagation/ActorPropagationTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/clientserver/TestClientServerTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/concurrentcommonrequesthandler/HandlerTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/errorreporting/ErrorReportingTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/latespanfinish/LateSpanFinishTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/listenerperrequest/ListenerTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/multiplecallbacks/MultipleCallbacksTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/nestedcallbacks/NestedCallbacksTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/promisepropagation/PromisePropagationTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/statelesscommonrequesthandler/HandlerTest.java, sdk-extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/suspendresumepropagation/SuspendResumePropagationTest.java
=> Change testbed to use the junit5 extension

opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/TestUtils.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/activespanreplacement/ActiveSpanReplacementTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/actorpropagation/ActorPropagationTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/baggagehandling/BaggageHandlingTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/TestClientServerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/concurrentcommonrequesthandler/HandlerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/latespanfinish/LateSpanFinishTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/listenerperrequest/ListenerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/nestedcallbacks/NestedCallbacksTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/promisepropagation/PromisePropagationTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/statelesscommonrequesthandler/HandlerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/suspendresumepropagation/SuspendResumePropagationTest.java
=> Change opentracing testbed to use the junit5 extension

CHANGELOG.md
I believe this is all the stuff that has been merged since 0.9.1 was released.
=> Add CHANGELOG entries for 0.10.0

api/src/main/java/io/opentelemetry/api/baggage/Baggage.java, api/src/main/java/io/opentelemetry/api/baggage/BaggageConsumer.java, api/src/main/java/io/opentelemetry/api/baggage/Entry.java, api/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/src/main/java/io/opentelemetry/api/baggage/package-info.java, api/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/src/test/java/io/opentelemetry/api/baggage/BaggageTestUtil.java, api/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java, api/src/test/java/io/opentelemetry/api/baggage/ScopedBaggageTest.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java
Since sent the tracestate version, figured I'd just go ahead and send this out.
Fixes #1960
=> Expose foreach consumer instead of Entry for baggage.

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java
=> Add the combined b3 header to the propagator fields

sdk/testing/build.gradle, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRule.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRuleTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
Also added a unit test for the junit5 extension
=> Add a junit4 rule for OTel testing.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java
Rather than just forwarding them immediately.
Resolves #1621
=> Make the BatchRecorderSdk actually batch the recordings

CHANGELOG.md
I'm planning on keeping the change log up to date as we go. Here's the installment for today.
=> update the changelog 2020-11-10

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/2047](https://github.com/open-telemetry/opentelemetry-java/issues/2047)
=> Update the zipkin exporter Span Status handling

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
Fixes #2056
=> Report BatchSpanProcessor current queue size

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusTest.java
removed SpanData.getCanonicalCode() and implementations
=> remove methods deprecated in 0.11.0

.github/CODEOWNERS, README.md
Christian (@Oberon00)  has been a consistent provider of quality PR reviews. I recommend he be made an approver.
=> Add Oberon00 as approver

settings.gradle
=> Publish Gradle build scan.

sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorFlushBenchmark.java
JMH gets unhappy if we leave threads around.
/cc @srprash
=> Shutdown BSP in benchmarks

.github/workflows/docker-test-containers.yml
Will change the references in integration tests after merging / running
=> Migrate docker image mirroring to ghcr.

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
Solves https://github.com/open-telemetry/opentelemetry-java/issues/1315 for span kind.
=> Add getKind to the ReadableSpan interface in SDK.

sdk-extensions/async-processor/src/main/java/io/opentelemetry/sdk/extension/trace/export/DisruptorAsyncSpanProcessor.java, sdk-extensions/aws/build.gradle, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/BeanstalkResource.java, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/DockerHelper.java, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/Ec2Resource.java, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EcsResource.java, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EksResource.java, sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/JdkHttpClient.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSampler.java
=> Remove Guava from SDK extensions, except zpages

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/Client.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/TestClientServerTest.java
=> handle case insensitive logic for keys on context extraction in OpenTracing TracerShim

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcSpanExporter.java
=> change the default timeouts for otlp and jaeger to 10s

sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/LambdaResource.java, sdk-extensions/aws/src/main/resources/META-INF/services/io.opentelemetry.sdk.resources.ResourceProvider, sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/LambdaResourceTest.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/2141
=> Add support for AWS Lambda resource attributes

QUICKSTART.md, api/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/src/main/java/io/opentelemetry/api/trace/TracerProvider.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java, sdk/common/src/test/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfoTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
=> Remove "semver" prefix from instrumentation library version

sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/TracerSdkProviderTest.java
and rename a few lingering pluralized idGenerator symbols.
amends #2022
=> Add an option to set an IdGenerator when building an SDK.

api/src/main/java/io/opentelemetry/api/internal/ReadOnlyArrayMap.java, api/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceState.java, api/src/main/java/io/opentelemetry/api/trace/TraceState.java, api/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java
Looks like builder was accidentally left in the interface.
=> Add TraceState.asMap

sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/TracerSdkProviderTest.java
=> Add an option to the SDK builder to specify an initial TraceConfig

api/internal/src/main/java/io/opentelemetry/api/internal/Utils.java, api/internal/src/test/java/io/opentelemetry/api/internal/UtilsTest.java
=> Remove deadcode from internal package

sdk/all/src/main/java/io/opentelemetry/sdk/Obfuscated.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java
=> Move obfuscated to sdk, make it package protected

api/internal/src/main/java/io/opentelemetry/api/internal/Utils.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DefaultMeter.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/BatchRecorderTest.java
=> Remove internal public validateLabelPairs, move to the class that uses it

api/internal/src/test/java/io/opentelemetry/api/internal/StringUtilsTest.java
=> Add unit tests for isValidMetricName

api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, api/baggage/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java, api/baggage/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java, api/context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java, api/context/src/test/java/io/opentelemetry/context/LazyStorageTest.java, api/internal/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/trace/src/jmh/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorInjectBenchmark.java, api/trace/src/test/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorTest.java
=> Small nits in api packages

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkManagement.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java
=> Mark as package protected deprecated Multi classes in SDK

api/metrics/src/main/java/io/opentelemetry/api/metrics/AsynchronousInstrument.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DefaultMeter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java
=> Remove deprecated setCallback, change SDK to avoid volatile

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/TraceMultiPropagator.java
=> Remove deprecated code from trace propagation extension

api/context/src/main/java/io/opentelemetry/context/Scope.java, api/context/src/main/java/io/opentelemetry/context/propagation/ContextPropagators.java, api/trace/src/main/java/io/opentelemetry/api/trace/Tracer.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2204
=> Remove references to TracingContextUtils

examples/jaeger/build.gradle
=> Fix Jaeger example to use the artifacts from the bom

exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingMetricExporterTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/MetricAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporter/otlp/MetricAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporterTest.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/MetricAdapterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusCollectorTest.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricsExporter.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/MetricInteroperabilityTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/Aggregations.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/data/MetricDataTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/CountAggregationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/LastValueAggregationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/SumAggregationTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricExporterTest.java
NON_MONOTONIC_SUM will be soon merged with SUM and offer the "isMonotonic" as a property.
=> Update types to reflect the names in proto

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/LabelNameSanitizer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/LabelNameSanitizerTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusCollectorTest.java
=> Add caching for sanitized labels in the Prometheus MetricAdapter.

sdk/all/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/ComponentRegistryTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterProviderSharedState.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java
=> Change ComponentRegistry to be a final class that accepts a factory method

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java
=> Change AbstractSynchronousInstrument to accept a bound factory instead of abstract method

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java
=> Avoid passing the meter SDK instance if unnecessary

api/metrics/src/main/java/io/opentelemetry/api/metrics/AsynchronousInstrument.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleUpDownSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleValueObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongUpDownSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongValueObserver.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java
=> Remove unnecessary generic argument from AsynchronousInstrument

api/metrics/src/main/java/io/opentelemetry/api/metrics/AsynchronousInstrument.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DefaultMeter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleUpDownSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleValueObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongUpDownSumObserver.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongValueObserver.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/DoubleSumObserverTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/DoubleUpDownSumObserverTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/DoubleValueObserverTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/LongSumObserverTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/LongUpDownSumObserverTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/LongValueObserverTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
=> Use standard Java interfaces instead of defining custom ones
