open-telemetry/opentelemetry-java

build.gradle, opentracing-shim/build.gradle, opentracing-shim/src/main/java/openconsensus/opentracingshim/ScopeManagerShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/ScopeShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanContextShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/TracerShim.java, settings.gradle
Important things to add:
1. Inter-process propagation (including baggage).
2. In-process propagation (added a super simple layer - we need to decide whether we support the 0.32 API, or do a 0.33 without the deprecated members).
And a few other items (which will be covered little by little in the next, related PRs).
```java
import openconsensus.opentracingshim.TracerShim;
import io.opentracing.Tracer;
Tracer tracer = new TracerShim(openconsensus.trace.Tracing.getTracer());
```
=> Initial OT Shim.

api/src/main/java/openconsensus/trace/data/AttributeValue.java, api/src/main/java/openconsensus/trace/data/AttributeValueType.java
This is done in order to have an easier way to extract the
underlying value from an AttributeValue.
PS - Shall we remove the `match()` part too? I'd say **yes**
=> Add AttributeValue.getType() and related members.

api/src/main/java/openconsensus/trace/BlankSpan.java, api/src/main/java/openconsensus/trace/Span.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java
=> Rename Span.putAttribute*() to Span.setAttribute*()

api/src/main/java/openconsensus/internal/Utils.java, api/src/main/java/openconsensus/stats/MeasureMap.java, api/src/main/java/openconsensus/stats/Stats.java, api/src/main/java/openconsensus/stats/StatsComponent.java, api/src/main/java/openconsensus/stats/view/data/Aggregation.java, api/src/main/java/openconsensus/stats/view/data/View.java, api/src/main/java/openconsensus/tags/data/Tag.java, api/src/main/java/openconsensus/trace/propagation/TextFormat.java
=> fix a few warnings and removed deprecated methods

opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java
One thing that came up: Will the new API support:
1) `null` for Event name? (`Span.addEvent((String)null)`)
2) `null` for values in the Event fields map (`Span.addEvent("myEvent", fields)`)
? 
(I'm guessing NO for both ;) )
=> Implement Span.log()* for the OT Shim.

api/src/main/java/openconsensus/trace/Span.java, api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/data/SpanData.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java
Fixes https://github.com/bogdandrutu/openconsensus/issues/56.
=> Use Span.Kind.INTERNAL as default.

api/src/main/java/openconsensus/trace/NoopTrace.java, api/src/main/java/openconsensus/trace/propagation/PropagationComponent.java
We will provide official formats for B3/W3C in a contrib package which will be shared by the default implementation and any other implementations.
=> Update the PropagationComponent to expose implementation specific formats.

api/src/main/java/openconsensus/trace/AttributeValue.java, api/src/main/java/openconsensus/trace/BlankSpan.java, api/src/main/java/openconsensus/trace/Link.java, api/src/main/java/openconsensus/trace/Span.java, api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/Status.java, api/src/main/java/openconsensus/trace/Tracer.java, api/src/main/java/openconsensus/trace/data/Event.java, api/src/main/java/openconsensus/trace/data/SpanData.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java
The main reason is because we have circular dependencies between packages: main -> data and data -> main
=> Move back AttributeValue and Status from data to the main package.

api/src/main/java/openconsensus/stats/Measure.java, api/src/main/java/openconsensus/stats/Measurement.java, api/src/main/java/openconsensus/tags/TagMap.java, api/src/main/java/openconsensus/trace/SpanData.java
I'm not sure what to do with thise:
```
/Users/sergeykanzhelev/src/openconsensus/api/src/main/java/openconsensus/trace/SpanBuilder.java:239: warning: {@code} within <code>
* {@code Callable<MyResult>} newCallable = tracer.withSpan(span, myCallable);
^
/Users/sergeykanzhelev/src/openconsensus/api/src/main/java/openconsensus/trace/Tracer.java:227: warning: {@code} within <code>
*     executor.execute(tracer.withSpan(span, {@code new Callable<MyResult>()} {
^
/Users/sergeykanzhelev/src/openconsensus/api/src/main/java/openconsensus/trace/Tracer.java:248: warning: {@code} within <code>
*     executor.execute(Context.wrap(tracer.withSpan(span, {@code new Callable<MyResult>()} {
```
=> fix javadoc issues

api/src/main/java/openconsensus/context/propagation/BinaryFormat.java, api/src/main/java/openconsensus/context/propagation/TextFormat.java, api/src/main/java/openconsensus/tags/NoopTags.java, api/src/main/java/openconsensus/trace/BlankSpan.java, api/src/main/java/openconsensus/trace/NoopTrace.java, api/src/main/java/openconsensus/trace/Span.java, api/src/main/java/openconsensus/trace/SpanBuilder.java, api/src/main/java/openconsensus/trace/Tracer.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/Propagation.java
Addresses #19, for your consideration - it only converts the core classes to interfaces (leaving alone `TraceId`, `Event`, etc)
=> Make core classes interfaces.

api/src/main/java/openconsensus/stats/Measure.java, api/src/main/java/openconsensus/stats/Measurement.java, api/src/test/java/openconsensus/stats/MeasureTest.java, api/src/test/java/openconsensus/stats/NoopStatsTest.java
This reverts commit b06d6422931a0cebc47dce68d091ef496d7a20de.
Related to https://github.com/bogdandrutu/openconsensus/issues/185.
=> Revert "Remove long values from stats, not too much value added, only complexity. (#114)"

api/src/main/java/openconsensus/tags/unsafe/ContextUtils.java, api/src/main/java/openconsensus/trace/unsafe/ContextUtils.java, api/src/test/java/openconsensus/trace/unsafe/ContextUtilsTest.java
I've just realized how badly OC got hit by the mistake to expose the Key and gRPC using directly the key, will be a bit mess to change that.
=> Restrict access to the key, add helper methods to interact with Context.

api/src/main/java/openconsensus/metrics/CounterDouble.java, api/src/main/java/openconsensus/metrics/CounterLong.java, api/src/main/java/openconsensus/metrics/GaugeDouble.java, api/src/main/java/openconsensus/metrics/GaugeLong.java, api/src/main/java/openconsensus/metrics/Metric.java, api/src/main/java/openconsensus/metrics/MetricRegistry.java, api/src/main/java/openconsensus/metrics/NoopMetrics.java, api/src/test/java/openconsensus/metrics/CounterDoubleTest.java, api/src/test/java/openconsensus/metrics/CounterLongTest.java, api/src/test/java/openconsensus/metrics/GaugeDoubleTest.java, api/src/test/java/openconsensus/metrics/GaugeLongTest.java, api/src/test/java/openconsensus/metrics/MetricRegistryTest.java, contrib/src/main/java/openconsensus/contrib/metrics/runtime/GarbageCollector.java, contrib/src/main/java/openconsensus/contrib/metrics/runtime/MemoryPools.java
Change the names to look more how they would have been with templates (if no boxing/unboxing problem): Gauge<Long> -> GaugeLong
OpenMetrics uses Counter as well for this.
Updates https://github.com/bogdandrutu/openconsensus/issues/220 - need to also update the protos to reflect these changes.
=> Rename Cumulative to Counter, and use names like templates GaugeLong.

opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/openconsensus/opentracingshim/SpanShim.java
We currently set `Status.UNKNOWN` in case of the OT's error value is `true`, but we should also set status for `false`.
This is mostly for being on the safe scenario, in case the user re-sets the `error` value.
=> Set status based on error, either true or false.

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/spi/TracerProvider.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java
Updates #107 
This is an initial draft currently only for tracer object. The design still depends on some questions in #107 e.g. whether we want to support java agents and/or we can assume that app init time can be always used to init the tracer.
This PR introduces a singleton object `OpenConsensus`. It's like a registry for `Tracer`, `Metrics` objects which instrumentation can use when a tracer is not explicitly provided.
The biggest difference to `GlobalTracer` is that it requires initialization of the registry before instrumentation initialization. Developers control application start-time and therefore can first initialize the tracer and then wire in instrumentations. 
The current proposal is that implementation (of a tracer) will set itself to the registry once it is created, I think …
=> Add a global registry

README.md
Addresses #186 
I left out `stats` (as it will likely be merged to `metrics`) as well as `resource` and the new `spi`, as they are more of advanced components.
=> Readme add modules desc

api/src/main/java/io/opentelemetry/context/propagation/TraceContextFormat.java, api/src/test/java/io/opentelemetry/context/propagation/TraceContextFormatTest.java
Updates #118 
Related to #258 
The implementation is ported from OpenCensus https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/trace/propagation/TraceContextFormat.java
=> Add W3C tracecontext propagation

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java
Simplify the code and handle null parents.
=> Clean up the asChildOf()/addReference code in the OT shim.

.github/CODEOWNERS
Per @bogdandrutu request on gitter
=> Add pavolloffay to codeowners

api/src/main/java/io/opentelemetry/trace/SpanData.java
At this moment `TimedEvent` only takes `SpanData.Event` objects.
=> Make TimedEvent accept io.opentelemetry.trace.Event-compliant objects.

sdk/src/main/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySampler.java, sdk/src/test/java/io/opentelemetry/sdk/trace/samplers/ProbabilitySamplerTest.java
OpenCensus used to use probability sampler of 1/10000 as default in trace configs. Not sure if we want to keep it that way in the new project.
=> Add ProbabilitySampler in SDK.

api/src/main/java/io/opentelemetry/trace/Span.java
=> Fix comment for Span.end() as there's no overload taking options anymore.

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java
We added these specific text formats for injection/extraction only, so we need to handle them as well in our shim layer.
=> OT Shim: Handle the specific TextFormat Inject/Extract formats too.

api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java
`CONTEXT_SPAN_KEY` is already made private.
=> Fix a stale Javadoc.

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Tracer.java, api/src/main/java/io/opentelemetry/trace/unsafe/ContextUtils.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, api/src/test/java/io/opentelemetry/trace/unsafe/ContextUtilsTest.java, contrib/src/test/java/io/opentelemetry/contrib/trace/CurrentSpanUtilsTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/310.
Followed @SergeyKanzhelev's suggestion in https://github.com/open-telemetry/opentelemetry-java/issues/310#issuecomment-498797101:
> - So we will call it `Default` span. 
> - `Default` will generate a new span ID. There will be built-in random algorithm.
Note invalid span is not yet included in this PR.
=> Rename BlankSpan to DefaultSpan.

api/src/main/java/io/opentelemetry/trace/SpanId.java, api/src/main/java/io/opentelemetry/trace/TraceId.java, api/src/test/java/io/opentelemetry/trace/SpanIdTest.java, api/src/test/java/io/opentelemetry/trace/TraceIdTest.java
Exposed the constructors taking `long`, as proposed in a recent call.
I re-used the existing tests, btw. Hope that is fine too ;)
=> API: Have TraceId/SpanId constructors taking long values.

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Tracer.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
=> Remove resource setter and getter from Tracer

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/SpanContext.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/LinkTest.java, api/src/test/java/io/opentelemetry/trace/SpanContextTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/380.
=> Rename Blank SpanContext to Invalid.

api/src/main/java/io/opentelemetry/trace/SpanData.java
We were taking SpanData.Link objects instead.
=> Make SpanData take *base* Link objects.

build.gradle, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsSpanImpl.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsSpanImplTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/375.
Only enabled for Java 8 and lower. For Java 9+, I got a lot of warnings like
```bash
warning: /modules/java.base/java/lang/SuppressWarnings.class: major version 54 is newer than 53, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
...
warning: Supported source version 'RELEASE_5' from annotation processor 'com.google.auto.value.extension.memoized.processor.MemoizedValidator' less than -source '1.7'
```
Seems to be related to AutoValue.
=>  Fail the build on warnings with '-Werror'.

sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanImpl.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsSpanImplTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessorTest.java
This allows to use the SpanProcessor and exporters with SpanData or other source of Spans (not only via the Span object from the API).
=> Decouple the getter methods for the Span in a different class.

opentracing-shim/src/main/java/io/opentelemetry/inmemorytrace/Check.java, opentracing-shim/src/main/java/io/opentelemetry/inmemorytrace/InMemorySpan.java, opentracing-shim/src/main/java/io/opentelemetry/inmemorytrace/InMemoryTracer.java, opentracing-shim/src/test/java/io/opentelemetry/inmemorytrace/InMemoryTracerTest.java
Adds a basic in-memory `Tracer` that we can later leverage for the OT shim tests (including the `testbed` examples).
Originated from #408
=> OT Shim: Add a super basic InMemoryTracer.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
Functionality extracted from https://github.com/open-telemetry/opentelemetry-java/pull/425. Tests will be added after the SpanBuilder is implemented.
=> Allow adding SpanProcessor in the TracerSdk.

api/src/main/java/io/opentelemetry/resources/Resource.java
> Referencing subclass from superclass initializer might lead to class loading deadlock.
=> Fix a potential ClassLoader deadlock and add missing Javadocs.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporterTest.java
Implemented support for InMemorySpanExporter, this PR cannot be merged until the SpanBuilderSdk is not finalized (just a hacky implementation for the moment to prove that everything works e2e).
Updates https://github.com/open-telemetry/opentelemetry-java/issues/277
=> Add support to install SpanProcessor and an InMemorySpanExporter for tests.

api/src/main/java/io/opentelemetry/distributedcontext/DistributedContext.java, api/src/test/java/io/opentelemetry/distributedcontext/DefaultDistributedContextManagerTest.java, sdk/src/main/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdk.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/DistributedContextSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/distributedcontext/ScopedDistributedContextTest.java
Fixes #436
API definition:
https://github.com/open-telemetry/opentelemetry-java/blob/ed42237b6c71052bbffe4d849647c53fae81b246/api/src/main/java/io/opentelemetry/distributedcontext/DistributedContext.java#L57-L61
=> Change DistributedContextSdk.Builder to use current dctx as implicit parent

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanImpl.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TraceProtoUtils.java, sdk/src/main/proto/trace/v1/trace.proto, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanImplTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TraceProtoUtilsTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporterTest.java
Fixes a bunch of places where Spans are created but not ended in tests. This is a good practice because test code will definitely be copied by others.
=> Remove TruncatableString from proto to sync with ot-proto.

api/src/main/java/io/opentelemetry/context/propagation/HttpTraceContext.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Tracer.java, api/src/test/java/io/opentelemetry/context/propagation/HttpTraceContextTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, opentracing-shim/src/main/java/io/opentelemetry/inmemorytrace/InMemoryTracer.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
See https://github.com/open-telemetry/opentelemetry-java/pull/446#discussion_r298641472.
Next: move HTTP and binary formats to `api.trace.propagation` to avoid circular dependency.
=> Rename TraceContextFormat to HttpTraceContext.

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
=> Return DefaultSpan if not recording events. Implement TracerSdk.shutdown().

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
When setting a parent (implicitly or explicitly), we should ignore it if the related `SpanContext.isInvalid()` value is true.
This showed up as converting `Span`s to protos resulted in `getParentSpanId()` being equal to non-empty values, even if the parent was `DefaultSpan.getInvalid()`, for example.
The only place I can see affected by this change, is samplers **now** getting a `null` parent `SpanId` for this case - would this really be a problem? If that's the case, then this check needs to be refined.
Let me know @bogdandrutu as this is very implementation-related ;)
=> SDK: Ignore parent if SpanContext.isInvalid() is true.

sdk/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSampledSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSampledSpansProcessorTest.java
An async `SpanProcessor` will be available as a different implementation of the `SpanProcessor`.
=> Remove sync prefix from SpanProcessor interface methods.

.travis.yml
This will cause https://github.com/open-telemetry/opentelemetry-java/pull/427 to fail (hopefully).
=> Fail if any previous command fails.

opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/activespanreplacement/ActiveSpanReplacementTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/actorpropagation/ActorPropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/TestClientServerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/concurrentcommonrequesthandler/HandlerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/latespanfinish/LateSpanFinishTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/listenerperrequest/ListenerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/nestedcallbacks/NestedCallbacksTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/promisepropagation/PromisePropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/statelesscommonrequesthandler/HandlerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/suspendresumepropagation/SuspendResumePropagationTest.java
Hadn't realized `InMemorySpanExporter` had restricted its creation. Updating this to get the master branch green again.
=> Update the InMemorySpanExporter creation calls from the testbed.

build.gradle, exporters/jaeger/README.md, exporters/jaeger/build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/main/proto/jaeger/api_v2/collector.proto, exporters/jaeger/src/main/proto/jaeger/api_v2/model.proto, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, settings.gradle
Closes #469 by implementing a Jaeger Span Exporter
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Implemented the Jaeger Span Exporter using gRPC as the transport

sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java
This also fixes a flaky test in the disruptor implementation `incrementAfterShutdown`.
=> Fix that disruptor does not accept events after shutdown.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
When using implicit parent `Span`s, we were not properly inheriting/setting their `TimestampConverter` (we were doing that only for explicit parents).
(Wish we had value-based tuples, so we could return parent `Span`/`SpanContext` in a single call ;) )
=> Properly set TimestampConverter from implicit parent Span.

opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/latespanfinish/LateSpanFinishTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java
Order the Spans in latespanfinish/ and multiplecallbacks/ cases
to *make sure* the invariant is enforced (prior to do assert
the conditions).
Fixes #487 
Fixes #490
=> Sort finished Spans by either start/finish time in OT testbed.

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/InMemorySpanExporterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterTest.java
Continuation of https://github.com/open-telemetry/opentelemetry-specification/pull/243
=> Fix typo in FailedNotRetryable

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Metric.java
Some of the reasons are listed in the https://github.com/open-telemetry/oteps/pull/26, and also it confuses users.
Few reasons:
* The user that writes the instrumentation does not know the `resource` that produces the telemetry.
* If needed to support a custom resource we should support configuring the `resource` similar to the proposed named tracer https://github.com/open-telemetry/oteps/pull/16
=> Remove capability to set a resource for metrics construction

opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/Client.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java, sdk_contrib/testbed/src/test/java/io/opentelemetry/sdk/contrib/trace/testbed/multiplecallbacks/Client.java, sdk_contrib/testbed/src/test/java/io/opentelemetry/sdk/contrib/trace/testbed/multiplecallbacks/MultipleCallbacksTest.java
Be more deterministic about this, as previous approaches
used sleep or sort by start time.
Previous failure was because of the fact we still couldn't use the same monotonic clock for the OT shim side, as we needed to use `SpanContext` as parent - now simply make sure that the callbacks are finished *after* the parent `Span` is done.
=> Use a CountDownLatch to coordinate MultipleCallbacksTest.

CONTRIBUTING.md, README.md
I closed a previous update docs PR after finding the information I needed in the current docs. The purpose of this PR is to organize the build directions a bit differently and call them out more. I think it would be easier for new contributors to find the information they need to quickly build.
=> organize build directions in docs

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
Before this, we had forgotten to properly carry the Links from `Span.Builder` to `Span`.
=> Make Span.Builder properly set the Links in the Span.

api/src/main/java/io/opentelemetry/trace/Tracestate.java, api/src/test/java/io/opentelemetry/trace/TracestateTest.java
Fixes #562
Note: This also adds support for `@` vendor prefix inside the key.
=> Per spec change, allow start digit and @.  

opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/OpenTelemetryInteroperabilityTest.java
Test that OpenTracing shim can continue trace started by SDK and vice versa.
cc @carlosalberto 
=> Test SDK and OpenTracing shim interoperability

sdk_contrib/inmemory_export/src/main/java/io/opentelemetry/sdk/contrib/trace/export/InMemoryTracing.java
We now use SpanData, not the proto representation.
=> Update the inline docs for InMemoryTracing.

sdk/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
I remember @bogdandrutu asking for convenience getters this in the past.
=> Expose the global telemetry objects as sdk ones.

sdk/src/main/java/io/opentelemetry/sdk/internal/Clock.java, sdk/src/main/java/io/opentelemetry/sdk/internal/MillisClock.java, sdk/src/main/java/io/opentelemetry/sdk/internal/TestClock.java, sdk/src/main/java/io/opentelemetry/sdk/internal/TimestampConverter.java, sdk/src/test/java/io/opentelemetry/sdk/internal/ClockTestUtil.java, sdk/src/test/java/io/opentelemetry/sdk/internal/TimestampConverterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
This relates to #590.
I'm not entirely what scope of cleanup was discussed around #590, but this removes protobufs from `TimestampConverter` and `Clock` while keeping the tests passing.  If there are additional specific cleanups in `TimestampConverter` (etc) that we think should be picked up as part of this, let's figure it out.
=> remove protobuf from timestamp converter and friends.

api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemoryTracingTest.java, exporters/otprotocol/src/main/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtils.java, exporters/otprotocol/src/test/java/io/opentelemetry/exporters/otprotocol/TraceProtoUtilsTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
First PR from a series of PRs to move the Sampler interface to the SDK to implement https://github.com/open-telemetry/opentelemetry-specification/pull/257
Also rename:
alwaysSample -> alwaysOn
neverSample -> alwaysOff
=> Move utils/Samplers from API to SDK Samplers

api/src/main/java/io/opentelemetry/trace/SpanContext.java, api/src/main/java/io/opentelemetry/trace/propagation/BinaryTraceContext.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/SpanContextTest.java, api/src/test/java/io/opentelemetry/trace/propagation/BinaryTraceContextTest.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java
Implements https://github.com/open-telemetry/opentelemetry-specification/pull/216
=> Add isRemote to the SpanContext

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
Add explicit timestamp for all the `Span.addEvent()` overloads in the API (no implementation, that is).
I had wanted to only add this for `addEvent(Event event)`, to prevent the overload 'explosion' ;)
=> Add explicit timestamp for Span events in the API.

sdk/src/main/java/io/opentelemetry/sdk/trace/IdsGenerator.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RandomIdsGenerator.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java
Currently the mechanism to inject a different ids generator is not implemented, but soon we will implement for clock, resource, etc.
=> Extract trace id generator in an interface to allow different implementations

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
This addresses #585 .
Using `synchronized(this)` is generally considered unsafe because any other object that has a reference to the instance in question can share the monitor can can potentially cause a deadlock.  This change uses a reentrant read/write lock which is fully private/encapsulated and prevents this deadlock potential.
Should also note that this removes lazy init for the events and attributes, which allows the fields to be final, removes concerns around nullability, and allows us to no longer hold a reference to the `TraceConfig` instance.
=> Leverage a private object monitor lock instead of synchronizing on "this".

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemoryTracingTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessorTest.java
Getting or updating the active configuration was moved to the TracerSdkFactory.
=> Remove trace config and shutdown from TracerSdk

api/src/main/java/io/opentelemetry/trace/TracerFactory.java, sdk/src/main/java/io/opentelemetry/sdk/trace/InstrumentationLibraryInfo.java, sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkFactory.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkFactoryTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
This implements the instrumentation library resource for named tracers and makes it available to `SpanProcessor`s (via `ReadableSpan`) and `SpanExporter`s (via `SpanData`).
Resolves #617
=> Add instrumentation library resource to named tracers

api/src/main/java/io/opentelemetry/metrics/CounterDouble.java, api/src/main/java/io/opentelemetry/metrics/CounterLong.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/GaugeDouble.java, api/src/main/java/io/opentelemetry/metrics/GaugeLong.java, api/src/main/java/io/opentelemetry/metrics/LabelSet.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/main/java/io/opentelemetry/metrics/Metric.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/CounterDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/CounterLongTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeLongTest.java, api/src/test/java/io/opentelemetry/metrics/MeasureLongTest.java, api/src/test/java/io/opentelemetry/metrics/ObserverDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/ObserverLongTest.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMetricBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
Except changes in Meter and DefaultMeter all the other changes are mechanical. 
Filed https://github.com/open-telemetry/opentelemetry-java/issues/683 to track the creation of LabelSet objects APIs.
=> Add LabelSet to the Meter API and change GetHandle to use it.

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/AttributesWithCapacity.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java
Fixes #660 
PS - I've used `AttributesWithCapacity` from the `Span.Builder` implementation itself, to keep the very same logic that `Span` uses to discard them when the max count is reached.
=> Allow recording attributes in Span.Builder

opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java
SpanContextShim objects are created on demand,
as it's an expensive operation because of a global
write lock, hence we need to handle the case
of starting a Span whose parent has no SpanContextShim
yet.
Fixes #671
=> Handle null parent's SpanContextShim in the OT Shim.

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java
```shell
$ make test verify-format
./gradlew clean assemble check --stacktrace
> Task :opentelemetry-all:javadoc
/Users/a14689/oss/opentelemetry-java/exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java:44: Warning: <code> in {@code}
*     {@code List<Span> spanItems} = exporter.getFinishedSpanItems();
^
/Users/a14689/oss/opentelemetry-java/exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java:38: Warning: <code> in {@code}
*     {@code List<io.opentelemetry.sdk.trace.SpanData>} spans = tracing.getFinishedSpanItems();
^
> Task :opentelemetry-exporters-inmemory:javadoc
/Users/a14689/oss/opentelemetry-java/exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java:44: Warning: …
```
=> Fix the warning that occurs when a code is used in a code tag

api/src/main/java/io/opentelemetry/metrics/CounterDouble.java, api/src/main/java/io/opentelemetry/metrics/CounterLong.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/GaugeDouble.java, api/src/main/java/io/opentelemetry/metrics/GaugeLong.java, api/src/main/java/io/opentelemetry/metrics/MeasureDouble.java, api/src/main/java/io/opentelemetry/metrics/MeasureLong.java, api/src/main/java/io/opentelemetry/metrics/Metric.java, api/src/main/java/io/opentelemetry/metrics/ObserverDouble.java, api/src/main/java/io/opentelemetry/metrics/ObserverLong.java, api/src/test/java/io/opentelemetry/metrics/CounterDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/CounterLongTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/GaugeLongTest.java, api/src/test/java/io/opentelemetry/metrics/MeasureDoubleTest.java, api/src/test/java/io/opentelemetry/metrics/MeasureLongTest.java, api/src/test/java/io/opentelemetry/metrics/TestLabelSet.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractGaugeBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMetricBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
Resolves #701 
This leaves the API without the ability to create a bound instrument with an empty LabelSet. Is that something that we should support?
=> Remove default bound

exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java
This PR was split from #693 at the request of @bogdandrutu. It just renames the internal `boolean hasBeenEnded` of `RecordEventsReadableSpan` to `hasEnded`, makes it public on the `ReadableSpan` interface and also adds it to `SpanData`.
=> Add hasEnded to ReadableSpan and SpanData (split from #693)

sdk/src/main/java/io/opentelemetry/sdk/resources/EnvVarResource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkFactoryBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkRegistry.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkRegistryBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkRegistryProvider.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkRegistryBuilderTest.java
I think this should at least partially resolve #518, in that it will enable building arbitrary service providers for the TracerSdkFactory.
resolves #735
=> Provide a builder for the TracerSdkRegistry, for ultimate configurability

sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Split & rebased from #693. The only difference to #693 is that the latency/duration is not added to SpanData, only ReadableSpan.
In effect, this PR:
- Changes the end time of active spans to return zero instead of the current duration/latency if the span has not been ended yet.
- Add a public getter for a ReadableSpan's latency/duration.
- In contrast to #693, this does *not* add the latency property to SpanData (I think this was a bad idea anyway).
=> Rework latency/duration/endTime of Span

sdk/src/main/java/io/opentelemetry/sdk/metrics/BaseBoundInstrument.java
@bogdandrutu this gets rid of the null checks on the auto-generated equals/hashcode
=> clean up the equals/hashcode on the BaseBoundInstrument

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
Personally, I'd prefer just having one varargs method that takes key/value pairs of Strings, but this will at least let API users add more than 4 labels in a LabelSet.
related to #723
=> Create a labelset with an arbitrary number of key/value pairs

sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java
Changed static create to public so it can be used by Spring Boot autoconfiguration.
=> Change MultiSpanExporter creation visibility

sdk_contrib/aws_v1_support/src/test/java/io/opentelemetry/sdk/contrib/trace/aws/Ec2ResourceTest.java
This avoids log errors and long waiting for retries to call into the AWS metadata, also unit-tests are deterministic and independent of the environment.
=> Avoid calling the AWS specific methods in unit-tests.

api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/Meter.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/metrics/DefaultMeterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleGaugeTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleMeasureTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongGaugeTest.java, api/src/test/java/io/opentelemetry/metrics/LongMeasureTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkLabelSet.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkLongCounterTest.java
For now, keeping the version that takes a Map, and the emptyLabelSet method, although they both technically could be removed if we go with this.
resolves #723
=> Change LabelSet creation to use varargs, rather than overloaded k/v methods.

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkLongCounterTest.java
I debated introducing more class hierarchy around the monotonic field and decided to not do that for now. It could be easily retrofitted if we think saving one boolean is worth the additional complication of another layer in the hierarchy.
=> The basics for a double counter

exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanDataTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java
This is intended to resolve #719 .
Note: there were a few used-only-in-testing attributes on the RERS. I removed them, since they were never used anywhere in the system aside from tests. If we end up needing them in the future, we can add them back.
=> Clean up the external interface for the RecordEventsReadableSpan

sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java
This test fails if run on a machine that is slow or overloaded because <100 ms could be too little to get the interrupt both triggered and processed (200 ms timeout - at least 100 ms sleep time, then the thread has to wake up and trigger the interrupt, then the exporter thread has to wake up and process the interrupt).
=> Fix exporterTimesOut test being flaky.

api/src/main/java/io/opentelemetry/context/propagation/HttpTextFormat.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java, sdk_contrib/testbed/src/test/java/io/opentelemetry/sdk/contrib/trace/testbed/clientserver/Client.java
Improving consistency and cohesion of naming.
Fixes #762
=> Rename Setter.put to Setter.set

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/trace/AttributeValue.java, api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/internal/StringUtilsTest.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Ignore null or blank string-valued span attributes.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Optimize SpanBuilderSdk link memory

examples/jaeger/README.md, examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java
Resolve #775 
@carlosalberto please test if this solves your problem.
=> Fix jaeger example

sdk/src/main/java/io/opentelemetry/sdk/metrics/MetricData.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MetricDataTest.java
This PR:
* Adds the notion of a Point as in the data model.
* Moves timestamps to the newly created Point as in the data model.
Still work left:
* Add label values to the base point.
* Add support for all types defined here https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/metrics/v1/metrics.proto
=> More progress on MetricData definition

sdk/src/main/java/io/opentelemetry/sdk/resources/ResourceConstants.java
Added new attribute names contained in recent merged PRs in the specifications.
=> Update to latest Resource semantic conventions.

api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleObserver.java, api/src/main/java/io/opentelemetry/metrics/Gauge.java, api/src/main/java/io/opentelemetry/metrics/Instrument.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBinding.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBound.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongObserver.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, api/src/main/java/io/opentelemetry/metrics/Observer.java, api/src/test/java/io/opentelemetry/metrics/DoubleObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongObserverTest.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/GarbageCollector.java, contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime/MemoryPools.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BaseInstrument.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java
For more details see https://github.com/open-telemetry/oteps/blob/master/text/0072-metric-observer.md
Also rename the result method from `put` to `observe`.
=> Remove bound support from Observers

sdk/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java, sdk/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkRegistry.java, sdk/src/test/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfoTest.java, sdk/src/test/java/io/opentelemetry/sdk/internal/ComponentRegistryTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkRegistryTest.java
The main idea is to use the ComponentRegistry for MeterSdk as well.
=> Refactor the tracer registry logic in a shared class

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkRegistry.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSharedState.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkLongCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkLongMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/SdkMetricsProviderTest.java
In this PR:
* Make use of the newly added ComponentRegistry in metrics;
* Add a Builder class for the MeterSdkRegistry;
* Add a Shared state class between MeterSdks, this class will start to be used soon;
=> Use the component registry in metrics, add a shared state

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/test/java/io/opentelemetry/internal/StringUtilsTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java
`isNullOrBlank` usually means null, empty, or only consisting of whitespace (cf. Kotlin's 
[`isNullOrBlank`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-null-or-blank.html), for example) so I renamed it to what it actually does to avoid confusion
=> Rename StringUtils.isNullOrBlank to isNullOrEmpty

api/src/main/java/io/opentelemetry/trace/AttributeValue.java
Is actually doesn't throw (`RecordEventsReadableSpanTest.setAttribute`).
https://github.com/open-telemetry/opentelemetry-java/blob/8b4c1488e936f42783396ebb9c44092364f7a339/sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java#L284-L289
Regarding error handling, the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md) defines:
> API methods MUST NOT throw unhandled exceptions when used incorrectly by end users. The API and SDK SHOULD provide safe defaults for missing or invalid arguments. For instance, a name like `empty` may be used if the user passes in `null` as the span name argument during `Span` construction.
=> Remove incorrect `@throws NullPointerException` in AttributeValue

api/src/main/java/io/opentelemetry/metrics/DoubleObserver.java, api/src/main/java/io/opentelemetry/metrics/LongObserver.java
This PR closes #824 aligning the examples in the API documentation with the implementation of the Observer meter.
=> Fix Observer API examples in Javadoc 

sdk/src/main/java/io/opentelemetry/sdk/metrics/BaseInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/BaseInstrumentWithBinding.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
No tests yet for the Observers, will add when we add the Callback support.
=> Add initial implementation for Observers

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java
Split from https://github.com/open-telemetry/opentelemetry-java/pull/831
=> Rename base classes to abstract class

api/src/main/java/io/opentelemetry/metrics/Counter.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBind.java, api/src/main/java/io/opentelemetry/metrics/InstrumentWithBinding.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java, api/src/main/java/io/opentelemetry/metrics/Measure.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java
I think this simplifies the usages of the bind/unbind pair.
=> Move unbind to the Bound to simplify usage

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java
=> AbstractBoundInstrument refcounts and keeps the state of mapped.

api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleMeasure.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongMeasure.java
This causes warnings, and with some compilers, errors. Adding the enclosing interface reference quiets that down.
=> add the missing enclosing interface

sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java
related to #766 
Is this the pattern that we think makes sense to use for instrumenting the SDK? Does this style of usage introduce a race condition in the creation of the SDKs? Does it mandate that the MeterSdk is created and installed before the TracerSdk is installed? Is there a better pattern to use?
=> Add instrumentation to the BatchSpansProcessor to count the number of dropped spans

sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java
=> Add the enclosing interface references to remove javadoc errors

sdk/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentWithBinding.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserver.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSharedState.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java
This change allows us to pass the entire Meter shared state to the instruments, next PR will add a registry for the Instruments that is passed to the Builders to register the created instruments when build is called.
=> Add a MeterSharedState class that includes the InstrumentationLibraryinfo

sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java
This is to hold the boilerplate logic and get it out of the specific implementations.
=> Introduce an abstract super class for aggregators.

sdk/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorAsyncSpanProcessor.java, sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java, sdk_contrib/async_processor/src/test/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorAsyncSpanProcessorTest.java
With https://github.com/open-telemetry/opentelemetry-specification/pull/370, the `SpanProcessor` interface changed introducing a new `ForceFlush()` method. 
Should we also provide a `ForceFlush(int, TimeUnit)` interface to configure an upper-bound time limit?
This also addresses #794.
=> Implementing ForceFlush for SpanProcessor

sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongMeasureSdkTest.java
TODO: need to work more on the case where any setter is used because that returns the non-sdk version so it still needs casting, will do that in a separate PR.
With this change I was able to remove a lot of the casts.
=> Return SDK builders in the MeterSdk to avoid casting in tests

api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java
resolves #895 
Note: This does not fully address #876 . That will wait until https://github.com/open-telemetry/opentelemetry-specification/issues/478 is resolved.
=> Make the HttpTraceContext be more forgiving in the face of invalid data.

api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextExtractBenchmark.java, api/src/jmh/java/io/opentelemetry/trace/propagation/HttpTraceContextInjectBenchmark.java, build.gradle
Enabled GC profiler for all the benchmarks.
=> Cleanup jmh and trace context benchmarks

sdk/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpansProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java, sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorAsyncSpanProcessor.java, sdk_contrib/async_processor/src/test/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorAsyncSpanProcessorTest.java
* MultiSpanProcessor dispatches start/end events only to SpanProcessors that require that.
* DisruptorSpanProcessor does not enqueue events if the next SpanProcessor does not require that event.
=> Avoid calling processors that do not require an event.

exporters/jaeger/build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, sdk_contrib/otproto/README.md, sdk_contrib/otproto/build.gradle, sdk_contrib/otproto/src/main/java/io/opentelemetry/sdk/contrib/otproto/TraceProtoUtils.java, sdk_contrib/otproto/src/test/java/io/opentelemetry/sdk/contrib/otproto/TraceProtoUtilsTest.java, settings.gradle
We don't want the Jaeger exporter which shares these utils to depend on the otelprotocol
=> Move otproto utils from exporter to a contrib sdk package

all/build.gradle, api/README.md, context_prop/README.md, contrib/runtime_metrics/README.md, contrib/trace_utils/README.md, exporters/inmemory/README.md, exporters/jaeger/README.md, exporters/logging/README.md, exporters/otprotocol/README.md, opentracing_shim/README.md, proto/README.md, sdk/README.md, sdk_contrib/async_processor/README.md, sdk_contrib/auto_config/README.md, sdk_contrib/aws_v1_support/README.md, sdk_contrib/otproto/README.md
All was genereting all javadoc as well because was copied form OpenCensus. We don't need to do that now, also all is not exported to maven.
Add links to javadoc hosted by `javadoc.io` for all exported packages.
=> Add javadoc link to all readmes

api/src/main/java/io/opentelemetry/correlationcontext/CorrelationsContextUtils.java, api/src/main/java/io/opentelemetry/correlationcontext/DefaultCorrelationContextManager.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/main/java/io/opentelemetry/trace/TracingContextUtils.java, sdk/src/main/java/io/opentelemetry/sdk/correlationcontext/CorrelationContextManagerSdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
=> Rename the Context methods returning Scope to currentContextWith()

opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/NoopSpanBuilderShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
This was an old TODO that I had totally forgotten about ;)
PS - We 'sadly' cannot call any shutdown routine as those methods live (for now, at least) only in the SDK portion (which we don't want to depend on).
=> Handle Tracer.close() in the OT shim.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TimedEvent.java, sdk/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TimedEventTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/data/SpanDataTest.java
Another step towards #993 and extends #1004. Closes #1022.
This PR adds support for dropping span attributes once the max configured in the `TraceConfig` has been reached and also maintain a count for the number of dropped attributes.
This also fixes up some existing tests that were broken by this change.
=> Limit RecordEventsReadableSpan attributes to configured max

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, sdk/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessorTest.java
resolves #1016 
Note: this change breaks any existing SpanExporters that aren't hosted in this repo.
=> Change the SpanExporter to take a collection.

sdk/README.md
This was forgotten in #823. Probably other READMEs are also affected.
=> Correct minimum Android API level in SDK README.

sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
This partially resolves #948 addressing:
- empty strings are now a valid `AttributeValue` 
- null values remove existing `AttributeValue`s and their relative key is dropped.
Note, Array will be handled in a follow up PR or as part of #807, depending on the merge order.
=> Revise null values for AttributeValue

.circleci/config.yml, Makefile, RELEASE.md, build.gradle
Fixes #971 
We still need to manually update the `version` field in `build.gradle`,  but once that is done, creating a branch starting with `v.` triggers a deployment to Bintray/Maven Central.
See https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.2.4 as an example (I used this one to verify all works great).
In a future we can play with plugins that automatically update the version and create a tag (such as the Maven Release plugin does).
PS - I'd like to stop repeating all the steps in the different tasks *if possible* (now we have very similar `build`, `java11` and `release` tasks). But we need somebody who is a Circle wizard or one who digs enough into this. Anyway, something to do in the future.
=> Add automatic release support

README.md
@jkwatson contributed to the project significantly since last year. Some of the major contributions are around metrics API, as well as reviewing a significant amount of PRs during this time.
=> Promote @jkwatson to maintainer

CONTRIBUTING.md
=> Note about docker requirement for tests

sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkProviderTest.java
Since there is no method to get the SpanProcessor(s),
there is no way to actually use the forceFlush API otherwise.
=> Add forceFlush on TracerSdkProvider.

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
=> Remove the finalizer on the RecordEventsReadableSpan.

opentracing_shim/build.gradle
Gradle should rerun automatically if any input/dependencies changed.
No other build.gradle uses cleanTest.
CC @carlosalberto
=> Don't uselessly rerun opentracing_shim tests.

api/src/jmh/java/io/opentelemetry/trace/DefaultTracerBenchmarks.java
resolves #788 
Benchmark results on my laptop:
=> simple benchmarks for the default tracer APIs

api/src/main/java/io/opentelemetry/trace/propagation/B3Propagator.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/main/java/io/opentelemetry/trace/propagation/JaegerPropagator.java, api/src/test/java/io/opentelemetry/trace/propagation/B3PropagatorTest.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, api/src/test/java/io/opentelemetry/trace/propagation/JaegerPropagatorTest.java, context_prop/src/main/java/io/opentelemetry/context/propagation/HttpTextFormat.java
I think this should resolve #916 , but if we want to have no-op implementations if the other two parameters are null, I can amend this PR with that.
=> Let the carrier be null on the inject methods, to support possible lambda usages

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java
The OpenTelemetry Span.Kind enumerated type values are in uppercase, e.g. SERVER, CLIENT. These are incompatible with Jaeger which is based on the OpenTracing semantics where these are in lowercase.
The spans are collected as expected, but Jaeger is unable to display deep dependancy graphs as these are based on span kind values in lowercase, e.g. "server".
=> Convert span kind values to lowercase for Jaeger exporter

api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java
* Check size first before accessing elements.
=> Fix HttpTraceContext propagator

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterTest.java
With the merging of https://github.com/open-telemetry/opentelemetry-specification/pull/511, this should get us into spec compliance.
=> Remove the RETRYABLE failure mode from the exporter interfaces.

api/src/jmh/java/io/opentelemetry/trace/propagation/JaegerPropagatorContextExtractBenchmark.java, api/src/jmh/java/io/opentelemetry/trace/propagation/JaegerPropagatorContextInjectBenchmark.java
resolves #1070 
The benchmarks i've added are pretty much identical to the ```HttpTraceContext...```  benchmarks.  
It looks like we could consolidate the common logic into a base class which could be used across both of the propagators benchmarks (and potentially the B3Propagator if a benchmark is ever needed for it). Thoughts?
=> Add jaeger propagator benchmarks

sdk/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java, sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java
Our SDK shouldn't prevent apps/cli tools/etc. from exiting.  Mark all threads/pools as daemon.
Closes #1093
=> Mark all threads/pools as daemon.

contrib/trace_propagators/src/jmh/java/io/opentelemetry/contrib/trace/propagation/PropagatorContextExtractBenchmark.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3Propagator.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagator.java, contrib/trace_propagators/src/test/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagatorTest.java
Now we've got benchmarks for the propagators, there looks like there's a few quick wins to optimise these.
B3 propagator: single header - when injecting context, values are written directly to char[] instead of string concatenation (similar to ```HttpTraceContext.inject```)
Jaeger propagator - when injecting context, values are written directly to char[] (as above)
Jaeger propagator - when extracting context, only do URL decoding if the delimiter cannot be found in the value.
I've also added extra benchmark to measure this, and a unit test, with some minor refactoring.
(compare these with screenshots in #1122)
Extract benchmarks:
Inject benchmarks:
=> Improve propagator performance

all/build.gradle, sdk_contrib/jaeger_remote_sampler/README.md, sdk_contrib/jaeger_remote_sampler/build.gradle, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/PerOperationSampler.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimiter.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimitingSampler.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/SamplingDecision.java, sdk_contrib/jaeger_remote_sampler/src/main/proto/jaeger/api_v2/sampling.proto, sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java, sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSamplerTest.java, sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimiterTest.java, sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimitingSamplerTest.java, sdk_contrib/jaeger_remote_sampler/src/test/resources/sampling.json, settings.gradle
Resolves #796
This PR adds Jaeger remote sampler. The sampling configuration is retrieved via gRPC (as opposed to thrift in Jaeger clients).
Othe notable changes:
* Added proto for Jaeger sampling model with service
* The proto is generated to the same package as Jaeger gRPC exporter (`io.opentelemetry.exporters.jaeger.proto.api_v2`), this differs from the package defined in Jaeger proto (`io.jaegertracing.api_v2`)
* Added RateLimitingSampler implementation from Jaeger
* There is e2e test with Testcontainers and mock proto service test
=> Add Jaeger remote sampler

QUICKSTART.md
=> quickstart: update link to "Obtaining a Tracer"

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java
The auto-instrumentation libraries add errors to the spans when they occur. The `error` tag is not added to the spans by the Jaeger exporter if the span status code is not `OK`.
When sending these spans to the OpenTelemetry Collector it will automatically add the `error` tag when it translates them, based on the status code, and sends them to the Jaeger collector.
This process does not take place when sending spans directly to a Jaeger collector (not using the OTel collector) and so the Jaeger UI does not display visual indicators for spans with errors.
By adding the `error` tag in the Adapter class if the span.status.code is not `OK`, if this tag hasn't already been added, means that it will be present when using either the OTel collector
or the Jaeger collector directly. The Otel …
=> Add error tag to spans for Jaeger exporter

examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, sdk/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java
It doesn't seem necessary for it to be public, and this will help make sure nobody does:
```
TracerSdk tracer = (TracerSdk) OpenTelemetry.getTracerProvider().get("...");
```
which will break under auto-instrumentation's TracerProvider substitution.
=> Make TracerSdk non-public

CHANGELOG.md, QUICKSTART.md, README.md, all/build.gradle, build.gradle, exporters/zipkin/README.md, exporters/zipkin/build.gradle, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinExporterConfiguration.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinExporterConfigurationTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, settings.gradle
Resolves #534 
Note: this code is heavily copied from the OpenCensus zipkin implementation.
=> First cut at a Zipkin Span Exporter

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/internal/Obfuscated.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, sdk/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/spi/TraceProviderSdkTest.java
**Problem statement:**
If users take the static global providers that are returned from the API, and cast them to their SDK specific implementations, then those casts will fail under auto-instrumentation, because auto-instrumentation takes over the static global providers returned by the API and points them to it's embedded SDK.
**Proposal:**
Prevent users from doing this to get SDK-specific implementation, so that auto-instrumentation does not cause them ClassCastException unexpectedly.
The preferably way to get the SDK-specific implementation is through `OpenTelemetrySdk` anyways.
**Implementation:**
Wrap (obfuscate) the static global providers that are returned from the API to prevent users from casting them to their SDK specific implementation.
Unfortunately, `OpenTelemetrySdk` needs …
=> Prevent casting to TraceProviderSdk

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
Setting the parent span id on a span if it is invalid causes errors in the OpenTelemetry Collector.
The parent span should not be set on a span when it is exported if the span id is invalid.
Fixes #1164
=> Ignore parent span id when invalid in OTLP exporter

.github/ISSUE_TEMPLATE/bug_report.md
I know that I did create a branch on this repo, but the github UI helped me created this template and I did not have other option. Thanks for understanding.
Updates https://github.com/open-telemetry/opentelemetry-java/issues/493
=> Add template for bug reporting

build.gradle, contrib/trace_propagators/build.gradle
As requested by @bogdandrutu (from comment in PR #1176), this PR fixes a dependency misconfiguration.
The ```jaeger_client``` test dependency was included in the dependencies in the root project, but it's only required in the ```contrib/trace_propagators``` project.
=> moved jaeger_client dependency to trace_propagators

exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java
=> Make the ZipkinSpanExporter public, so it can actually be used.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/package-info.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/README.md, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/package-info.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/package-info.java
=> Add system/env vars and properties configuration for Metric classes

api/src/main/java/io/opentelemetry/trace/TraceId.java, api/src/test/java/io/opentelemetry/trace/TraceIdTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java
This resolves #1190 
Since the method is marked as internal, I also followed the suggestion proposed in the last SIG call and rename it to `getTraceRandomPart()`
=> Fix getTracerLower behavior

sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractCounter.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractMeasure.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractObserver.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleObserverSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/InstrumentDescriptor.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongMeasureSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongObserverSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractCounterTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractMeasureTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractObserverTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/InstrumentRegistryTest.java
This way we embed all informations in the InstrumentDescriptor, so no need to override equal and hashCode in the Abstract[Counter, Measure, Observer].
This is extracted from https://github.com/open-telemetry/opentelemetry-java/pull/1201  where I am adding the new instruments, and I found that after adding UpDownCounter the only reason to have AbstractCounter or AbstractUpDownCounter was to include these 2 fields in equals and hashCode.
=> Add instrument type and value type to InstrumentDescriptor

.github/CODEOWNERS
During the past 2-3 months @thisthat contribute significant PRs to the Java repository (like the config refactoring) as well as participated in a bunch of code reviews and technical discussions.
=> Proposal: Add @thisthat as an approver

api/src/main/java/io/opentelemetry/metrics/AsynchronousInstrument.java, api/src/main/java/io/opentelemetry/metrics/SynchronousInstrument.java
All the sync instruments inherited their builders from SynchronousInstrument.Builder which by default referred to Instrument.Builder.
The idea behind this is that if we add a new property to the SynchronousInstrument.Builder all sync instrument builders will inherit that property.
=> Add a Builder in the SynchronousInstrument

exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java
(cherry picked from commit 414ddb05fa132289fcdac4c3e7b7a42f47b8cfa6)
=> Make the ZipkinSpanExporter public, so it can actually be used. (#1186)

examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java
This shows better idiomatic usage of the API.
=> Move the span operations inside the scope in the http server example

api/src/main/java/io/opentelemetry/metrics/spi/MetricsProvider.java, api/src/main/java/io/opentelemetry/trace/spi/TraceProvider.java
While testing an alternate TracerProvider implementation, I found that the docs for `TraceProvider` service lookup had an incorrect spelling of the class name.
=> Correct spelling of key/file for the TraceProvider service lookup.

build.gradle
resolves #1246 
result:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>io.opentelemetry</groupId>
<artifactId>opentelemetry-context-prop</artifactId>
<version>0.5.0-SNAPSHOT</version>
<name>OpenTelemetry Java</name>
<description>OpenTelemetry Context Propagation</description>
<url>https://github.com/open-telemetry/opentelemetry-java</url>
<licenses>
<license>
<name>The Apache License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
</license>
</licenses>
<developers>
<developer>
<id>opentelemetry</id> …
```
=> fix: force maven publish to include version for api conf

sdk/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanWrapper.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
This is a optimization of the creation of the SpanData implementation. 
master benchmark:
```
SpanPipelineBenchmark.runThePipeline_05Threads                                   thrpt    5  3352.511 ±  53.533  ops/ms
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.alloc.rate                    thrpt    5  7233.932 ± 138.314  MB/sec
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.alloc.rate.norm               thrpt    5  3400.001 ±   0.001    B/op
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.churn.PS_Eden_Space           thrpt    5  7310.190 ± 695.826  MB/sec
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.churn.PS_Eden_Space.norm      thrpt    5  3435.823 ± 315.746    B/op
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.churn.PS_Survivor_Space       thrpt    5     0.232 ± …
```
=> Return a wrapped span for SpanData so only the mutable data is copied.

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Avoid `@SuppressWarnings("MixedMutabilityReturnType")` by always return an immutable list/map from the helper methods.
This also removes an unnecessary wrapping of the Collection.emptyMap which is already immutable.
Also remove test and check for null links, RERS should never receive null links because it is internal class and only builder calls it.
=> Refactor the logic to get immutable attributes, links and events

api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/correlationcontext/spi/CorrelationContextManagerFactory.java, api/src/main/java/io/opentelemetry/metrics/spi/MeterProviderFactory.java, api/src/main/java/io/opentelemetry/trace/TracerProvider.java, api/src/main/java/io/opentelemetry/trace/spi/TracerProviderFactory.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, sdk/src/main/java/io/opentelemetry/sdk/correlationcontext/spi/CorrelationContextManagerFactorySdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/spi/MeterProviderFactorySdk.java, sdk/src/main/java/io/opentelemetry/sdk/trace/spi/TracerProviderFactorySdk.java, sdk/src/main/resources/META-INF/services/io.opentelemetry.correlationcontext.spi.CorrelationContextManagerFactory, sdk/src/main/resources/META-INF/services/io.opentelemetry.correlationcontext.spi.CorrelationContextManagerProvider, sdk/src/main/resources/META-INF/services/io.opentelemetry.metrics.spi.MeterProviderFactory, sdk/src/main/resources/META-INF/services/io.opentelemetry.metrics.spi.MetricsProvider, sdk/src/main/resources/META-INF/services/io.opentelemetry.trace.spi.TraceProvider, sdk/src/main/resources/META-INF/services/io.opentelemetry.trace.spi.TracerProviderFactory, sdk/src/test/java/io/opentelemetry/sdk/correlationcontext/spi/CorrelationContextManagerFactorySdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/spi/MeterProviderFactorySdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/spi/TracerProviderFactorySdkTest.java
Two benefits:
1) It makes the naming less confusing 
2) lines up with the naming of SPI interfaces in the auto-instrumentation project
Resolves #1213
=> change the naming of the SPI provider classes to *Factory

contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorExtractor.java
Making it consistent with HttpTraceContext logging behavior.
Reported on gitter: https://gitter.im/open-telemetry/opentelemetry-auto-instr-java?at=5ec670f84412600ccd5bc4bc
=> Remove verbose logging

sdk/src/main/java/io/opentelemetry/sdk/trace/RandomIdsGenerator.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RandomIdsGeneratorTest.java
When creating a custom `IdsGenerator`, I think it is common to want to delegate to the default random one, e.g., only customize trace ID and use the same code for span ID. I noticed this when writing https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/awsagentprovider/src/main/java/com/softwareaws/xray/opentelemetry/exporters/AwsXrayIdsGenerator.java#L29
The `AwsXrayIdsGenerator` in this repo has a huge dependency on the xray SDK which I want to remove (then I don't need to fork there :) ), and this would help when doing that.
~Also made `RandomIdsGenerator` a singleton while here.~
Realized it's more useful to be able to customize Random than make singleton.
=> Expose RandomIdsGenerator so it can be delegated to.

exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/TimedEvent.java, sdk/src/main/java/io/opentelemetry/sdk/trace/data/EventImpl.java, sdk/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TimedEventTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/data/SpanDataImplTest.java
And, make the internal TimedEvent implement that interface, so we don't need to copy the data in the Span pipeline.
This is continuing work towards #1191 
Benchmark results before this change:
```
SpanPipelineBenchmark.runThePipeline_05Threads                                   thrpt    5  4004.539 ± 255.354  ops/ms
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.alloc.rate                    thrpt    5  7670.084 ± 495.608  MB/sec
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.alloc.rate.norm               thrpt    5  3016.001 ±   0.001    B/op
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.churn.PS_Eden_Space           thrpt    5  7677.574 ± 530.403  MB/sec
SpanPipelineBenchmark.runThePipeline_05Threads:·gc.churn.PS_Eden_Space.norm      thrpt    5  3019.633 ± 288.382    B/op …
```
=> Convert the exportable Event to an interface

examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldClient.java, examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldClientStream.java, examples/grpc/src/main/java/io/opentelemetry/example/HelloWorldServer.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java, examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
PR #1241  changed the names of
[Batch|Simple]SpansProcessor to [Batch|Simple]SpanProcessor but did not change the examples to
match. 
This fixes the examples so that they now build correctly.
=> Fix examples to use [Batch|Simple]SpanProcessor

sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java
This is meant for use by custom Sampler implementations. As of now, you have to use an anonymous inner class or otherwise derive a new class because there is no publicly accessible implementation of Decision.
=> Add public Samplers.emptyDecision(boolean) and decision(boolean, Map).

examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/PerOperationSampler.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimitingSampler.java, sdk_contrib/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/RateLimitingSamplerTest.java
Update code per latest spec, see:
https://github.com/open-telemetry/opentelemetry-specification/pull/621
The goal is to avoid any SDK implementation from taking a dependency on it.
=> Remove SpanID from sampling parameters

build.gradle, contrib/trace_utils/src/main/java/io/opentelemetry/contrib/trace/CurrentSpanUtils.java, contrib/trace_utils/src/test/java/io/opentelemetry/contrib/trace/CurrentSpanUtilsTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/AbstractBoundInstrumentTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java, sdk_contrib/aws_v1_support/src/test/java/io/opentelemetry/sdk/contrib/trace/aws/AwsXRayIdsGeneratorTest.java, sdk_contrib/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/contrib/trace/jaeger/sampler/JaegerRemoteSampler.java, settings.gradle
I normally use Java 14 and found my build failing due to deprecated source=7 option. I figured suppressing this option would be enough to get the build to work and ended up in a rabbit hole :)
- Suppress options warnings because we are a library, not executable, so warnings about compiler arguments aren't so useful
- Instead of updating check to disable Werror on Java 9+, enabled Werror on all Java. 
- Update error prone to fix buggy check that triggered false positive on Utils.checkNotNull
- Only set error prone javac for pre Java 9 (though I don't think anyone uses such a JDK to build this project)
- Improve javax.annotation-api branch to apply to Java 9+ forever
- Update jacoco and mockito to support Java 14
- Fix error prone warnings
- Fix mockito deprecations
=> Update config / deps to allow building on Java 14.

api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorSingleHeader.java, contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagator.java, contrib/trace_propagators/src/test/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorTest.java, contrib/trace_propagators/src/test/java/io/opentelemetry/contrib/trace/propagation/JaegerPropagatorTest.java
Fixes #1272 
I don't imagine we propagating invalid `SpanContext` instances with non-default TraceFlags/TraceState, hence the `isValid()` check, as opposed to compare against `SpanContext.getInvalid()` ;)
=> Do not inject invalid SpanContext instances.

exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/trace/data/test/TestSpanData.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TestUtils.java, sdk/src/test/java/io/opentelemetry/sdk/trace/data/SpanDataImplTest.java
Addressing issue #1291. SpanDataImpl is only used by tests now so has been renamed to TestSpanData.
=> Renamed SpanDataImpl to TestSpanData and moved to subdir test (#1291)

sdk/src/main/java/io/opentelemetry/sdk/common/export/ConfigBuilder.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/package-info.java, sdk/src/test/java/io/opentelemetry/sdk/common/export/ConfigBuilderTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
1. Extended ConfigBuilder for building TraceConfig class to support config from env vars
2. Added getDoubleProperty to ConfigBuilder class
Fixes #1239
=> Support env vars for TraceConfig initialization

sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
Main motivation is to add tests for empty config map, so need to get access to the "default" values and getters, then no need to use mockito for the case where the map is not empty.
=> Avoid mockito magic for span processors test, test with empty configmap

sdk_contrib/aws_v1_support/src/main/java/io/opentelemetry/sdk/contrib/trace/aws/resource/AwsResource.java, sdk_contrib/aws_v1_support/src/main/java/io/opentelemetry/sdk/contrib/trace/aws/resource/Ec2Resource.java, sdk_contrib/aws_v1_support/src/test/java/io/opentelemetry/sdk/contrib/trace/aws/resource/Ec2ResourceTest.java
I realized in #1289 I accidentally renamed the test file to `Ec2Resource` when I meant to rename the logic to that and the test to `Ec2ResourceTest` (currently test file doesn't end with Test). Sorry about this ><
=> Fix incorrect renaming of files.

examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongValueObserverExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
Most of this was just running `googleJavaFormat` on the examples, which I guess hadn't been being done.
=> Example cleanup/update for latest APIs

CONTRIBUTING.md, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, build.gradle
resolves #1187 
Tests now use Java 8.
I modified the ```HttpTraceContextTest``` to demonstrate that Java 8 is used,  I removed some boilerplate, which is now using lambdas.
I also disabled the ```Java7ApiChecker``` and ```AndroidJdkLibsChecker``` errorprone checks when compiling tests as these will warn if you use e.g. streams in your test.
=> use java 8 for tests

all/build.gradle, all/src/test/java/io/opentelemetry/InternalApiProtectionTest.java, api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/test/java/io/opentelemetry/internal/StringUtilsTest.java, build.gradle, buildscripts/checkstyle.license, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractor.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorSingleHeader.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/StringUtils.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorTest.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/StringUtilsTest.java
Fixes #1125, second attempt.
This PR adds InternalApiProtectionTest which uses ArchUnit to enforce architectural constraints. It only verifies that classes in contrib packages do not use classes in internal package of API module.
Test was added into opentelemetry-all module because the latter depends on all other submodules and therefore sees all classes in the project.
All found violations were fixed.
StringUtils was copied from Guava, so its original copyright notice was preserved with slight formatting changes. Even then I had to change our checkstyle configuration to make it pass.
=> Extension packages should not use "internal" API package

sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
I've added some comment to #1275 
This PR will prevent the ```description``` test in ```JaegerRemoteSamplerTest``` from immediately calling the ```GrpcCleanupRule``` before the sampling strategy is retrieved by gRPC in a separate thread.
=> fix for potential race condition in JaegerRemoteSamplerTest

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
https://github.com/open-telemetry/opentelemetry-specification/pull/641
=> Add semantic attributes for HTTP content length.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/package-info.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
OTLP Exporter in [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) is not configurable to:
- useTransportSecurity instead of usePlaintext
- insert values into Metadata headers (in ClientInterceptor)
From PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/567#issuecomment-648600894
Decided to try add configuration directly to OTLP Exporter.
=> enhance OTLP Exporter configuration

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
Corresponds to https://github.com/open-telemetry/opentelemetry-specification/pull/652 which is approved and just waiting to be merged. Sending this in the hopes that it speeds up getting both merged :)
=> Add semantic attribute for peer.service

sdk/src/main/java/io/opentelemetry/sdk/resources/ResourceConstants.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/DockerHelper.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/EcsResource.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/resource/DockerHelperTest.java, sdk_extensions/aws_v1_support/src/test/java/io/opentelemetry/sdk/extensions/trace/aws/resource/EcsResourceTest.java
**Description:** Add container id in AWS ECS Plugin
Container.id semantic conversions https://github.com/open-telemetry/opentelemetry-specification/pull/673
**Testing:** Verified in https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/tree/both-otel-and-xray
Can get AWS service resources in Span.
**Documentation:** https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-plugins
=> support container id in AWS ECS plugin

sdk/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java
I started looking at the data coming out of our aggregators for ValueRecorders, and realized that the current approach of having our MMSC aggregations be cumulative probably isn't very useful. In particular, the min & max are only useful when considered over a reporting interval, rather than over the lifetime of the process.
So, I propose in this PR to change to having the ValueRecorders use a delta-aggregation for MMSC, so as to make all 4 values produced be useful.
=> Change the usage of MMSC aggregations to always be deltas.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/CommonAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/CommonAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/MetricAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/ResourceAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
=> Update the OTLP proto to the latest released version (0.4.0)

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporter.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporterTest.java
Fixes #1360 
Implemented `InMemoryMetricExporter` similar to `InMemorySpanExporter` and also added `InMemoryMetricExporterTest` for testing `InMemoryMetricExporter`. Used `LinkedBlockingQueue` for maintaining inmemory `MetricData` and avoiding manual locks for synchronization.
=> Added InMemoryMetricExporter

sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
=> BatchSpanProcessor: rename a variable and fix the list initialization size.

api/src/main/java/io/opentelemetry/common/ImmutableKeyValuePairs.java, api/src/main/java/io/opentelemetry/common/Labels.java, api/src/test/java/io/opentelemetry/common/ImmutableKeyValuePairsTest.java, api/src/test/java/io/opentelemetry/common/LabelsTest.java
While writing some manual instrumentation, I found it very useful to keep a constant Labels instance, but then append to them when actually recording metrics (to add Span status, for instance). This method will help do that more efficiently than having to manually copy the labels from one instance to a new builder.
=> Add a toBuilder method to Labels

api/src/main/java/io/opentelemetry/internal/Utils.java, api/src/test/java/io/opentelemetry/internal/UtilsTest.java
Randomly noticed this in #1403
- Don't allow `null` error message - surely we don't want our error messages to have the unhelpful string just `null`
- Similarly, a vararg being `null` would require actually passing in `null` which we should never really be doing. I'm guessing this was a mistake instead of checking empty length
- Just use `String` for error message for simplicity. I can't imagine someone ever passing an object, and indeed the codebase neve does so, seems nice to simplify and simplify the javadoc
=> Don't allow null error messages and some cleanup

exporters/prometheus/src/main/java/io/opentelemetry/exporters/prometheus/PrometheusCollector.java, exporters/prometheus/src/test/java/io/opentelemetry/exporters/prometheus/PrometheusCollectorTest.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricProducer.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
- renamed the misleading method name for getting metric data.
- added javadoc in places where it was missing to clarify implementation details
resolves #1405
=> More fully document the MetricProducer class

examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java
This fixes a bug where each time a new HttpClient is instantiated, it adds a new SpanExporter to the
global OpenTelemetry SDK instance.
=> Call initTracer just once at beginning of main in http example

sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandler.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandlerTest.java
`TracezDataAggregator` modifed `getOkSpans` and `getErrorSpans` to return an immutable list, which caused a immutable list sorting bug in `TracezZPageHandler`. 
This pull request fixes the bug.
=> Fixed immutable list sorting bug in TraceZ zPage

QUICKSTART.md
Fixes #1426 which has a broken ["Semantic Conventions"](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-semantic-conventions.md) link in the [Span Attributes section of the Quickstart guide](https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md#span-attributes), resulting in a 404 page.
The fix points the link to the [Trace Semantic Conventions page](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions).
=> Fix semantic conventions link

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
I was randomly looking through the `Span` API and was surprised to see null checks in the no-op span for sure but also in the real span. It seems to not follow the spec with regards to error handling. "API methods MUST NOT throw unhandled exceptions when used incorrectly by end users. "
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles
=> Remove null checks in Span API.

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java, api/src/test/java/io/opentelemetry/trace/SpanBuilderTest.java
=> Return Invalid Spans from the no-op Tracer when there is no SpanContext

api/src/main/java/io/opentelemetry/trace/attributes/BooleanAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/DoubleAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/LongAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/StringAttributeSetter.java, api/src/test/java/io/opentelemetry/trace/attributes/BooleanAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/DoubleAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/LongAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/StringAttributeSetterTest.java
They're `AttributeSetter`s so should work on `Attributes` ;) And comes in handy when adding semantic attributes to events and resources.
=> Add version of attribute setters that operate on Attributes.

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java
I also went ahead and sync'd up the configuration settings between OTLP span and metrics exporters.
A common base class might be nice for those two builders in the future.
Closes #1463
=> Set default endpoint for OTLP exporters

exporters/jaeger/README.md, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporterTest.java
Currently, the Jaeger exporter uses system property names that look like env vars `JAEGER_ENDPOINT` / `JAEGER_SERVICE_NAME`, which has caused confusion for a couple of opentelemetry-javaagent users.
This fixes that by using the now standard `ConfigBuilder` for `JaegerGrpcSpanExporter.Builder` (and following the conventions from `ZipkinSpanExporter`).
Closes #1408
=> Fix Jaeger exporter system property config

api/src/main/java/io/opentelemetry/trace/attributes/BooleanAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/DoubleAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/LongAttributeSetter.java, api/src/main/java/io/opentelemetry/trace/attributes/StringAttributeSetter.java, api/src/test/java/io/opentelemetry/trace/attributes/BooleanAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/DoubleAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/LongAttributeSetterTest.java, api/src/test/java/io/opentelemetry/trace/attributes/StringAttributeSetterTest.java
This is particularly helpful in unit tests / IDE debug.
=> Return a readable tostring for attribute setters.

extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3Propagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractor.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorMultipleHeaders.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorTest.java
From the B3 Spec (https://github.com/openzipkin/b3-propagation) 
`Trace identifiers are 64 or 128-bit, but all span identifiers within a trace are 64-bit`
Identifiers must also be implemented as hex-characters. 
Technically these checks were happening before (and these tests would have passed), but an exception was raised elsewhere in the code. It felt more intuitive to move the checks into this validity checking function.
=> B3: Add Additional Validity Checks and tests for Trace and Span ID

extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3Propagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractor.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorMultipleHeaders.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorSingleHeader.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/Common.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/OtTracerPropagator.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorTest.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/OtTracerPropagatorTest.java
supports propagation headers used by lightstep tracers, copied from the lightstep tracer and the b3 opentelemetry propagator (in this package).
I couldn't find the issue again, but I remember reading that these were welcome in the extensions module. If someone remembers which issue the ot-tracer headers were mentioned feel free to tag it here.
=> feat(extensions): ot-tracer propagator

build.gradle, exporters/zipkin/build.gradle, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java
Unfortunately, this makes the `zipkin-sender-okhttp3` dependency required.
I'm not sure if it's possible to make `OkHttpSender` the default while also giving users the option to shed it from their dependencies if they need to use something small (`URLConnectionSender`).
Maybe it's not a good idea to have any default Sender, and instead require users to bring their own?
Would close #1409
=> Use OkHttpSender by default in ZipkinSpanExporter

sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/1445 and implements the changes outlined in https://github.com/open-telemetry/opentelemetry-specification/issues/728
=> Change default sampler to ParentOrElse(AlwaysOn)

build.gradle
compileOnly seems to be enough.
Also note that `JavaVersion.current()` returns the JVM running gradle. Which should be OK if we have compile-time troubles, but the final pom/runtime dependencies should only depend on the target Java version. That could be retrieved using `JavaVersion.toVersion(it.targetCompatibility)` inside a JavaCompile task configuration, but it seems we don't need that here.
Note that this broke execution on Java 7 when the instrumented app would try to use some annotation that is also delivered in that dependency. E.g. an older Jetty would fail loading a servlet because of `java.lang.UnsupportedClassVersionError` in `javax/annotation/security/RunAs`. We should make sure to (also) use the java11-built library in the Java 7 integration test.
=> Don't add runtime-dependency on javax-annotations.

sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/main/java/io/opentelemetry/sdk/trace/SpanWrapper.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Fixes #1479: `io.opentelemetry.sdk.trace.SpanWrapper` does not store the value of `hasEnded`, `name` or `endEpochNanos`, so updates to the originial Span would be inadvertedly reflected in the SpanData.
Also adds an unit test to check some other immutability properties of SpanWrapper.
=> Fix SpanWrapper snapshot being incomplete.

extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/AwsXRayPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorMultipleHeaders.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorSingleHeader.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagator.java
If incoming request does not have a B3 header, then `B3PropagatorExtractorMultipleHeaders` used to print a message that `Invalid TraceId in B3 header`. This is very confusing for an end user and just misleading.
=> Fix too noisy B3 propagator

QUICKSTART.md
This PR follows from discussion on https://github.com/open-telemetry/opentelemetry-java/pull/1419. 
This is intended to be a an "implementation" of https://github.com/open-telemetry/opentelemetry-specification/issues/696
In the future, authors should continue to use `java.util.logging` with an appropriate log level to log messages, so that users have full control over the logging output by OpenTelemetry.
=> Add documentation about Java Logger for Error Handling

build.gradle
Since we migrated to a newer Junit (even later Junit 4 versions would have had assertThrows; AssertJ has assertThatExceptionOfType().isThrownBy) and Java 8, we can use assertThrows.
I think the actual refactoring was already done in #1489 by @anuraaga (thank you!), so this only needs to re-enable the warning.
=> Enable errorprone's ExpectedExceptionChecker

exporters/prometheus/src/main/java/io/opentelemetry/exporters/prometheus/MetricAdapter.java, exporters/prometheus/src/test/java/io/opentelemetry/exporters/prometheus/MetricAdapterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporters/prometheus/PrometheusCollectorTest.java
Now that we've decided that the instrument name is effectively globally scoped, we shouldn't be prefixing the instrumentation library name onto the prometheus metric names.
=> Remove the instrumentation library name from the prometheus metric names

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
=> fix splitting metadata key-value substring with more than one '=' sign

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java
#1135 talks about hiding `DefaultSpan` completely. I couldn't quite find a good home for the factory methods (maybe `DefaultTracer`?) but it seems like a good idea.
In the meantime, it's more important to make the return type of the factories generic because users should definitely not have to care whether a span is a `DefaultSpan` or not. In practice, the return value of `DefaultSpan` makes it difficult to bridge them in auto instrumentation.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/764
=> Return Span from DefaultSpan factories.

api/src/main/java/io/opentelemetry/common/Attributes.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java
It's fairly easy to imagine wanting to add attributes to an existing `Attributes`, maybe storing a base in a config and tweaking at runtime.
Side effect is `Builder` constructor is made non-public which was probably intended.
=> Add Attributes.toBuilder

sdk/src/main/java/io/opentelemetry/sdk/metrics/ActiveBatcher.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleLastValueAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCount.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCount.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/NoopAggregator.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregatorTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/aggregator/NoopAggregatorTest.java
Fixes #1453 
The fix is to introduce an AtomicBoolean in the AbstractAggregator that tracks whether recordings have been made since the last reset was done. The ActiveBatcher queries the aggregator and if no recordings have been made, it skips generating metric points.
=> Fix for Issue with bound instruments generating datapoints from no recordings.

exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporter.java, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporter.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporterTest.java, exporters/inmemory/src/test/java/io/opentelemetry/exporters/inmemory/InMemorySpanExporterTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingMetricExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporters/logging/LoggingSpanExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporters/logging/LoggingSpanExporterTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, sdk/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/src/main/java/io/opentelemetry/sdk/common/export/CompletableResultCode.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/src/test/java/io/opentelemetry/sdk/common/export/CompletableResultCodeTest.java, sdk/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
This PR recognises that the export and flush methods of span and trace exporters can be, and often are, implemented with long-lived operations over networks. We, therefore, see that these method return types are represented using a `CompletableResultCode` type that can be completed asynchronously for either failure or success scenarios. In either instance, the export code can now perform actions on failure and success. In the case of failure, which can also constitute a cancellation by an upstream component (such as a batch span processor), an exporter can now interrupt its threads or perform any other action it needs to. This approach of handling failure is also safer than what now exists, which is for an upstream component to interrupt a thread.
The PR approach is focused on changing …
=> Makes Export methods async

api/src/main/java/io/opentelemetry/common/AttributeValue.java, api/src/main/java/io/opentelemetry/common/Attributes.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java, sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java, sdk/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Update attributes API to the latest spec: https://github.com/open-telemetry/opentelemetry-specification/pull/777
=> Update Attributes API to comply the spec 

sdk/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java
It doesn't exactly fix the underlying issue in #1439 (that will probably take a redesign), but it at least documents it more clearly to reduce surprise.
=> Add documentation to make it clear that the MetricProducer cannot be shared across exporters

sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/src/main/java/io/opentelemetry/sdk/resources/ResourceProvider.java, sdk/src/test/java/io/opentelemetry/sdk/resources/ResourceProvidersTest.java, sdk/src/test/java/io/opentelemetry/sdk/resources/TestResourceProvider.java, sdk/src/test/resources/META-INF/services/io.opentelemetry.sdk.resources.ResourceProvider
=> Add ResourceProvider SPI to allow for custom Resources

QUICKSTART.md
=> Document TraceConfig

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
This small PR implements [two new semantic attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-thread-attributes), added in https://github.com/open-telemetry/opentelemetry-specification/pull/789
=> Implement thread.id and thread.name semantic attributes

api/src/main/java/io/opentelemetry/trace/TraceState.java, api/src/test/java/io/opentelemetry/trace/TraceStateTest.java
=> Update the TraceState key validations to more closely match the w3c spec

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/ReadWriteSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessor.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorEventQueue.java, sdk_extensions/async_processor/src/test/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessorTest.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessor.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessorTest.java
=> Introduce a ReadWriteSpan interface and pass it to the onStart of the SpanProcessor

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
`withDeadlineAfter` sets deadline _from the time of its call_. Which means that is has to be called write before the actual call to `export`.
=> Timeout fix in OTLP exporters

sdk/common/build.gradle, sdk/common/src/main/java/io/opentelemetry/sdk/common/export/CompletableResultCode.java, sdk/common/src/test/java/io/opentelemetry/sdk/common/export/CompletableResultCodeTest.java
In #1579 #1571 etc, we found that we do need to allow users to be able to wait for a result, perhaps in a FaaS scenario or just in a unit test. Extracted this out since I ended up needing it in another PR. Added a test for interruption since that PR too. @iNikem
=> Add helpers to CompletableResultCode to wait for a result.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigSystemPropertiesTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
This seems like the bare minimum to get #1557 unblocked and preserve at least the parenting logic when a user configures a probability sampler. 
Resolves #1526 
Note: we definitely need to figure out a more robust configuration story for samplers, but that's out of scope for this PR.
=> Preserve the ParentOrElse behavior when changing sampling probability via configuration

exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
We already did so for OTLP exporters.
=> Use asyncronous calls for exporting from Zipkin and Jaeger exporters.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
closes  [https://github.com/open-telemetry/opentelemetry-java/issues/1572](https://github.com/open-telemetry/opentelemetry-java/issues/1572)
=> Rename ParentOrElse to ParentBased and generalize to support all cases

api/src/main/java/io/opentelemetry/trace/DefaultSpan.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/trace/DefaultSpanTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1597](https://github.com/open-telemetry/opentelemetry-java/issues/1597)
=> Add an overload to the recordException method to support additional attributes

exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/MetricAdapterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java
Currently, java instrumentation smoke tests fail because we use JSON. collector `file` exporter writes as JSON and the tests read the JSON. But currently the JSON is not compatible between collector and Java because of renamed enums. Updating the proto will allow us to continue to develop against new versions of the collector.
I'm guessing the intent of the metrics protocol change is for the SDK to also adopt similar data structures. I'm not doing that in this PR since I only want to make the SDK JSON-compatible with the latest collectors - at the same time I've probably made them somewhat compatible for metrics too. The conversion of summary to histogram is clearly not ideal, converting double values into long counts, but I think semantically it may capture something reasonable. Anyways …
=> Update opentelemetry-proto to latest version.

api/src/main/java/io/opentelemetry/trace/DefaultTracer.java, api/src/test/java/io/opentelemetry/trace/DefaultTracerTest.java
See https://github.com/open-telemetry/opentelemetry-java/pull/1611#discussion_r481282746
=> DefaultTracer: Fix noParent being ignored after explicit parent.

README.md
Anuraag has been a fantastic and consistent reviewer and contributor, and has shown that he is committed to making the project successful. I'd like to promote him to maintainer from approver.
=> Promote @anuraaga to maintainer

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java
Currently it's not possible to wait / listen on the result of a flush.
=> Return result in TracerSdkProvider.forceFlush

api/src/main/java/io/opentelemetry/internal/StringUtils.java, api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java, api/src/test/java/io/opentelemetry/metrics/DoubleCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleUpDownCounterTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleUpDownSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/DoubleValueObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongUpDownCounterTest.java, api/src/test/java/io/opentelemetry/metrics/LongUpDownSumObserverTest.java, api/src/test/java/io/opentelemetry/metrics/LongValueObserverTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkTest.java
This PR properly addresses the requirements for metric instrument names.
[Spec link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#instrument-naming-requirements)
=> Case-insensitive names for metric instruments

CONTRIBUTING.md, README.md
And, add a link in the README to the examples
=> Remove instructions on generating javadoc

examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSampler.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSamplerTest.java
This PR updates the names of Sampling result for consistency, closing [#1648](https://github.com/open-telemetry/opentelemetry-java/issues/1648)
The changes have been made following these specifications:  
[open-telemetry/opentelemetry-specification#938](https://github.com/open-telemetry/opentelemetry-specification/pull/938)
[open-telemetry/opentelemetry-specification#956 ](https://github.com/open-telemetry/opentelemetry-specification/pull/956)
Changed from:
- `NOT_RECORD`
- `RECORD`
- `RECORD_AND_SAMPLED`
Changed to: 
- `DROP`
- `RECORD_ONLY`
- `RECORD_AND_SAMPLE`
=> Updated sampling result name

api/src/main/java/io/opentelemetry/metrics/DoubleCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleSumObserver.java, api/src/main/java/io/opentelemetry/metrics/DoubleUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/DoubleUpDownSumObserver.java, api/src/main/java/io/opentelemetry/metrics/DoubleValueObserver.java, api/src/main/java/io/opentelemetry/metrics/DoubleValueRecorder.java, api/src/main/java/io/opentelemetry/metrics/LongCounter.java, api/src/main/java/io/opentelemetry/metrics/LongSumObserver.java, api/src/main/java/io/opentelemetry/metrics/LongUpDownCounter.java, api/src/main/java/io/opentelemetry/metrics/LongUpDownSumObserver.java, api/src/main/java/io/opentelemetry/metrics/LongValueObserver.java, api/src/main/java/io/opentelemetry/metrics/LongValueRecorder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterSdkRegistryTest.java
This is a follow-up from #870 
After `MeterRegistry` was renamed to `MeterProvider`, some of the javadoc examples still pointed to the old name, which could be misleading/confusing for new users.
There was also one remaining variable reference.
=> Rename dangling references to MeterRegistry

api/src/main/java/io/opentelemetry/common/AttributeKey.java, api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java
This was done by tricking AutoValue with a separate field for the storage.
resolves #1678
=> Make the getKey method on AttributeKey non-nullable

.circleci/config.yml, all/build.gradle, integration_tests/tracecontext/README.md, integration_tests/tracecontext/build.gradle, integration_tests/tracecontext/src/main/java/io/opentelemetry/Application.java, integration_tests/tracecontext/src/main/java/io/opentelemetry/Request.java, integration_tests/tracecontext/tracecontext-integration-test.sh, settings.gradle
It's already done for Python and JS.
Although most of the tests pass there are some which fail.
Because execution of the tests is not part of the circleci workflow it doesn't affect build.
```
----------------------------------------------------------------------
Ran 40 tests in 1.220s
FAILED (failures=3, skipped=6)
```
=> Add w3c context propagation tests

api/src/main/java/io/opentelemetry/trace/Span.java, api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
This adds a semantic attribute key for `exception.escaped` as introduced in open-telemetry/opentelemetry-specification#784 (updated in open-telemetry/opentelemetry-specification#946).
It also cleans up the javadoc on the existing exception semantic attributes.
=> Add exception.escaped, clean up exception attributes javadoc.

exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java
=> round the zipkin span duration up to 1 microsecond, if it's zero.

api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/OtTracerPropagator.java, integration_tests/tracecontext/src/main/java/io/opentelemetry/Application.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java
We check for `isValid` everywhere so this will not be a performance hit, explicitly because the DefaultSpan.getInvalid().getContext().isValid() will be memoized.
=> Avoid usage of getSpanWithoutDefault when possible.

sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource/Ec2Resource.java
At least the first warning definitely should be flipped or it always logs when off EC2. The other ones also don't seem helpful to warn over since it's not critical resource information.
=> Log EC2Resource messages at FINE.

api/src/main/java/io/opentelemetry/trace/attributes/SemanticAttributes.java
=> Fix type for REDIS_DATABASE_INDEX semantic attribute

QUICKSTART.md, api/src/main/java/io/opentelemetry/trace/Status.java, api/src/test/java/io/opentelemetry/trace/StatusTest.java, examples/otlp/src/main/java/io/opentelemetry/example/OtlpExporterExample.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/AdapterTest.java, exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/SpanAdapter.java, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/SpanAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporterTest.java, extensions/trace_utils/src/main/java/io/opentelemetry/extensions/trace/CurrentSpanUtils.java, extensions/trace_utils/src/test/java/io/opentelemetry/extensions/trace/CurrentSpanUtilsTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk_extensions/testbed/src/test/java/io/opentelemetry/sdk/extensions/trace/testbed/errorreporting/ErrorReportingTest.java, sdk_extensions/tracing_incubator/src/test/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilderTest.java, sdk_extensions/zpages/src/jmh/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorBenchmark.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezDataAggregatorTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessorTest.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandlerTest.java
resolves #1700 
Note: I made the numeric codes match the proposed protobuf status codes.
=> Update for the more restricted span status codes.

.github/workflows/continuous-build.yml
For #1381
We've made a lot of good progress on migrating instrumentation repo to actions. This repo is much easier, so we may as well do it. It let's us easily test multiple OS's, to avoid an e.g. Windows contributor have the build fail for them. Supports testcontainers well without having to fallback to a machine executor. And I think we can use a similar config for release builds later, which would allow starting a release from a button on the UI without any local, manual steps at all.
I haven't added snapshot publishing to this yet since presumably that should go together with removing the CircleCI master build. I do upload to codecov since I think uploading twice is harmless. And I just run `:check` - the circleci config separates out several tasks, but from what I can tell `:check` …
=> Add GitHub Actions continuous build to replace CircleCI.

api/src/main/java/io/opentelemetry/common/Attributes.java, api/src/main/java/io/opentelemetry/common/package-info.java, api/src/main/java/io/opentelemetry/trace/Span.java, api/src/test/java/io/opentelemetry/common/AttributesTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java
=> Make setting null-valued attributes a no-op, and document that their behavior is undefined.

build.gradle, exporters/jaeger/build.gradle, exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java, integration_tests/build.gradle, opentracing_shim/build.gradle, sdk/common/build.gradle, sdk/common/src/test/java/io/opentelemetry/sdk/common/CompletableResultCodeTest.java, sdk/tracing/build.gradle, sdk_extensions/jaeger_remote_sampler/build.gradle, sdk_extensions/testbed/build.gradle
Noticed these sometimes fail randomly. Also went ahead and made awaitility automatic test dependency since it's otherwise harmless yet often useful since we have many async tests.
=> Use awaitility / higher timeout to reduce flakiness.

.github/workflows/continuous-build.yml
I was hoping since this is a simple build it'd be ok but I see the throttling happening quite a bit here too. I hope it's not permanent but let me try disabling it to see the effect on the build @iNikem @vlsi
=> Disable cache action remote proxy

exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporterTest.java
If the thread sleeps for 500ms or so between the calls of `withDeadlineAfter` and `export`, the test will fail. A full GC or similar, during CI, can get to that range and we see this happen more often on GitHub Actions which might have more thread contention that CircleCI. Increasing the deadline should reduce the chance of this, and I think for the original intent of the regression test, we can get seconds of runtime back by only exporting once and sleeping for a small amount more than the deadline, which guarantees triggering the previously broken behavior.
=> Increase deadline for deadline test.

bom/build.gradle, build.gradle
Don't set packaging type explicitly since Gradle determines it automatically, set description for BOM project, and remove outdated bom publication configuration
=> Fixes for BOM publishing

sdk/common/src/test/java/io/opentelemetry/sdk/common/CompletableResultCodeTest.java
Not totally sure but seems reasonable to require some time to propagate interruption to another thread and can get unflipped by the time of assertion.
=> Remove assertion on interrupted which is not reliable.

sdk_extensions/logging/src/test/java/io/opentelemetry/sdk/logging/LogSinkSdkProviderTest.java, sdk_extensions/logging/src/test/java/io/opentelemetry/sdk/logging/sdk/BatchLogProcessorTest.java
500ms tends to be a bit tight on slower machines like GitHub so lightened a bit.
=> Loosen test waiting time and migrate to junit5 while here.

build.gradle
Follow-up for #1529.
Since we also have a "Validate Gradlew Wrapper" task, I was somehow expecting this to be checked already. Since it was outdated for quite some time, maybe we can just remove the `wrapper{}` block from build.gradle? No idea what the implications would be.
=> Update wrapper declaration in build.gradle

api/src/main/java/io/opentelemetry/baggage/Entry.java, api/src/main/java/io/opentelemetry/baggage/EntryMetadata.java, api/src/test/java/io/opentelemetry/baggage/DefaultBaggageManagerTest.java, api/src/test/java/io/opentelemetry/baggage/EntryMetadataTest.java, api/src/test/java/io/opentelemetry/baggage/EntryTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/BaggageSdkTest.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/ScopedBaggageTest.java
This is the first step toward a W3C Baggage Propagator implementation.
Amends #1530
=> Turn the Baggage metadata into a simple wrapper for a String.

api/src/main/java/io/opentelemetry/baggage/Baggage.java, api/src/main/java/io/opentelemetry/baggage/BaggageManager.java, api/src/main/java/io/opentelemetry/baggage/DefaultBaggageManager.java, api/src/main/java/io/opentelemetry/baggage/Entry.java, api/src/test/java/io/opentelemetry/OpenTelemetryTest.java, api/src/test/java/io/opentelemetry/baggage/DefaultBaggageManagerTest.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShimTable.java, sdk/baggage/src/main/java/io/opentelemetry/sdk/baggage/BaggageManagerSdk.java, sdk/baggage/src/main/java/io/opentelemetry/sdk/baggage/BaggageSdk.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/BaggageManagerSdkTest.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/BaggageSdkTest.java, sdk/baggage/src/test/java/io/opentelemetry/sdk/baggage/ScopedBaggageTest.java
Parenting is still allowed via the Context.
Also, renamed many old variables and method to use the new baggage name.
Builds on changes in #1764
Amends #1530
=> Remove the method to parent via Baggage. 

sdk/all/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanAttributeTruncateBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorFlushBenchmark.java, sdk/baggage/src/main/java/io/opentelemetry/sdk/baggage/BaggageSdk.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/CompletableResultCode.java, sdk/common/src/test/java/io/opentelemetry/sdk/common/CompletableResultCodeTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/BatchRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCount.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleSumAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCount.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongSumAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/NoopAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/README.md, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregatorTest.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
* Use lambdas or method references where possible
* Remove dead code
* Make members final where possible
* Use Objects.equals instead of manually implementing the same functionality
=> Fix warnings found by idea IDE in the SDK dir.

all/build.gradle
I noticed reports with low coverage had these protos included, which have almost no coverage. I'm not sure why sometimes they're included in the report and sometimes not, but I could reliably see reports locally have lots of red for this folder before the change and it's gone after.
=> Exclude jaeger proto classes from coverage.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/Aggregations.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java
See this spec update:  https://github.com/open-telemetry/opentelemetry-specification/pull/984
Resolves #1780
=> Convert the ValueObserver instruments to use the LastValue aggegration.

extensions/trace_propagators/src/jmh/java/io/opentelemetry/extensions/trace/propagation/PropagatorContextExtractBenchmark.java, extensions/trace_propagators/src/jmh/java/io/opentelemetry/extensions/trace/propagation/PropagatorContextInjectBenchmark.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3Propagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractor.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorMultipleHeaders.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorExtractorSingleHeader.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/B3PropagatorTest.java, extensions/trace_propagators/src/test/java/io/opentelemetry/extensions/trace/propagation/TraceMultiPropagatorTest.java
resolves #1684 
Wasn't sure what you had in mind for making the ```B3Propagator``` configurable so I added a builder that can configure creation of it.
Default (inject single header)
```
B3Propagator.getInstance();
```
Using builder
```
B3Propagator.builder()
.injectFromMultipleHeaders()
.build();
```
=> changed B3Propagator to default to inject/extra single header

.circleci/config.yml, .github/workflows/patch-release-build.yml, .github/workflows/release-build.yml, Makefile, README.md, RELEASING.md, build.gradle, settings.gradle
This makes three major changes
- Use nebula-release-plugin for determining version number of project. Mainly to allow SNAPSHOT version to automatically be set to the minor version after the previous release tag on master. This is same pattern as instrumentation repo.
- Add a release workflow which builds artifacts for a version specified by the releaser, updates README, tags master with the released version
- Add a patch release workflow that first creates a release branch if none exists yet, cherrypicks provided commits, and builds artifacts for provided version, tags release branch, updates README in master
Because SNAPSHOT versions are based on the previous tag on master, there is a chicken/egg problem where our current tag is on a release branch and not picked up. So until the next …
=> Add GitHub workflows to automate releases

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessor.java, sdk_extensions/async_processor/src/main/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorEventQueue.java, sdk_extensions/async_processor/src/test/java/io/opentelemetry/sdk/extensions/trace/export/DisruptorAsyncSpanProcessorTest.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessor.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TracezSpanProcessorTest.java
=> Add Context arg to SpanProcessor.OnStart.

build.gradle, exporters/jaeger/build.gradle, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, integration_tests/build.gradle, integration_tests/src/test/java/io/opentelemetry/JaegerExporterIntegrationTest.java, integration_tests/tracecontext/build.gradle, sdk_extensions/aws_v1_support/build.gradle
restassured launches a groovy runtime, which sometimes causes random failures like I saw on Java 14. The groovy is presumably to support some hip assertions, but ours are definitely not taking advantage of this complexity - switched to a normal http request / parse.
Fixes #1816
=> Replace restassured test assertion with okhttp/jackson

QUICKSTART.md, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/package-info.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigSystemPropertiesTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
resolves [https://github.com/open-telemetry/opentelemetry-java/issues/1802](https://github.com/open-telemetry/opentelemetry-java/issues/1802)
=> Update TraceConfig configuration option names

context/src/test/java/io/opentelemetry/context/ContextTest.java
I've generally found 10 seconds to be a "good default" test timeout to deal with CI issues (https://github.com/open-telemetry/opentelemetry-java/runs/1273993981?check_suite_focus=true). The only reason I didn't use 10 here was at first I didn't realize I'd need a separate thread executor (direct executor generally doesn't require a high timeout) until I started writing `WrapScheduledExecutorService` but hadn't backport the timeout bumps.
=> Increase timeout for context wrap test.

exporters/otlp/src/test/java/io/opentelemetry/exporters/otlp/OtlpGrpcMetricExporterTest.java
I made a similar change in the span exporter but not metric exporter since it hadn't flaked yet.
=> Loosen deadline check in metric exporter.

api/src/main/java/io/opentelemetry/baggage/propagation/W3CBaggagePropagator.java, api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/trace/propagation/HttpTraceContextTest.java, context_prop/src/main/java/io/opentelemetry/context/propagation/DefaultContextPropagators.java, context_prop/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/AwsXRayPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/B3Propagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/JaegerPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/OtTracerPropagator.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/TraceMultiPropagator.java
The added unit tests for HttpTraceContext demonstrates one case where that is useful. A getter that handles null gracefully would be another case.
Note that inject already allowed null carriers, but extract (where these are actually more likely to happen) did not. For example, if I have a getter that handles null like an empty headerlist, I still get a NPE when using HttpTraceContext. This PR fixes that.
=> Fix non-null carrier not working in extract.

context/src/main/java/io/opentelemetry/context/Context.java, context/src/main/java/io/opentelemetry/context/ContextStorage.java, context/src/main/java/io/opentelemetry/context/DefaultContext.java, context/src/main/java/io/opentelemetry/context/LazyStorage.java, context/src/main/java/io/opentelemetry/context/PersistentHashArrayMappedTrie.java
Got lost in merge.
Fixes #1820
/cc @iNikem
=> Restore third party copyright headers in context package.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Sampler.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/PerOperationSampler.java, sdk_extensions/jaeger_remote_sampler/src/main/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSampler.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/RateLimitingSamplerTest.java
See this recent spec update: https://github.com/open-telemetry/opentelemetry-specification/pull/881
=> Change the sampling API to take a parent Context, rather than SpanContext

.circleci/config.yml, .github/workflows/continuous-build.yml
Removes codecov publishing from CircleCI too.
After merging this and confirming it works OK, I will remove the CircleCI build.
=> Publish snapshots from GitHub CI instead of CircleCI

settings.gradle
When running build with Gradle 8, error prone plugin logs a warning that's been fixed.
=> Update error prone plugin to support toolchains.

.github/workflows/master-build.yml, .github/workflows/pr-build.yml
There is a small disruption to contributor experience with the single file because GitHub does not collapse the checks if any are skipped. It seems like something they should fix - but these files shouldn't have much churn anyways so even with some blatant duplication I think this is better.
=> Split off PR build to separate workflow

QUICKSTART.md, api/src/main/java/io/opentelemetry/DefaultOpenTelemetry.java, api/src/main/java/io/opentelemetry/OpenTelemetry.java, api/src/main/java/io/opentelemetry/spi/OpenTelemetryFactory.java, exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryMetricExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, integration_tests/src/main/java/io/opentelemetry/SendTraceToJaeger.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/OpenTelemetryInteroperabilityTest.java, perf_harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanAttributeTruncateBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdkFactory.java, sdk/all/src/main/resources/META-INF/services/io.opentelemetry.spi.OpenTelemetryFactory, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/ZPageServer.java, sdk_extensions/zpages/src/test/java/io/opentelemetry/sdk/extensions/zpages/TraceConfigzZPageHandlerTest.java
See #1737 for the discussion.
I don't want to merge a bad PR and a followup renaming like last time since it's confusing and a bit too tedious. I have two commits here, https://github.com/open-telemetry/opentelemetry-java/commit/949bfec50307d4da4a8cd028da3bf617049b8224 is the significant one to check out, the other just applies renames.
Fixes #1109 (each app can have its own OpenTelemetry for different Resource which seems to be the crux of the issue)
Fixes #1149
Fixes #1454
Fixes #747
=> Make OpenTelemetrySdk implement the OpenTelemetry interface and have SPI find it.

extensions/trace_utils/src/test/java/io/opentelemetry/extensions/trace/CurrentSpanUtilsTest.java
I'll probably replace usages of mock(Span) with spy globally later, but figure here it's an important example of using it to avoid doCallRealMethod, which is tedious for interfaces IMO (but a decision mockito has made and seems final).
=> Replace mock with spy in CurrentSpanUtilsTest.

QUICKSTART.md
Add additional links to the glossary where it is made clear that the instrumenting library may be the same as the instrumented library, in which case the library author is to provider their own library's name as the instrumenting library.
=> Add more details for library authors to quickstart

exporters/jaeger/build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java
The `JaegerGrpcSpanExporter.Builder` has a public method that takes a `io.grpc.ManagedChannel`. Unless the Jaeger exporter declares an api dependency on GRPC API in Gradle, Gradle consumers will not find the GRPC API on their compile path.
=> Make GRPC an API dependency of Jaeger exporter

context/src/main/java/io/opentelemetry/context/ContextStorage.java, context/src/main/java/io/opentelemetry/context/LazyStorage.java
For agent to override the ContextStorage implementation, we have a similar classloading ordering problem as with `Span.current` so need a package private method instead to instrument.
=> Add get() method to LazyStorage instead of accessing field directly.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/Samplers.java
=> Make the ParentBased sampler (and builder) public so SDK users can create their own combinations

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/IdsGenerator.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RandomIdsGenerator.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RandomIdsGeneratorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SamplersTest.java, sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/AwsXRayIdsGenerator.java
I didn't keep the `ThreadLocalRandom` piece from the previous javadoc but am a bit on the fence. While it's an implementation detail that we may even change later, so usually wouldn't put it in a javadoc, it's an important implementation detail that users may need to know.
=> Expose factory for random IDs generator instead of type.

build.gradle, sdk_extensions/zpages/README.md
- Add a badge to indicate the latest version. This is more reliable than manually updating the readme with releases.
- Adjust the Maven and Gradle snippets to not include a version number, since it quickly becomes out of date.
- Remove dependencies that are pulled in transitively from the Maven and Gradle snippets. They already don't include all of the transitive dependencies, so no need to only include some.
- Add a link to the blog post introducing zPages, to give more information.
=> Update zPages readme

all/build.gradle
These don't have any coverage since the code is run in docker. A more general rule is to only have coverage of what we publish to maven - which I'll probably refactor this list into being generated programatically at some point.
=> Remove integration tests from coverage report.

context/src/main/java/io/opentelemetry/context/Context.java, context/src/main/java/io/opentelemetry/context/DefaultContext.java, context/src/test/java/io/opentelemetry/context/ContextTest.java
I noticed after integrating Context into the instrumentation we don't really need the `with` overloads. Also on a second thought, they seem to conflict with the recommendation in the javadoc to "combine multiple related items together into a single key instead of separating them" - it seems extremely rare you'd have key / value available to store at the same time even when they're not related (in our potential use case, it's basically when one of them is `ImplicitContextKeyed` in which case we don't have a method for combining into a single write anyways). So figured it's good to keep it small for now.
Also added some javadoc drift fixes.
=> Remove Context.with overloads.

api/src/main/java/io/opentelemetry/api/baggage/BaggageUtils.java, context/src/braveInOtelTest/java/io/opentelemetry/context/OpenTelemetryCurrentTraceContext.java, context/src/grpcInOtelTest/java/io/grpc/override/ContextStorageOverride.java, context/src/main/java/io/opentelemetry/context/Context.java
False positives happen only in interop cases where scopes are wrapped, but in vast amount of user code it should be precise. Agent will have to disable it though since we open scope in `onMethodEnter` and close in `onMethodExit`
=> Add MustBeClosed to Context.makeCurrent

.github/workflows/docker-test-containers.yml, exporters/jaeger/src/test/java/io/opentelemetry/exporters/jaeger/JaegerIntegrationTest.java, integration_tests/src/test/java/io/opentelemetry/JaegerExporterIntegrationTest.java, perf_harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk_extensions/jaeger_remote_sampler/src/test/java/io/opentelemetry/sdk/extensions/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java
Docker Hub pull limit coming up, so let's copy our images to hopefully reduce potential flakiness. Working on hopefully getting a GHCR repo which would be less backdoor (tied to GitHub permissions, etc) than bintray.
=> Add workflow to copy docker hub images to bintray and use in integration tests.

exporters/zipkin/src/main/java/io/opentelemetry/exporters/zipkin/ZipkinSpanExporter.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanWrapper.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk_extensions/tracing_incubator/src/main/java/io/opentelemetry/sdk/extensions/incubator/trace/data/DelegatingSpanData.java, sdk_extensions/tracing_incubator/src/main/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilder.java, sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TracezZPageHandler.java, testing_internal/src/main/java/io/opentelemetry/sdk/trace/TestSpanData.java, testing_internal/src/test/java/io/opentelemetry/sdk/trace/TestSpanDataTest.java
It's either all `get` or no `get` so this seems the way to allow a mix.
Alternatively, `isEnded` and `isParentRemote` would be allowed without hacking, but the latter sounds bad to me (but still better than `isRemoteParent` which is incorrect)
Fixes #1910
=> Rename getHasRemoteParent and getHasEnded to remove get.

api/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/src/main/java/io/opentelemetry/api/trace/propagation/HttpTraceContext.java
We don't want users to extend classes that are not interfaces in our API
=> Ensure all public classes in the API are final

gradle.properties
I just noticed that this repo also has the same problem as instrumentation repo, which I filed an issue about in https://github.com/gradle/gradle/issues/14224
The actual max workers is 8, which is high enough to cause a reasonable probability of two testcontainers at the same time which usually fails. One alternative is to combine all of our testcontainer tests into one project, integration-tests, so they don't run in parallel. This seems like an OK approach to me. In the meantime, let's match the value with the instrumentation repo, which I think can help with our testcontainer woes.
=> Reduce max workers since Gradle cheats anyways

CONTRIBUTING.md
=> Initial list of best practices to follow in our project

api/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java, opentracing_shim/README.md, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/OpenTracingShim.java, opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/package-info.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/OpenTracingShimTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/OpenTelemetryInteroperabilityTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/activespanreplacement/ActiveSpanReplacementTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/actorpropagation/ActorPropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/baggagehandling/BaggageHandlingTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/TestClientServerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/concurrentcommonrequesthandler/HandlerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/latespanfinish/LateSpanFinishTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/listenerperrequest/ListenerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/nestedcallbacks/NestedCallbacksTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/promisepropagation/PromisePropagationTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/statelesscommonrequesthandler/HandlerTest.java, opentracing_shim/src/test/java/io/opentelemetry/opentracingshim/testbed/suspendresumepropagation/SuspendResumePropagationTest.java
* Rename TraceShim factory to OpenTracingShim
* Remove factory method from OpenTracingShim which used mixed pieces of the openTelemetry components.
* Made the constructor for W3CBaggagePropagator private.
* Updated OpenTracingShim README
=> Miscelleneous cleanup

README.md
Now API packages already moved to `.api.package`
=> Fix api link in README.md

api/src/main/java/io/opentelemetry/api/trace/propagation/HttpTraceContext.java, extensions/trace_propagators/src/main/java/io/opentelemetry/extensions/trace/propagation/Common.java
It looks like w3c was the only one logging at info
Fixes #1963
=> Use fine logging in w3c/b3 propagator instead of info.

context/src/main/java/io/opentelemetry/context/ContextStorage.java, context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java
~~Currently the `ThreadLocalContextStorage` sets the `ThreadLocal` to `Context.root()` within the static constructor.  However, this only sets the value of the `ThreadLocal` for the thread that happens to execute that constructor.  For all other threads the `ThreadLocal` remains unset and `THREAD_LOCAL_STORAGE.get()` will return `null` which is likely unexpected by the consumer.~~
~~There are two options here:~~
1. ~~Have `THREAD_LOCAL_STORAGE` be a class derived from `ThreadLocal<Context>` and override the `initialValue` method to return an initial value for when the thread local has not been set for the current thread.~~
2. ~~Have `current()` check if `THREAD_LOCAL_STORAGE.get()` returns `null` and return `Context.root()` instead.~~
~~Since all reads to the `ThreadLocal` go through the …
=> Documents that ContextStorage.current can return null

api/src/main/java/io/opentelemetry/api/trace/TraceState.java, api/src/main/java/io/opentelemetry/api/trace/propagation/HttpTraceContext.java, api/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java
I noticed instead of exposing `Entry`, we can follow the same pattern as we do in `Attributes`. We could remove Entry completely in the future if wanted (presumably users will prefer us to implement `Map` in the future anyways)
=> Expose foreach consumer instead of entries for trace state.

CHANGELOG.md
- update formatting for unreleased CHANGELOG entries
- final edit of unreleased CHANGELOG entries
- added [PR-2002](https://github.com/open-telemetry/opentelemetry-java/pull/2002) to extensions breaking changes
=> Update CHANGELOG 0.10.0 formatting and edit entries

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/AttributesMapTest.java
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes
This only changes attributes attached to Spans. Other attributes are sorted in lexigraphical order, by key, at the moment.
I don't know why the spec says that we should keep them in order...that feels like an odd expectation, especially for Java users who would probably think of them like a `Map`, which wouldn't provide ordering guarantees, normally.
=> Keep Span Attributes in order, as the spec strongly suggests.

.github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml
It's not necessary to run this build workflow when only  `*.md` files are modified. Please consider if that make sense.
=> Add paths-ignore for PR Build

.github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml
This reverts commit 72c88b61
Unfortunately, this made it so doc-only PRs can never go green, because we require the builds to pass for PRs.
=> Revert "Add paths-ignore for PR Build (#2017)"

api/build.gradle, build.gradle, context/build.gradle, exporters/jaeger-thrift/build.gradle, exporters/jaeger/build.gradle, exporters/logging/build.gradle, exporters/otlp/build.gradle, exporters/prometheus/build.gradle, exporters/zipkin/build.gradle, extensions/trace-propagators/build.gradle, extensions/trace-utils/build.gradle, integration-tests/build.gradle, proto/build.gradle, sdk-extensions/aws-v1-support/build.gradle, sdk-extensions/jaeger-remote-sampler/build.gradle, sdk-extensions/logging/build.gradle, sdk-extensions/otproto/build.gradle, sdk-extensions/resources/build.gradle, sdk-extensions/tracing-incubator/build.gradle, sdk/all/build.gradle, sdk/common/build.gradle, sdk/metrics/build.gradle, sdk/tracing/build.gradle, settings.gradle
As far as I can tell, the androidscents we use and is commonly documented is basically unmaintained - I can't find a project page and the last release was Android API 27 some years ago. So naturally they also don't have any signature that models the desugaring mechanism we are expecting Android users to do.
Gummy bears is a relatively new project but seems to be filling this void excellently
https://github.com/open-toast/gummy-bears
I confirmed that the new signature accepts `Instant` with the `coreLib` classifier version and fails without it
Fixes #1808
Changelog:
- Replace animalsniffer Android API check with gummy bears to recognize modern Android desugaring
=> Switch animal sniffer signature to gummy bears.

sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/TracerSdkTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1997](https://github.com/open-telemetry/opentelemetry-java/issues/1997)
=> Provide default implementations for SpanProcessor.shutdown and forceFlush

api/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/OpenTracingShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/OpenTelemetryInteroperabilityTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/TestUtils.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/activespanreplacement/ActiveSpanReplacementTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/baggagehandling/BaggageHandlingTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/clientserver/TestClientServerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/concurrentcommonrequesthandler/HandlerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/latespanfinish/LateSpanFinishTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/listenerperrequest/ListenerTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/multiplecallbacks/MultipleCallbacksTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/nestedcallbacks/NestedCallbacksTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/statelesscommonrequesthandler/HandlerTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimiterTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSamplerTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/testbed/clientserver/TestClientServerTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/testbed/errorreporting/ErrorReportingTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/testbed/statelesscommonrequesthandler/HandlerTest.java
Remove uses of JUnit 4 and JUnit 5 assert* where a functional equivalent exists in AssertJ. JUnit 5's assertThrows remains.
Fixes #1994
Conversion was done primarily using automated replacement, but I tried to find places where manual improvements could be made. For example, when the expected/actual were obviously in the wrong order for `assertEquals` or where `assertThat(list).hasSize(n)` could replace `assertEquals(n, list.size())`
=> Replace all assertions with AssetJ's assertThat

api/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/src/main/java/io/opentelemetry/api/common/Attributes.java, api/src/main/java/io/opentelemetry/api/common/Labels.java, api/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java, api/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java, api/src/test/java/io/opentelemetry/api/internal/ImmutableKeyValuePairsTest.java
This just reuses `ImmutableKeyValuePairs` for most heavy-lifting.
I did this now mainly since I realized `equals` is buggy (doesn't handle parenting correctly) and this fixes it.
Changelog:
- Baggage implementation changed from a HashMap with parenting for data reuse to array.
=> Implement baggage using array of key/value pairs instead of Map.

QUICKSTART.md
=> Update the QUICKSTART.md for the 0.10.0 release.

context/build.gradle, context/src/main/java/io/opentelemetry/context/DefaultContext.java, context/src/main/java/io/opentelemetry/context/LazyStorage.java, context/src/test/java/io/opentelemetry/context/LazyStorageTest.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1818](https://github.com/open-telemetry/opentelemetry-java/issues/1818)
=> Add a way to enforce default context storage implementation

api/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/src/test/java/io/opentelemetry/api/common/AttributesTest.java
Turns out quicksort isn't stable (equal-comparing keys don't stay in source-order).
Resolves #2043
=> Switch the key/value pair sorting to mergesort, because it is stable

api/src/main/java/io/opentelemetry/api/trace/PropagatedSpan.java, api/src/main/java/io/opentelemetry/api/trace/Span.java, api/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/SpanAdapter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/testbed/errorreporting/ErrorReportingTest.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanBuckets.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatus.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/testbed/errorreporting/ErrorReportingTest.java
* Clean up the SpanBuilder javadoc to match the current APIs
* Scrub mentions of canonical status code
* Deprecate the getCanonicalCode method on SpanBuilder and replace with getStatusCode
=> Some cleanup in span land.

.github/workflows/master-build.yml, .github/workflows/pr-build.yml
GitHub seems to default to 272 still - while we will want to revert this eventually to make sure it continues to be autobumped in the future, we're currently seeing core dumps that may be fixed by temporarily manual bumping.
http://openjdk.5641.n7.nabble.com/Bug-3812-New-IcedTea7-Backport-JDK-8250861-quot-Crash-in-MinINode-Ideal-PhaseGVN-bool-td431647.html
=> Explicitly bump CI to Java 8.0.275.

.github/workflows/master-build.yml, .github/workflows/pr-build.yml
I think in the instrumentation repo where we use the same plugin, it was ok on CircleCI since it defaults to fetching the full repo. And I noticed we don't actually have a GH version of that build there right now.
=> Fetch full repo in continuous build to allow computing nebula version.

api/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/all/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
We discussed this possibility several times, so I thought I'd give it a try.
Feedback welcome. This resolves #2018 as well.
=> Make the OpenTelemetrySdk a subclass of DefaultOpenTelemetry

api/src/main/java/io/opentelemetry/api/trace/TraceState.java, api/src/main/java/io/opentelemetry/api/trace/TraceStateBuilder.java, api/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java
Similar to #1964 and because of https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles
=> Ignore invalid usage of TraceState instead of throwing.

api/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, api/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java
And add a method to set the propagators on an instance, so that capability is preserved.
Resolves #2088
=> Deprecate the toBuilder methods on the OpenTelemetry classes

build.gradle, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/SpanBucket.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Long term we have #1944 but in the meantime, we definitely can't be using beta APIs so removed them and added a checker.
=> Remove usages of beta Guava APIs.

sdk-extensions/async-processor/src/test/java/io/opentelemetry/sdk/extension/trace/export/DisruptorAsyncSpanProcessorTest.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterBenchmark.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/NoopSpanExporter.java, sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/export/MultiSpanExporterTest.java
`forwarding` also came to mind instead of `delegating`. Either way, seems nice to hide the implementation.
=> Hide implementation of MultiSpanExporter/Processor behind interface.

api/src/main/java/io/opentelemetry/api/common/AttributesBuilder.java, api/src/test/java/io/opentelemetry/api/common/AttributesTest.java
Thanks to https://github.com/open-telemetry/opentelemetry-specification/commit/06638fc65519a021e29a213e54feae30880ce39e#diff-500cb43b9725373c25ea03660c293e59681e6e2f6ba3eb588188ed3b83dcbdcd
This is not ABI compatible but is API compatible for practical usages of the methods so I didn't do any deprecation.
=> Disallow null attribute array values.

exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcSpanExporter.java, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java
=> Change the default port that the OTLP exporters point to.

extensions/runtime-metrics/README.md, extensions/runtime-metrics/src/main/java/io/opentelemetry/extension/metrics/runtime/GarbageCollector.java, extensions/runtime-metrics/src/main/java/io/opentelemetry/extension/metrics/runtime/MemoryPools.java, extensions/runtime-metrics/src/main/java/io/opentelemetry/extension/metrics/runtime/package-info.java, extensions/runtime-metrics/src/test/java/io/opentelemetry/extension/metrics/runtime/MemoryPoolsTest.java
This module has been moved over to the instrumentation project: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1720
=> Deprecate the runtime-metrics code.

api/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java
Perhaps resolves #1834 
/cc @Oberon00 Does this close the loop on using the tracing SDK alone without the other pieces?
=> Add a static builder method to the OpenTelemetry interface.

sdk-extensions/resources/README.md, sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResource.java, sdk-extensions/resources/src/main/resources/META-INF/services/io.opentelemetry.sdk.resources.ResourceProvider, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResourceTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceAttributes.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/1908
=> Support process.runtime.* resource attributes

api/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/src/main/java/io/opentelemetry/api/trace/propagation/HttpTraceContext.java, api/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java, context/src/main/java/io/opentelemetry/context/propagation/NoopTextMapPropagator.java, context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java, context/src/test/java/io/opentelemetry/context/propagation/DefaultPropagatorsTest.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXRayPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/TraceMultiPropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/TraceMultiPropagatorTest.java
- changes the return type of the fields() method in TextMapPropagator from List<String> to Collection<String>
Addresses: #2011
=> Changes TextMapPropagator.fields() return type from List to Collection

api/src/main/java/io/opentelemetry/api/common/Attributes.java, api/src/main/java/io/opentelemetry/api/common/ReadableAttributes.java, api/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/src/main/java/io/opentelemetry/api/internal/ReadOnlyArrayMap.java, api/src/test/java/io/opentelemetry/api/common/AttributesTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/AttributesMapTest.java
If this makes sense, I'll follow up with the rest of the types.
Implementation copied from https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/internal/collect/UnsafeArrayMap.java
While it's possible to directly implement `Map`, I think `asMap` is better since it makes sure these are compile errors which I think they should be.
```java
Map<AttributeKey<?>, Object> attributes = Attributes.builder().build() // Users should be using Attributes type
Attributes attributes = Attributes.builder().build();
attributes.put() // Because of Map, these write operations leak into Attributes
```
`asMap` provides an intentional step to get into a read-only Map view. It's very unlikely Java would heap-allocate the wrapper in most code I think.
I considered making the unsupported …
=> Add asMap for Attributes.

settings.gradle
We use codecov - presumably this is some legacy artifact.
=> Remove coveralls plugin

sdk/all/build.gradle, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/common/build.gradle, sdk/common/src/main/java/io/opentelemetry/sdk/common/export/ConfigBuilder.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/EnvAutodetectResource.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourcesConfig.java, sdk/metrics/build.gradle, sdk/trace/build.gradle, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java
For #1944 
Remaining are gRPC-based artifacts (always use guava), opencensus shim (it's going away in new implementation type), and jfr (will probably use weak-lock-free for it after https://github.com/raphw/weak-lock-free/pull/12)
=> Remove Guava dependencies from SDK

api/src/main/java/io/opentelemetry/api/trace/attributes/SemanticAttributes.java, buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2
Including:
* update spec version to latest commit
* regenerate SemanticAttributes
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/2139
=> Fix buildscripts/semantic-convention/generate.sh script

extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextExtractBenchmark.java, extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextInjectBenchmark.java
Running the benchmark on an **m5.xlarge AWS EC2 instance, with 16 GB of memory and 4 vCPUs** for the trace propagators:
```shell
Benchmark                                                                                                               Mode  Cnt     Score     Error   Units
PropagatorContextExtractBenchmark.AwsXrayHeaderContextExtractBenchmark.measureExtract                                   avgt   15   373.515 ±   3.002   ns/op
PropagatorContextExtractBenchmark.AwsXrayHeaderContextExtractBenchmark.measureExtract:·gc.alloc.rate                    avgt   15   980.100 ±   7.732  MB/sec
PropagatorContextExtractBenchmark.AwsXrayHeaderContextExtractBenchmark.measureExtract:·gc.alloc.rate.norm               avgt   15   576.000 ±   0.001    B/op …
```
=> Adding micro-benchmarks for AwsXRayPropagator

extensions/trace-utils/README.md, extensions/trace-utils/src/main/java/io/opentelemetry/extension/trace/CurrentSpanUtils.java, extensions/trace-utils/src/main/java/io/opentelemetry/extension/trace/MessageEvent.java, extensions/trace-utils/src/test/java/io/opentelemetry/extension/trace/CurrentSpanUtilsTest.java
If anyone wants to keep these classes, let me know. `MessageEvent` seems very strange to me, I guess it should be related to the semantic attributes somehow. I'm pushing to delete it. `CurrentSpanUtils` is not useful really unless using the `boolean endSpan` feature. I've marked it for deprecation, but if anyone wants to keep this, I would probably remove the `boolean endSpan` since I don't think it should ever be used if not for it's auto-end-span functionality.
=> Deprecate trace-utils

sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java
Making the following changes to span creation according to the [span configuration](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/performance-benchmark.md#span-configuration) for performance benchmarking:
- Adding a service resource
- Adding the always on sampler
- Adding a single long type attribute
- Adding an event with no attributes
The benchmark result on a m5.xlarge EC2 instance:
```shell
Benchmark                                                                         Mode  Cnt     Score     Error   Units
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread                                thrpt   10  3274.915 ±  16.454  ops/ms
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.alloc.rate                 thrpt   10   882.267 ±   3.930  MB/sec …
```
=> Refactoring span benchmarking as per the spec

sdk/common/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java
Extreme nit, but I think during IntelliJ debugging I've noticed it's much more common to use a hyphen for this
=> Use hyphen for thread name prefix.

examples/build.gradle, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClient.java, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongValueObserverExample.java, examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
Note: the only actual breaking change that needed to be fixed was the removal of ReadableAttributes usage. Everything else is just getting rid of the deprecated usages.
=> Update the examples for the 0.12.0 release.

api/trace/src/main/java/io/opentelemetry/api/trace/propagation/TemporaryBuffers.java, api/trace/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/trace/src/test/java/io/opentelemetry/api/trace/propagation/TemporaryBuffersTest.java
=> Move TemporaryBuffers to be a package protected class, no need to expose this class

exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/SpanAdapter.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSampler.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java
Consistency with other APIs and reduction of confusion of return type not being `Context`
=> Rename Link.getContext -> Link.getSpanContext

api/baggage/src/jmh/java/io/opentelemetry/api/baggage/BaggageBenchmark.java, api/src/jmh/java/io/opentelemetry/api/trace/BaggageBenchmarks.java
Resolves #791 
The benchmarks here are for 0,1,10 and 100 items for each of the 4 different scenarios.
```
Benchmark                                                                       (itemsToAdd)  Mode  Cnt       Score       Error   Units
BaggageBenchmark.baggageItemBenchmark                                                      0  avgt   15      25.129 ±     0.717   ns/op
BaggageBenchmark.baggageItemBenchmark:·gc.alloc.rate                                       0  avgt   15    3035.656 ±    81.597  MB/sec
BaggageBenchmark.baggageItemBenchmark:·gc.alloc.rate.norm                                  0  avgt   15     120.000 ±     0.001    B/op
BaggageBenchmark.baggageItemBenchmark:·gc.churn.G1_Eden_Space                              0  avgt   15    3041.779 ±   131.702  MB/sec …
```
=> add some basic benchmarks for various baggage operations

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkManagement.java
This should make it clear it is a terminal operation. 
Resolves #2054
=> Add a section to the TracerSdkManagement.shutdown javadoc

.github/workflows/master-build.yml, .github/workflows/pr-build.yml
Reverts open-telemetry/opentelemetry-java#2072
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2073
=> Revert "Explicitly bump CI to Java 8.0.275."

sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourcesConfig.java
`ResourcesConfig` is specifically to configure SPI, a non-programmatic tool. I guess having a programmatic way of specifying it has no use case.
=> Move ResourcesConfig builder private

extensions/trace-propagators/README.md
This is intended to address #2067.  
I took a best guess at documenting where to go for help, so maybe this is just a start...and hopefully @anuraaga and @carlosalberto are both ok with the direct mentions (if not, please say something).  Are there other maintainers to mention as well?
We can talk about this more in #2067 but @anuraaga mentioned adding a [CODEOWNERS](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location) file, but those github docs didn't really suggest a good (supported) subdir location.
=> Update README for extensions propagators

sdk/all/build.gradle, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/all/src/jmh/resources/otel.yaml
Refactoring the span pipeline benchmark to align it to the throughput measurement in the spec. 
The OTLP collector is spun up using testContainers and OTLP exporter is being used to send spans to the collector.
running the benchmark with `./gradlew -PjmhIncludeSingleClass=SpanPipelineBenchmark :opentelemetry-sdk:jmh` on an m5.xlarge EC2 instance gives the following result:
```shell
Benchmark                                                                                                 Mode  Cnt       Score       Error   Units
SpanPipelineBenchmark.BatchSpanProcessorBenchmark.measureSpanPipeline                                    thrpt   15  527317.589 ± 42314.216   ops/s
SpanPipelineBenchmark.BatchSpanProcessorBenchmark.measureSpanPipeline:·gc.alloc.rate                     thrpt   15 …
```
=> Span benchmark with OTLP exporter and collector

exporters/jaeger-thrift/build.gradle, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java
This removes an unnecessary dependency from `jaeger-thrift` on grpc
=> remove test dependency on grpc

api/trace/src/main/java/io/opentelemetry/api/trace/Span.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
I noticed that shims like in https://github.com/open-telemetry/opentelemetry-java/pull/2060 would be easier to write with boring implementations in default methods.
=> Implement more Span default methods.

QUICKSTART.md, README.md
resolves #2246 
resolves #2247
=> Update some out-of-date/broken docs

sdk/common/src/main/java/io/opentelemetry/sdk/internal/JavaVersionSpecific.java
I don't know of any reason this needs to be public. So, let's not!
=> Make JavaVersionSpecific non-public.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/InstrumentRegistryTest.java
Fields removed:
* MeterProviderSharedState
* MeterSharedState
* InstrumentAccumulator - moved up one level
=> Remove unused fields from AbstractInstrument

sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TraceConfigzZPageHandler.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSdkManagement.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfigBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java
Consistency, and it looks like we get some better validation behavior (throw on set, not build) to boot.
I hadn't actually noticed we were using `Utils` here. In our meeting I think we were all ok with expecting the bom to be used to align dependencies so I'm perfectly fine with cross-referencing internal packages in this repo.
=> Move TraceConfig.Builder to the top level

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAsynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractSynchronousInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentProcessor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueObserverSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewRegistryTest.java
I was wrong initially, what we had as Batcher is actually the Processor in Go.
=> Rename accumulator to processor to match Go

api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetryBuilder.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetryBuilder.java, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
This PR also fixes the DefaultOpenTelemetry builder to be it's own class and not a sub-class.
=> Remove OpenTelemetryBuilder interface, every implementation will have it's own builder

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongLastValueAggregator.java
Not a problem in the Double version where this is implemented correctly.
=> Call point constructor with the value got instead of getting the value again

api/common/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java, api/common/src/main/java/io/opentelemetry/api/common/AttributeKey.java, api/common/src/main/java/io/opentelemetry/api/common/AttributeKeyImpl.java, api/common/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/common/src/test/java/io/opentelemetry/api/common/AttributeKeyTest.java, api/common/src/test/java/io/opentelemetry/api/common/AttributesTest.java, api/common/src/test/java/io/opentelemetry/api/common/LabelsTest.java, build.gradle
Instead passes a special `Comparator` to sortAndFilter where the old behavior is actually needed. A bit annoying, but all inside an internal class.
Also tried out a testing library I've been wanting to check out :) It was reporting the lack of getType in equals before the change.
Fixes #2282
=> Make AttributeKey compare normally with both type/key.

build.gradle, exporters/jaeger/build.gradle, proto/build.gradle, sdk-extensions/aws/build.gradle, sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/Ec2ResourceTest.java, sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/JdkHttpClientTest.java
Switches wiremock with armeria which supports junit5.
=> Migrate AWS mock server tests to junit5.

api/context/src/main/java/io/opentelemetry/context/ArrayBasedContext.java, api/context/src/test/java/io/opentelemetry/context/ContextTest.java
It's difficult to debug context issues, such as IntelliJ debugger view or the error messages from `StringContextStorage`, without a toString on Context.
=> Add Context.toString

api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java
Example usage in the `Application.java`.
=> Remove unnecessary setPropagators from OpenTelemetry interface

docs/rationale.md
As an alternative approach to #2212 
This options adds `-alpha` to the released *versions* of immature libraries, rather than adding `-experimental` to the artifacts.
Another option to fulfill  https://github.com/open-telemetry/opentelemetry-specification/issues/1267
=> Another option for release versioning proposal

CONTRIBUTING.md
Adds a section about class member ordering, since it's not covered in the google style guide, seemed like a good idea to document it, so we don't need to argue about it.
Also adds a line about the instability of `toString()` methods.
=> CONTRIBUTING.md update with some more best practices.

api/metrics/build.gradle, sdk/metrics/build.gradle
Resolves #2266.
After doing a `./gradlew clean build` the jars with alpha look like:
```
$ find . -name '*.jar' | grep alpha
./sdk/metrics/build/libs/opentelemetry-sdk-metrics-0.13.0-alpha-SNAPSHOT.jar
./sdk/metrics/build/libs/opentelemetry-sdk-metrics-0.13.0-alpha-SNAPSHOT-sources.jar
./sdk/metrics/build/libs/opentelemetry-sdk-metrics-0.13.0-alpha-SNAPSHOT-javadoc.jar
./api/metrics/build/libs/opentelemetry-api-metrics-0.13.0-alpha-SNAPSHOT-javadoc.jar
./api/metrics/build/libs/opentelemetry-api-metrics-0.13.0-alpha-SNAPSHOT-sources.jar
./api/metrics/build/libs/opentelemetry-api-metrics-0.13.0-alpha-SNAPSHOT.jar
```
=> inject alpha into the version for metrics api and sdk.

sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
For reasons see https://github.com/open-telemetry/opentelemetry-java/pull/2223#issuecomment-741095083, and just apply the basic rule of defining an API, when in doubt don't add it, we can always add more functionality, but we cannot remove it.
=> Remove duplicate getters and builder options from SDK

exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcSpanExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/package-info.java, exporters/otlp/src/test/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporterTest.java, exporters/otlp/src/test/java/io/opentelemetry/exporter/otlp/OtlpGrpcSpanExporterTest.java, sdk-extensions/otproto/README.md, sdk-extensions/otproto/build.gradle, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/CommonAdapter.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/CommonProperties.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/MetricAdapter.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/ResourceAdapter.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/SpanAdapter.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/package-info.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/CommonAdapterTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/MetricAdapterTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/ResourceAdapterTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/SpanAdapterTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtilsTest.java
In #2295 we are thinking of using these outside the gRPC exporter artifacts. And we probably will want to provide HTTP exporters eventually as well, so we need these conversions to live outside. `otproto` seems designed for it based on the README.
=> Move OTLP adapters to otproto module for use outside of gRPC exporters.

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
The Zipkin exporter specification for error handling has slightly changed regarding the removal of the `otel.status_description` tag in favour for the error tag.
Due to this, we now move the `error` tag setting into the `!status.isUnset()` condition.
Resolves [2272](https://github.com/open-telemetry/opentelemetry-java/issues/2272)
=> Update Zipkin exporter error handling

exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingMetricExporter.java, exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/OtlpGrpcMetricExporter.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/FakeMetricExporter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricExporter.java
closes [https://github.com/open-telemetry/opentelemetry-java/issues/2316](https://github.com/open-telemetry/opentelemetry-java/issues/2316)
=> Make MetricExporter shutdown method returns CompletableResultCode.

api/metrics/build.gradle, bom/build.gradle, build.gradle, sdk/metrics/build.gradle
This rolls back #2311 and reimplements #2328.
It does feel a bit hacky, but in my testing it does actually include `alpha` in the artifact names, poms, etc...and the bom change omits the metrics artifacts from the bom entirely.
=> Metrics are alpha take 2

extensions/annotations/build.gradle
If someone only uses `@WithSpan` annotation and declares `o.opentelemetry:opentelemetry-extension-annotations` as the only dependency, he will get these warnings on compilation:
```
warning: unknown enum constant Kind.INTERNAL
reason: class file for io.opentelemetry.api.trace.Span not found
```
According to [this](https://stackoverflow.com/questions/51368530/suppress-unknown-enum-constant-warning-for-enums-used-in-class-retention-annot) this is because `WithSpan` uses `Span.Kind` in its API. But in gradle it is declared as `implementation` dependency. Declaring it as `api` dependency should fix the problem.
=> Span.Kind is a part of annotation API and should be declared as such.

.github/workflows/master-build.yml, .github/workflows/pr-build.yml
Lately codecov has been flaky for unknown reasons - it works well for many commits then stops working for many commits. This uploads the HTML report to GitHub Actions so at least there's something to look at.
=> Upload coverage HTML report as action artifact.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/spi/SdkMeterProviderFactory.java, sdk/metrics/src/main/resources/META-INF/services/io.opentelemetry.spi.metrics.MeterProviderFactory, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/spi/SdkMeterProviderFactoryTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/spi/SdkTracerProviderFactory.java, sdk/trace/src/main/resources/META-INF/services/io.opentelemetry.spi.trace.TracerProviderFactory, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/spi/SdkTracerProviderFactoryTest.java
Follow the java convention to name Factories, ${CLASS_NAME}Factory.
=> Consistent naming for SPI classes

api/all/build.gradle, sdk/all/build.gradle
The gradle publishing hacks that put `-alpha` into the version string of the metrics modules missed the poms for the api and sdk modules, as seen here: https://bintray.com/beta/#/open-telemetry/maven/opentelemetry-java/0.13.0?tab=files
This PR is a stop-gap measure that makes the api and sdk modules depend directly on the metrics-api and metrics-sdk (respectively) at the `v0.13.0-alpha` version.  It's not great, but it should work around the current breakage.  This will end up being removed when the api and sdk no longer depend on the metrics modules at all.
=> Stop gap measure to fix api and sdk pom breakage dependency on metrics.

.github/workflows/patch-release-build.yml
Because changes might already exist in the release branch.
=> Don't require commit SHAs.

examples/build.gradle, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClient.java, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClientStream.java, examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpClient.java, examples/http/src/main/java/io/opentelemetry/example/http/HttpServer.java, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java, examples/metrics/src/main/java/io/opentelemetry/example/metrics/LongValueObserverExample.java, examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java, examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java, examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ZipkinExample.java
I think there is probably still work to be done on cleaning up the story in these examples, since SDK and API usage tends to be mixed together in unfortunate ways.
=> Convert the examples to not use the GlobalOpenTelemetry instance.

extensions/kotlin/src/test/kotlin/io/opentelemetry/extension/kotlin/KotlinCoroutinesTest.kt, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/jfr-events/src/test/java/io/opentelemetry/sdk/extension/jfr/JfrSpanProcessorTest.java, sdk-extensions/zpages/src/jmh/java/io/opentelemetry/sdk/extension/zpages/TracezDataAggregatorBenchmark.java, sdk-extensions/zpages/src/jmh/java/io/opentelemetry/sdk/extension/zpages/TracezSpanBucketsBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanAttributeTruncateBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorFlushBenchmark.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/testbed/clientserver/Client.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/testbed/clientserver/Server.java
Mostly to make the tests more readable rather than relying on what happens to be in the global at the time (possibly mutated in another test in the package).
=> Reduce usage of GlobalOpenTelemetry

exporters/prometheus/build.gradle
`PrometheusCollector` extends `Collector` so the prometheus artifact is actually in the public API of the module.
=> Make prometheus client API dependency of exporter.

api/context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java, api/context/src/test/java/io/opentelemetry/context/propagation/MultiTextMapPropagatorTest.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/TraceMultiPropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/TraceMultiPropagatorTest.java
This resolves #2244...even if the implementation here doesn't perfectly match what's in that issue.  There were discussions on the previous PR (#2273) and we agreed to deprecate the extension class and remove it in the next release.  Since 0.13.0 went out today, I assumed we could remove it in 0.14.0 but maybe people think 0.15.0 is better?
In any case, I also brought some missing tests over, hopefully coverage goes up slightly.
=> Deprecate trace mutli propagator

extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextExtractBenchmark.java, extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextInjectBenchmark.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagatorTest.java
Currently the id generator and propagator do not consistently spell xray which has been a bit strange. Now they do.
=> Rename AwsXRayPropagator to AwsXrayPropagator

README.md
README seems to have two broken links, this small change fixes them
=> Fix README tracing and baggage api links

.github/workflows/codeql-analysis.yml
Follow up to issue https://github.com/open-telemetry/oteps/issues/144
[CodeQL](https://github.com/github/codeql-action) is GitHub's static analysis engine which scans repos for security vulnerabilities. As the project grows and we near GA it might be useful to have a workflow which checks for security vulnerabilities with every PR so we can ensure every incremental change is following best development practices. Also passing basic security checks will also make sure that there aren't any glaring issues for our users.
* This PR adds [CodeQL](https://github.com/github/codeql-action) security checks to the repo
* After every run the workflow uploads the results to GitHub. Details on the run and security alerts will show up in the `security` tab of this repo.
**Workflow Triggers**
* daily …
=> Add CodeQL security scans

api/metrics/src/main/java/io/opentelemetry/api/metrics/GlobalMetricsProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilderTest.java
For consistency with `OpenTelemetrySdkBuilder` and for use from the autoconfigure wrapper.
=> Add SdkMeterProviderBuilder.buildAndRegisterGlobal

buildscripts/checkstyle.xml
I found `LeftCurly` is incompatible with formatting produced by googlejavaformat some times. But anyways, we don't need checkstyle to look at any sort of formatting since it's handled by googlejavaformat / spotless so we may as well prevent possibility of conflicts and get a bit of checkstyle performance.
=> Remove formatting checks from checkstyle

.github/workflows/master-build.yml
Because  github [enable actions by default](https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/) ,every time I sync my repo with upstream, it will run actions ,thgen I get notifications about some jobs fail.
Though I can disable action in settings，but i  think some job will never run in fork repo like ''Publish snapshots to JFrog' .
So i add `if condition` here
=> prevent workflow 'Publish snapshots to JFrog' in fork repo

README.md
Since https://github.com/open-telemetry/community/pull/587 was merged
=> Remove gitter link from README

exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftIntegrationTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerIntegrationTest.java, integration-tests/src/test/java/io/opentelemetry/JaegerExporterIntegrationTest.java, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java
Also migrate images to the ghcr ones I had set up but forgot to apply the change for.
Fixes #1871 (hopefully, will reopen if this doesn't actually fix it)
=> Use health port for jaeger container startup check.

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/ImmutableSamplingResult.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
If anyone is relying on this currently, it's not too difficult to use a custom sampler implementation until the spec is updated.
Fixes #2420
=> Remove sampling probability attribute when was not accepted to spec.

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerManagement.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
This makes the shutdown method more consistent across the SDK.
=> Change the SdkTracerManagement shutdown method to return CompletableResultCode

build.gradle, exporters/otlp/trace/build.gradle, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/TlsExportTest.java, exporters/otlp/trace/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/trace/TlsExportTest.java, exporters/otlp/trace/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/trace/TlsExportTest.java
While working on autoconfiguration, I noticed we support setting TLS but very few people will actually be able to use it since we don't support setting trusted certs. Now they can be set programattically - will add support for the env variable in a followup, and add to metrics exporter in a followup.
=> Allow setting trusted certs for OTLP Trace exporter

sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
And remove the old TODOs from the BSP test.
resolves #1588
=> Add a test for the RECORD_ONLY span handling in the BatchSpanProcessor

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtils.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TraceConfigzZPageHandler.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanAttributeTruncateBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerProviderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigSystemPropertiesTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
Now that `updateTraceConfig` is deprecated, I think we do want this to avoid the tedium / lack of discoverability of `getDefault().toBuilder()`
=> Add TraceConfig.builder()

api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetryBuilder.java, api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/spi/OpenTelemetryFactory.java, api/all/src/main/java/io/opentelemetry/spi/trace/TracerProviderFactory.java, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, build.gradle, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdkFactory.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/spi/SdkTracerProviderFactory.java
We have autoconfigure module for SDK customization and would like to see patterns related to custom SDKs before SPIing to much initially.
Hopefully this helps with #2022
=> Deprecate OpenTelemetry SPI.

sdk/common/src/main/java/io/opentelemetry/sdk/internal/JavaVersionSpecific.java
I didn't actually know that jul supports parameters too, and did this mostly because of it being forked from code that uses slf4j.
Fixes #2455
=> Fix logging statement for java version

sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
While I had some mind to mark this module as alpha as well but it's not that much work to make it ready I guess.
- Builder to top level
- setEndpoint similar to other gRPC builders
- setInterval with TimeUnit / Duration instead of only millis
- set, not with
- changed initial sampler default to parent-based since surely it's a better default
=> Make JaegerRemoteSamplerBuilder consistent with other builders.

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
See this spec update: https://github.com/open-telemetry/opentelemetry-specification/pull/1322
=> Set the default traceidratio to 1.0 when it is not specified

gradle/wrapper/gradle-wrapper.properties
Notably kotlin build scripts are now not very slow to compile. I'd like to use them here to have IntelliJ actually complete stuff when writing build scripts.
=> Update to Gradle 6.8

perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterRegistryTest.java
Depends on https://github.com/open-telemetry/opentelemetry-java/pull/2489
=> For async instrument tests call the public metric producer method, instead of passing timestamp

gradle/wrapper/gradle-wrapper.properties
Reverts open-telemetry/opentelemetry-java#2482
Need fix for this first
https://github.com/gradle/gradle/issues/15768
=> Revert "Update to Gradle 6.8"

sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
Right now there's a race if the jaeger lookup actually succeeds before the assertion runs.
=> Use bogus endpoint for initialSampler test to prevent flakiness.

exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/Adapter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanBuckets.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/StatusData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusDataTest.java
There is some inconsistency here. I think there are three options
1. Remove `isUnset` because there is no similar `isError`, and its behavior is different from `isOk` which checks two codes
2. Remove both `isUnset` and `isOk`
3. Add `isError`, change `isOk` to only check OK
I like `isOk` since it's annoying to check two codes to know whether a status is erroneous or not so I've picked the first option. I'm ok with 2 as well. 3 seems silly since it just duplicates the fairly simple code-vs-enum comparison into methods, but it would be more consistent than the current method names.
=> Deprecate StatusData.isUnset

bom/build.gradle
Fixes #2511 
We'll want to cherrypick this for a patch release.
=> Set the opentelemetry-bom archive name explicitly to fix publishing issue

examples/build.gradle, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java, examples/metrics/build.gradle, examples/otlp/build.gradle, examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java, examples/prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java, examples/sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java, examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ExampleConfiguration.java, examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ZipkinExample.java
As a part of #2393 I'd like to get the examples to better separate SDK and API usage. Here I've updated the zipkin example to do that. If we like this structure, I'll follow-up and update all the examples (or someone else can pick that up, of course).
=> Update the zipkin example to better match best practices, and update all to work with 0.14.1

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
Had already removed from SimpleSpanProcessor but not here yet.
=> Deprecate BatchSpanProcessor.setExportOnlySampled

sdk-extensions/autoconfigure/gradle.properties
Had meant to do this since it depends on metrics, and SDK environment variables still somewhat fluxing.
=> Set autoconfigure release to alpha.

build.gradle
When looking around, I realized many Gradle projects don't set this since there's no `addDefaultImplementationEntries` like in Maven. But doesn't hurt.
Fixes #2549
=> Use archivesBaseName for Implementation-Title

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, sdk-extensions/autoconfigure/build.gradle, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk-extensions/autoconfigure/src/testInitializeRegistersGlobal/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfigurationTest.java
Currently calling initialize explicitly does not register the global, meaning a subsequent call to get the global actually reinitializes the SDK by calling initialize again. This isn't intended nor efficient/safe.
=> Register global in autoconfigure

CHANGELOG.md
I believe this will make the changelog up-to-date with what we are planning on releasing for our 1.0 release candidate next week.
=> add changelog entries for the default service name changes

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
see this spec change:  https://github.com/open-telemetry/opentelemetry-specification/pull/1325
=> remove the `millis` from the BSP config options

sdk-extensions/autoconfigure/build.gradle, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ConfigurationException.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/testOtlpTls/java/io/opentelemetry/sdk/autoconfigure/OtlpTlsTest.java
I was originally hoping this would solve https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1829 but realized that's about mTLS, not TLS. I don't think the spec defines variables for mTLS yet (technically the current variable is misdocced I guess). But now that I made this change it doesn't hurt to get it in and the variable will likely be renamed in the future.
=> Allow setting trusted certificate variable.

.codecov.yaml, .github/workflows/master-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml, CONTRIBUTING.md, QUICKSTART.md, README.md, RELEASING.md
This gets the repo ready (and updates the docs) to rename the `master` branch to `main`.
See here:  https://github.com/open-telemetry/community/issues/402
=> rename master -> main

build.gradle, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/InteroperabilityTest.java, sdk/common/src/test/java/io/opentelemetry/sdk/common/CompletableResultCodeTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/StressTestRunner.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/StressTestRunner.java
We only use guava in tests now, so we can use JRE version which has less chance of conflicts with other libraries.
=> Migrate to guava JRE version

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/otproto/src/main/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtils.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/TraceProtoUtilsTest.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TraceConfigzZPageHandler.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezTraceConfigSupplier.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/ZPageServer.java, sdk-extensions/zpages/src/test/java/io/opentelemetry/sdk/extension/zpages/TraceConfigzZPageHandlerTest.java, sdk-extensions/zpages/src/test/java/io/opentelemetry/sdk/extension/zpages/ZPageServerTest.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProviderBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfigBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerProviderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/config/TraceConfigTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
For #2022
Didn't bother with deprecating since it seems complicated to do here.
Given how often our unit tests set samplers, and rarely they set limits, there does seem to be a nice win here.
/cc @iNikem
=> Move Sampler to SdkTracerProvider

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ConfigProperties.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ConfigurableSpanExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TestConfigurableSpanExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurableSpanExporterProvider
This need was uncovered while working on a custom distribution of the opentelemetry auto-instrumentation agent.
In order for this to work, we really wanted access to the `ConfigProperties` as well, so we could leverage the standardized property handling that it provides.
Alternative approaches would be welcome, but this seems like a pretty clean pattern. In fact, we might want to add the `ConfigProperties` to other auto-configuration SPI methods as well, so we don't have to figure out how to add them later.
=> Enable auto-configuration of custom, named span exporters.

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ConfigProperties.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ConfigPropertiesTest.java
- Update ConfigBuilder in `sdk/common/export` to include a `getDurationMillisProperty` method.
- Add a short + limited duration parser that simply extract that "units" string and relies
on substring efficiency (we assume config doesn't have to be fast as it's likely read about once)
- Add tests to verify various incarnations of duration are parsed to appropriate millisecond values.
Fixes #2435
This is my first PR to OTel-Java so sending this out for early review/evaluation. Want to verify the following:
- Is this the right location for this utility?
- Am I violating unit-test best practices?
- Do you want better documentation on the format, or can I try to contribute that directly to the speicfication?
=> Add a Duration parser for configuration.

exporters/zipkin/build.gradle
We have `Sender` and `BytesEncoder` in our builder API
=> Expose zipkin as an API dependency.

README.md
@tsloughter brought this up on Gitter, it seems fair to me to reduce the cognitive load of the terms as most users don't need to worry about alternative implementations at all.
=> Remove word reference from implementation

exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporter.java, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterBuilder.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
Moved the fallback to default resource logic closer to where service name is picked up in Jaeger. And for Zipkin, I think we accidentally lost filling in endpoint, so restoring that is a lot of the change.
=> Remove deprecated setServiceName

build.gradle.kts, exporters/jaeger-thrift/build.gradle, exporters/jaeger/build.gradle, exporters/logging/build.gradle, exporters/zipkin/build.gradle, proto/build.gradle, sdk-extensions/jaeger-remote-sampler/build.gradle
Instead, simplifies the top level config to use direct sourceset inclusion instead of somewhat fuzzy task name exclusion.
=> Consolidate animalsniffer config to top level.

.github/workflows/pr-examples-build.yml, examples/build.gradle, examples/grpc/README.md, examples/http/README.md, examples/jaeger/README.md, examples/prometheus/README.md, examples/sdk-usage/README.md, examples/settings.gradle, examples/zipkin/README.md, integration-tests/build.gradle, integration-tests/tracecontext/build.gradle, integration-tests/tracecontext/tracecontext-integration-test.sh, settings.gradle
Since that's its job, so less configuration on our side. Removes use of a potentially non-inclusive term too.
=> Use shadow plugin to generate bundled jars.

build.gradle.kts
- Sets title explicitly to same as project description
- Enables HTML5 since we always build with Java 11 using toolchains
- Couple of other miscellaneous
Fixes #2652
=> Tweak javadoc options

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java
This changes the logic so that we only need to have called shutdown on the TracerSharedState, not that it has successfully shut down. Otherwise, a failed shutdown would continue to produce spans when it shouldn't be.
=> Update the check in the tracer to see if the SDK has been shut down.

api/all/src/jmh/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorInjectBenchmark.java, api/all/src/main/java/io/opentelemetry/api/trace/TraceState.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanContextTest.java, api/all/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java, api/all/src/test/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorTest.java, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/AdapterTest.java, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java, exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, extensions/trace-propagators/src/jmh/java/io/opentelemetry/extension/trace/propagation/PropagatorContextInjectBenchmark.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagatorTest.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/JaegerPropagatorTest.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagatorTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSamplerTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/SpanAdapterTest.java, sdk-extensions/zpages/src/test/java/io/opentelemetry/sdk/extension/zpages/TracezSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/ParentBasedSamplerTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/AlwaysOffSamplerTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/AlwaysOnSamplerTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
* Avoid calling TraceState.builder().build() and replace it with TraceState.getDefault();
* Avoid storing TraceFalgs.getDefault() and TraceFalgs.getSampler() and use them directly;
=> Cleanup usages of TraceState and TraceFlags

api/all/src/main/java/io/opentelemetry/api/trace/BigendianEncoding.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java, api/all/src/main/java/io/opentelemetry/api/trace/TraceFlags.java, api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/trace/BigendianEncodingTest.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java, api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/TraceMarshalerTest.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/SpanAdapterTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
Summary of changes:
* getHexLength renamed to getLength
* bytesFromHex/bytesToHex renamed to asBytes/fromBytes.
* bytesFromHex/bytesToHex renamed to asLongHigh/asLongLow
* Update javadoc.
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2666
=> [BREAKING CHANGE] Cleanup TraceId/SpanId classes. Ensure consistency.

api/all/src/main/java/io/opentelemetry/api/trace/DefaultTracer.java
There don't seem to be anymore instances where public class has method `getInstance` and returns interface. I found this one location where non-public class returns non-public class instead of interface, which is not consistent with our other such cases.
Fixes #2658
=> Return Tracer from DefaultTracer.getInstance

api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java
Updates https://github.com/open-telemetry/opentelemetry-java/issues/2623
=> Remove Memoized for byte arrays. Byte-arrays are not immutable

api/all/src/jmh/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorBenchmark.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanContextTest.java, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/InteroperabilityTest.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java, sdk-extensions/jfr-events/src/main/java/io/opentelemetry/sdk/extension/jfr/ScopeEvent.java, sdk-extensions/jfr-events/src/test/java/io/opentelemetry/sdk/extension/jfr/JfrSpanProcessorTest.java, sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanProcessor.java, sdk-extensions/zpages/src/test/java/io/opentelemetry/sdk/extension/zpages/TracezZPageHandlerTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#retrieving-the-traceid-and-spanid
Not breaking change since methods were just renamed anyway.
There is one more advantage to this, if we ever want to add back the wrapper classes for Trace/Span id we will be able to have nice getters. Related to https://github.com/open-telemetry/opentelemetry-java/issues/2719 and the fact that we may have to add the wrappers to avoid multiple validations, this does not mean that we will do it that way but leaves the option open.
=> Consistent name for Trace/Span ids getters with the specification

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
It will always be possible to add it back if this becomes a problem for our users.
=> [BREAKING CHANGE] Remove not very used `getTraceState` method from SpanData

sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezZPageHandler.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
It will always be possible to add it back if this becomes a problem for our users.
=> [BREAKING CHANGE] Remove not very used `isSampled` method from SpanData

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracePropagatorTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
This is done to match the name in other SIGs and the name it will have in the Specification ([see this](https://github.com/open-telemetry/opentelemetry-specification/pull/1402)).
Updated its small documentation piece as well.
=> Rename OtTracerPropagator to OtTracePropagator.

api/all/src/main/java/io/opentelemetry/api/trace/BigendianEncoding.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java, api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanIdTest.java, api/all/src/test/java/io/opentelemetry/api/trace/TraceIdTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/AdapterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/TraceMarshalerTest.java, sdk-extensions/otproto/src/test/java/io/opentelemetry/sdk/extension/otproto/SpanAdapterTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
This reverts commit d6fea3a70af466f1ef358ab3126a667a9607fd5e.
There currently isn't any way to get an ID from OTLP, which is often used in integration tests. Insrumentation repo used these methods and for now I've inlined everything down through BigEndianEncoding, but I think we need to provide this.
=> Restore Trace/SpanId.fromBytes

api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java
And, remove that extra validation from propagators.
I didn't remove it from the B3 Propagator(s) yet... that will take a bit more work to untangle.
Resolves #2719
=> Validate the span id and trace id when creating the SpanContext

api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java, api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/all/src/test/java/io/opentelemetry/api/internal/ImmutableKeyValuePairsTest.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/common/ArrayBackedLabels.java
This will allow us to store internally an array and size or other combination that makes sense for performance.
=> Move sort and dedup to constructor of ImmutableKeyValuePairs

api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java
This change will reduce the number of allocations by 2 for the case where all entries are valid,
and by 1 when entries are filtered in the dedup.
**Benchmarks Before:**
**Benchmarks After:**
Updates https://github.com/open-telemetry/opentelemetry-java/issues/2765
=> Improve ImmutableKeyValuePairs dedup, do everything inplace

api/context/src/main/java/io/opentelemetry/context/StrictContextStorage.java, api/context/src/strictContextEnabledTest/java/io/opentelemetry/context/StrictContextStorageTest.java
This doesn't make `StrictContextStorage` public but at least allows instrumentation tests to do something like this if they want.
```java
@AfterEach
void tearDown() {
((AutoCloseable) ContextStorage.get()).close();
}
```
@mateuszrzeszutek has been looking into activating strict context storage in our tests and we do need some way to call this.
=> Make StrictContextStorage closeable.

examples/logging/build.gradle, examples/logging/src/main/java/io/opentelemetry/example/logging/ExampleConfiguration.java, examples/logging/src/main/java/io/opentelemetry/example/logging/LoggingExporterExample.java, examples/settings.gradle
This PR adds an example to the examples directory showing how to make use of the logging exporters for trace and metrics in a single runnable example. I thought this would help to address #2508 
The jaeger example was used as a basis for this example, altered to make use of the logging exporters
=> 2508: Logging Exporter Example for Trace and Metrics

sdk/common/build.gradle.kts, sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceProvidersTest.java, sdk/common/src/testResourceDisabledByEnv/java/io/opentelemetry/sdk/resources/ResourceDisabledByEnvTest.java, sdk/common/src/testResourceDisabledByProperty/java/io/opentelemetry/sdk/resources/ResourceDisabledByPropertyTest.java
Lacking anything in the spec, this follows the rule of do what agent is doing right now. 
It's a small external configuration change which I think is within the scope of RC.
Fixes #2526
=> Rename disabled resources property to be consistent with agent.

examples/http/src/main/java/io/opentelemetry/example/http/ExampleConfiguration.java, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java, examples/otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java, examples/zipkin/src/main/java/io/opentelemetry/example/zipkin/ExampleConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
Resolves #2825
I updated the examples, as well, since they were also not doing it correctly.
=> Properly shutdown tracer providers synchronously via close()

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java
This PR updates `TracerProviderConfiguration` to use a `SimpleSpanProcessor` whenever the environment variable `otel.traces.exporter` is set to `logging`. Right now on the main branch, an autoconfigured SDK always uses a `BatchSpanProcessor`.
fixes: #2816
=> 2816: Autoconfigure to use SimpleSpanProcessor when logging exporter is used

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
While looking at https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2266 I noticed that the spec defines endpoint as a schemed URL for Jaeger too, but we don't handle it. This means there's no environment variable for specifying an insecure or secure connection.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter
I just copied the code from the OTLP exporter, presumably we need to clean these up to remove support for schemaless though.
=> Use schemed endpoint for jaeger exporter.

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
There seem to be some opencensus-specific hacks still left over.
Only randomly went through the code since it showed up in codecov report of unrelated diff - apparently the `// don't crash the caller if there was a problem reading nics.` sometimes and sometimes doesn't throw on CI :O
=> Minor cleanups to zipkin exporter.

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, sdk-extensions/autoconfigure/src/testJaeger/java/io/opentelemetry/sdk/autoconfigure/JaegerConfigTest.java
It was already deprecated with warning for OTLP. It wasn't for Jaeger, but I think we can live with it.
=> Remove support for schemaless URLs for gRPC exporters.

api/all/src/jmh/java/io/opentelemetry/api/trace/DefaultTracerBenchmarks.java, api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/trace/DefaultTracerProvider.java, api/all/src/main/java/io/opentelemetry/api/trace/Tracer.java, api/all/src/main/java/io/opentelemetry/api/trace/TracerProvider.java, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, api/all/src/test/java/io/opentelemetry/api/trace/DefaultTracerProviderTest.java, api/all/src/test/java/io/opentelemetry/api/trace/DefaultTracerTest.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanBuilderTest.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DefaultMeterProvider.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/GlobalMetricsProvider.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/Meter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/MeterProvider.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/BatchRecorderTest.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java, integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/NoopSpanBuilderShim.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java
Removes `Tracer.getDefault` and `Meter.getDefault` since they're easy to get from the providers.
=> [Breaking Change] Rename API getDefault to noop!

api/all/src/jmh/java/io/opentelemetry/api/baggage/BaggageBenchmark.java, api/all/src/main/java/io/opentelemetry/api/baggage/BaggageBuilder.java, api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/all/src/test/java/io/opentelemetry/api/baggage/BaggageTest.java, api/all/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java, api/all/src/test/java/io/opentelemetry/api/baggage/ScopedBaggageTest.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanContextShim.java
Instead, expect `Baggage.current().toBuilder()`
Fixes #2784
=> [Breaking Change] Remove BaggageBuilder.setParent / setNoParent

exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporter.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporter.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporter.java
Also avoids exporting some internal properties in the Jaeger exporter
=> Mark public classes as final in the exporters directory

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
This is to prevent people from casting to the SDK implementation.
Resolves #2788
=> Obfuscate the GlobalOpenTelemetry instance.

sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSampler.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSamplerTest.java
When we made the remote sampler `Sampler.parentBased` previously, we removed the need for the parent check here. I'm pretty sure we don't need the Links check either but opened https://github.com/open-telemetry/opentelemetry-java/discussions/2874 to confirm. /cc @yurishkuro
=> Make jaeger rate limit sampler only rate limit

VERSIONING.md
I think these are generally allowed by semver since a user needs to update the POM anyways when updating, but we want to make sure they don't need to update code / retest everything.
=> Allow updates that may require additional POM updates on minor updates.

RELEASING.md
GitHub seems to have improved the way to link to workflows, though it means the old links don't work correctly anymore.
=> Update links to workflows in RELEASING.md

code-of-conduct.md
Followed same pattern as Kubernetes projects, which link to the community repo, which links to CNCF
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/code-of-conduct.md
=> Add code-of-conduct file.

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/context/build.gradle.kts, build.gradle.kts, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/DoubleMinMaxSumCountAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/LongMinMaxSumCountAggregator.java
FWICT, `GuardedBy` is the only annotation that has the problem in #2897. But we can easily avoid it by using the JDK's annotation, which errorprone does support in the same way as its own.
We can't lose the killer `MustBeClosed` so I scoped the annotations down to only the context package to prevent accidentally using the wrong `GuardedBy` in others.
Fixes #2897
=> Reduce usage of errorprone annotations to MustBeClosed.

api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/Tracer.java
Before https://github.com/open-telemetry/opentelemetry-java/pull/2881 is merged I think in order to not have "behavior" changes after 1.0 is better to remove all throws statements.
=> Remove throws statements from the API until we decide how to document it

README.md
A small URL typo in the README.md.
=> Update README.md #2922

api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java, api/all/src/test/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorTest.java, extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsXrayPropagator.java, extensions/aws/src/test/java/io/opentelemetry/extension/aws/AwsXrayPropagatorTest.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractor.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorMultipleHeaders.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorSingleHeader.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjector.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/JaegerPropagatorTest.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracePropagatorTest.java
While it's not quite as bad as other parts of the API throwing since adding propagators is explicit, we still want to prevent exceptions in apps as per the otel's error handling rules.
Started looking into these files as part of #2736 and realized that it doesn't seem so bad to just remove the `@Nullable` given all these checks anyways.
=> Don't throw on null in propagator implementations.

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricAdapter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoubleHistogramData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoubleHistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricDataType.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/data/MetricDataTest.java
under the suggestion of @bogdandrutu, this PR is splitted from #2581 and adds histogram-related metric data types into the core SDK.
=> Histogram Aggregation - core SDK - data

api/all/src/main/java/io/opentelemetry/api/trace/TraceFlags.java
The correct behavior here is not yet known, so remove the documentation that implies a strict contract around the parsing of TraceFlags from hex inputs.
=> Remove the documentation about explicit exceptions thrown when TraceFlags are invalid

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricAdapter.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/MetricAdapterTest.java
follow up PR of #2581 
- implement histogram aggregation export in OTLP.
=> Histogram Aggregation - OTLP exporter

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAccumulator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewRegistry.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/View.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/ViewBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewRegistryTest.java
- View class as an overarching concept for AggregationFactory. In the future we can add more specifics into it
- The grand idea here is basically based around OpenCensus Views. We want to be able to register custom projections (views) on the metrics which would allow us to use different aggregations and pre-processing techniques.
- This is the very first step where we just introduce a view and wrap existing AggregatorFacotry
- Immediately next we would like to have LabelsProcessors added to the views which are going to be a separate PR, but at a glance - same thing we discussed in https://github.com/open-telemetry/opentelemetry-java/issues/1810. Whole PR might be found here https://github.com/open-telemetry/opentelemetry-java/pull/2800
=> introducing view

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/MetricAdapterTest.java
follow up of #2581 
- implement histogram aggregation export in Prometheus.
=> Histogram Aggregation - Prometheus exporter

sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResourceTest.java
If the other test ran first, the singleton would already be initialized with an empty value. Presumably something changed that is causing test order to be different (or more random) than before causing test failures.
=> Don't use singleton in resource test

docs/jmh.md, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java
The trace benchmarks were out of date (passing `host:port` instead of `http://host:port` to the SpanProcessor).  This fixes that and adds a doc for how to run the jmh tasks.
=> Fix trace benchmark

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
We have this check for attributes but seems we can have it for events too.
=> Don't copy events toSpanData if ended.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractAccumulator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/processor/LabelsProcessor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/processor/LabelsProcessorFactory.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/processor/NoopLabelsProcessor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/View.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/ViewBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SynchronousInstrumentAccumulatorTest.java
* Introducing Labels Processor. The idea that this is a interception mechanism to manipulate labels during instrument binding or value recording.
* Couple of representative use cases:
* * I would like to add certain labels extracted from baggage/context to all measurements recorded
* * I would like to strip certain labels from measurements (useful in case pre-instrumented frameworks)
It is an implementation for https://github.com/open-telemetry/opentelemetry-java/issues/1810. Based on https://github.com/open-telemetry/opentelemetry-java/pull/2956 and whole idea is sketched in this PR https://github.com/open-telemetry/opentelemetry-java/pull/2800
=> labels processor

api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
Fixes #2955
Spec PR :https://github.com/open-telemetry/opentelemetry-specification/pull/1492
=> Ignore null / invalid spancontext and handle null attributes for links.

extensions/kotlin/src/test/kotlin/io/opentelemetry/extension/kotlin/KotlinCoroutinesTest.kt
`GlobalScope.launch` isn't supposed to inherit context
https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#children-of-a-coroutine
But the test didn't fail since actually we weren't awaiting on the result anyways. Switched to launching a child coroutine the correct way (I think) and awaiting
=> Fix unit test for kotlin context propagation.

sdk-extensions/autoconfigure/README.md
The description for configuring otlp headers is that they should be separated using semicolons.  However, tracing the code and testing with a vendor that uses multiple headers as configuration items shows that headers should be separated using commas instead.  
You can see this by viewing the source for either SpanExporterConfiguration or MetricExporterConfiguration and reviewing the line as given:
`config.getCommaSeparatedMap("otel.exporter.otlp.headers").forEach(builder::addHeader);`
Tracing back from this point shows that the header values are separated using commas.
=> Update description on otel.exporter.otlp.headers

examples/build.gradle, examples/settings.gradle, settings.gradle.kts
Former is sunset and flaky, latter we don't need since no Android build
=> Remove jcenter and google repositories from build.

sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorCpuBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorDroppedSpansBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorMetrics.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorMultiThreadBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/DelayingSpanExporter.java
Description:
This PR adds two benchmarks.
1. Current benchmark executs forceFlush() on every loop and creates a bottleneck which results in not stressing batch span processor. Current benchmark only
measures throughput which is not helpful on its own since number of spans getting exported is also important. BatchSpanProcessorMultiThreadBenchmark is created to address this issue.
2. Measuring CPU usage of exporter thread is also important, but the current benchmarks consumes as much CPU as possible which makes the measurement not meaningful.
To maintain a steady state, this PR creates a benchmark that generates 10k spans per second per thread. One would need to attach a profiler such as yourkit or JProfiler
to the benchmark run to understand the processor's CPU usage. …
=> Add batch span processor benchmarks

perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
This changes the IntervalMetricReaderBuilder.build() method to not auto-start the IMR. There is a new method on the builder `buildAndStart()` which will do both for you.  
Adds a method to the IntervalMetricReader to start the background thread, but this is not called as a part of the constructor.
=> Don't auto-start the IntervalMetricReader in the constructor.

sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
Description:
Batch span processor currently is aggressive in the sense that any new spans are sent to the exporter,
this involves lots of overhead from signaling under heavy load and overhead from constant polling by exporter thread
under less load. This PR makes exporter thread wait for maxExportBatchSize to avoid busy polling of the queue.
BatchSpanProcessorMultiThreadBenchmark.java result
BatchSpanProcessorCpuBenchmark.java result
=> Optimize batch span processor

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java
Also fix the test that was in place to check this but was a false negative since the first export still works without this bugfix, but not any further ones.
CC @arminru @thisthat
=> Fix IntervalMetricReader breaking if export() throws.

api/metrics/src/main/java/io/opentelemetry/api/metrics/GlobalMeterProvider.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java, sdk-extensions/autoconfigure/src/testPrometheus/java/io/opentelemetry/sdk/autoconfigure/PrometheusTest.java, sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/BatchLogProcessor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilderTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
I think this was just an accidental naming snafu.
=> Rename GlobalMetricsProvider to GlobalMeterProvider

build.gradle.kts
We already set the release compiler option, so no need to set the target/source compatibility.
According to <https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:release>,
> If set, it will take precedences over the `AbstractCompile.getSourceCompatibility()` and
`AbstractCompile.getTargetCompatibility()` settings.
=> Remove redundant build script code.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
Clears the way for #3060 by making SdkMeterProvider immutable.
=> Move registerView from SdkMeterProvider to SdkMeterProviderBuilder. (#3060)

website_docs/_index.md, website_docs/automatic_instrumentation.md, website_docs/getting_started.md, website_docs/instrumentation_examples.md, website_docs/manual_instrumentation.md
Per https://github.com/open-telemetry/opentelemetry.io/issues/472, we're adding the documentation content from the website to each repository. After a release of that requires documentation changes, please make an issue or PR in the website repository in order to have the changes mirrored.
=> Add opentelemetry.io docs

exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftIntegrationTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerIntegrationTest.java, integration-tests/src/test/java/io/opentelemetry/JaegerExporterIntegrationTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/ResourceBuilder.java, sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2975
=> Resource.Builder for convenient work with Resource class

sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
If `shutdown` runs synchronously due to thread timing, it will NPE on the mock's result code if not mocked.
=> Fix flaky test

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulator.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AsynchronousInstrumentAccumulatorTest.java
Reverts open-telemetry/opentelemetry-java#3088
Turns out this wasn't what was breaking the build.
=> Revert "Revert "Fix bug where AsynchronousInstrumentAccumulator does not call configured LabelProcessorFactory."

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/SdkMeterProviderConfigurer.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/SdkTracerProviderConfigurer.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TestMeterProviderConfigurer.java, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.SdkMeterProviderConfigurer, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java
Adds `SdkMeterProviderConfigurer` SPI to the autoconfiguration module. 
Closes #3060.
=> Add autoconfiguration SdkMeterProviderConfigurer SPI. (#3060)

integration-tests/tracecontext/build.gradle.kts, integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java, integration-tests/tracecontext/src/test/java/io/opentelemetry/integrationtests/tracecontext/TraceContextIntegrationTest.java
Due to many failures can't actually assert anything yet but it's still worth having logs of where we are.
=> Run w3c tracecontext tests as part of build.

api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagatorTest.java, build.gradle.kts, integration-tests/tracecontext/src/main/java/io/opentelemetry/Application.java
Got down to just 6 failures of the testsuite, all requiring support for handling multiple instances of a header which OpenTelemetry doesn't support yet.
Biggest changes were
- Trace state discarded if any item fails (I don't see this in the spec but it's being tested by test suite)
- Load SDK since trace ID generation is tested
=> Fix more tracestate testsuite cases.

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRule.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java
I've seen some tests fail due to this being missing on Ubuntu running on Windows WSL. Not sure why it runs differently on that setup.
=> Make the test extensions defensively reset the GlobalOpenTelemetry instance before setting

examples/otlp/docker/otel-collector-config-demo.yaml, examples/otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java, examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java
Also, fixes a broken collector config for the latest dev version.
=> Add a ValueRecorder to the otlp example and properly start the IntervalMetricReader

all/src/test/java/io/opentelemetry/all/SdkDesignTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/BatchRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/DoubleValueRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownCounterSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongUpDownSumObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueObserverSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/LongValueRecorderSdkTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterRegistryTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
Resolves #1718
There are numerous possible approaches to that. I decided to implement a weak guardrails, limiting the scope to known issues only. Basically the goal of the test is to ensure that public SDK methods, that override an API method will always return API type, java type or void. I intentionally decided against simple check if method returned by a SDK method is exactly the same as returned by corresponding API method to allow covariant returns within API scope.
=> SDK arch test - ensuring that API implmenetation returns only API types

build.gradle.kts
Resolves #3032 
Once implementation version is included in manifest files, it can be easily read in the runtime.
=> adding implementation-version to manifest files

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjector.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorMultipleHeaders.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
See this spec change from v1.2.0: https://github.com/open-telemetry/opentelemetry-specification/pull/1570
=> Have the B3Propagator only include the relevant fields for injection format

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
=> Update semantic convention constants generator script and template

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java
Also includes minor doc fixes.
=> Support otel.exporter.jaeger.timeout

sdk-extensions/tracing-incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/ExecutorServiceSpanProcessor.java, sdk-extensions/tracing-incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/ExecutorServiceSpanProcessorBuilder.java
I realized this got merged without quite all the required javadoc.
=> Add some javadoc to the new ExecutorServiceSpanProcessor & builder.

api/all/src/main/java/io/opentelemetry/api/trace/DefaultTracer.java, api/all/src/main/java/io/opentelemetry/api/trace/PropagatedSpan.java, api/all/src/main/java/io/opentelemetry/api/trace/Span.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java, api/all/src/test/java/io/opentelemetry/api/trace/PropagatedSpanTest.java, api/all/src/test/java/io/opentelemetry/api/trace/SpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
Adds helper methods `Span#setAttributes` and `SpanBuilder#setAttributes` which accept an `Attributes` instance and copy the attributes into the span.
=> Add Span#setAttributes method to add Attributes to a Span

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java
An alternative to #3153, assuming that the spec gets updated to default to an empty string, rather than null.
=> Default the tracer name to an empty string

api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java, api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributesBuilder.java, api/all/src/main/java/io/opentelemetry/api/common/AttributeKeyImpl.java, api/all/src/test/java/io/opentelemetry/api/common/AttributeKeyTest.java
`AttributeKey.getKey()` does not have the `@Nullable` annotation, but can return `null` which isn't really allowed. We hide this from users in almost all practical APIs, for example by filtering them out when building `Attributes` but still, I think we should make our `@Nullable` aspect correct (well, I am trying to add Nullaway to the build and found this, which Nullaway doesn't like correctly. Most Nullaway fixes will be trivial but split this one out since it's a logic change). 
The spec forbids both null and empty string keys
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes
We end up creating them to avoid crashing apps. But I think it means that coercing null to empty does not make us any less spec compliant and fixes …
=> Coerce null AttributeKey to empty string

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testZipkin/java/io/opentelemetry/sdk/autoconfigure/ZipkinConfigTest.java
=> Add the option to configure the zipkin exporter timeout.

.github/workflows/main-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml, .github/workflows/release-build.yml
For some reason, now 18.04 is failing, but 20.04 is passing. I don't understand what's going on here, but hopefully this will move our PRs forward again. 
Note: I changed the branch protection rules to require 20.04 on PRs, assuming this will move forward.
=> rev ubuntu up to 20.04

.github/workflows/pr-examples-build.yml, examples/build.gradle, examples/gradle.properties
Also, remove example build vs. snapshots
Resolves #3122
=> Update example dependencies to 1.2.0

api/all/src/main/java/io/opentelemetry/api/internal/TemporaryBuffers.java, api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java, api/all/src/main/java/io/opentelemetry/api/trace/TraceId.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/test/java/io/opentelemetry/api/internal/TemporaryBuffersTest.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/HexEncodingStringJsonGenerator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorInjectorSingleHeader.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java
Also replaces loop over `String` with `getChars` which is hotspottable.
=> Move TemporaryBuffers to internal and use it everywhere.

perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java
**Description:**
The legacy gRPC port(55680) in OTLP Receiver will be disabled in OTel Collector before the collector GA.
This CR replaced all gRPC port occurrences from `55680` to `4317` in this repo.
**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector/issues/2565
=> Remove the OTLP receiver legacy gRPC port(55680) references

README.md
Added the link to Actions tab for the CI badge.
cc @alolita
=> Update link for CI status badge

sdk/trace/build.gradle.kts, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/ExporterBenchmark.java, sdk/trace/src/jmh/resources/otel.yaml
But something strange happening here. On my machine I got the following results:
```
Benchmark                                                                                 Mode  Cnt        Score        Error   Units
ExporterBenchmark.JaegerBenchmark.createAndExportSpan                                     avgt   10  1320789.103 ± 161003.787   ns/op
ExporterBenchmark.JaegerBenchmark.createAndExportSpan:·gc.alloc.rate                      avgt   10        5.898 ±      0.520  MB/sec
ExporterBenchmark.JaegerBenchmark.createAndExportSpan:·gc.alloc.rate.norm                 avgt   10    12219.282 ±    381.806    B/op
ExporterBenchmark.JaegerBenchmark.createAndExportSpan:·gc.churn.G1_Eden_Space             avgt   10        5.303 ±     25.351  MB/sec …
```
=> Add a benchmark comparing OTLP and Jaeger exporter

sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/ExceptionBenchmark.java
Results from my machine demonstrate that recording exception may be quite an expensive operation:
```
Benchmark                                                                     Mode  Cnt      Score      Error   Units
ExceptionBenchmark.createException                                            avgt   10   1043.408 ±   52.696   ns/op
ExceptionBenchmark.createException:·gc.alloc.rate                             avgt   10    438.773 ±   23.161  MB/sec
ExceptionBenchmark.createException:·gc.alloc.rate.norm                        avgt   10    720.000 ±    0.001    B/op
ExceptionBenchmark.createException:·gc.churn.G1_Eden_Space                    avgt   10    442.504 ±  129.812  MB/sec
ExceptionBenchmark.createException:·gc.churn.G1_Eden_Space.norm               avgt   10    724.855 ± …
```
=> Add benchmark for recording exception on a span

extensions/incubator/build.gradle.kts, extensions/incubator/src/jmh/java/io/opentelemetry/extension/incubator/PassThroughPropagatorBenchmark.java, extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/propagation/PassThroughPropagator.java, extensions/incubator/src/test/java/io/opentelemetry/extension/incubator/propagation/PassThroughPropagatorTest.java
For https://github.com/open-telemetry/opentelemetry-specification/issues/1717
About 3x performance for passing through vs parse/serialize.
```
Benchmark                                                                 Mode  Cnt      Score     Error   Units
PassThroughPropagatorBenchmark.parse                                     thrpt   60   5705.975 ±  75.797  ops/ms
PassThroughPropagatorBenchmark.parse:·gc.alloc.rate                      thrpt   60   2174.161 ±  28.934  MB/sec
PassThroughPropagatorBenchmark.parse:·gc.alloc.rate.norm                 thrpt   60    600.000 ±   0.001    B/op
PassThroughPropagatorBenchmark.parse:·gc.churn.G1_Eden_Space             thrpt   60   2178.084 ±  43.372  MB/sec
PassThroughPropagatorBenchmark.parse:·gc.churn.G1_Eden_Space.norm        thrpt   60 …
```
=> Add a prototype PassThroughPropagator

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java
Already implemented by HashMap more directly.
=> Remove unneeded forEach from AttributesMap.

context/src/main/java/io/opentelemetry/context/ContextKey.java
There is no `getValue` in the `Context` interface
=> Change context.getKey to context.get

api/all/src/main/java/io/opentelemetry/api/trace/Tracer.java
**Problem:**
Javadocs comments at Tracer interface contains call of unexistent method OpenTelemetry.getTracer()
**Solution:**
Replace OpenTelemetry.getTracer() with OpenTelemetry.getTracer(String, String) in examples at javadocs
=> javadocs: fix code examples

api/all/src/jmh/java/io/opentelemetry/api/trace/SpanIdBenchmark.java, api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java, api/all/src/main/java/io/opentelemetry/api/internal/Utils.java
Benchmark results before (pay special to attention to `gc.alloc.rate.norm`):
```
Benchmark                                                    Mode  Cnt     Score     Error   Units
SpanIdBenchmark.getSpanIdBytes                               avgt   15    66.128 ±   0.299   ns/op
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate                avgt   15  6367.137 ±  28.810  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate.norm           avgt   15   664.000 ±   0.001    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space       avgt   15  6373.704 ± 159.516  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space.norm  avgt   15   664.673 ±  15.814    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Old_Gen          avgt   15     0.011 ±   0.004  MB/sec …
```
=> Remove unnecessary string allocation on hot path

api/all/src/jmh/java/io/opentelemetry/api/trace/SpanIdBenchmark.java, api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java, api/all/src/main/java/io/opentelemetry/api/internal/Utils.java
I realized we should avoid this too given just how hot the code path is. Over many forks I can confirm there is a significant (not huge) change in the execution time, so I guess the GC profiler somehow doesn't keep track of lambda overhead.
I considered porting over Guava's `Preconditions` handling of `%s` but figured it's not worth it, the tried and trued if statement pattern doesn't seem like much of a regression to me.
After
```
Benchmark                                                    Mode  Cnt    Score    Error   Units
SpanIdBenchmark.getSpanIdBytes                               avgt   45   22.248 ±  0.098   ns/op
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate                avgt   45  685.071 ±  3.113  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate.norm           avgt   45 …
```
=> Don't create Supplier when decoding byte

api/all/src/jmh/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorBenchmark.java, api/all/src/main/java/io/opentelemetry/api/baggage/propagation/Element.java, api/all/src/main/java/io/opentelemetry/api/baggage/propagation/Parser.java
Randomly noticed. Just small improvement
After
```
Benchmark                                                                Mode  Cnt      Score      Error   Units
W3CBaggagePropagatorBenchmark.largeBaggage                               avgt   45     42.915 ±    0.496   us/op
W3CBaggagePropagatorBenchmark.largeBaggage:·gc.alloc.rate                avgt   45    368.208 ±    4.159  MB/sec
W3CBaggagePropagatorBenchmark.largeBaggage:·gc.alloc.rate.norm           avgt   45  24872.049 ±    0.062    B/op
W3CBaggagePropagatorBenchmark.largeBaggage:·gc.churn.G1_Eden_Space       avgt   45    370.006 ±   25.219  MB/sec
W3CBaggagePropagatorBenchmark.largeBaggage:·gc.churn.G1_Eden_Space.norm  avgt   45  24992.676 ± 1681.603    B/op
W3CBaggagePropagatorBenchmark.largeBaggage:·gc.churn.G1_Old_Gen …
```
=> Use constant for baggage validation bitsets

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java
Even though metrics aren't stable yet, it seems good to have some configuration consistency.
=> Update the metrics autoconfigure code with support for duration units.

exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/CommonAdapterBenchmark.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/ResourceAdapterBenchmark.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/CommonAdapter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ResourceAdapter.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/CommonAdapterTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/ResourceAdapterTest.java
Since Resource and IL are essentially constants we can reduce GC pressure by caching conversion to proto. An interesting takeaway is Before actually GC's while After doesn't, I think it demonstrates going from affecting an app's GC to not affecting it for these two codepaths.
After
```
Benchmark                                             Mode  Cnt   Score    Error   Units
CommonAdapterBenchmark.toProto                        avgt   45  11.798 ±  0.055   ns/op
CommonAdapterBenchmark.toProto:·gc.alloc.rate         avgt   45   0.001 ±  0.001  MB/sec
CommonAdapterBenchmark.toProto:·gc.alloc.rate.norm    avgt   45  ≈ 10⁻⁵             B/op
CommonAdapterBenchmark.toProto:·gc.count              avgt   45     ≈ 0           counts
ResourceAdapterBenchmark.toProto                      avgt   45 …
```
=> Cache Resource and Instrumentationlibrary protos.

exporters/logging-otlp/README.md
=> Fix the javadoc link for the logging-otlp exporter

exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/SpanAdapterBenchmark.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/CommonAdapter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/SpanAdapter.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/SpanAdapterTest.java
- Don't allocate `KeyValue.Builder` when not used
- Use singleton `Status` proto if no description
- `computeIfAbsent` / forEach because Java 8 now
- Cache ID bytes conversion (we'll expect many cache hits for trace ID, and some cache hits for span ID which are parents of other spans)
After
```
Benchmark                                                  Mode  Cnt     Score     Error   Units
SpanAdapterBenchmark.toProto                               avgt   45     2.803 ±   0.013   us/op
SpanAdapterBenchmark.toProto:·gc.alloc.rate                avgt   45  1692.960 ±   8.383  MB/sec
SpanAdapterBenchmark.toProto:·gc.alloc.rate.norm           avgt   45  7472.003 ±  12.027    B/op
SpanAdapterBenchmark.toProto:·gc.churn.G1_Eden_Space       avgt   45  1694.252 ±  43.026  MB/sec …
```
=> Performance tweaks to SpanAdapter

extensions/trace-propagators/build.gradle.kts, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3ConfigurablePropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3MultiConfigurablePropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerConfigurablePropagator.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTraceConfigurablePropagator.java, extensions/trace-propagators/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurablePropagatorProvider, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/testConfigError/java/io/opentelemetry/sdk/autoconfigure/ConfigErrorTest.java
While I'm not exactly sure what @kenfinnigan will do with them, if there's a use case I don't see anything wrong with this since the autoconfigure dep isn't leaked at all.
https://github.com/open-telemetry/opentelemetry-java/discussions/3284
=> Use autoconfigure SPI for trace-propagators extension.

sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/StatusBenchmark.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/ImmutableStatusData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/data/ImmutableStatusDataTest.java
For a complete enum-switch, Java bytecode is a table lookup within the bytecode so always beats a memory lookup via EnumMap. More importantly, it's way less code
After (Ran benchmarks before setting to more appropriate AverageTime and too lazy to rerun for an obvious improvement, higher is better)
```
Benchmark                                                      Mode  Cnt   Score    Error   Units
StatusBenchmark.createWithoutDescription                      thrpt   30   0.384 ±  0.004  ops/ns
StatusBenchmark.createWithoutDescription:·gc.alloc.rate       thrpt   30  ≈ 10⁻⁴           MB/sec
StatusBenchmark.createWithoutDescription:·gc.alloc.rate.norm  thrpt   30  ≈ 10⁻⁶             B/op
StatusBenchmark.createWithoutDescription:·gc.count            thrpt   30     ≈ 0           counts
``` …
=> Use switch instead of enummap for status creation

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java
When reading code, randomly found this method which was a bit confusing since it doesn't always copy, only when it is ensuring a limit.
=> Small tweak to name of internal method.

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
=> Make sure the 2nd call to shutdown() on the GRPC exporters succeeds.

extensions/annotations/src/main/java/io/opentelemetry/extension/annotations/SpanAttribute.java, extensions/annotations/src/main/java/io/opentelemetry/extension/annotations/WithSpan.java, extensions/annotations/src/main/java/io/opentelemetry/extension/annotations/WithSpanAttribute.java, extensions/annotations/src/test/java/io/opentelemetry/extension/annotations/WithSpanUsageExamples.java
Adds a new annotated that when combined with the `@WithSpan` annotation will add the value of the annotated parameter as an attribute to the newly-created `Span`:
```java
@WithSpan("method")
public void someMethod(@SpanAttribute("name") String someName) {
// do stuff
}
```
For the above example the OTel auto-instrumentation will create a new `Span` with the name "method" and will take the value of the parameter `someName` and add it as a String attribute with the name "name".
For the attribute names there is the caveat that, by default, the Java compiler does not include the parameter name metadata in the compiled classes.  You can opt-into this by passing the `-parameters` compiler argument.  Without this the instrumentation cannot derive a useful name for the parameter.  This could be …
=> Add @SpanAttribute annotation for adding attributes to spans created through instrumentation

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/trace/DefaultTracerBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/TracerBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/TracerProvider.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DefaultMeterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/GlobalMeterProvider.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/MeterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/MeterProvider.java, api/metrics/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java, docs/apidiffs/current_vs_latest/opentelemetry-api.txt, docs/apidiffs/current_vs_latest/opentelemetry-extension-trace-propagators.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricAdapter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/SpanAdapter.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/MetricAdapterTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/SpanAdapterTest.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterRegistryTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerProviderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerTest.java
This is an alternative approach to #3299 utilizing a builder for tracers/meters, rather than adding another overload with a confusing nullable parameter.
=> Introduce usage of the OpenTelemetry schema with a Tracer/MeterBuilder

docs/apidiffs/current_vs_latest/opentelemetry-extension-annotations.txt
#3168 added a new annotation but the apidiff update is missing. As a result, the diff crops up in other PRs, e.g. https://github.com/open-telemetry/opentelemetry-java/pull/3312/files#diff-619e30119c066f6bb370538e7126a2c0acaa4316bafc55441dccaf3e3e438182
=> Fix missing apidiff from #3168.

docs/apidiffs/current_vs_latest/opentelemetry-extension-annotations.txt, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java
We commonly use the toString generated from the AutoValue TestData in test assertions, which look terrible because of the huge Resource that gets printed before some important stuff
=> Reorder methods on SpanData for better AutoValue toString

sdk/trace-shaded-deps/src/main/java/io/opentelemetry/sdk/trace/internal/JcTools.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
We are currently using `jlink` and we favour not including the `jdk.unsupported` module in our builds. This causes a failure in open-telemetry, though:
```
[otel.javaagent 2021-06-22 05:21:27:988 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.3.0
[otel.javaagent 2021-06-22 05:21:28:177 +0000] [main] INFO io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native …
```
=> BatchSpanProcessor falls back to ArrayBlockingQueue if `jdk.unsupported` is not available

all/build.gradle.kts, buildSrc/src/main/kotlin/otel.jacoco-conventions.gradle.kts
Broke this when trying to switch to `<>` syntax but muscle memory adding the configureEach
https://github.com/open-telemetry/opentelemetry-java/commit/ce9c8854c7484b8af260d8da122525b919fa8a42#diff-272fb3a27b813eb474376e65452cf2753ac06c9cafe5e6e35e7d05a92d7e4f58L46
=> Fix jacoco by eagerly configuring it.

.github/workflows/main-build.yml, .github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml, all/build.gradle.kts, buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts, sdk-extensions/jfr-events/build.gradle.kts
As we add more java versions to our test set, adding tasks to the same build won't scale as well as going ahead and parallelizing on GHA. This makes us more consistent with instrumentation repo too.
BTW I found https://github.com/line/armeria/issues/3673
=> Use property to specify test java version instead of adding tasks.

.editorconfig
If this is acceptable, I can reformat all the `.gradle` and `.kts` files either in this PR or subsequent PR (to change indent from 4 to 2 spaces).
=> Sync .editorconfig with instrumentation repo

sdk/trace-shaded-deps/build.gradle.kts, sdk/trace/build.gradle.kts
Seeing https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3471 I thought of making another attempt to find a cleaner approach to embedding a relocated archive. This pattern is different - it's probably a little better
- Does not "side-step" Gradle by copying into the output Jar. So the classes are available in areas Gradle knows they should be (we see this with the removal of `jmh(":sdk:trace-shaded-deps")`). It doesn't remove the need of `compileOnly` though since it only adds classes to the output, not Java to the input (which don't exist in shaded form) which is needed for compilation
- No evaluation order dependency, always a benefit to reduce build fragility
Because shadow outputs straight to a jar though we still don't seem to have a way to avoid having the …
=> Different pattern for embedding shaded dependency.

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
For attributes it's very common to just assert the entries in the attributes, so this can reduce two indents
=> Add hasAttributes which takes a list of entries.

sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
This doesn't seem too elegant but for one location figured it's simple enough.
Fixes test flake
```
BatchSpanProcessorTest > continuesIfExporterTimesOut() FAILED
java.lang.NullPointerException: Cannot invoke "io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(java.lang.Runnable)" because "shutdownResult" is null
at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$2(BatchSpanProcessor.java:257)
at io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(CompletableResultCode.java:126)
at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.shutdown(BatchSpanProcessor.java:253)
at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.access$200(BatchSpanProcessor.java:121)
at …
```
=> Remock shutdown after reset.

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TraceAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
For the common pattern of `hasSpansSatisfyingExactly`, there isn't any way to verify the parent of a span since we don't have any trace data in scope, only a TraceAssert. Allowing access of spans through the TraceAssert enables this and is similar to what we have in instrumentation repo (this is probably the biggest gap between the two right now). Also added a shortcut `hasParent` which seems worth it.
=> Add TraceAssert.getSpan

buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
Just `-PdisableErrorProne=true` or put it in your personal gradle.properties file.
=> Provide an option for disabling errorprone for a smoother dev experience

sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java
- Fix benchmark setup to use `SdkMeterProviderBuilder` rather than directly instantiate and risk not configuring necessary components.
- add 'realistic' histogram benchmark for comparison against prototype.
=> Fixes #3392 - Metric benchmark no longer throws NPE

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
It's awkward to have to use an ID, the invalid ID, when just wanting to check that there is no parent span.
=> Add hasNoParent assertion

buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
Disabling all compilation tasks completely is an interesting way of disabling the check :) This needed an update when changed from Groovy to Kotlin
=> Fix disableErrorProne to not disable compilation

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/build.gradle.kts, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
Exceptions are converted to data by our SDK so it makes sense to have an assertion matching the logic
=> Add assertion for exception

docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TestConfigurableSamplerProvider.java, sdk-extensions/tracing-incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/ExecutorServiceSpanProcessorTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/SamplingResult.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/SamplingResultTest.java
https://github.com/open-telemetry/opentelemetry-java/pull/3360
Fixes #3354
rebase it by re-create the branch and re-push
=> Add factories for SamplingResult

.editorconfig
Syncing with otel-java-instrumentation (#3677)
=> Preserve spaces in gradle.properties

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TraceAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TracesAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
It's reasonable to need to set up assertions programatically, for example when testing a method that executes dozens of requests to verify concurrency. This way a List type of thing doesn't need to be converted to an array and is consistent with the other vararg methods we have in our APIs
=> Add Iterable versions of hasTraces / Spans

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
While it's more common to check both key and value, it may be appropriate to only check key. In particular, this is extremely important to add to `hasEntrySatisfying` (as in this PR) since otherwise in the case of a missing key, it fallsback to a null check with an unhelpful assertion message `Expecting actual to not be null`
=> Add AttributesAssert.containsKey

.github/workflows/main-build.yml, .github/workflows/pr-build.yml
@jkwatson While sorting through some of the very common CI failures like the HttpSpanExporter one, let's go ahead and use our judgment to merge PRs when a reasonable representative set of the jobs pass, if that's ok with you.
=> Don't fail fast on tests.

.github/workflows/main-build.yml, .github/workflows/pr-build.yml
Prevents build cache from one java overwriting the other, preventing caching of all but one java version. This was needed when we migrated to use same pattern as instrumentation for testJavaVersion.
=> Set jobid for build cache.

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-jaeger-remote-sampler.txt, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSampler.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerIntegrationTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
When debugging logs of CI, I noticed 90% of the log is spam from leaked jaeger pollers.
=> Allow Jaeger remote sampler to be closed.

docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Adds the `getParentSpanContext` method to the `ReadableSpan` interface to get the `SpanContext` of the parent span, or `SpanContext#getInvalid` if the span is a root span.  I believe that this is already allowed by the opentelemetry-specification as it states:
> A function receiving this as argument MUST be able to access all information that was added to the span, as listed in the API spec.
and the API spec explicitly lists the parent span or span context as one of those pieces of information.
This information is already accessible via calling `toSpanData`, but that method is expensive as it synchronized and needs to make copies of the mutable state of the span.
=> Adds getParentSpanContext to ReadableSpan interface
