open-telemetry/opentelemetry-java

exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metric/OtlpHttpMetricExporter.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java
I can't reason out why this would actually cause a different in the flaky test we're seeing but want to give it a YOLO attempt. I have been able to confirm that the test fails despite the log message definitely being printed as below. 
Logunit's general structure is `beforeTestExecution`, essentially `Logger.getLogger(name).addHandler(listHandler)`. I don't see any thread safety issues or anything, digging through JDK code I could see getLogger returning a different instance if the calling class's "module" (JMS) is different but that shouldn't be the case. But anyways, maybe `static` does something let's see.
```
Aug 10, 2021 6:13:21 AM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with HTTP status code 500. Error message: Server …
```
=> Staticially initialize HTTP exporter loggers.

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ConfigurableMetricExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TestConfigurableMetricExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurableMetricExporterProvider
- Creates ConfigurableMetricExporterProvider SPI
- Updates Metric setup to use SPI registry after built-in
=> Add a new configurable metric exporter to autoconf

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
The default method implementation of TracerProvider.tracerBuilder and OpenTelemetry.tracerBuilder is not very helpful, as demonstrated by this PR.
~~I will amend the PR later to provide a fix, just wanted to give you a quick heads-up  since the release of 1.5 seems imminent -- probably this should be fixed before. @jkwatson @anuraaga~~
=> Fix OpenTelemetrySdk(.tracerProvider).tracerBuilder() being noop.

docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporter.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java, sdk-extensions/autoconfigure/src/testResourceDisabledByEnv/java/io/opentelemetry/sdk/resources/ResourceDisabledByEnvTest.java, sdk-extensions/autoconfigure/src/testResourceDisabledByProperty/java/io/opentelemetry/sdk/resources/ResourceDisabledByPropertyTest.java, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ContainerResourceTest.java, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/OsResourceTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java, sdk/common/src/test/java/io/opentelemetry/sdk/resources/ResourceTest.java
It's pretty common to see code that just wants to get the value of a single resource attribute...and there wasn't a method to do this, so there were law of demeter violations sprinkled about. This adds the `getResource(key)` method and cleans up some of the `.getAttributes().get(key)` calls. 
Vendors will be able to leverage this too.
=> Add Resource.getAttribute() 

exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java
Haven't seen the HTTP exporters flake in a while and finally saw a gRPC one do so. So applying same pattern.
Ref: https://github.com/open-telemetry/opentelemetry-java/pull/3459#issuecomment-897363405
=> Use static loggers for gRPC exporters too.

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-jaeger-remote-sampler.txt, sdk-extensions/jaeger-remote-sampler/build.gradle.kts, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProvider.java, sdk-extensions/jaeger-remote-sampler/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurableSamplerProvider, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProviderTest.java, sdk-extensions/jaeger-remote-sampler/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This PR makes `JaegerRemoteSampler` available via SPI. The ultimate goal is to make it available in the java auto-instrumentation (javaagent).  I have talked about this with @tedsuo and @yurishkuro that including it in the javaagent distro should be fine (Jaeger is considered as a special vendor). 
After this PR is merged I will create a PR to auto-instrumentation to package it in the final distribution. We should also document it in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration
=> Make Jaeger remote sampler available via SPI

exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporterTest.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporterTest.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/SpanAdapter.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/TraceMarshaler.java
Resources are essentially Singletons, and TracerProvider ensures the same for InstrumentationLibraryInfo. We may as well use an IdentityHashMap when grouping them to not rely on performance characteristics of `hashCode`.
=> Use IdentityHashMap for grouping.

dependencyManagement/build.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, exporters/otlp-http/metrics/build.gradle.kts, exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metric/OtlpHttpMetricExporter.java, exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metric/OtlpHttpMetricExporterBuilder.java, exporters/otlp-http/trace/build.gradle.kts, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/GrpcStatusUtil.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/GrpcStatusUtilTest.java, exporters/otlp/metrics/build.gradle.kts, exporters/otlp/trace/build.gradle.kts, proto/build.gradle.kts
otlp-http currently includes an unused gRPC dependency because of this which isn't intended. Our gRPC exporters actually already had implementation dependencies on these artifacts anyways.
=> Make proto dependency on gRPC compileOnly.

dependencyManagement/build.gradle.kts, exporters/otlp/trace/build.gradle.kts, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/InstrumentationLibraryMarshaler.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/TraceMarshaler.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/SpanDataRandomizerRegistry.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/TraceMarshalerTest.java
And fix TraceMarshaler marshaling of schemaUrls.
This generates 100 different SpanData every CI run. Though I've ran through 100000 locally with no error.
It did solve the most important issue of automatically detecting schemaUrl had drifted. I think this gives good confidence and we can go ahead and switch the marshaler used by the exporters.
=> Test TraceMarshaler with random SpanData.

exporters/jaeger-thrift/README.md, exporters/jaeger/README.md, exporters/logging/README.md, exporters/otlp-http/metrics/README.md, exporters/otlp-http/trace/README.md, exporters/otlp/common/README.md, exporters/otlp/metrics/README.md, exporters/otlp/trace/README.md, exporters/prometheus/README.md, exporters/zipkin/README.md, extensions/annotations/README.md, extensions/trace-propagators/README.md, sdk-extensions/async-processor/README.md, sdk-extensions/aws/README.md
Went to add javadoc links to the new OTLP http modules, and noticed that a bunch of broken javadoc links. Went through and fixed all the ones I found.
Separately, there are a bunch of readmes that are missing altogether, or are missing javadoc links. Figure I'll add those in a separate PR.
=> Fix javadoc

api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributes.java, api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributesBuilder.java, api/all/src/main/java/io/opentelemetry/api/common/Attributes.java, api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/all/src/test/java/io/opentelemetry/api/common/AttributesTest.java, api/all/src/test/java/io/opentelemetry/api/internal/ImmutableKeyValuePairsTest.java
resolves #2765 
This handles `of(k,v)`, `of(k1,v1,k2,v2)` and a single element AttributesBuilder.
=> Optimize 1 & 2 element attributes creation

exporters/otlp/trace/build.gradle.kts, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/ExportTraceServiceResponse.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/MarshalerInputStream.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/MarshalerTraceServiceGrpc.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java
This is almost exactly like @bogdandrutu's #2890 though I made a few tweaks to avoid any dependency on the generated gRPC code to in the future allow us to remove dependency on the generated proto completely.
=> Plugin the custom marshaler to otlp:trace span exporter.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongGaugeBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleSumObserverTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownSumObserverTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongGaugeBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongSumObserverTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongUpDownSumObserverTest.java
The was a comment from @jkwatson.   I liked it, so I took the 5 minutes to do it.  Happy to take it or leave it.
Should not change anything materially as these classes are all package-private.
=> Rename instruments from *Sdk. -> Sdk*

exporters/otlp-http/trace/build.gradle.kts, exporters/otlp-http/trace/src/jmh/java/io/opentelemetry/exporter/otlp/http/trace/HttpSpanExporterBenchmark.java, exporters/otlp-http/trace/src/jmh/java/io/opentelemetry/exporter/otlp/http/trace/TraceBenchmarkState.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/ProtoRequestBody.java
Was curious about the difference between writing through `toByteArray` and straight for okhttp. The additional time for a relatively large, but single buffer, isn't that big of a deal but there is definitely more GC activity introduced. The `ProtoRequestBody` is pretty tiny and simple so think this could be worth it but what do you think? The pattern will also be a bit easier to adapt to `TraceMarshaler`.
```
Benchmark                                                               (numSpans)  Mode  Cnt       Score       Error   Units
HttpSpanExporterBenchmark.writeByteArray                                       512  avgt   10     360.983 ±    11.766   us/op
HttpSpanExporterBenchmark.writeByteArray:·gc.alloc.rate                        512  avgt   10     628.052 ±    19.436  MB/sec …
```
=> Serialize proto directly into okhttp buffer.

exporters/logging-otlp/build.gradle.kts, exporters/otlp-http/metrics/build.gradle.kts, exporters/otlp-http/trace/build.gradle.kts, exporters/otlp/common/build.gradle.kts, exporters/otlp/metrics/build.gradle.kts, exporters/otlp/trace/build.gradle.kts
This is a bit of a mess but will get cleaned up after 1) migrating HTTP exporter to TraceMarshaler (coming soon after #3519) and 2) Adding a MetricMarshaler (coming eventually). On the bright side, forgetting to add `:proto` where it's needed results in a quick compile failure.
=> Make proto dependency in otlp-common compileOnly.

exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/package-info.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/package-info.java
Noticed that the `package-info.java` files in `:exporters:otlp:metrics` and `:exporters:otlp:trace` have some information that appears to be a remnant of a time when the exporters were configurable via `ConfigProperties`.
=> Remove outdated docs in otlp package-info.java files

docs/apidiffs/current_vs_latest/opentelemetry-extension-kotlin.txt
A change was made to `:extensions:kotlin` without running the apidiff script.
=> Add missing API diff.

exporters/otlp-http/build.gradle.kts, exporters/otlp/build.gradle.kts, sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtilTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Related to this [open spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1879).
A note on the implementation: I was getting annoyed with how repetitive the configuration was for OTLP exporters. The extraction of config properties for OTLP grpc traces / metrics exporters is mostly the same. Adding support for protocol configurability of protocol means more copy / pasta or adding some abstraction. Went with adding an abstraction. 
I initially added a `OtlpExporterBuilder` interface located in `:exporters:otlp:common` with methods common across all the OTLP exporters, but ran into all sorts of `NoClassDefFoundError` errors I couldn't get past. The solution I landed is to have a method that accepts a bunch of consumers which are invoked after config properties …
=> Add OTLP protocol configurability to autoconfigure

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
I had to tweak the generator template a bit to account for some new constants that didn't map to java constant names.
=> Update the semantic conventions to 1.6.0

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigTest.java
=> Support comma separated list for exporters for otel.traces.exporter.

api/all/src/main/java/io/opentelemetry/api/common/AttributeKeyImpl.java, api/all/src/test/java/io/opentelemetry/api/common/AttributeKeyTest.java
This turns out to be very helpful when looking up attribute keys in an attributes map.
I thought about using AutoValue's `@Memoize`, but the implementation for that is lazy double-checked lock (i.e. a volatile read), which seems unnecessary overhead in this case.
=> Cache AttributeKey hashCode

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/AnchoredClock.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java
Currently we compute current `nanoTime` twice for a root span unnecessarily. `nanoTime` calls into the OS so it's not the fastest API out there and this does end up showing up on flame graphs. It's not so difficult to avoid this.
After
```
Benchmark                                                          Mode  Cnt     Score    Error   Units
FillSpanBenchmark.setFourAttributes                               thrpt   60  2164.882 ± 28.919  ops/ms
FillSpanBenchmark.setFourAttributes:·gc.alloc.rate                thrpt   60   813.621 ± 10.910  MB/sec
FillSpanBenchmark.setFourAttributes:·gc.alloc.rate.norm           thrpt   60   592.000 ±  0.001    B/op
FillSpanBenchmark.setFourAttributes:·gc.churn.G1_Eden_Space       thrpt   60   813.659 ± 24.409  MB/sec …
```
=> Only compute nanoTime once for a root span.

api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java
@trask This changed the flamegraphs quite a bit to not have a dominant base16 validation in them. 0 is still better than non-0 but maybe this changes the importance of the other PR (though I left a comment on that which could allow us to eat the cake).
After
```
Benchmark                                                          Mode  Cnt     Score    Error   Units
FillSpanBenchmark.setFourAttributes                               thrpt   60  3208.277 ± 48.574  ops/ms
FillSpanBenchmark.setFourAttributes:·gc.alloc.rate                thrpt   60  1205.990 ± 18.235  MB/sec
FillSpanBenchmark.setFourAttributes:·gc.alloc.rate.norm           thrpt   60   592.000 ±  0.001    B/op
FillSpanBenchmark.setFourAttributes:·gc.churn.G1_Eden_Space       thrpt   60  1206.781 ± 33.014  MB/sec …
```
=> Remove branches from isValidBase16

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MarshalerUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricsRequestMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/TraceRequestMarshaler.java
Solves a TODO. I suspect the original implementation didn't include them since they're not 100% correct - you're supposed to compare against the first entry in the `enum`, which may not necessarily be `0`. OTLP will always use `0` following best practices though and I think this is safe enough.
=> Add MarshalerUtil enum helpers.

exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/RequestMarshalState.java
We expect AttributeKey to always be singleton for performance - on the flip side, attributes added without creating constants can be considered non-performance-sensitive code I think. So our benchmark should reflect the actual performance-sensitive case to possibly, in the future, add optimizations that benefit it at the expense of some slowdown in non-performance-sensitive code.
=> Use constants for AttributeKeys in JMH

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpiUtil.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ThrowingConfigurableMetricExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ThrowingConfigurablePropagatorProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ThrowingConfigurableSamplerProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ThrowingConfigurableSpanExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurablePropagatorProvider, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.metrics.ConfigurableMetricExporterProvider, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSamplerProvider, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider
In https://github.com/aws-observability/aws-otel-java-instrumentation/issues/77 I noticed that it's possible for a bad SPI implementation to prevent others from being usable since we load them eagerly without catching exceptions. I think it's worth making sure that one bad SPI doesn't remove the flag completely so this catches and logs a failure. If the bad SPI was actually specified for the flag, it would result in a ConfigurationException still as we'd want.
I think for the non-configurable SPIs (*ProviderConfigurer) it seemed still fine to bubble the exception as they are not just an option out of many but code that needs to be executed.
=> Catch exceptions when loading a configurable SPI.

dependencyManagement/build.gradle.kts, integration-tests/src/test/java/io/opentelemetry/B3PropagationIntegrationTest.java
based on @anuraaga's https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4068#issuecomment-915739043
just temporary until better solution implemented
=> Use older okhttp version to avoid dependency on kotlin stdlib

docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanLimits.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanLimitsBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java
Followup to Issue #3551.
Also noticed an inconsistency between the name of the new span attribute value length setter and getter so I've fixed that as well. Will be good to get that aligned before the release 😬!
=> Add autoconfigure for span attribute value length limits

exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/MarshalerInputStreamBenchmarks.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/RequestMarshalBenchmarks.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/otlp/internal/RequestMarshalState.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/InstrumentationLibraryMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/JsonSerializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/Marshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MarshalerUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MetricsRequestMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ProtoSerializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ResourceMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/Serializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/TraceRequestMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/MetricsRequestMarshalerTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/SpanDataRandomizerRegistry.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/TraceRequestMarshalerTest.java, exporters/otlp/trace/build.gradle.kts
Depends on #3586
JSON serialization without any real change to the Marshalers :) (aside from the preserialized which are rare)
The performance matches our current byte-buddy generated marshalers - this is because protobuf-jackson is awesome :-) In particular, I suspect the main reason is that it is preserializing the field names which are constant. We can do similar without too much effort, but luckily it doesn't regress so that can come later. Also added what the upstream JSON serializer looks like for kicks.
And for reference binary is about 13 for the 16-cnt case. This was my original objective with protobuf-jackson, to make sure JSON is within an order of magnitude, which upstream isn't. But we do see the significant benefit binary still gets us over it.
```
Benchmark …
```
=> Implement JsonSerializer

integration-tests/build.gradle.kts, integration-tests/src/test/java/io/opentelemetry/OtlpExporterIntegrationTest.java, integration-tests/src/test/resources/otel-config.yaml
Per a conversation in last week's SIG meeting, I've added an integration test confirming compatibility between the OTLP exporters and the collector. This isn't (currently) an exhaustive test of all the fields available on the protos, but it should act as a decent starting point.
=> Add OTLP integration test for gRPC and HTTP Trace and Metric exporters

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/AlwaysSampleFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/ExemplarFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/ExemplarReservoir.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/ExemplarSampler.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/FilteredExemplarReservoir.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/NeverSampleFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/WithTraceExemplarFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/exemplar/ExemplarFilterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/exemplar/FilteredExemplarReservoirTest.java
Depends on #3583
- Add `ExemplarFitler` interface
- Add three default impelementaitons (with traces, none and all)
- Create `FilteredExemplarReservoir` that allows pre-filtering measurements prior to actual reservoir sampling.
=> Wire in Exemplar Pre-Filters

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtilTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Updating the config properties for protocol now that they're official in the [spec](https://github.com/open-telemetry/opentelemetry-specification/pull/1880).
=> Remove experimental prefix from otlp protocol config properties

all/build.gradle.kts, dependencyManagement/build.gradle.kts
The junit4/5 integration for archunit is apparently just a caching mechanism for performance, which is probably why despite our tests being jupiter, they still worked ok. Also, while junit4 requires explicit activation of the caching mechanism (which we weren't doing), junit5 is apparently automatic so this might improve something. But primarily to remove the word junit4 from the build to prevent confusion.
=> Switch to archunit junit5

dependencyManagement/build.gradle.kts, exporters/zipkin/build.gradle.kts, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java
This is the last junit4 test in the repo aside from our explicit junit4 rule test in sdk-testing
=> Migrate Zipkin integration test from junit4 to junit5 + testcontainers

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java
Randomly found this and let IntelliJ automatically convert this - we generally prefer concatenation since basically same if not better readability and if we ever get to compile against Java 9+ we'll get free performance.
=> Use concatenation instead of stringbuilder in RERS.

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts, dependencyManagement/build.gradle.kts
Can remove vintage since no more non-jupiter tests
=> Remove junit vintage engine and update dependencies.

exporters/otlp-http/metrics/build.gradle.kts, exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp-http/trace/build.gradle.kts, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/TlsUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/ManagedChannelUtil.java
okhttp-tls has a dependency on the fairly large bouncycastle for certificate generation. We don't actually need it's generation so the thought of excluding bouncycastle came to mind - but I realized we already had all the relevant code here anyways.
=> Remove dependency on okhttp-tls

exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/LogAdapterTest.java, sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/data/LogRecord.java, sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/data/LogRecordBuilder.java, sdk-extensions/logging/src/test/java/io/opentelemetry/sdk/logging/LogSinkSdkProviderTest.java, sdk-extensions/logging/src/test/java/io/opentelemetry/sdk/logging/sdk/BatchLogProcessorTest.java
I think this is our convention - it solves a nullness issue which is why I found it.
=> Make LogRecord required parameters final.

sdk-extensions/zpages/src/main/java/io/opentelemetry/sdk/extension/zpages/TracezSpanBuckets.java
Nullness checker found the usage of `Map.get()` without null check, which in practice wasn't an issue since we prepopulate the map with all values of an enum. So in other words the keys to the maps were constant (well one of them only had one item inside). This made me think we should just use constants instead.
We can expect a significant performance improvement since complete enumswitch is just a single jump (though switching from HashMap to EnumMap would have gotten very similar improvement, but still require adding nullness casts)
=> Don't use hashmap for zpage buckets since the keys are constant.

all/build.gradle.kts
Recently introduced these to this new internal package so need to exclude
=> Exclude internal Time protos used by jaeger marshaling from coverage

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/DefaultConfigProperties.java
It's no big deal but it's a bit annoying to see the opentelemetry-spi package in codecov have 50% coverage as it just looks like a project with low coverage even though it isn't really. The simple fix is to pass and then ignore this NumberFormatException as a cause (the other location we were calling the constructor that has a cause is an invalid cert exception that is tedious to verify)
=> Pass a cause to ConfigurationException somewhere.

CONTRIBUTING.md, README.md, bom-alpha/build.gradle.kts, bom/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/io/opentelemetry/gradle/OtelBomExtension.kt, buildSrc/src/main/kotlin/otel.bom-conventions.gradle.kts
This is an alternative to #3603 (which I'd still prefer).
Since there was no agreement on renaming the projects, we can at least save ourselves the trouble of writing the substitutions for an included build by hand every time and let gradle to it in a semi-automated way.
This adds the `generateBuildSubstitutions` task to the bom projects, which is a convenience task that can be used to
generate a code snippet that can be copy-pasted
for use in composite builds.
Output for (stable) bom:
```kotlin
dependencySubstitution {
substitute(module("io.opentelemetry:opentelemetry-api")).using(project(":api:all"))
substitute(module("io.opentelemetry:opentelemetry-context")).using(project(":context"))
substitute(module("io.opentelemetry:opentelemetry-exporter-jaeger")).using(project(":exporters:jaeger" …
```
=> Add generateBuildSubstitutions task to bom projects.

.github/workflows/codeql-analysis.yml, .github/workflows/main-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml, .github/workflows/release-build.yml, buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts, gradle.properties
Doesn't change the target compatibility to 17.
Does still build fine if Gradle is run with Java 11. Now it can also be run with Java 17 (with the gradle.properties workaround)
=> Build with Java 17

exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java
Should be 'plain' instead of 'plan' which matches nearby comment.
=> Fix typo in exception message

buildSrc/build.gradle.kts, settings.gradle.kts
I mainly wanted to update Kotlin to possibly avoid this weird warning on newer Java but seems to have not been fixed, hopefully next time.
```
Compilation with Kotlin compile daemon was not successful
java.rmi.ServerError: Error occurred in server thread; nested exception is:
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil
at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:386)
at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
at …
```
=> Update Gradle plugins

exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp-http/metrics/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterTest.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp-http/trace/src/test/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterTest.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterBuilder.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogsExporterTest.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java
[Spec](https://github.com/open-telemetry/opentelemetry-specification/pull/1955) now says that `none` must be a supported compression type.
=> Add support for none compression keyword

integration-tests/build.gradle.kts, integration-tests/src/test/java/io/opentelemetry/OtlpExporterIntegrationTest.java
Rounding out the otlp integration test with the addition of the [http/protobuf log](https://github.com/open-telemetry/opentelemetry-java/pull/3682) exporter.
=> Add integration test for otlp http/protobuf log exporter

exporters/otlp-http/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterBuilder.java, exporters/otlp-http/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterTest.java
[PR #3682](https://github.com/open-telemetry/opentelemetry-java/pull/3682) and [PR #3687](https://github.com/open-telemetry/opentelemetry-java/pull/3687) were outstanding at the same time and support for `none` compression for the `OtlpHttpLogExporter` didn't make it in. This fixes that.
=> Add missing none compression support to OtlpHttpLogExporter

sdk-extensions/tracing-incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/ExecutorServiceSpanProcessor.java, sdk-extensions/tracing-incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/ExecutorServiceSpanProcessorTest.java
The test for forceFlush for this processor is flaky because the processor doesn't actually force a flush. Now it does.
It's pretty complex fix though, I couldn't come up with a better pattern. Let me know with some code if anyone has a better idea.
@Oberon00 Are you still interested in this processor? Wondering if anyone is actually using it.
=> Actually flush in ExecutorServiceSpanProcessor

sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ContainerResource.java, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ContainerResourceTest.java
=> Handle multiple hyphens in container prefix when parsing cgroups

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java
The `@Immutable` annotation was recently removed from `MetricData`, I believe accidentally. This restores it.
=> Restore @Immutable annotation on MetricData

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java
Minor optimization to use new `AttributeBuilder#removeIf(..)` in the `AttributeProcessor#filterByKeyName(..)` implementation.
=> Use AttributeBuilder#removeIf in AttributeProcessor#filterByKeyName

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Updating autoconfigure configuration of the periodic metric reader to be based off `otel.metric.export.interval`, and deprecating `otel.imr.export.interval`. 
This system property was introduced in spec [PR 2038](https://github.com/open-telemetry/opentelemetry-specification/pull/2038).
The spec also introduced another property, `OTEL_METRIC_EXPORT_TIMEOUT`, but `PeriodicMetricReader` doesn't yet have a configurable export timeout.
=> Configure periodic metric reader interval with otel.metric.export.interval

exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/SystemOutLogExporterTest.java, exporters/otlp-http/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/logs/LogsRequestMarshalerTest.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogsExporterTest.java, exporters/otlp/logs/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/ExportTest.java, exporters/otlp/logs/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/logs/ExportTest.java, exporters/otlp/logs/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/logs/ExportTest.java, exporters/otlp/logs/src/testOkHttpOnly/java/io/opentelemetry/exporter/otlp/logs/OkHttpOnlyExportTest.java, integration-tests/src/testOtlpCommon/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogEmitterSharedState.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogEmitter.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogEmitterProvider.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogEmitterProviderBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogData.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogDataBuilder.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/LogEmitterSharedStateTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterProviderBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterProviderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/data/LogDataBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/util/TestUtil.java, sdk/logs/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Resolves #3817
Allow the clock to be overridden so that we aren't directly coupled to `System.currentTimeMillis()` and is more consistent with how metrics and traces handle temporality.
It is slightly different due to the `ComponentRegistry` used in `SdkLogEmitterProvider` but I think it's covered.
=> Let clock be overridden for log creators

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DeltaMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/DeltaMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricReaderCumulativeTest.java
This PR adds some naive protections for metrics cardinality:
- It aggressively forgets metric streams when temporality is cumulative. Currently, if temporality is cumulative and async instruments stop recording for a metric stream for an export, that stream is removed. The PR changes sync instruments to have the same behavior. This is the most conservative thing we can do from a memory management perspective. In the past we've talked about having TTL, where if a stream isn't recorded for the TTL, it's removed. This is a more aggressive, and simpler to implement removal policy that I think is a good start.
- It caps the number of metric streams for each `MetricStorage`. There is one metric storage per view, so each view has a cap number of metric streams. I set the number to 2000, which I …
=> Metric cardinality limits

exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java, exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp-http/metrics/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterTest.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtilTest.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Resolves #3790.
Make the preferred temporality of the OTLP grpc / http metric exporter configurable. Can be configured programmatically or via env / system properties.
=> OTLP metric temporality configuration

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/Serializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/metrics/HistogramDataPointMarshaler.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/PrimitiveLongList.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/PrimitiveLongListTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoubleHistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/MetricDataUtils.java
Since we've talked about needing this for the exponential histogram, which may have many buckets, figured may as well add for the current one first. While the impact shouldn't be as big for a normal histogram, I think, it's still a reasonable optimization I think.
=> Use a wrapper of primitive long array for histogram counts.

api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundDoubleCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundDoubleHistogram.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundDoubleUpDownCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundLongCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundLongHistogram.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/BoundLongUpDownCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleCounterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleGaugeBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleHistogram.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleUpDownCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleUpDownCounterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongCounterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongGaugeBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongHistogram.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongUpDownCounter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/LongUpDownCounterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/Meter.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/MeterBuilder.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/ObservableMeasurement.java, api/metrics/src/main/java/io/opentelemetry/api/metrics/package-info.java
- Add "how to select instrument" guidance to `Meter`.
- Add information about `bound` and its limitations
- Add expectations of callbacks.
- Improve documentation on `UpDownCounter` vs. `Counter`.
=> Take a pass at fixing metrics API javadoc issues/missing information.

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java
While Prometheus client supports exemplars on any sample, ingestion is currently failing for non-histogram metric types.
Fixes #3884.
=> Remove exemplars from Gauge/Sums in Prometheus samples

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/MarshalerUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/Serializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/metrics/NumberDataPointMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/metrics/MetricsRequestMarshalerTest.java
Fix #3889 
There may be more instances of this, just fixing the obvious ones.
=> OTLP exporter - oneof primtives must have their default values serialized.

sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/metrics/AbstractSumDataAssert.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/metrics/DoubleHistogramAssert.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/metrics/DoubleHistogramPointDataAssert.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/metrics/ExponentialHistogramAssert.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/metrics/MetricDataAssert.java
Came across a handful of typos in the `:sdk:metrics-testing` module and felt compelled to fix them.
=> Fix typos in metrics-testing package

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
~Looks like no breaking changes this time around, so we can keep kicking this particular can down the road for a little while longer.~
Two items were removed:
DB_CASSANDRA_KEYSPACE and DB_HBASE_NAMESPACE
I think I'll add them back manually and mark them as deprecated for now.
=> update semconv to v1.8.0

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-http-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ExporterMetrics.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/DefaultGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/DefaultGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/GrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporterBuilder.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcRetryTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java
To prepare for removing GlobalMeterProvider.
- I'll add to logs in a separate PR, currently it's not autoconfigured.
- Currently, the metric exporter doesn't generate metrics since GlobalMeterProvider isn't ready in time. Metric exporter is a unique one so I guess we'll add a mutation-based approach only for it later.
=> Don't use global meter provider for trace export

sdk/common/src/test/java/io/opentelemetry/sdk/internal/ThrottlingLoggerTest.java
The one we've seen elsewhere for not keeping a static reference to the actual logger and having it GC'd before being captured
```
> Task :sdk:common:test
ThrottlingLoggerTest > delegation() FAILED
org.opentest4j.AssertionFailedError: oh no! ==> None of the 0 captured log events matched the filter predicate
at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
at app//io.github.netmikey.logunit.api.LogCapturer.lambda$assertContains$3(LogCapturer.java:174)
at java.base@11.0.11/java.util.Optional.orElseGet(Optional.java:369)
at app//io.github.netmikey.logunit.api.LogCapturer.assertContains(LogCapturer.java:173)
at app//io.opentelemetry.sdk.internal.ThrottlingLoggerTest.delegation(ThrottlingLoggerTest.java:3 …
```
=> Fix flaky ThrottlingLogger test

exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
This wasn't meant to be callable from subclasses - making private to reduce @jkwatson's worries about spaghetti :)
=> Make method private

.codecov.yaml
I guess it's pretty common to have patch diffs with less than 90% coverage that don't strongly affect the coverage of the build.
=> Lower codecov patch target.

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporter.java
fixes OkHttp thread not exiting on shutdown:
```
[E] Non-daemon threads currently preventing JVM termination: - 37: Thread[DestroyJavaVM,5,main]
[E]  -  - 27: Thread[OkHttp localhost Writer,5,main]
[E]  -  - 25: Thread[OkHttp localhost,5,main]
```
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#shutdown-isnt-necessary
Fixes #3900
=> evict okhttp connections on shutdown

exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
My bad - I had turned these numbers down not wanting tests that always take 2+ secs, but seems to have made the build much flakier.
=> Slow down per export test

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusCollector.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/CollectionInfo.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/TemporalityUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricExporter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricReader.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReaderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalityUtilsTest.java
Per [recent change](https://github.com/open-telemetry/opentelemetry-specification/pull/2154) to the spec.
=> Remove supported temporality

sdk/metrics/src/debugEnabledTest/java/io/opentelemetry/testing/TestSourceInfo.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DebugUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java
The metric descriptor compatibility check currently ignores instrument type and instrument value type. This leads to confusing errors when conflicts occur. For example, the following code:
```
SdkMeterProvider sdkMeterProvider = SdkMeterProvider.builder().build();
Meter meter = sdkMeterProvider.get(CardinalityTest.class.getName());
meter.counterBuilder("foo").build().add(1);
meter.histogramBuilder("foo").build().record(1);
```
Produces:
```
This aggregator does not support recording double values.
java.lang.UnsupportedOperationException: This aggregator does not support recording double values.
```
This PR strengthens the compatibility check so that in addition to name, description, and unit, instruments must also match instrument type and and instrument value type. 
After this change, …
=> Fix metric descriptor compatibility check

sdk/common/src/main/java/io/opentelemetry/sdk/internal/PrimitiveLongList.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/PrimitiveLongListTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java
Also added optimized equals / hashcode since I noticed they're used in ExponentialHistogramBuckets, though there is possibly more optimization possible by avoiding the copy into the array
=> Use PrimitiveLongList in ExponentialHistogramBuckets

sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogEmitterProvider.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterProviderTest.java
For symmetry with TracerProvider and MeterProvider.
=> Add SdkLogEmitterProvider#get(String)

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricReaderCumulativeTest.java
Expand testing…/expectations to match cumulative user expecations.
- Cumulatives are now preserved until at/near limits
- We drop all but latest attributes once we reach limit (aggressive GC vs. LRU)
We can improve this more in the future.
=> Fix up cumulatives to be preserved in more scenarios. 

exporters/otlp/logs/build.gradle.kts, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/MarshalerLogsServiceGrpc.java
Fix logs exporter module name and description
=> Fix logs exporter module name

docs/apidiffs/current_vs_latest/opentelemetry-exporter-logging-otlp.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-logging.txt, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporter.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporterTest.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingMetricExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/SystemOutLogExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingMetricExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/SystemOutLogExporterTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricExporter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/testing/InMemoryMetricExporterTest.java
According to the spec, the [in-memory](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/in-memory.md) and [standard output](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/stdout.md) exporters must allow aggregation temporality to be specified. This makes preferred temporality configurable at creation time.
=> Configurable temporality

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/concurrent/JreDoubleAdder.java
We omitted `@IgnoreJRERequirement` on one class in #3945.
=> Add @IgnoreJRERequirement to JreDoubleAdder

CHANGELOG.md
I have intentionally not updated docs / japicmp since it's an interim release. I'm wondering if we should also skip the CHANGELOG and reflect the final state in 1.10.0 without the RC steps in it, open to either approach. We do need the notes in the GitHub releases at least though to provide documentation on the deprecations / removals
=> Update CHANGELOG for 1.10.0 RC1

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ScopeManagerShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
Details are described in: https://github.com/open-telemetry/opentelemetry-java/issues/3952
A scope is returned to make sure the context is restored.
=> Stop throwing an exception when ScopeManagerShim activate a null Span

sdk/all/build.gradle.kts, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdkBuilder.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
Preparing to add autoconfigure support for logs.
First step is extending `OpenTelemetrySdk` to include `SdkLogEmitterProvider`.
=> Add SdkLogEmitterProvider to OpenTelemetrySdk

.github/workflows/codeql-analysis.yml, .github/workflows/main-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/pr-examples-build.yml, .github/workflows/release-build.yml
Temurin JDK
https://github.com/actions/setup-java/blob/main/README.md
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't
be updated anymore. It is highly recommended to migrate
workflows from adopt to temurin to keep receiving software
and security updates.
=> Temurin JDK

.github/workflows/docker-test-containers.yml
https://hub.docker.com/_/eclipse-temurin
https://www.infoq.com/news/2021/10/adoptium-releases-temurin-jdk/
=> use Eclipse Temurin JDK docker image

api/all/src/main/java/io/opentelemetry/api/metrics/ObservableDoubleMeasurement.java, api/all/src/main/java/io/opentelemetry/api/metrics/ObservableLongMeasurement.java, buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-api.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-logging-otlp.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-logging.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-http-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk.txt
=> Remove deprecated methods from ObservableMeasurement

examples/otlp/docker/docker-compose.yaml
Without this it choses an ephemeral port and so the default Jaeger exporter configuration doesn't work.
=> Add port mapping to example docker-compose.yaml

sdk-extensions/autoconfigure/README.md
There is a problem with the url in `sdk-extensions/autoconfigure/README.md`.
=> Fix the problem that README.md failed to display [javadoc-image]

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java, docs/apidiffs/current_vs_latest/opentelemetry-api.txt, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
Add to `GlobalOpenTelemetry`:
- `MeterProvider getMeterProvider()`
- `Meter getMeter(String instrumentationName)`
- `MeterBuilder meterBuilder(String instrumentationName)`
Add to `OpenTelemetry`:
- `MeterProvider getMeterProvider()`
- `Meter getMeter(String instrumentationName)`
- `MeterBuilder meterBuilder(String instrumentationName)`
I've omitted the `Meter getMeter(String instrumentationName, String instrumentationVersion)` versions of accessors as they don't exist for metrics.
=> Expand GlobaOpenTelemetry and OpenTelemetry to include metric accessors

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ExporterMetrics.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporter.java
There was a typo in the name of the counter for OkHttpGrpcExporter. Was `otlp.exported.exported`, should have been `otlp.exporter.exported`.
Refactored to use `ExporterMetrics` like the other OTLP exporters so that metric names and attributes are standardized.
=> Use ExporterMetrics for OkHttpGrpcExporter

examples/jaeger/README.md, examples/jaeger/build.gradle, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java, examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java, examples/otlp/build.gradle, examples/otlp/docker/docker-compose.yaml, examples/otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java, examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java, exporters/jaeger/build.gradle.kts, exporters/otlp/common/build.gradle.kts
Resolves #4040.
Another option would be to use `setEndpoint(String)` instead of `setChannel(ManagedChannel)` for [configuration](https://github.com/open-telemetry/opentelemetry-java/blob/main/examples/jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java#L40).
=> Remove grpc dependency from examples

docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk.txt, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/SystemClock.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/NoopSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RandomIdGenerator.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/MultiSpanExporter.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/NoopSpanExporter.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/MultiSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/NoopSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/NoopSpanExporterTest.java
When debugging issues, it can be invaluable to know the resolved SDK configuration, for example a typo like `OTEL_TRACE_SAMPLER=traceidratio(0.1)` could result in all spans being traced despite seeming to have set the sampler. I think it's worth it for us to add toString to SDK components with their configuration, especially because we have autoconfigure, not programming-only configuration.
Note this was triggered by debugging a production issue related to sampling and wanting to know what the actual sampler being used is in a reliable way.
The toString isn't beautiful at all without newlines, I just stuck with what IntelliJ generates. But it doesn't necessarily need to be beautiful, just give the information which is currently not easy to get to (mostly in javaagent, where SDK is hidden …
=> Add toString to SDK trace components and print autoconfigured SDK

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java
While rare, an IP address can change between test and assertion causing a flaky test. It seems enough to make sure the value was marshaled correctly.
Fixes #4066
=> Don't lookup IP address again in jaeger exporter assertion.

.github/workflows/pr-build.yml
Already the case for main build probably accidentally drifted
=> Collect coverage on Java 17 PR build.

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/DefaultGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/DefaultGrpcExporterBuilder.java
`DefaultGrpcExporter` calls `.withCompression(..)` twice. This removes the redundant call.
=> Remove redundant compression configuration

api/all/src/main/java/io/opentelemetry/api/internal/Contract.java, api/all/src/main/java/io/opentelemetry/api/internal/GuardedBy.java, api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/all/src/main/java/io/opentelemetry/api/internal/OtelEncodingUtils.java, api/all/src/main/java/io/opentelemetry/api/internal/ReadOnlyArrayMap.java, api/all/src/main/java/io/opentelemetry/api/internal/Utils.java, api/all/src/main/java/io/opentelemetry/api/internal/ValidationUtil.java, context/src/main/java/io/opentelemetry/context/internal/shaded/AbstractWeakConcurrentMap.java, context/src/main/java/io/opentelemetry/context/internal/shaded/WeakConcurrentMap.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/Serializer.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/GrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/metrics/ExponentialHistogramBucketsMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/metrics/ExponentialHistogramDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/metrics/ExponentialHistogramMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/retry/RetryInterceptor.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/DaemonThreadFactory.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/JavaVersionSpecific.java, sdk/common/src/main/java/io/opentelemetry/sdk/internal/ThrottlingLogger.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java, sdk/trace-shaded-deps/src/main/java/io/opentelemetry/sdk/trace/internal/JcTools.java
Noticed that several public classes in internal packages were missing the `This class is internal and is hence not for public use. Its APIs are unstable and can change at any time.` disclaimer. 
Did a survey of all internal packages and added it to all public classes and interfaces.
=> Add missing internal disclaimers

README.md
Jack has been a prolific contributor and an excellent code reviewer. I would like to promote him to maintainer status for this project.
[This PR also moves Bogdan to "emeritus" status in the README.]
=> Promote Jack Berg to maintainer

README.md
We discussed removing some folks from the approver list a while ago, but apparently, I never followed through and did it. Not sure where that PR went, but here it is again.
Anyway, thanks @pavolloffay @thisthat @arminru and @tylerbenson for your service. Please let us know if you are interested in getting back into the approval game.
=> Remove legacy approvers

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanWrapper.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Before: Highly obtuse name
After: Consistent with every other (*) SDKFoo implementation of an API Foo.
Also note that the builder for this class is `SdkSpanBuilder`
(*) I didn't actually confirm but highly suspect this is true
=> Rename RecordEventsReadableSpan to SdkSpan

README.md
I randomly noticed the link in our contributors image (had always assumed it's a GitHub native feature) and tried opening it. Found it redirects to a newer site so figured it's good to use the newer one. The snippet copied from it includes the attribution, while I don't think there's any license requiring it, I think it's nice to do so.
=> Use newer contributors image link.

exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/DefaultGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/retry/RetryUtil.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/retry/RetryUtilTest.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterTest.java, exporters/otlp/logs/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyLogExporterTest.java, exporters/otlp/metrics/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/metrics/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcNettyMetricExporterTest.java, exporters/otlp/trace/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, exporters/otlp/trace/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettySpanExporterTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
Was updating some code to use the latest version of the agent, and to use the `OkHttpGrpcExporter` instead of the `DefaultGrpcExporter`, and realized that while `OkHttpGrpcExporter` supports setting a retry policy, its not actually possible to enable it programmatically or via environment variables. 😞 
This fixes that by adjusting the reflective access method to work with both `DefaultGrpcExporterBuilder` and `OkHttpGrpcExporterBuilder`.
=> Enable reflective setting of retry policy for OkHttpGrpcExporter

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java
closes #4109 
Configures the `BatchSpanProcessor` with the `MeterProvider` provided to the `TracerProviderConfiguration` in the autoconfigure extension.
I'm open to ideas for any additional test cases as well to help protect against this again in future refactors
=> BatchSpanProcessor metrics

sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProviderTest.java
There was a time back in the day the jaeger sampler was never closed in tests. Now there are still a few left. Hoping this is the source of the flakiness in the test will check after merging
=> Close jaeger sampler in provider test too.

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
While this does contribute to some confusing output in tests (e.g., ERROR being displayed even though it's correct for the test) I think overall it's still worth it to more easily find unexpected logs happening instead (such as jaeger spam in https://github.com/anuraaga/opentelemetry-java/runs/4932526232?check_suite_focus=true)
=> Output logging messages in tests.

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
I was working on adding support for metrics customizers in `AutoConfigurationCustomizer` and ran into an issue: We currently don't register the `SdkMeterProvider` with `OpenTelemetrySdkBuilder` unless an exporter is explicitly set. This presents issues when adding a meter provider customizer method because we no we won't be able to know whether or not an `SdkMeterProviderBuilder` was extended with a reader based on whether `otel.metrics.exporter` has been set. And actually, the current metrics SPI `ConfigurableMetricExporterProvider` suffers from this same issue: if I configure a reader via `ConfigurableMetricExporterProvider`, but don't change `otel.metrics.exporter`, then my SPI customization will be ignored. 
I don't actually thing the existing protective measure is doing anything at …
=> Use noop meter provider if no readers registered

docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-trace.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-jaeger-remote-sampler.txt, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterBuilder.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/trace/build.gradle.kts, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/trace/src/testSpanPipeline/java/io/opentelemetry/exporter/otlp/trace/SpanPipelineOtlpBenchmark.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java
We'd generally like users to be using the okhttp transport and wouldn't even have this method in the API ideally to allow switching transports when we need. For now let's deprecate, and maybe hear back on some use cases which would probably be forwarded to the spec.
=> Deprecate gRPC setChannel

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Found an old rule for the proto module, which was dropped.
=> Drop java convention for old proto module

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/SdkTracerProviderConfigurer.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TestTracerProviderConfigurer.java
`SdkTracerProviderConfigurer` has been superseded by `AutoConfigurationCustomizer#addTracerProviderCustomizer(BiFunction)`.
=> Deprecate SdkTracerProviderConfigurer

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/retry/RetryInterceptor.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryInterceptorTest.java
Some New Relic folks using the retry feature let me know that `RetryInterceptor` doesn't retry on transient network errors like connection timeout. I took a look and confirmed that this is the case. 
Anytime we call `chain.proceed(chain.request())` without wrapping in a try / catch, connection errors can occur which bubble up without retry. This PR wraps treats all `IOExceptions` that occur during calls to `chain.proceed(chain.request())` as retryable. 
Note that there a variety of settings on `OkHttpClient.Builder` that can impact the conditions that cause `IOException` to be throw:
- [callTimeout](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#callTimeout-java.time.Duration-) - we set this today to 10s, and allow users to configure it. The total amount of …
=> Retry on connection timeouts

exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryInterceptorTest.java
There's been a number of test flakes in the `RetryInterceptorTest` since I introduced the change to retry on connect timeout. I believe the flakes are due to a very low connect timeout setting, which causes normal requests to occasionally timeout. 
I considered extending the connect timeout setting to something like 100ms, which would reduce the likelihood of the flake but may not eliminate it altogether since normal requests might take longer than 100ms to connect if the test environment is resource constrained. Instead, I opted to use a `OkHttpClient` with a short connect timeout configuration only for the connect timeout tests. The other tests get the default 10s connect timeout.
=> Fix retry interceptor test flake

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java
Likely fixes #4164.
If a user configured OTLP metrics, but doesn't have the OTLP exporter on the classpath for the configured exporter, then a periodic metric reader will be registered with a `null` exporter, which causes errors.
=> Do not register periodic metric reader when exporter is null

exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogExporterTest.java, exporters/otlp-http/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterTest.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/logs/LogsRequestMarshalerTest.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterTest.java, exporters/otlp/logs/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyLogExporterTest.java, exporters/otlp/logs/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyShadedLogExporterTest.java, exporters/otlp/logs/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyOkHttpLogExporterTest.java, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogDataAssert.java, sdk/logs-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogData.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogDataBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogDataImpl.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/util/TestUtil.java
The log name has been removed from the [spec](https://github.com/open-telemetry/opentelemetry-specification/pull/2271) and is [being deprecated](https://github.com/open-telemetry/opentelemetry-proto/pull/357) from the proto.
=> Deprecate log name field

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusType.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/MetricAdapterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java
With metrics nearing stability, I think coupling the exporter to the prometheus client library has some risk as it may not make it in time. It's nice to also get some performance by directly serializing given how huge they can be (in particular, lots of arrays allocated for histograms in the adapter code that are eliminated). Many Java apps have a strong correlation between full GC and Prometheus scrapes :) I will move the `Collector` integration into an alpha extension instead so it can be decoupled from a stable release.
This only adds serialization logic, it doesn't use it yet or remove a few smaller usages of the client library that are left which will come in followups. 
Maintenance-wise, given the above benefits, I think 414 LoC of the serializer vs 340 LoC for the MetricAdapter is …
=> Add Prometheus text format serializers.

exporters/prometheus/src/integrationTest/java/io/opentelemetry/exporter/prometheus/AbstractPrometheusIntegrationTest.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusCollector.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusCollectorTest.java
I don't mind extracting this into an extension right away but wonder what people think of just deprecating for this release and see if we get feedback. Yes it's weird to deprecate prometheus with a reference to micrometer integration :) But I think in practice it's much more common to be using micrometer than the prometheus library directly so want to see if it's enough. For reference, unlike `setChannel` with the similar strategy, this module is still alpha.
=> Deprecate PrometheusCollector

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributeAssertion.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/EventDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertions.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertionsTest.java
Fixes #3993 
Played around a bit and came up with this which seems to have good UX. The goals are
1) Can define all assertions with lambdas
2) Can use same method name for all types
3) All entrypoints in one location (OpenTelemetryAssertions)
4) Can mix exact and loose assertions (lower priority)
Took a lot of API to achieve these, especially 2) but I guess we want to prioritize ease of writing assertions and this seems OK but open to any feedback to make it better.
=> Add ability to do loose attribute matching while checking all keys.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java
Looks like accidentally made public, since constructor is private there is almost no way a user could be using this so no need to deprecate. Though anyways this will probably be the release with many non-deprecatable changes to metrics SDK.
=> Make AbstractInstrumentBuilder private.

.github/workflows/docker-test-containers.yml
`docker pull` then `push` causes only the current platform's image to be copied, missing multiarch, e.g. arm64. This isn't a huge deal but it's probably better to make sure the reimaging is multiplatform given it's relatively easy.
https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md
=> Use crane to copy test docker images

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/AggregatorFactory.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/Aggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/DefaultAggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/DropAggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/ExplicitBucketHistogramAggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/LastValueAggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/SumAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/DeltaMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorageTest.java
`Aggregator` is an internal type since we don't support custom aggregations yet, so we can't have a public API method returning it. This internal interface hack is probably the only solution but it should work well.
=> Make createAggregator non-public

exporters/prometheus/build.gradle.kts, exporters/prometheus/src/module/java/io/opentelemetry/exporter/prometheus/HackForJpms.java, exporters/prometheus/src/module/java/module-info.java, exporters/prometheus/src/testJpms/java/io/opentelemetry/exporters/prometheus/test/JpmsTest.java, exporters/prometheus/src/testJpms/java/module-info.java
Fixes #4192
With this adding module-info somewhere, it's probably best to go ahead and add it everywhere, will followup with that afterward. Currently it's only particularly important for prometheus and zpages which are using httpserver.
Tried using javamodularity plugin but don't think it works in toolchains mostly because of an old [TODO](https://github.com/java9-modularity/gradle-modules-plugin/blob/master/src/main/java/org/javamodularity/moduleplugin/extensions/DefaultModularityExtension.java#L74). It's approach of having two java compilation tasks output to the same directory also will probably break build caching. The alternative is a `HackForJpms.java` unfortunately.
When applying to all the projects, I will try out a DSL to define the module in the java file to let it autogenerate …
=> Add module-info to prometheus exporter

api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/internal/W3CTraceContextEncoding.java, api/all/src/main/java/io/opentelemetry/api/trace/propagation/internal/package-info.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanLinkMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/traces/TraceRequestMarshalerTest.java
Includes the trace state in the marshaled spans and span links, resolving the corresponding TODOs in the code.
Adds a static utility method to W3CTraceContextPropagator to serialize a `TraceState` to string (according to the W3C trace context recommendation.
Fixes: #4189
=> Marshal trace state in OTLP exporter

README.md
Fixing a typo in the readme where it states that the `opentelemetry-alpha-bom` dependency should be used for alpha dependencies. Correct would be `opentelemetry-bom-alpha`
=> Fixed minor typo in README regarding the alpha bom reference

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExemplarMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricsRequestMarshalerTest.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/MetricAdapterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/internal/metrics/MetricAdapter.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/internal/metrics/MetricAdapterTest.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ExemplarDataAssert.java, sdk/metrics-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoubleExemplarData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/ExemplarData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/LongExemplarData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/exemplar/AbstractFixedSizeExemplarReservoir.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/AggregatorHandleTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleLastValueAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleSumAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongLastValueAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongSumAggregatorTest.java
I deprecated in this PR but maybe we'll just delete anyways as there will probably be some harder changes coming up. 
- Record SpanContext instead of span / trace ID. Throughout the SDK we conventionally use invalid SpanContext to indicate not traced, and valid one to indicate traced. It seems to work well here, eliminating Nullable, and notably the cross-nullable relationship where either both are null or both are filled.
- Remove getValueAsDouble. We don't have it on e.g. SumData so this doesn't feel symmetric. getValueAsDouble seems to be primarily useful in prometheus conversion but such a utility can just live there. (Another location was the assertion but that should possibly be double / long specific like our other assertions). An alternative is to remove LongExemplarData, we don't …
=> Cleanup ExemplarData

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java
Issue: https://github.com/open-telemetry/opentelemetry-java/issues/4201
The slow test is `diffAccumulation()` which was taking around 10 seconds on my machine. The problem is when the tests are comparing bucket counts between one empty and one non-empty bucket counts. The bucket set that is empty has `indexStart = Integer.MIN_VALUE` so comparing the buckets takes several seconds because it's iterating from such a low value. 
~~I've added the `isEmpty()` check to the beginning of the `sameBucketCounts()` method to fix this.~~
~~However, this brings a problem with `AdaptingCircularBufferArray`. In the case where an `AdaptingCircularBufferArray` has been `diff()`ed back down so it's empty, `isEmpty()` returns false because the index is no longer the null index. As a result I have added the …
=> Fix slow ExponentialHistogram tests 

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/AttributesMap.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/4161
Android desugaring is not smart enough to handle calling `HashMap.forEach` through `Attributes.forEach`. This pr helps out desugaring by adding an explicit call to `HashMap.forEach` that desugaring can rewrite it.
=> Fix android desugaring for HashMap.forEach

sdk-extensions/metric-incubator/src/test/java/io/opentelemetry/sdk/viewconfig/ViewConfigTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/Aggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/AggregationTest.java
As discussed at the SIG, we don't see a way to actually change the histogram that is returned by this method in the future, in which case it currently overlaps with `explicitBucketsHistogram`, and constrains us if we do end up wanting to encourage a different one, such as exponential, as the de-facto.
https://github.com/open-telemetry/opentelemetry-specification/issues/2382
=> Deprecate automatic histogram method for removal.

sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricCustomizer.java, sdk-extensions/metric-incubator/src/main/java/io/opentelemetry/sdk/viewconfig/ViewConfig.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/InstrumentSelectorBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/MeterSelectorBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/ViewBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableDoubleCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableDoubleUpDownCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableLongCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableLongUpDownCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/InstrumentSelectorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/view/MeterSelectorTest.java
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view
- Removes `AttributesProcessor` (internal class) from public API
- Removes regex matching. Spec only specifies wildcard matching, which we can add support for later, I think in the same `setName` method because wildcards are not valid characters in instrument names. Programmatic matching with `Predicate` is left in as it seems generally useful and can be used to implement regex matching if needed anyways
- Uses same method name for string and predicate filters. I think this removes the need of "only one of" type of methods because it's the pattern of overloading a behavior for different input types. If it looks weird to have `.setName(Predicate<String>)`, happy to revert
- Don't …
=> Cleanups to View configuration

CHANGELOG.md
Didn't get a chance to wait for Maven Central propagation for japicmp yet so just sending changelog
=> CHANGELOG for 1.12 release

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceProviderCustomizer.java, sdk-extensions/autoconfigure/src/testFullConfig/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
Add a new configuration: `otel.java.enabled.resource.providers`. 
All resource providers will be enabled if this configuration key is not configured, otherwise only the specific resource providers will be enabled.
If a resource provider is configured in both `otel.java.enabled.resource.providers` and `otel.java.disabled.resource.providers`, then it will be disabled.
close #4220
=> feat: Add enabled resource providers configuration

sdk-extensions/metric-incubator/src/test/java/io/opentelemetry/sdk/viewconfig/ViewConfigTest.java, sdk/metrics/src/debugEnabledTest/java/io/opentelemetry/testing/SourceInfoTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DebugUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ImmutableView.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewBuilderImpl.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/View.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/view/ViewBuilder.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
The primary objective of this PR is to make sure getSourceInfo and getAttributeProcessor are not public (requires `View` to be an interface). A secondary objective is to allow adding experimental options such as baggage in an internal-only way (requires `ViewBuilder` to be an interface).
=> Extract View configuration interface so it only exposes public API.

sdk/common/src/main/java/io/opentelemetry/sdk/common/CompletableResultCode.java
In particular I think this is important for the `CompletableResultCode.SUCCESS` singleton, since you can easily have multiple threads calling `whenComplete()` on it.
See #4282 for an alternative option to this PR.
=> Reduce lock scope in CompletableResultCode.whenComplete()

micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryDistributionSummary.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryMeterRegistry.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryMeterRegistryBuilder.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryTimer.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/PrometheusModeNamingConvention.java, micrometer1-shim/src/test/java/io/opentelemetry/micrometer1shim/PrometheusModeTest.java
This PR copies https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5537 into this repo's micrometer shim.
=> Implement "Prometheus mode" for better micrometer->OTel->Prometheus support

docs/common-github-actions-practices.md
I think I've gone far enough with exploring all the github actions stuff, no need to keep scattering PRs all over the three repos, and time to document the desired state and then sync everything up.
The major change for this repository (and contrib too) would be moving off of nebula and adopting the release branch automation from the instrumentation repository. @anuraaga was receptive to this idea if we implement all of the same release automation across all three repos (and we discussed an additional automation for PR backports, which I documented here but have not implemented anywhere yet).
(and yes, I am volunteering to do this work if/once we establish consensus)
cc @open-telemetry/java-instrumentation-maintainers
=> Common github action practices

docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, exporters/prometheus/src/integrationTest/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/ImmutableHistogramPointData.java
These methods were only used in one place and not essential to the histogram data model.
=> Drop HistogramPointData utility methods

sdk-extensions/metric-incubator/src/test/java/io/opentelemetry/sdk/viewconfig/ViewConfigTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentSelectorBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/InstrumentSelectorTest.java
Per the [view](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view) spec:
> If none the optional criteria is provided, the SDK SHOULD treat it as an error. It is recommended that the SDK implementations fail fast. Please refer to [Error handling in OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md) for the general guidance.
=> Throw exception if view instrument selector selects nothing

.github/workflows/docker-test-containers.yml
While the alpine image is a little smaller, not that much, but it loses out on multiarch (i.e., performance on Apple silicon).﻿
=> Use debian openjdk17 test image

.github/workflows/main-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/release-build.yml
Similar to @iNikem's https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4470:
> Every time I look at the failed build, I have to scroll several screens up to find out the root case. Gradle failure stacktrace is useful when we have a problem within gradle tool itself, which happens very seldom.
Also sent similar PR to contrib: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/277
=> Remove --stacktrace from gradle builds

api/all/src/jmh/java/io/opentelemetry/api/trace/TraceStateBenchmark.java, api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceState.java, api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java, api/all/src/test/java/io/opentelemetry/api/trace/TraceStateTest.java
I had started by just optimizing, but noticed the builder reuse bug while at it - I probably wouldn't have noticed if there wasn't a significant loss in performance for single item after the optimizations which I was investigating.
I have also gone ahead and fixed max entry check here.
After
```
Benchmark                                                                  Mode  Cnt     Score     Error   Units
TraceStateBenchmark.fiveItems                                              avgt   15   228.005 ±  11.950   ns/op
TraceStateBenchmark.fiveItems:·gc.alloc.rate                               avgt   15   536.211 ±  24.653  MB/sec
TraceStateBenchmark.fiveItems:·gc.alloc.rate.norm                          avgt   15   192.009 ±   0.003    B/op …
```
=> Fix tracestate builder reuse, max entry check, and optimize it.

exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricsRequestMarshalerTest.java, exporters/prometheus/src/integrationTest/java/io/opentelemetry/exporter/prometheus/MetricAdapterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/internal/metrics/MetricAdapter.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/HistogramPointDataAssert.java, sdk/metrics-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/HistogramAccumulation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/MetricDataUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/ImmutableHistogramPointData.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/data/ImmutableMetricDataTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleHistogramAggregatorTest.java
Related to #4267.
Figure it would be good to make these part of the metric data model before stabilization. Not strictly necessary to do now because they're optional and could be later added with a default of `null`.
=> Add min and max to HistogramPointData

exporters/otlp-http/metrics/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterTest.java, exporters/otlp-http/trace/src/test/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcRetryTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpRetryTest.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java, sdk-extensions/jaeger-remote-sampler/src/testGrpcNetty/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerGrpcNettyTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterProviderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableInstrumentTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, testing-internal/src/main/java/io/opentelemetry/internal/testing/slf4j/LoggerExtension.java, testing-internal/src/main/java/io/opentelemetry/internal/testing/slf4j/SuppressLogger.java, testing-internal/src/main/resources/simplelogger.properties
Another round of log suppression. I believe that the only remaining logs to standard error are coming from libraries that log to SLF4J, which our `@SuppressLogger` annotation isn't able to suppress. Would be great to get those suppressed as well as they're all the same SSL exceptions that look like:
```
[armeria-common-worker-nio-2-21] WARN com.linecorp.armeria.server.HttpServerPipelineConfigurator - [id: 0xad7721fe, L:/127.0.0.1:55103 ! R:/127.0.0.1:55150] Unexpected exception:
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
```
=> Another round of log suppression

.github/scripts/generate-release-contributors.sh, .github/workflows/release.yml, docs/common-github-actions-practices.md
* heredoc problems in the scripts
* trying to use the release tag before it was made (when calling generate-release-contributors.sh)
* chmod +x for generate-release-contributors.sh
* usage of `$version` instead of `$VERSION` in a couple of places
=> Release workflow fixes

.github/workflows/build-pull-request.yml
Missed this one: https://github.com/open-telemetry/opentelemetry-java/blob/main/docs/common-github-actions-practices.md#configure-cancel-in-progress-on-pull-request-workflows
=> Add github action concurrency control

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-http-metrics.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp-metrics.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, exporters/otlp-http/metrics/gradle.properties, exporters/otlp/all/build.gradle.kts, exporters/otlp/metrics/gradle.properties, sdk-extensions/autoconfigure/build.gradle.kts, sdk/all/build.gradle.kts, sdk/metrics/gradle.properties
- Mark `:sdk:metrics`, `:exporters:otlp:metrics`, and `:exporters:otlp-http:metrics` as stable
- Include `:exporters:otlp:metrics` in `:exporters:otlp:all`
- Include `:sdk:metrics` as api dependency in `:sdk:all`
=> Mark metrics components as stable

.github/scripts/markdown-link-check-with-retry.sh, .github/workflows/reusable-markdown-link-check.yml, docs/common-github-actions-practices.md
It looks like we need this after all: https://github.com/open-telemetry/opentelemetry-java/runs/6033601095?check_suite_focus=true
=> Retry markdown link check on failure

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java, exporters/prometheus/src/testJpms/java/io/opentelemetry/exporters/prometheus/test/JpmsTest.java
This doesn't stop us from exporting two identical time series, filed https://github.com/open-telemetry/opentelemetry-specification/issues/2493 for spec on working on that. This should still help in many cases.
Fixes #4382
=> Ensure prometheus metrics with the same name are serialized as a group.

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtilTest.java, sdk-extensions/autoconfigure/src/testOtlpGrpc/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Remove `otel.exporter.otlp.metrics.temporality`, which is superseded by `otel.exporter.otlp.metrics.temporality.preference`.
=> Remove old option for specifying temporality

.github/workflows/build-pull-request.yml, .github/workflows/build.yml, buildSrc/src/main/kotlin/otel.jacoco-conventions.gradle.kts
Also doesn't set up multiple test Javas in a workflow which is a legacy when we tested all versions in the same job.
=> Run tests with Java 18

api/all/src/main/java/io/opentelemetry/api/internal/ValidationUtil.java, api/all/src/main/java/io/opentelemetry/api/metrics/DefaultMeter.java, api/all/src/test/java/io/opentelemetry/api/internal/ValidationUtilTest.java, api/all/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/IdentityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
Resolves #4378.
I think returning a noop instrument is the least wrong solution:
- Throwing an exception is not in line with API patterns
- If we log a warning but allowed the invalid name to be used, we'd put the burden on exporters to figure out how to handle metrics that break the rules.
- If we log a warning an transform the name to be valid, we'd be making up unspecified rules, and could cause unexpected conflicts with other metrics.
=> Return noop instrument if name is invalid

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/metrics-testing/build.gradle.kts, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AbstractPointDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AssertUtil.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributeAssertion.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoubleGaugeAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoublePointDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ExemplarDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongGaugeAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongPointDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/MetricDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertions.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/TraceAssertionsTest.java
Significant differences from current API
- `hasPointsSatisfying` instead of `points()`. I found the later in practice just needs to be followed with satisfiesExactly and additional `assertThat` so we can save
https://github.com/open-telemetry/opentelemetry-java-contrib/blob/0dd50e3ab7dd48b1422f2368a58c3657f44ab685/jmx-metrics/src/test/java/io/opentelemetry/contrib/jmxmetrics/OtelHelperSynchronousMetricTest.java#L61
would become
```java
assertThat(metric)
.hasPointsSatisfying(point -> point.hasValue(123.456))
```
- `hasDoubleGaugeSatisfying` instead of `hasDoubleGauge()`. In this case, the latter does have some savings in typing. I would like to add it later if desired and initially keep a baseline where assertion methods can be called in any order
- Attributes methods from SpanData …
=> Move gauge assertions into stable testing artifact.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java
For testing agent configures `PeriodicMetricReader` to run with a short interval. Due to this it may log `No metric data to export - skipping export.` multiple times for each test. Decreasing the log level to `FINEST` should keep it out from agent debug logs.
=> Decrease logging level for no metric data exported

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
Fix `BatchSpanProcessor` worker thread is killed by non-runtime exception.
close #4348
=> fix: fix BatchSpanProcessor with non-runtime exception

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java
Revert https://github.com/open-telemetry/opentelemetry-java/pull/4405 as @anuraaga believes it is better to suppress this on the agent side.
=> Revert PeriodicMetricReader logging level change

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoubleSumAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/HistogramAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/HistogramPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongSumAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/MetricDataAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SummaryAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SummaryPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ValueAtQuantileAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java
Didn't migrate exponential histogram yet since it's still internal. Will probably migrate the assertions themselves to internal in the future.
=> Migrate sum, histogram, summary assert to stable testing.

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/data/ExceptionEventData.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/data/ImmutableExceptionEventData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Resolves open-telemetry/opentelemetry-java#4424
=> Apply attribute limits to exception events

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TraceAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/TraceAssertionsTest.java
In some agent test spans don't appear in a fixed order. It would be nice to have a version of `hasSpansSatisfyingExactly` that ignores the oder of the spans.
=> Add hasSpansSatisfyingExactlyInAnyOrder

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AbstractPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoubleGaugeAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoublePointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/DoubleSumAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/HistogramPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongGaugeAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LongSumAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/MetricAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/OpenTelemetryAssertions.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SummaryPointAssert.java
Trace assertions have some mix of `Data` or not on whether there is a corresponding SDK class for it, but this isn't really very helpful. An assertion is an assertion and there's not much need for the word - for metrics we can clean up a bit
=> Remove Data from metric assertion class names

docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, exporters/prometheus/src/integrationTest/java/io/opentelemetry/exporter/prometheus/PrometheusCollector.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/metrics/OpenCensusAttachingMetricReader.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricReader.java, sdk/metrics-testing/src/test/java/io/opentelemetry/sdk/testing/exporter/InMemoryMetricReaderTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReaderTest.java
=> Rename MetricReader#flush() to forceFlush()

micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/Bridging.java, micrometer1-shim/src/test/java/io/opentelemetry/micrometer1shim/FunctionCounterTest.java, micrometer1-shim/src/test/java/io/opentelemetry/micrometer1shim/GaugeTest.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/4381
I added a descriptions cache, only the first description seen will be used, the rest will just get ignored (pretty much the same behavior as `PrometheusMeterRegistry`). I tried to use the `MeterFilter` for that at first, but it turned out `Meter.Id` does not have any method for overriding the description.
=> Solve the duplicate metrics definition issue in Micrometer shim

dependencyManagement/build.gradle.kts, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/HistogramDataPointMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricsRequestMarshalerTest.java, sdk/metrics-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ExponentialHistogramPointDataAssert.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/Aggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExplicitBucketHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DropAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialHistogramAccumulation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/MetricDataUtils.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/exponentialhistogram/ExponentialHistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/exponentialhistogram/ImmutableExponentialHistogramPointData.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExplicitBucketHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBucketsTest.java
- Update to otlp proto 0.17.0
- Add min and max support to exponential histogram aggregation, and exponential histogram point data
- Add otlp min and max serialization support for explicit bucket histograms and exponential histograms
- Remove unused `Aggregator#diff` implementation from explicit bucket histogram and exponential histogram aggregators. This code path is only used when an asynchronous instrument is aggregated in delta temporality, which is not supported for histograms. 
Resolves #4267.
=> Update to otlp proto 0.17.0

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/SdkMeterProviderUtil.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MeterSharedState.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
Adds a testing utility method that allows `SdkMeterProvider` to be reset, which clears all registered instruments and storages. The initially configured resource, views, and readers are left alone. Any calls to record measurements to existing instruments after reset don't do anything, and those resource can be garbage collected as soon as there are no remaining referenced.
Originally discussed in the Java SIG for assisting in testing `opentelemetry-java-instrumentation`, but also necessary for a complete solution in #4459.
=> Add experimental method to reset SdkMeterProvider

sdk-extensions/autoconfigure/README.md
Removed unused property referenced in autoconfigure docs. Referenced in #4448.
=> Drop reference to OTEL_EXPORTER_LOGGING_PREFIX

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/RegisteredReader.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MeterProviderSharedState.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/export/RegisteredReaderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorageTest.java
=> Fix delta intervals

sdk/metrics/README.md
These are really out of date. Also, docs should live on opentelemetry.io, which I've recently updated to include an introduction to [metrics](https://opentelemetry.io/docs/instrumentation/java/manual/#metrics).
=> Drop outdated metrics sdk readme

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java
`otel.metrics.exporter` setting support multiple values. 
close #4195
=> feat: `otel.metrics.exporter` setting support multiple values

exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp-http/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogExporterBuilder.java, exporters/otlp-http/metrics/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/DefaultGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/DefaultGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterUtil.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/OkHttpGrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/OkHttpGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporterBuilder.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryUtilTest.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogExporterBuilder.java, exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/trace/src/jmh/java/io/opentelemetry/exporter/otlp/trace/GrpcExporterBenchmark.java, exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java
`GrpcExporterBuilder` supports to set a custom `MeterProvider`, which is exposed in the [OtlpGrpcSpanExporterBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L140). The `JaegerGrpcSpanExporterBuilder` should have the same functionality.
I could not find a dedicated tests for the `OtlpGrpcSpanExporterBuilder` using a `MeterProvider` implementation beside NOOP. I guess this is part of the underlying `GrpcExporterBuilder`.
=> Add setter for MeterProvider to JaegerGrpcSpanExporterBuilder

dependencyManagement/build.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger.txt
No code changes, but still good to update to latest version which marks logs as stable.
=> Update to proto 0.18.0

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LogEmitterProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
- Implement [attribute limits](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#attribute-limits) from specification
- General attribute length and count limits as well as signal specific (span) limits now apply to span attributes
- General attribute count limits now apply to span events and span links
- General attribute length and count limits now apply to logs
=> Implement general attribute limits

README.md
Change the example of Otel artifacts that require the `-alpha` BOM now that metrics are stable.
Use the examples of the Semantic Conventions constants, the SDK Autoconfigure Extension, and the Logs SDK & exporter.
=> README: Change the example of Otel artifacts that require the `-alpha` Maven BOM now that metrics are stable

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ConfigProperties.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ConfigUtil.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/NullDefaultUtility.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtil.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ConfigPropertiesTest.java
Related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4925
This adds several default-capable get* methods to `ConfigProperties`. This can help to reduce the number of null checks. These defaults are then wired up in several places.
=> Add default getters to ConfigProperties

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
=> Add experimental option to disable autoconfigured opentelemetry SDK

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure-spi.txt, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/MarshalerCollectorServiceGrpc.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/MarshalerMetricsServiceGrpc.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/MarshalerTraceServiceGrpc.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/DefaultGrpcExporterBuilder.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterUtil.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/retry/RetryUtilTest.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/MarshalerLogsServiceGrpc.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
Fixes #4513
OkHttp already allows setting the host header to override host on HTTP/1 or :authority on HTTP/2. For the gRPC codepath we need to propagate it through though.
=> Allow overriding OTLP gRPC authority.

integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java
The OTLP integrations tests are slow because they wait on PeriodicMetricExporter's 5s export interval. There's a bunch of different variations of the test which mean we wait on this 5s export interval many times.
This speeds that up by closing, and triggering a flush.
Also makes the log testing use `SdkLogEmitterProvider` instead of directly calling `LogExporter#export`. This brings logs in line with traces and metrics.
On my machine the OTLP integration tests take 61s before this change, and 7s after. Nice.
=> Speed up OTLP integration tests

sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/internal/aggregator/HistogramAggregationParam.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialBucketStrategy.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ExponentialHistogramAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AggregationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBucketsTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/ExponentialCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ExponentialHistogramAggregationTest.java
- Set default positive and negative buckets to 160 to reflect [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-histogram-aggregation)
- Remove scale as a configurable parameter. to reflect the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-histogram-aggregation). Scale always starts at 20, reduces down to reflect the range of recorded measurements.
- Minimum number of buckets is 1 instead of 0. Configuring buckets to 0 causes exceptions to be thrown at runtime.
=> Tighten up exponential histogram implementation

RELEASING.md
@anuraaga we now 1Password is used to share credentials in opentelemetry. My understanding is that you get setup by talking to @codeboten.
=> Indicate that passwords are stored in 1Password

.github/workflows/stale-pr.yml
As discussed in Java office hours, adding a way to indicate that PRs labeled `prototype` are exempt from stale checker.
=> Prototype PRs are exempt from stale check

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ScopeManagerShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ShimUtil.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/ShimUtilTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanWrapper.java
make the tracing shim compatible with span wrappers, such as https://github.com/zalando/opentracing-toolbox/tree/main/opentracing-proxy
=> opentracing-shim: support span wrappers

exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftIntegrationTest.java
I'm no advocate of jaeger-thrift :P But I figure it's worth understanding what works and doesn't. Specifically, I remember hearing users using this exporter with UDP, even if our intent wasn't to support that.
See #4577
=> Add test for jaeger-thrift over UDP

.github/dependabot.yml
Same as used in java-instrumentation, here's example PRs: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed
=> Dependabot for gradle plugins

api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, api/all/src/test/java/io/opentelemetry/api/internal/ImmutableKeyValuePairsTest.java
Fix ImmutableKeyValuePairs bugs: throw `java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 6` when the testcase is
```
assertThat(new TestPairs(new Object[] {"one", 55, "one", null, "one", 66}).get("one"))
.isEqualTo(66);
```
=> bugfix: fix ImmutableKeyValuePairs bugs

sdk/trace-shaded-deps/src/main/java/io/opentelemetry/sdk/trace/internal/JcTools.java, sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/JcToolsTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
* Remove unnecessary "queue.isEmpty()" check while adding each span to batch list.
* Use MpscArrayQueue drain util method, which handle all cases when queue is empty or size > maxExportBatchSize
* Added a static method "drain" under JcTools with a generic consumer to handle cases for any type of Queue or span. 
* This PR is basically improving testing coverage and minor code-efficiency  for feature added  through https://github.com/open-telemetry/opentelemetry-java/pull/2983  & https://github.com/open-telemetry/opentelemetry-java/pull/3034 
* All existing Unit Test are passing (no regression)
* Added a new test class for JCTool.
-------
> Happy Case:  (Queue with N size containing N item, and maxExportBatchSize = N)  ✅
Step1: Added 10000000 (N) items to both queue.
Step2: Create two …
=> Added a static method "drain" under JcTools with a generic consumer

.github/CODEOWNERS
Saddens me to do this, but apparently it's now an error to leave @anuraaga in there. 😿
=> Remove @anuraaga from CODEOWNERS :(

docs/sdk-configuration.md
There were lingering references to `TracerSdkManagement` and `TraceConfig`, both of which have been gone for a while. After removing the sections that referenced those, it didn't seem like it made much sense to keep the hypothetical mutation example, so I removed it and emphasized the points about problems with sdk mutability.
=> Clean up to sdk docs re: mutability

sdk/common/src/main/java/io/opentelemetry/sdk/internal/AttributesMap.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/AttributesMapTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
The log SDK needs a mutable `Attributes` implementation to avoid excess allocations. Moving `AttributesMap` to `:sdk:common` rather than reimplementing.
=> Move AttributesMap to :sdk:common

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure-spi.txt, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizerProvider.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/Ordered.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ResourceProvider.java, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpiUtil.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/SpiUtilTest.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/FirstCustomizerProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/FirstResourceProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/OrderedSpiTest.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/SecondCustomizerProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/SecondResourceProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/ThirdCustomizerProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/ThirdResourceProvider.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
Resolves #4555
I copied the javaagent's [`Ordered`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/extension/Ordered.java) interface into the autoconfigure-spi module; in the future we'll remove the agent one and use the SDK `Ordered` uniformly across all SPIs.
=> Add ordering to autoconfigure SPIs

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/auth/Authenticator.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporterBuilder.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/auth/AuthenticatingExporterTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/auth/AuthenticatorTest.java
Support simple authentication protocols on OTLP HTTP exporters as discussed in, https://github.com/open-telemetry/opentelemetry-java/issues/4590
=> Simple OTLP HTTP authentication - otel internal api

integration-tests/otlp/src/main/resources/otel-config.yaml
The build has consistently failing lately on ubuntu. See [here](https://github.com/open-telemetry/opentelemetry-java/runs/7584652594?check_suite_focus=true) and [here](https://github.com/open-telemetry/opentelemetry-java/runs/7584652594?check_suite_focus=true) for examples.
I was able to reproduce it locally, but only after I pulled down the `ghcr.io/open-telemetry/opentelemetry-java/otel-collector` image used in the integration test, and found messages like this in the collector logs:
```
2022-08-01T21:06:02.015Z	error	exporterhelper/queued_retry.go:183	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "otlp", "error": "Permanent error: rpc error: code = Internal desc = com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer: Can't decode …
```
=> Disable compression in collector exporter

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts
Adds a check for API change source compatibility. Could prevent issues like #4639
I couldn't find documentation on it though except [corresponding test](https://github.com/siom79/japicmp/blob/ec933f5bb5d6ee3d3a343a75d1aef03106add8c5/japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java#L986).
Tried it by adding a new method to a public interface. Without this change build passes, with this change it fails.
=> jApiCmp: check if source is compatible 

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterUtil.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
Fix some small mispellings where OTLP should be OTEL in these strings
in log messages that are emitted when gRPC unimplemented responses are
received when exporting:
- OTLP_TRACES_EXPORTER -> OTEL_TRACES_EXPORTER
- OTLP_METRICS_EXPORTER -> OTEL_METRICS_EXPORTER
- OTLP_LOGS_EXPORTER -> OTEL_LOGS_EXPORTER
This will match the environement variables listed here:
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
=> Fix misspellings in log message envvar suggestions

api/all/src/main/java/io/opentelemetry/api/internal/ValidationUtil.java
Constructing an `AssertionError` is rather expensive, and pointless in
cases that we're not even going to log it. With this commit we skip all
this unnecessary work.
Relates https://github.com/elastic/elasticsearch/issues/89107
=> Avoid unnecessary stack trace capture

README.md, docs/apidiffs/current_vs_latest/opentelemetry-extension-annotations.txt, exporters/jaeger-proto/README.md, extensions/annotations/README.md, extensions/annotations/src/main/java/io/opentelemetry/extension/annotations/SpanAttribute.java, extensions/annotations/src/main/java/io/opentelemetry/extension/annotations/WithSpan.java, extensions/annotations/src/test/java/io/opentelemetry/extension/annotations/WithSpanUsageExamples.java
As discussed in this PR #4260 [comment](https://github.com/open-telemetry/opentelemetry-java/pull/4260#issuecomment-1159292041), we want to move `:extensions:annoations` to `opentelemetry-java-instrumentation` so it can live along side its primary implementation in the java agent. 
The work to move has been completed in [#6245](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6245). This is a followup to indicate that the `:extensions:annotations` is deprecated. We'll continue to publish until 2.0.0 but will not make future changes. 
cc @trask
=> Mark :extensions:annotations as deprecated

micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryCounter.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryFunctionCounter.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryFunctionTimer.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryGauge.java, micrometer1-shim/src/main/java/io/opentelemetry/micrometer1shim/OpenTelemetryMeter.java
=> Remove duplicate and unnecessary code in micrometer1shim

docs/apidiffs/current_vs_latest/opentelemetry-exporter-zipkin.txt, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/LocalInetAddressSupplier.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformer.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformerTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinTestSpan.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinTestUtil.java
This factors out a new class called `OtelToZipkinSpanTransformer` to improve the single responsibility of the `ZipkinSpanExporter`. Before this change, the exporter was both a transformer and an exporter.
For context -- This need arose from a request to filter the local IP address from exported Spans in Splunk's Android SDK. Currently, the `ZipkinExporter` really only made that possible by filtering at the encoder, rather than the data model itself. That felt clunky, and this change helps to improve that by allowing a the transformer to be injected into the exporter, and transformer is the unit that is IP aware (and can be created without one).
Should be API backwards compatible, but please keep me honest.
Related: It occurred to me that the current implementation (even with this PR …
=> Improve single responsibility of ZipkinSpanExporter.

sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java
We can return early when the `EMPTY` resource instance is passed to merge in order to shave a few allocations/checks.
=> Return early if merging empty resource

sdk/logs/build.gradle.kts
This property controls the `Automatic-Module-Name` field in the jar manifest, and the location of the `version.properties` file. It is currently wrong for the log SDK artifact.
=> Fix log sdk module name

sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/EcsResource.java, sdk-extensions/aws/src/test/java/io/opentelemetry/sdk/extension/aws/resource/EcsResourceTest.java, sdk-extensions/aws/src/test/resources/ecs-container-metadata-v3.json, sdk-extensions/aws/src/test/resources/ecs-container-metadata-v4.json, sdk-extensions/aws/src/test/resources/ecs-task-metadata-v3.json, sdk-extensions/aws/src/test/resources/ecs-task-metadata-v4.json
This improves the detection of resource attributes on ECS by fetching ECS metadata from `ECS_CONTAINER_METADATA_URI` or `ECS_CONTAINER_METADATA_URI_V4`.
Previously only `CONTAINER_NAME` and `CONTAINER_ID` id were set.
Now we set:
- CONTAINER_ID
- CONTAINER_NAME
- AWS_ECS_CONTAINER_ARN
- CONTAINER_IMAGE_NAME
- CONTAINER_IMAGE_TAG
- aws.ecs.container.image.id
- AWS_LOG_GROUP_ARNS
- AWS_LOG_GROUP_NAMES
- AWS_LOG_STREAM_NAMES
- AWS_ECS_TASK_ARN
- AWS_ECS_TASK_FAMILY
- AWS_ECS_TASK_REVISION
Especially `AWS_LOG_GROUP_ARNS` is important so that connection of traces to logs works OOTB on X-Ray.
=> Improve detection of resource attributes on ECS

sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ContainerResource.java, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ContainerResourceTest.java
PR for [issue#4730](https://github.com/open-telemetry/opentelemetry-java/issues/4730).
Since k8s v1.24+, dockerShim is removed, and you can check the method of containerd generating CGroup path [here](https://github.com/containerd/containerd/blob/bbe46b8c43fc2febe316775bc2d4b9d697bbf05c/pkg/cri/server/helpers_linux.go#L63). before containerd v1.5.0, generating CGroup path method with systemd look [this](https://github.com/containerd/containerd/blob/release/1.4/cmd/ctr/commands/run/run_unix.go#L254).
If the cgroupDriver is `systemd` and the container is `cri-contrainerd v1.6.8`, the cgroup line like:
'11:devices:/system.slice/containerd.service/kubepods-pod87a18a64_b74a_454a_b10b_a4a36059d0a3.slice:cri-containerd:05c48c82caff3be3d7f1e896981dd410e81487538936914f32b624d168de9db0'.
If the …
=> Fix container detection fails in k8s with containerd v1.5.0+ environments

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/ConditionalResourceProvider.java, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/java/io/opentelemetry/sdk/autoconfigure/ConditionalResourceProviderTest.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/java/io/opentelemetry/sdk/autoconfigure/FirstResourceProvider.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/java/io/opentelemetry/sdk/autoconfigure/SecondResourceProvider.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
Alternative implementation of #4718; we talked about this in yesterday's SIG meeting.
If this looks okay to you, I'll add some tests and mark it as ready for review.
=> Add experimental ConditionalResourceProvider interface

CHANGELOG.md, docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger-proto.txt, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationScopeInfo.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributesAssert.java
=> Changelog 1.18.0

README.md
@mateuszrzeszutek and @trask have been providing very helpful reviews for a while now, and as maintainers of `opentelemetry-java-instrumentation` are probably the biggest users of this repository. 
Your feedback / contributions are much appreciated!
=> Add @trask and @mateuszrzeszutek as approvers

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/logs/LogsRequestMarshalerTest.java, sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogDataAssert.java, sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/logs/TestLogData.java, sdk/logs-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogData.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkReadWriteLogRecord.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogData.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogEmitterTest.java
Allows the [dropped_attributes_count](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L157) field to be populated when exporting logs over OTLP.
=> Implement dropped attribute count in logs

.github/workflows/build.yml
Noticed the job name was showing up as " (skipped)" on `main` even though it wasn't really
=> Fix skipped name

CONTRIBUTING.md
Codifies discussions in #4661.
=> Define project scope

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/Propagation.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ScopeManagerShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
`Baggage` without a valid `Span` should still be properly propagated in inter-process and in-process operations.
This is part of the [OT compatibility section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md) - essentially, the changes are:
1) [ActiveSpan()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#get-the-active-span): 
> If the current OpenTelemetry Span's SpanContext is invalid but the current Baggage is not empty, this operation MUST return a new Span Shim containing a no-op OpenTelemetry Span and the non-empty Baggage.
2) [Tracer.Extract()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentra …
=> [OT Shim] Fully support Baggage-only propagation.

api/logs/src/main/java/io/opentelemetry/api/logs/DefaultLogger.java, api/logs/src/main/java/io/opentelemetry/api/logs/DefaultLoggerProvider.java, api/logs/src/main/java/io/opentelemetry/api/logs/EventBuilder.java, api/logs/src/main/java/io/opentelemetry/api/logs/Logger.java, api/logs/src/main/java/io/opentelemetry/api/logs/LoggerBuilder.java, api/logs/src/main/java/io/opentelemetry/api/logs/LoggerProvider.java, api/logs/src/test/java/io/opentelemetry/api/logs/DefaultLoggerProviderTest.java, api/logs/src/test/java/io/opentelemetry/api/logs/DefaultLoggerTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogger.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLoggerBuilder.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerTest.java
=> Add event API

sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ProcessResource.java, sdk-extensions/resources/src/test/java/io/opentelemetry/sdk/extension/resources/ProcessResourceTest.java
Synching fix in [opentelemetry-java-instrumentation PR #6716](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6716).
=> Fix ProcessResource directory separator

api/logs/src/test/java/io/opentelemetry/api/logs/DefaultLoggerProviderTest.java, api/logs/src/test/java/io/opentelemetry/api/logs/DefaultLoggerTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerTest.java
I introduced some new tests in a recent PR that create noisy expected logs. This suppresses them.
=> Suppress logs in logger tests

bom-alpha/build.gradle.kts
Resolves #4747.
The resulting pom artifact looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>io.opentelemetry</groupId>
<artifactId>opentelemetry-bom-alpha</artifactId>
<version>1.19.0-alpha-SNAPSHOT</version>
<packaging>pom</packaging>
<name>OpenTelemetry Java</name>
<description>OpenTelemetry Bill of Materials (Alpha)</description>
<url>https://github.com/open-telemetry/opentelemetry-java</url>
<licenses>
<license>
<name>The Apache License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
</license> …
```
=> Make opentelemetry-bom-alpha depend on opentelemetry-bom

CHANGELOG.md, sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
This provides support to the new `otel.sdk.disabled=false` system property recently added to the OTel specification here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration
=> Add support for new system property otel.sdk.disabled

api/logs/src/main/java/io/opentelemetry/api/logs/GlobalLoggerProvider.java, api/logs/src/test/java/io/opentelemetry/api/logs/GlobalLoggerProviderTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testInitializeRegistersGlobal/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java
Like GlobalOpenTelemetry, opentelemetry-java-instrumentation's log appender API includes logic to ensure that the logger provider is set only once. (See code [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-appender-api-internal/src/main/java/io/opentelemetry/instrumentation/api/appender/internal/LogEmitterProviderHolder.java)). This PR brings that logic to `GlobalLoggerProvider`.
=> Ensure GlobalLoggerProvider is set once

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialHistogramIndexer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/exponentialhistogram/ExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/exponentialhistogram/ExponentialHistogramPointData.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBucketsTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialHistogramIndexerTest.java
Implements spec PR [#2633](https://github.com/open-telemetry/opentelemetry-specification/pull/2633).
Resolves #4698.
=> Lower exclusive exponential histogram bounds

sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcRetryTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpRetryTest.java
I think this can help with #4624. 
It's a little delicate here, but in the case of a "bad" error code that we don't expect a retry for, we try and verify that it both failed and that the attempt was just 1. In the flaky example run linked in #4624, the attempt count was 0, which strongly suggests a race condition. That is, I think we were checking the count before the operation has completed.
I think what happened is that the `.isSuccess()` call fails both when the underlying call fails but also when the call has not completed. By putting an explicit `.isDone()` check after the `.join()` we can then tell if/when this happens again and then bump up the wait time. I suspect we just hit a cloud glitch and got stalled/lags, as happens sometimes. With this change, we should know.
=> Ensure done before checking success to help troubleshoot timeout issues

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java
Implements [spec PR #2785](https://github.com/open-telemetry/opentelemetry-specification/pull/2785).
=> Add support for BatchLogRecordProcessor autoconfiguration

.github/workflows/backport.yml, .github/workflows/prepare-patch-release.yml, .github/workflows/prepare-release-branch.yml, .github/workflows/release.yml
similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6862
@jack-berg it may be worth comparing this repo's branch protections against https://github.com/open-telemetry/opentelemetry-java-contrib/settings/branches
=> Update bot branch names

buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
Related change - https://github.com/open-telemetry/opentelemetry-specification/commit/0b45213858e23aedb6f6de5fab17d2843a9f24c5
=> Added info what are the new semantic attributes to be used

api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/all/src/main/java/io/opentelemetry/api/internal/PercentEscaper.java, api/all/src/test/java/io/opentelemetry/api/baggage/propagation/PercentEscaperFuzzTest.java, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationFuzzTest.java
=> Decode resource attributes specified via otel.resource.attributes

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/OtlpUserAgent.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/OtlpUserAgentTest.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java
Implements spec [PR #2684](https://github.com/open-telemetry/opentelemetry-specification/pull/2684).
=> Add User-Agent header to OTLP exporter requests

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java
Partially resolves: #4829
I have added a `toString` method to the abstract class to make it available for every implementation of the AbstractInstrument. I believe the better way would be adding toString method to each the subclasses, but I would appreciate a piece of advice here.
Sample toString for the SdkDoubleHistogram is:
```
SdkDoubleHistogram{descriptor=InstrumentDescriptor{name=testHistogram, description=, unit=, type=HISTOGRAM, valueType=DOUBLE}}
```
=> Add toString method to AbstractInstrument

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExplicitBucketHistogramUtils.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterProviderTest.java
=> Add zero bucket boundary to default explicit bucket histogram

sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSampler.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSamplerTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSamplerTest.java
=> Make description of Samplers Locale independent

docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger.txt, docs/apidiffs/current_vs_latest/opentelemetry-exporter-zipkin.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporterBuilder.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilderTest.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporterBuilderTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/TelemetryExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
The `GrpcExporterBuilder` enables compression when `none` is configured.
The `OkHttpExporterBuilder` has no way to disable compression via `none` once it's set (which seems wrong for a mutable builder).
The `JaegerGrpcSpanExporterBuilder` and `ZipkinSpanExporterBuilder` have no configuration for compression at all.
* Fix handling of compressionMethod `none` in `GrpcExporterBuilder`
* Fix handling of compressionMethod `none` in `OkHttpExporterBuilder`
* Add compression configuration to `JaegerGrpcSpanExporterBuilder`
* Add compression configuration to `ZipkinSpanExporterBuilder`
**Note**: All exporters except `ZipkinSpanExporterBuilder` default to compression disabled. In Zipkin the internally used `HttpSender.Builder` has `compressionEnabled = true`. This behavior was not changed, so the …
=> Unify compression configuration for exporters

sdk/logs/build.gradle.kts, sdk/logs/src/jmh/java/io/opentelemetry/sdk/logs/LogsBenchmarks.java
The typical usage for logs presents the opportunity for hotspots that don't exist in traces or metrics. 
The main use case we want to support is writing log appenders, which bridge other log APIs / frameworks into opentelemetry. Its very typical for these frameworks to have the notion of named loggers, which maps nicely to OpenTelemetry instrumentation scope name. However, this requires that appender implementations obtain a `Logger` instance for each log record processed. [Here's](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.17/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/OpenTelemetryAppender.java#L143-L144) an example. Its not typical to obtain a new tracer or meter for each span / …
=> Add benchmark for log sdk

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/OpenTracingShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/OpenTracingShimTest.java
This matches the expected name from the [related Spec section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#create-an-opentracing-tracer-shim).
=> OT Shim: Use 'opentracing-shim' as instrumentation scope name.

sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/ComponentRegistryTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLoggerBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLoggerProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerBuilder.java
Followup to #4891.
Reduces allocations on happy path by avoiding creation of extra `InstrumentationScopeInfo` / `InstrumentationScopeInfoBuilder` instances that aren't strictly needed. Does this by adjusting changing `ComponentRegistry#get(InstrumentationScopeInfo)` to `ComponentRegistry#get(String name, @Nullable String version, @Nullable String schemaUrl, Attributes attributes)`, and only building `InstrumentationScopeInfo` the first time we see a component with a particular identity. 
Benchmark before:
```
Benchmark                                                  Mode  Cnt     Score     Error   Units
LogsBenchmarks.emitSimpleLog                               avgt   10    35.035 ±   0.732   ns/op
LogsBenchmarks.emitSimpleLog:·gc.alloc.rate                avgt   10  2173.006 ±  43.649 …
```
=> Optimize log hot path

sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/MultiLogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/NoopLogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLoggerProviderBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessor.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/MultiLogRecordProcessorTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/NoopLogRecordProcessorTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerProviderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessorTest.java
Alternative to #4888 which adds context as an argument to processor. This allows context to be garbage collected sooner than with #4888 as described [here](https://github.com/open-telemetry/opentelemetry-java/pull/4888#discussion_r1005948699). 
Resolves #4147.
=> Add context argument to LogRecordProcessor#onEmit

opentracing-shim/build.gradle.kts, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java
This includes:
* The Baggage union of ALL parents is used.
* All parents are added as Links, in order to preserve the OpenTracing reference type as an attribute (either CHILD_OF or FOLLOWS_FROM).
Fixes #4906 
Fixes #4907
=> OpenTracing Shim: Full multiple parent support.

sdk-extensions/incubator/README.md, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/zpages/ZPageServer.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/zpages/ZPageServerTest.java
This addresses #1414.
I tried it with two instances and it seemed to work fine. I also included some simple manual span creation in the example for people to test with easily.
=> De-singleton ZPageServer implementation

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SummaryPointAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ValueAtQuantileAssert.java
`SummaryPointData` and `ValueAtQuantile` are _not_ deprecated.
=> Fix misleading javadoc

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java
Fixes #4908 
This happens via:
* SpanBuilder.withTag()
* Span.setTag()
=> OpenTracing Shim: Handle unsupported types when setting Attributes.

sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/ComponentRegistryTest.java
Noticed this bug today working on something else.
=> Fix concurrent modification exception in ComponentRegistry

.github/workflows/build.yml
Failure example [here](https://github.com/open-telemetry/opentelemetry-java/actions/runs/3472564107/jobs/5803557611).
=> Disable jApiCmp diff check on release branches

.github/workflows/build.yml
Additional change needed to skip japicmp on release branches.
=> Disable japicmp when base_ref is release

.github/workflows/build.yml
Ran into this recently in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7046 where it didn't catch that I hadn't committed an api diff file
=> Update apidiff to check newly created files too

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/EventDataToAnnotation.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformer.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/EventDataToAnnotationTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinTestUtil.java
=> Zipkin exporter: Serialize EventData attributes as JSON

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanBuilderShimTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/SpanShimTest.java
=> OpenTracing Shim: Properly set the status based on the error tag.

exporters/logging/build.gradle.kts, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/LoggingLogRecordExporterProvider.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/LoggingMetricExporterProvider.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/LoggingSpanExporterProvider.java, exporters/logging/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.logs.ConfigurableLogRecordExporterProvider, exporters/logging/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.metrics.ConfigurableMetricExporterProvider, exporters/logging/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogRecordExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java
Related to #4949.
Implements `Configurable{Signal}ExporterProvider` SPIs for the exporters that live in `:exporters:logging`.
=> Implement logging exporter providers

exporters/zipkin/build.gradle.kts, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/internal/ZipkinSpanExporterProvider.java, exporters/zipkin/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java
=> Implement zipkin exporter provider

exporters/zipkin/README.md
=> Fix out of date zipkin exporter docs

exporters/logging-otlp/build.gradle.kts, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/LoggingLogRecordExporterProvider.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/LoggingMetricExporterProvider.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/LoggingSpanExporterProvider.java, exporters/logging-otlp/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.logs.ConfigurableLogRecordExporterProvider, exporters/logging-otlp/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.metrics.ConfigurableMetricExporterProvider, exporters/logging-otlp/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogRecordExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java
=> Implement logging-otlp exporter providers

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/DefaultConfigProperties.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LogRecordExporterConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ConfigPropertiesTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LogRecordExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationFuzzTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/SpiUtilTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableLogRecordExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSamplerTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/OtlpConfigUtilTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java, sdk-extensions/autoconfigure/src/testLoggingOtlp/java/io/opentelemetry/sdk/autoconfigure/LoggingOtlpTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcConfigTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpGrpcRetryTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java, sdk-extensions/autoconfigure/src/testOtlp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpRetryTest.java
Related to #4949.
As SPI implementations are added in various modules, the test code should follow, which requires some implementation of the `ConfigProperties` interface.
This PR moves `DefaultConfigProperties` to an internal package of `:sdk-extensions:autoconfigure-spi`. This gives implementers of SPIs (including us) a nice test utility, so long as they're willing to accept that the APIs may change.
=> Move DefaultConfigProperties to autoconfigure-spi

.github/dependabot.yml
We've intentionally pinned a specific version as discussed [here](https://github.com/open-telemetry/opentelemetry-java/pull/4787#discussion_r981317670).
=> Ignore dependabot updates to kotlinx-coroutines-core

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ScopeManagerShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/ShimUtil.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/ShimUtilTest.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
=> OpenTracing Shim: Log invalid arguments instead of throwing exceptions.

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java
Currently an extra copy of exponential histogram buckets is made during collection, which causes extra memory allocation when temporality is cumulative.
This PR addresses it by mutating the buckets instead of operating on a copy.
Here's the the `HistogramCollectBenchmark` before:
```
Benchmark                                                                      (aggregationGenerator)  (aggregationTemporality)  Mode  Cnt           Score           Error   Units
HistogramCollectBenchmark.recordAndCollect                               EXPONENTIAL_BUCKET_HISTOGRAM                     DELTA    ss    5  9507808383.600 ± 160312845.363   ns/op
HistogramCollectBenchmark.recordAndCollect:·gc.alloc.rate                EXPONENTIAL_BUCKET_HISTOGRAM                     DELTA    ss    5           3.493 ± …
```
=> Stop extra copy of exponential histogram buckets

exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricsRequestMarshalerTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialBucketStrategy.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialHistogramAccumulation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/exponentialhistogram/ExponentialHistogramBuckets.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExponentialHistogramAggregatorTest.java
Exponential histograms separately track bucket counts in the negative and positive range. Currently, histograms are not permitted to record negative measurements, yet we allocate memory to negative buckets anyway. The exponential histogram aggregation logic works with negative measurements in anticipation of them being permitted in the future, but even when they are permitted, many instruments will only record positive values. 
This PR adjusts the exponential histogram aggregation to lazily instantiate both positive and negative buckets.
Here are the results of the `HistogramCollectBenchmark` before:
```
Benchmark                                                                          (aggregationGenerator)  (aggregationTemporality)  Mode  Cnt           Score           Error   Units …
```
=> Lazily initialize exponential histogram buckets

api/all/src/main/java/io/opentelemetry/api/metrics/MeterBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/TracerBuilder.java, api/logs/src/main/java/io/opentelemetry/api/logs/LoggerBuilder.java
#4711 was closed because we haven't had demand for scope attributes yet, but it included some useful javadoc clarifications in LoggerBuilder, MeterBuilder, and TracerBuilder that I think are worth retaining.
=> Update LoggerBuilder, MeterBuilder, TracerBuilder javadoc

exporters/jaeger/build.gradle.kts, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/internal/JaegerGrpcSpanExporterProvider.java, exporters/jaeger/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/NotOnClasspathTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfigurationTest.java
Related to #4949.
Depends on #4993 since the existing jaeger exporter configuration configures `JaegerSpanExporterBuilder#setMeterProvider`.
=> Implement jaeger exporter provider

api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java, api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java, api/all/src/test/java/io/opentelemetry/api/internal/ConfigUtilTest.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/CodedOutputStream.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/debug/DebugConfig.java
There are a few places where we read from system properties. This adjusts those to use ConfigUtil so that property names normalization occurs in a standard way.
=> Use ConfigUtil internally

README.md
Allows easy navigation to the slack channel.
=> Added slack link in readme for #otel-java

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusType.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java
=> Drop delta metrics in prometheus exporter

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfigurationTest.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/internal/aggregator/HistogramCollectBenchmark.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/AlwaysOffFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/AlwaysOnFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/ExemplarFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/TraceBasedExemplarFilter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/exemplar/ExemplarFilterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/TemporalMetricStorageTest.java
=> Align exemplar filter names with spec

CHANGELOG.md, context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java, context/src/test/java/io/opentelemetry/context/ContextTest.java
=> Make closing scope idempotent and noop when different context is active

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongGaugeBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkObservableInstrument.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/CallbackRegistration.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableInstrumentTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/CallbackRegistrationTest.java
Resolves #5013.
The sample code I posted [here](https://github.com/open-telemetry/opentelemetry-java/issues/5013#issuecomment-1339733154) now prints:
```
io.opentelemetry.sdk.metrics.SdkMeterProvider: SdkMeterProvider{clock=SystemClock{}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.22.0-SNAPSHOT"}}, metricReaders=[InMemoryMetricReader{aggregationTemporality=CUMULATIVE}], views=[]}
io.opentelemetry.sdk.metrics.SdkMeter: SdkMeter{instrumentationScopeInfo=InstrumentationScopeInfo{name=meter, version=null, schemaUrl=null, attributes={}}}
io.opentelemetry.sdk.metrics.SdkLongCounter$SdkLongCounterBuilder: SdkLongCounterBuilder{instrumentDescriptor=InstrumentDescripto …
```
=> Add toString to SdkMeter, SdkObservableInstrument, AbstractInstrumentBuilder

.github/repository-settings.md
**EDIT**: Adds `.github/repository-settings.md` documenting differences in repository setting from those specified in the [community repo](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branches). Documenting these differences is [required](https://github.com/open-telemetry/community/blame/main/docs/how-to-configure-new-repository.md#L43-L47).
cc @trask
=> Add repository settings

.github/workflows/release.yml
This PR updates the usage of set-output command in GH actions.
Reference : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
ChangeLog entry is not required
=> chore(GHA): Update the usage of set-output command in GH actions

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/OtlpUserAgent.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/OtlpUserAgentTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java
Apparently spaces aren't allowable characters in the `<product>` portion of the `User-Agent`. See [opentelemetry-specification#3052](https://github.com/open-telemetry/opentelemetry-specification/pull/3052).
=> Replace OTLP User-Agent spaces with dashes

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/module/java/module-info.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java
=> PrometheusHttpServer drops metrics with same name and different type

docs/apidiffs/current_vs_latest/opentelemetry-sdk.txt, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java
=> Add shutdown / close to OpenTelemetrySdk

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/TracesAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/TracesAssertTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
- sort spans by start time (parents before children as tiebreaker) to avoid common causes for flaky tests
=> improve span order

buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReaderTest.java
Working #5090 and noticed that `MetricReader` didn't implement `Closeable`. 
Adjusted `MetricReader` to extend `Closeable`, and added a default implementation so the change is backwards compatible. Ran into some issues where japicmp was flagging a false positive that the change was breaking. Ended up needing to dive deeper into the japicmp gradle plugin than I wanted to to discover the source of the bug, but along the way found some better ways to organize our config which make it easier to comprehend.
=> Add close method to MetricReader

exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcNettyMetricExporterTest.java, exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettySpanExporterTest.java, exporters/otlp/all/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcNettyShadedMetricExporterTest.java, exporters/otlp/all/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettyShadedSpanExporterTest.java, exporters/otlp/all/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcOkHttpMetricExporterTest.java, exporters/otlp/all/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcOkHttpSpanExporterTest.java, exporters/otlp/logs/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyLogRecordExporterTest.java, exporters/otlp/logs/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyShadedLogRecordExporterTest.java, exporters/otlp/logs/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyOkHttpLogRecordExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
The build output is full of ugly stack traces that start look like the following:
```
[Test worker] ERROR io.grpc.internal.ManagedChannelOrphanWrapper - *~*~*~ Previous channel ManagedChannelImpl{logId=95, target=127.0.0.1:49651} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:100)
```
I've been ignoring this for a while thinking that it wasn't easily solved, but took a closer look today and noticed that the stack trace actually points to the site where a `ManagedChannel` was initialized and never shutdown. Went through offending tests and …
=> Shutdown ManagedChannel resources in tests

exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/OkHttpGrpcExporter.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/UpstreamGrpcExporter.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporter.java, exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporter.java, exporters/jaeger-thrift/src/test/java/io/opentelemetry/exporter/jaeger/thrift/JaegerThriftSpanExporterTest.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogRecordExporter.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporter.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporter.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogRecordExporterTest.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporterTest.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporterTest.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingMetricExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/SystemOutLogRecordExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingMetricExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/LoggingSpanExporterTest.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/SystemOutLogRecordExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
Add proper shutdown implementation to all the exporters:
- Shutting down multiple times logs a warning
- Calling export after shutdown returns `CompletableResultCode.ofFailure()` and skips export
=> Add proper shutdown implementations for all exporters

.github/dependabot.yml, dependencyManagement/build.gradle.kts
#5128 build is failing because mockito 5 requires java 11 support. If we want to include it in our build, we could require java 11+ to run tests, but the simplest approach is to pin the version to mockito 4.x.x.
=> Ignore updates to mockito 5

exporters/jaeger/build.gradle.kts, exporters/otlp/common/build.gradle.kts, sdk-extensions/jaeger-remote-sampler/build.gradle.kts
Gets rid of gradle warnings about implicit dependencies:
> Task :exporters:jaeger:sourcesJar
Execution optimizations have been disabled for task ':exporters:jaeger:sourcesJar' to ensure correctness due to the following reasons:
Gradle detected a problem with the following location: '/Users/jberg/code/open-telemetry/opentelemetry-java/exporters/jaeger/build/generated/source/wire'. Reason: Task ':exporters:jaeger:sourcesJar' uses this output of task ':exporters:jaeger:generateMainProtos' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a …
=> Make implicit gradle dependencies explicit

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
Note: this is the first time in a while where we have keys that have changed, but the names of the attributes have not. We don't have a way to deal with this particular change to make it non-breaking for people who might be using them. 
Also, I think I caught all the deprecated items, but if I missed some, please call them out!
=> Update the semantic conventions to v1.17.0

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfigurationTest.java
=> support the "none" option for propagator configuration

sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
Close OpenTelemetrySdk in OpenTelemetryExtension after all tests
=> Close OpenTelemetrySdk after all tests

sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java
This PR enables support for `parentbased_jaeger_remote` sampler that is documented in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration) but cannot be instantiated.
=> Support parentbased_jaeger_remote sampler.

.github/dependabot.yml
junit-pioneer 2.0 requires Java 11
=> Limit junit-pioneer to 1.x

sdk-extensions/autoconfigure/README.md
As we can see in https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L45 and also in https://github.com/open-telemetry/opentelemetry-java/issues/3240, the name of the enable/disable resource providers ends with `resource.providers`, not `resource-providers`.
=> docs(readme): fix resource providers property docs

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java
After recent changes, cumulative aggregations now use the same `AggregationHandle` over the course of their life, resulting in lower allocation than delta, which issue new `AggregationHandle` instances after each collect. This isn't necessary - after collecting and reseting, the `AggregationHandles` are back to their initial state and can be reused. 
The result is a >50% memory allocation reduction for delta instruments. Pretty slick for just a handful of lines of code!
Performance benchmarks before:
```
Benchmark                                                                            (aggregationGenerator)  (aggregationTemporality)  Mode  Cnt           Score            Error   Units
HistogramCollectBenchmark.recordAndCollect …
```
=> Reuse aggregation handles for delta temporality

sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfigTest.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExponentialHistogramIndexerBenchmark.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/internal/aggregator/HistogramAggregationParam.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/Aggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/Base2ExponentialHistogramIndexer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleBase2ExponentialHistogramAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleBase2ExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/Base2ExponentialHistogramAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AggregationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/Base2ExponentialHistogramIndexerTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleBase2ExponentialHistogramAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleBase2ExponentialHistogramBucketsTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/Base2ExponentialHistogramAggregationTest.java
Followup to [#5143](https://github.com/open-telemetry/opentelemetry-java/pull/5143#discussion_r1083306340).
=> Add Base2 prefix to internal exponential histogram classes

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AttributeAssertion.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/MetricAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/ResourceAssert.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/SpanDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/TraceAssertionsTest.java
The `SpanDataAssert` and `MetricAssert` classes are missing convenient methods to assert resource attributes. The provided `hasResource()` quickly reaches its limits when the captured `Resource` is populated with (system dependent) autoconfigured values (e.g. host resources).
This PR adds a `ResourceAssert` class with methods to assert the resource schema URL and the resource attributes, copying the already established assertion methods from the span attributes.
See also https://cloud-native.slack.com/archives/C014L2KCTE3/p1675083869242799
=> Add resource assertion methods to SpanDataAssert and MetricAssert

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java
@jkwatson PTAL - would be good to get this late addition in before the release. Not too many changes with this update, luckily.
=> Update semconv to 1.18.0

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
this should fix https://github.com/open-telemetry/opentelemetry-java/actions/runs/4130211540/jobs/7136668009
=> Suppress spotless configuration in cve check

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/FixedSizeExemplarReservoir.java
This change is part of the #5178 but can be considered separately. 
I noticed that a decent amount of allocations happen in exemplar classes even when exemplars are disabled. The culprit is that we when collecting, we allocate a `new ArrayList<>()` even when a reservoir has received no measurements. 
Performance before:
```
Benchmark                                                                            (aggregationGenerator)  (aggregationTemporality)  Mode  Cnt           Score           Error   Units
HistogramCollectBenchmark.recordAndCollect                                        EXPLICIT_BUCKET_HISTOGRAM                     DELTA    ss    5  3390255558.400 ±  29491981.021   ns/op
HistogramCollectBenchmark.recordAndCollect:·gc.alloc.rate …
```
=> Avoid exemplar allocations if there are no measurements

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/HistogramExemplarReservoir.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/exemplar/HistogramExemplarReservoirTest.java
As noted by @dashpole [here](https://github.com/open-telemetry/opentelemetry-java-docs/pull/96#issuecomment-1428747455) there's a bug in the `HistogramExemplarReservoir` implementation. 
[HistogramPointData](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramPointData.java#L68) only supports double exemplars. Despite our API supporting both `LongHistogram` and `DoubleHistogram`, long values are simply converted to doubles in the aggregator. However, the `HistogramExemplarReservoir` didn't get the memo and reports a value of `0.0` when any long measurement is recorded as an exemplar. 
This fixes the issue by casting long measurements to double before storing in the reservoir.
=> Stop ignoring long measurements in HistogramExemplarReservoir

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java
=> Fix autoconfigure shutdown hook

sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java
I've seen this test flake occur a number of times ([example](https://github.com/open-telemetry/opentelemetry-java/actions/runs/4163981695/jobs/7205028081#step:5:1280)) where FullConfigTest fails because the test expects the emitted log records from the log api and event api to be in one batch, but occasionally they're split across two. 
I was able to reliably recreate this by placing a `Thread.sleep(1000)` in between the calls to the log and event API. 
Fixing it by lengthening the export interval and relying on `forceFlush()`.
=> Fix test flake in FullConfigTest

sdk-extensions/autoconfigure/README.md
Related to #4748, updated to the new package name.
=> Fixed example resource provider fully qualified class name

buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, sdk-extensions/incubator/README.md, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/SelectorSpecification.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfig.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfigCustomizerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfigTest.java, sdk-extensions/incubator/src/test/resources/empty-view-config.yaml, sdk-extensions/incubator/src/test/resources/full-config.yaml, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentSelector.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentSelectorBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/InstrumentSelectorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java
Implements spec PR [#3184](https://github.com/open-telemetry/opentelemetry-specification/pull/3184).
=> Allow views to select on instrument unit

settings.gradle.kts
Address failing [CodeQL](https://github.com/open-telemetry/opentelemetry-java/actions/runs/4299298665) workflow, which [doesn't support kotlin 1.8.10](https://github.com/github/codeql/pull/11637#issuecomment-1418657970) yet.
`opentelemetry-java-instrumentation` dealt with something [similar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7788).
=> Downgrade kotlin to 1.8.0

opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/OpenTracingShim.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/TracerShimTest.java
Fixes #5081 
As per the 1.17 Specification, the OpenTracing Tracer [Close](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#close) operation was added.
I feel tempted to deprecate the `OpenTracingShim.createTracerShim(OpenTelemetry)` method overload, as it wraps the actually `TracerProvider` with `ObfuscatedTracerProvider`, which prevents checking whether the actual instance implements `Closeable` or not.
=> OpenTracing Shim: Update Tracer.close()

.github/workflows/release.yml
The release [partially completed](https://github.com/open-telemetry/opentelemetry-java/actions/runs/4386207903/jobs/7679942522). Artifacts were published but the following steps were not completed.
In order to allow re-running the release job, this disables the "Build and publish artifacts" step.
=> Skip build and publish step to finish release

api/all/src/jmh/java/io/opentelemetry/api/common/AttributesBenchmark.java, api/all/src/main/java/io/opentelemetry/api/internal/ImmutableKeyValuePairs.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsBenchmarks.java
The metrics hot path involves finding the relevant `AggregationHandle` in a `ConcurrentHashmap` for a given measurement based on its `Attributes`. We recommend that callers save references to common `Attributes` to prevent extra allocations on each measurement. In this case, callers can benefit from caching `Attributes#hashCode` so that it doesn't need to be recomputed each time we record a measurement and do a lookup in the `ConcurrentHashmap`. 
I've added benchmarks to `AttributesBenchmark`, which shows a ~15x improvement in time to compute `hashCode` (not surprising). But its more interesting to see the performance improvement in an actual metrics scenario. I've extended `MetricsBenchmark` to include a case where there's enough cardinality to make the map lookup not completely trivial …
=> Cache ImmutableKeyValuePairs#hashCode

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
=> Make the Executor for PrometheusHttpServer configurable

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/marshal/MarshalerTest.java
=> Fix marshaler self suppression error

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java
They are expensive in this context
=> Remove streams from B3Propagator

CHANGELOG.md, buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/DelegatingSpanData.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/data/DelegatingSpanDataTest.java, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
There were a bunch of [breaking changes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/schemas/1.19.0) in the spec in 1.19.0 along with changes in internal yaml structure and signal types.
Spec changes caused build-tool to break (https://github.com/open-telemetry/opentelemetry-specification/issues/3299) and fix requires semconv generation script changes implemented in this PR and shown in https://github.com/open-telemetry/build-tools/pull/157
=> Update semconv to 1.19.0 and related build tool changes

opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/OpenTracingShimTest.java
To resolve https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7488#discussion_r1151104185
=> Adds version to otel tracer instrumentation scope

buildSrc/build.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-extension-kotlin.txt, settings.gradle.kts
Investigated why [upgrading wire-gradle-plugin](https://github.com/open-telemetry/opentelemetry-java/pull/5323#discussion_r1152572032) impacts kotlin extension. Determined that `wire-gradle-plugin` has a transitive dependency on the gradle kotlin plugin, which itself has a dependency on the kotlin plugin which resolves in a weird way.
Moving our kotlin plugin dependency from `settings.gradle.kts` to `buildSrc/build.gradle.kts` seems to resolve the conflict consistently.
=> Move kotlin plugin dependency to buildsrc

sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorBuilder.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorTest.java
See defaults [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#batching-processor).
=> Align BatchLogRecordProcessor defaults with specification

api/logs/src/main/java/io/opentelemetry/api/logs/DefaultLogger.java, api/logs/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java, api/logs/src/test/java/io/opentelemetry/api/logs/DefaultLoggerTest.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogRecordExporterTest.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/SystemOutLogRecordExporter.java, exporters/logging/src/test/java/io/opentelemetry/exporter/logging/SystemOutLogRecordExporterTest.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/logs/LogsRequestMarshalerTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/FakeTelemetryUtil.java, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogRecordDataAssert.java, sdk/logs-testing/src/main/java/io/opentelemetry/sdk/testing/logs/TestLogRecordData.java, sdk/logs-testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogRecordData.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerProviderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/SdkLoggerTest.java
Was adding support [observed timestamp](https://github.com/open-telemetry/opentelemetry-java/pull/5367) and I noticed `LogRecordBuilder#setEpoch` is poorly named. The log record data model has two timestamp fields (timestamp and observed timstamp), and `setEpoch` is ambiguous about which is being set.
Let's get this resolved before stabilizing. I propose we rename to `setTimestamp`, which is more clear.
=> Rename setEpoch to setTimestamp

exporters/common/build.gradle.kts, exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsConfigHelper.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsUtil.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/ManagedChannelUtil.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/okhttp/OkHttpExporterBuilder.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/TlsConfigHelperTest.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/testing-internal/build.gradle.kts, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java
Related to #5280 and this [comment](https://github.com/open-telemetry/opentelemetry-java/pull/5280#discussion_r1146352645).
The overall goal is to provide a low level API for configuring SSL on the exporters for when configuring a static certificate or static mTLS isn't good enough. This should be the last API we add, acting as a catch all for other TLS scenarios. 
Ideally we'd be able to just expose a `setSslContext(SSLContext)` method. SSLContext is initialized using `KeyManager`(s) and `TrustManager`(s), and produces a `SSLSocketFactory` via `SSLContext#getSocketFactory()`.
However, our dependence on okhttp complicates this, since okhttp requires TLS to be configured via `OkHttpClient.Builder#sslSocketFactory(SSLSocketFactory, X509TrustManager)`. You'd think that because a `SSLContext` …
=> Add skaffolding for low level exporter SSL API

exporters/otlp/testing-internal/build.gradle.kts, integration-tests/otlp/build.gradle.kts, integration-tests/tracecontext/build.gradle.kts
The [default configuration](http://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html) skips test dependency groups, but we have a number of testing modules which look like regular published modules. Skipping owasp dependencyCheck on these to avoid [false positives](https://github.com/open-telemetry/opentelemetry-java/actions/workflows/owasp-dependency-check-daily.yml).
=> Skip OWASP dependencyCheck on test modules

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Need to skip one more set of configurations to get the owasp check to pass without false positives.
=> OWASP dependencyCheck skips jmh configurations

exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogRecordExporterTest.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/logs/LogsRequestMarshalerTest.java
=> Serialize observed timestamp

sdk-extensions/jaeger-remote-sampler/src/testGrpcNetty/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerGrpcNettyTest.java
This test flakes fairly frequently ([example](https://github.com/open-telemetry/opentelemetry-java/actions/runs/4708069727/jobs/8350293854)). The tests validate the behavior when the server returns various errors, and assert that the default configuration is not updated, and that there are warnings of the errors in the logs. I think the test flakes because the polling interval is low at just 50ms, allowing the sampler to perform a second successful request and update its configuration before the assertions take place. Recreated locally by adding manual `Thread.sleep`, and verified this should fix the issue.
=> Fix flakey JaegerRemoteSamplerGrpcNettyTest

buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
The deprecated semantic convention keys `MESSAGING_PROTOCOL` and `MESSAGING_PROTOCOL_VERSION` are missing a link to their according replacements. See https://github.com/open-telemetry/opentelemetry-specification/pull/2957
If you don't know where to look, it's quite cumbersome to find the spec change PR. In the worst case developers remove their attributes instead of updating correctly.
=> Add missing links to deprecated constants in SemanticAttributes

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java
=> Add check for metrics name to prevent add duplicated _total suffix

exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java
Fixes the build. See #5414, #5415, #5416.
Appears that the collector behavior has recently changed.
=> Update prometheus test to reflect new collector behavior

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/TlsConfigHelperTest.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterTest.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcLogRecordExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcMetricExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcSpanExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/TelemetryExporterBuilder.java
Relates to #5211.
This is a follow-up from #5246 and provides new methods for configuring TLS on the OTLP exporters in a more DIY or BYO fashion. This allows users to preconfigure their own existing `X509TrustManager`, `X509KeyManager`, and/or `SSLSocketFactory` without necessarily having to manually deal with certificate bytes (existing APIs).
=> Add new TLS related APIs on OTLP exporter builders.

docs/apidiffs/current_vs_latest/opentelemetry-opentracing-shim.txt, opentracing-shim/gradle.properties
=> Mark opentracing-shim as stable

sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProvider.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProviderTest.java
=> fixes jaeger remote sampler service strategies bug

exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/logs/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterTest.java
Looks like there was a typo in one of the method names @breedx-splk.
=> Rename misnamed setSslContext method

docs/apidiffs/current_vs_latest/opentelemetry-exporter-jaeger.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-jaeger-remote-sampler.txt, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/jaeger/src/test/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterTest.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java, sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java
Relates to comment https://github.com/open-telemetry/opentelemetry-java/pull/5280#discussion_r1146529453
=> Add new TLS related APIs on Jaeger buiders.

integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java
Good to confirm that exemplars work round trip: sdk -> otlp -> collector -> otlp -> java otlp receiver
=> Add exemplar to otlp integration test

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/HistogramPointAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java
I ran into some issues with double metrics precision in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8490#discussion_r1193622265, figured we might as well add a method varian that allows passing `Offset`
=> Add a `hasBucketBoundaries()` variant that allows specifying precision

api/all/src/main/java/io/opentelemetry/api/DefaultOpenTelemetry.java, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/NoopLogRecordProcessor.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/NoopLogRecordProcessorTest.java
A small improvement. The behavior is similar to https://github.com/open-telemetry/opentelemetry-java/blob/93bcdf28706c1b6830394dc3a6d4dae1844e1c90/context/src/main/java/io/opentelemetry/context/propagation/NoopTextMapPropagator.java#L36-L39
=> Add meaningful `.toString` to `NoopLogRecordProcessor` and `DefaultOpenTelemetry`

sdk/common/build.gradle.kts
Fixes #5474.
`opentelemetry-sdk-common` publishes is a multi-version jar. It looks like the sources and javadoc jars incorrectly include compiled class files. This fixes that, including the correct files in each the respective jars.
=> Ensure correct compiled output and sources are included in multi version jar

buildscripts/semantic-convention/generate.sh, buildscripts/semantic-convention/templates/SemanticAttributes.java.j2, semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/ResourceAttributes.java, semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java
=> Update to semconv 1.20.0

sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/View.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/SdkMeterProviderUtil.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/CardinalityLimitSelector.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/RegisteredView.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/RegisteredViewTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java
=> Experimental metric reader and view cardinality limits

CHANGELOG.md, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ReadWriteLogRecord.java
~~Couple more PRs in [1.27.0 milestone](https://github.com/open-telemetry/opentelemetry-java/milestone/14) to resolve before releasing.~~
=> Prepare for 1.27.0 release

.github/workflows/build.yml, settings.gradle.kts
I worked with @iNikem to obtain a set of credentials on https://ge.opentelemetry.io. One logged in, I could create an access token, which I've added as a secret for github actions under `GRADLE_ENTERPRISE_ACCESS_KEY`.
=> Publish build scans to ge.opentelemetry.io

.github/repository-settings.md, .github/workflows/backport.yml, .github/workflows/prepare-patch-release.yml, .github/workflows/prepare-release-branch.yml, .github/workflows/release.yml
TODO: delete unused `BOT_TOKEN` and `DOC_UPDATE_TOKEN` secrets.
Following the [good example](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/.github/repository-settings.md#secrets-and-variables--actions) from `opentelemetry-java-instrumentation`.
=> Document github actions secrets

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/Advice.java
There may be other places like this, @open-telemetry/java-maintainers you can fix them if you want.
=> Make Advice proper immutable class

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorageTest.java
show duplicated metric tags to help debugging
=> show duplicated metric tags

context/build.gradle.kts, dependencyManagement/build.gradle.kts, exporters/prometheus/build.gradle.kts, extensions/kotlin/build.gradle.kts, integration-tests/otlp/build.gradle.kts, sdk-extensions/autoconfigure/build.gradle.kts, sdk/common/build.gradle.kts, sdk/metrics/build.gradle.kts, sdk/trace-shaded-deps/build.gradle.kts
Recent changes to gradle have resulted in a number of warnings popping up in the build. See this [build](https://github.com/open-telemetry/opentelemetry-java/actions/runs/5307690567/jobs/9606451167?pr=5550) for example. 
This PR addresses them.
=> Fix various gradle warnings

exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java
Build failing after recent update to collector test image. See example [here](https://github.com/open-telemetry/opentelemetry-java/actions/runs/5329938835/jobs/9675023969?pr=5559).
=> Fix prometheus integration test

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/OrderedSpiTest.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/java/io/opentelemetry/sdk/autoconfigure/ConditionalResourceProviderTest.java
This aligns AutoConfiguredOpenTelemetrySdkBuilder with our other builders.
=> Refactor autoconfigure registerShutdownHook(boolean) to disableShutdownHook()

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testAutoConfigureOrder/java/io/opentelemetry/sdk/autoconfigure/OrderedSpiTest.java, sdk-extensions/autoconfigure/src/testConditionalResourceProvider/java/io/opentelemetry/sdk/autoconfigure/ConditionalResourceProviderTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/metric/viewconfig/ViewConfigCustomizerTest.java
GlobalOpenTelemetry makes you opt into initializing with autoconfigure by setting a environment variable / system property.
In contrast, AutoConfiguredOpenTelemetrySdk will set GlobalOpenTelemetry by default. This PR aligns AutoConfiguredOpenTelemetrySdk with the opt-in behavior of GlobalOpenTelemetry, and also with our general advice discouraging use of GlobalOpenTelemetry.
Also, this PR changes AutoConfiguredOpenTelemetrySdkBuilder#setResultAsGlobal(boolean) to simply be AutoConfiguredOpenTelemetrySdkBuilder#setResultAsGlobal(). This means there is no option to undo a decision to `setResultAsGlobal` after its previously been invoked. 
This aligns with our builders elsewhere.
=> AutoConfiguredOpenTelemetrySdkBuilder does not set GlobalOpenTelemetry by default

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/internal/EnvironmentResourceProvider.java, sdk-extensions/autoconfigure/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationFuzzTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
Related to #5464.
Implementation of my preferred solution to provide public access to resource configured from the environment, as discussed [here](https://github.com/open-telemetry/opentelemetry-java/pull/5544#issuecomment-1595302453).
Adds new public method `ResourceConfiguration#createEnvironmentResource()` to autoconfigure.
=> Add public API to access environment resource

sdk-extensions/autoconfigure/README.md
Doc is not aligned with actual value: https://github.com/open-telemetry/opentelemetry-java/blob/83de956128420e2f4be0b41a218c250389c6d587/sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorBuilder.java#L23
=> Fix batch log record processor default

.github/scripts/generate-release-contributors.sh
this is the only usage I found still remaining: https://github.com/search?q=org%3Aopen-telemetry%20opentelemetry-java-bot&type=code
=> Delete old bot account

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/CardinalityTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java
=> After cardinality limit exceeded record measurements to overflow series

api/all/src/main/java/io/opentelemetry/api/trace/Span.java, api/all/src/test/java/io/opentelemetry/api/common/AttributesTest.java
=> Update javadoc to allow null/empty attr values 

opencensus-shim/build.gradle.kts, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java, opentracing-shim/build.gradle.kts, opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java, opentracing-shim/src/test/java/io/opentelemetry/opentracingshim/OpenTracingShimTest.java
Resolves #5369.
Converts remaining code that reads version from `version.properties` to instead obtain it from a generated class.
=> Use OtelVersionClassPlugin instead of reading version from resource

build.gradle.kts, buildSrc/build.gradle.kts
The existing warning is wrong (says java 11 is required to build instead of java 17) and is in the wrong place (gradle fails with compatibility exception when building `buildSrc` before the `build.gradle.kts` has a chance to run).
=> Fix gradle java version requirement warning

.github/ISSUE_TEMPLATE/bug_report.md, buildSrc/build.gradle.kts
Also update sample compiler version.
=> Refer to Adoptium/Temurin instead of AdoptOpenJDK

opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryTraceComponentImpl.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/InteroperabilityTest.java
Previously, the default OpenCensus sampler would run *before* the shim calls the OpenTelemetry API. This causes both the OpenCensus and OpenTelemetry samplers to be evaluated, and they must both pass to be sampled.
This PR changes the default OpenCensus sampler for the shim to be `Samplers.alwaysSample()`.  That way, users can just configure Sampling in OpenTelemetry.
=> Change OpenCensus shim default sampling to defer to OpenTelemetry

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsConfigHelper.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterOkHttpSenderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterOkHttpSenderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterOkHttpSenderTest.java, exporters/otlp/all/src/testJdkHttpSender/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterJdkSenderTest.java, exporters/otlp/all/src/testJdkHttpSender/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterJdkSenderTest.java, exporters/otlp/all/src/testJdkHttpSender/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterJdkSenderTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpLogRecordExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpMetricExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpSpanExporterBuilderWrapper.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/export/RetryPolicy.java
Related to #5642. If merged, I'll follow up with a PR to add the same to the OtlpGrpc{Signal}Exporters.
=> Add OtlpHttp{Signal}Exporter#toBuilder() methods

sdk-extensions/autoconfigure/README.md
Was having a hard time navigating the autoconfigure docs the other day because the's not a lot of organization.
This reorganizes it into sections for each signal provider (tracer provider, meter provider, logger provider) which contain configuration related to that specific signal, and a general configuration section containing signal agnostic options (exporters, resource, attribute limits, propagator).
Also generates the TOC with markdown-doc, which is what the specification uses. Didn't want to be heavy handed and introduce a bunch of automation / checking, so I just added a comment with instructions.
=> Reorganize autoconfigure docs by signal

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterTest.java, exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyLogRecordExporterTest.java, exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcNettyMetricExporterTest.java, exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettySpanExporterTest.java, exporters/otlp/all/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyShadedLogRecordExporterTest.java, exporters/otlp/all/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcNettyShadedMetricExporterTest.java, exporters/otlp/all/src/testGrpcNettyShaded/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettyShadedSpanExporterTest.java, exporters/otlp/all/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcNettyOkHttpLogRecordExporterTest.java, exporters/otlp/all/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcOkHttpMetricExporterTest.java, exporters/otlp/all/src/testGrpcOkhttp/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcOkHttpSpanExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java
Continuation of #5652.
Resolves #5642.
=> Add OtlpGrpc{Signal}Exporter#toBuilder() methods

sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ConfigurationReader.java
We switched from snakeyaml to snakeyaml-engine in #5138.
One of the motivations for this was because of https://nvd.nist.gov/vuln/detail/CVE-2022-1471.
Since then, snakeyaml agreed to release 2.0 to address/quiet scanners: https://bitbucket.org/snakeyaml/snakeyaml/issues/561/cve-2022-1471-vulnerability-in#comment-64876314 (which is great).
Still probably a good idea to consolidate on snakeyaml-engine.
Btw, this doesn't remove `snakeyaml` from the classpath, since `jackson-dataformat-yaml` still uses `snakeyaml`. They have updated to `snakeyaml-engine` in `master`, but won't be released until 3.0 (https://github.com/FasterXML/jackson-dataformats-text/tree/master/yaml).
=> Switch from snakeyaml to snakeyaml engine

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java
#5680  and #5652 opened the door to an easy toString implementation on OTLP exporters. This continues down the path of making it easier to diagnose the configuration of OpenTelemetrySdk, since the otel java agent or any other application can log `OpenTelemetrySdk#toString()`.
Another nice side affect of this is that it makes it easier to compare configured instances of the OTLP exporters (i.e. from file configuration) without a bunch of reflective introspection to examine internal fields.
Note, in order to avoid printing secrets, I print all headers as `{header-name}=OBFUSCATED`. Better to be overly restrictive about what we print than accidentally print some secret because we misidentify a header as safe to print.
=> Add toString to OTLP exporters

extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/DoubleHistogramAdviceConfigurer.java, extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/ExtendedDoubleHistogramBuilder.java, extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/ExtendedLongHistogramBuilder.java, extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/LongHistogramAdviceConfigurer.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AdviceTest.java
It struck me as a little bit of an ergonomics problem to have to pass a collection of doubles when setting explicit bucket boundaries for a LongHistogram builder/advice.
See how the `AdviceTest` changes in this PR for an example of how this should feel a slight bit better.
=> Add LongHistogramAdviceConfigurer to improve api surface types

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogRecordDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java
This brings log asserts into parity with metric and span asserts. Been meaning to do this for a while.
=> Add hasResourceSatisfying to LogRecordDataAssert

extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/CounterAdviceConfigurer.java, extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/metrics/ExtendedDoubleCounterBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownCounter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongGaugeBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/Advice.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AdviceAttributesProcessor.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AbstractInstrumentBuilderTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AttributesAdviceTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ExplicitBucketBoundariesAdviceTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableInstrumentTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/CallbackRegistrationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/AdviceAttributesProcessorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistryTest.java
Implements https://github.com/open-telemetry/opentelemetry-specification/pull/3546
I only added implementation for the `DoubleCounter` in this PR; I'll extend it to all other instruments in the following PR if this one is accepted.
=> Add attributes advice API (just `DoubleCounter` for now)

build.gradle.kts, dependencyManagement/build.gradle.kts, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java, settings.gradle.kts
This plugin was used to manually detect dependency updates prior to us using dependabot / renovate.
=> Remove unused com.github.ben-manes.versions plugin

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusUnitsHelper.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusUnitsHelperTest.java
Description:
Discovered during https://github.com/open-telemetry/opentelemetry-go/pull/4374#pullrequestreview-1548606912.
`B` means `bel` in UCUM, so `MB` is `megabel`, for example. `$` is also not UCUM.
https://ucum.org/ucum#section-Alphabetic-Index-By-Symbol
=> prometheus exporter: remove non-ucum units from conversion

sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanExporterFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanProcessorFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanExporterFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanProcessorFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactoryTest.java
Builds on #5687, #5399 by adding logic to interpret trace provider portion of configuration schema.
=> Add SdkTracerProvider configuration factory

buildSrc/build.gradle.kts
Same as https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9294
Resolves #5760
Related issue https://github.com/github/codeql/issues/14046
=> Revert kotlin upgrade; the newest version does not agree with CodeQL

dependencyManagement/build.gradle.kts, sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/PropagatorsFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/PropagatorsFactoryTest.java
Builds on #5751, #5687, #5399, #5757 by adding logic to interpret the propagators portion of configuration schema.
=> Add ContextPropagators configuration factory

sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/FileConfigUtil.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SamplerFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SamplerFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactoryTest.java
Builds on #5751, #5687, #5399, #5757, #5758 by adding logic to interpret the sampler portion of configuration schema.
=> Add Sampler configuration factory

docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewBuilder.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/ViewTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessorTest.java
Adds a helper function for specifying that a view should retain only a specific set of attribute keys:
Previous:
```
Set<String> keysToRetain = new HashSet<>(Arrays.asList("key1", "key2"));
View view = View.builder().setAttributesFilter(keysToRetain::contains);
```
After:
```
View view = View.builder().setAttributesFilter(new HashSet<>(Arrays.asList("key1", "key2")));
```
As an added benefit, we can have ensure a proper `toString()` implementation when the helper function is used:
```
Set<String> keysToRetain = new HashSet<>(Arrays.asList("key1", "key2"));
View view = View.builder().setAttributesFilter(keysToRetain::contains);
view.toString(); // View{aggregation=DefaultAggregation, attributesProcessor=AttributeKeyFilteringProcessor{nameFilter=io.opentelemetry.sdk.metrics.ViewTest$$Lambda$ …
```
=> Add AttributesProcessor toString, add attribute filter helper

docs/apidiffs/current_vs_latest/opentelemetry-exporter-zipkin.txt, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java, sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanExporterFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanExporterFactoryTest.java
Builds on #5751, #5687, #5399, #5757, #5758, #5763 by adding logic to interpret the sampler portion of configuration schema.
=> Add SpanExporterFactory support for zipkin exporter

sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogLimitsFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogRecordLimitsAndAttributeLimits.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LoggerProviderAndAttributeLimits.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LoggerProviderFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsAndAttributeLimits.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderAndAttributeLimits.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogLimitsFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LoggerProviderFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactoryTest.java
Builds on #5751, #5687, #5399, #5757, #5758, #5763, #5771, #5773 by adding logic to interpret general attribute limits in addition to signal specific log and span limits.
=> General attribute limits configuration factory

api/all/src/main/java/io/opentelemetry/api/metrics/Meter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
~Pending spec PR https://github.com/open-telemetry/opentelemetry-specification/pull/3648~ Spec update is merged!
=> Increase metric name maximum length from 63 to 255 characters

README.md
Noticed a couple issues when I was settings up the `semantic-conventions-java` README and using this README as a reference.
=> Fix README.md CI link, tweak status phrasing

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/ConfigProperties.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/DefaultConfigProperties.java, sdk-extensions/autoconfigure-spi/src/test/java/io/opentelemetry/sdk/autoconfigure/spi/internal/ConfigPropertiesTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
=> DefaultConfigProperties#getMap filters entries with blank values intead of throwing

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/SerializerTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/TestConstants.java
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-attributes
> OpenTelemetry Metric Attributes MUST be converted to [Prometheus labels](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). String Attribute values are converted directly to Metric Attributes, and non-string Attribute values MUST be converted to string attributes following the [attribute specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute). Prometheus metric label keys are required to match the following regex: [a-zA-Z_]([a-zA-Z0-9_])*. Metrics from OpenTelemetry with unsupported Attribute names MUST replace invalid characters with the _ …
=> Prometheus exporter: handle colliding metric attribute keys

docs/apidiffs/current_vs_latest/opentelemetry-sdk-logs.txt, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ReadWriteLogRecord.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/ReadWriteLogRecordTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleUpDownCounterTest.java
This addition of `addAllAttributes()` matches exactly what is in the `Span` interface (signal type interface parity).
In Android, we expect to need to add a common set of "global" attributes to every event in a standard way.  This helps to facilitate that more cleanly than other approaches.
=> Add addAllAttributes() to ReadWriteLogRecord.

.github/repository-settings.md, .github/workflows/benchmark-tags.yml, .github/workflows/benchmark.yml
These workflows run a few JMH benchmarks and publish the results to a `benchmarks` branch. The expectation is that the branch would be published via github pages.
`benchmark-tags.yml` is intended to run manually as needed to populate benchmark data from historical versions. This works because the benchmarks being run have been in place for a long time. If we needed a new benchmark, methodologies would need to change.
In order for this to work, a new github pages branch needs to be created (assuming `benchmarks`):
```shell
git checkout --orphan benchmarks
git commit --allow-empty -m "Init"
git push origin benchmarks
```
(not tested, but something to this effect.)
Note: this won't actually work until the org-level self-hosted runner is configured to allow these workflows.
=> Add Benchmark workflows

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SdkObservableMeasurement.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleGaugeTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableDoubleCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkObservableDoubleUpDownCounterTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SdkObservableMeasurementTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java
=> Drop NaN measurements to metric instruments

.github/config/markdown-link-check-config.json
https://github.com/maxcellent/javadoc.io/issues/180 javadoc.io has been down for the whole day. Creating a pr to exclude it from link checks in case we need to get the build passing before it gets fixed.
=> Ignore javadoc.io links

.github/workflows/benchmark-tags.yml, .github/workflows/benchmark.yml
This is more consistent with other repos and allows us to include other things in the future without breaking urls.
A separate PR to move the existing data to that folder: #5875
=> Move data dir to `benchmarks`

sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfigurationTest.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/5866
My guess is that `configureMetricReader_KnownSpiExportersOnClasspath` fails with `java.net.BindException: Address already in use` because `configureReader_PrometheusOnClasspath`, which is the only test that also starts `PrometheusHttpServer` in `MetricExporterConfigurationTest` had not yet shut down `PrometheusHttpServer`. Shutting down `PrometheusHttpServer` https://github.com/open-telemetry/opentelemetry-java/blob/5ccc7fccb3fd0bdfa902bfea7bcee43384cdcf3e/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java#L164 waits for 10s for the server to shut down, running time of `configureReader_PrometheusOnClasspath` is 10.104s. So it think it is plausible that …
=> Fix flaky MetricExporterConfigurationTest

sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ConfigurationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ConfigurationReader.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ConfigurationReaderTest.java
Environment variable substitution was one of the key parts of file configuration described in the [original OTEP](https://github.com/open-telemetry/oteps/blob/main/text/0225-configuration.md#environment-variable-substitution).
I've been holding off defining it in the [file configuration spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md) because I've been trying to define the key [parse / create operations](https://github.com/open-telemetry/opentelemetry-specification/pull/3437), and it makes sense to describe environment variable substitution as a requirement of `parse`.
So while this isn't part of the spec yet, I will be trying to get it added as soon as possible. I think the syntax of environment variables …
=> Add env var substitution support to file configuration

exporters/sender/jdk/build.gradle.kts, exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java, exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java
Fixes a TODO in JdkHttpSender by ensuring that it retries on connect exceptions. 
Thanks to @mikelaspina for the report!
=> JdkHttpSender should retry on connect exceptions

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracePropagatorTest.java
Fixes an issue in opentracing baggage propagation.
There is no guarantee that `TextMapGetter`s  will send headers(`.keys()`) as lowercase strings. Some of the `TextMapGetter`s like `undertow:1.7` send the headers as they receive them(e.g. `Ot-Baggage-Key`) but ensure case insensitivity of headers by allowing `get()` to be called regardless of the header name case. This behaviour breaks the `OtTracePropagator` because it expects lowercase literal `ot-baggage-` to be present in header name.
This PR fixes that issue.
=> Fix opentracing header name issue

sdk-extensions/jaeger-remote-sampler/src/testGrpcNetty/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerGrpcNettyTest.java
https://scans.gradle.com/s/wcf3eniwf5tb6/tests/task/:sdk-extensions:jaeger-remote-sampler:testGrpcNetty/details/io.opentelemetry.sdk.extension.trace.jaeger.sampler.JaegerRemoteSamplerGrpcNettyTest/initialSampler()?expanded-stacktrace=WyIwIl0&top-execution=1
Test fails when remote configuration is received before asserting sampler description.
The same test with okhttp uses `example.com` as target
https://github.com/open-telemetry/opentelemetry-java/blob/efa46a5dccb962b50943a0b4905c1800282d6be6/sdk-extensions/jaeger-remote-sampler/src/test/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerTest.java#L251
=> Fix flaky jaeger remote sampler test

context/src/main/java/io/opentelemetry/context/StrictContextStorage.java
https://ge.opentelemetry.io/s/y3ppcyqy2q5v2/tests/task/:instrumentation:reactor:reactor-netty:reactor-netty-1.0:javaagent:test/details/io.opentelemetry.javaagent.instrumentation.reactornetty.v1_0.ReactorNettyHttpClientUsingFromTest/shouldNotLeakConnections()?expanded-stacktrace=WyIwIl0&top-execution=1
Also see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7304
Apparently `ReferenceQueue#remove()` can return null on openj9.
=> Add null check to StrictContextStorage

exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/internal/otlp/GrpcGzipBenchmark.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/internal/otlp/MetricsRequestMarshalerBenchmark.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/internal/otlp/RequestMarshalBenchmarks.java, exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/internal/otlp/TestOutputStream.java
`ByteArrayOutputStream`, that is currently used, also allocates memory which is included in the jmh output. Removing the allocations for the output buffer gives a more accurate representation of the allocations performed by the marshaling.
=> Use a custom output stream in marshaling jmh benchmarks

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpLogRecordExporterProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpMetricExporterProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpSpanExporterProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/AutoConfigureListener.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/internal/SpiHelper.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableLogRecordExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableMetricExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/provider/MetricCustomizer.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/provider/TestConfigurableLogRecordExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/provider/TestConfigurableMetricExporterProvider.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/provider/TestConfigurableSpanExporterProvider.java
Resolves #5862, #5021.
Add a new (experimental) interface called `AutoConfigureListener`. This is not a standalone SPI. Instead, implementations of existing SPIs can additionally implement `AutoConfigureListener`. By doing so, they get a callback to the autoconfigured `OpenTelemetrySdk` instance.
Why have SPI implementations implement an additional interface instead of adding a new SPI? If we were to introduce a new standalone SPI, each SPI implementation that needs a callback would have to hold a reference to their configured SDK components in a static variable, and update those references with `OpenTelemetrySdk` in the callback.
With the strategy in this PR, the same SPI implementation instance that configured the SDK component is invoked with the `OpenTelemetrySdk`, so it only has to …
=> Autoconfigure listener

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRule.java, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtension.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit4/OpenTelemetryRuleTest.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/junit5/OpenTelemetryExtensionTest.java
Just extending the JUnit extensions with missing log support. Came across this omission writing some custom instrumentation the other day.
=> Add log support to junit extensions

api/events/src/main/java/io/opentelemetry/api/events/DefaultEventEmitter.java, api/events/src/main/java/io/opentelemetry/api/events/EventBuilder.java, api/events/src/main/java/io/opentelemetry/api/events/EventEmitter.java, api/events/src/test/java/io/opentelemetry/api/events/DefaultEventEmitterTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventEmitterProvider.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventEmitterProviderTest.java
There are several cases where events may need to be emitted with a timestamp that is different from "now" (the current time), the main ones being:
* Handling events that occur prior to SDK initialization
* Event log recording/playback
These are not contrived use cases. In Android, we have a specific need to track certain startup behaviors, and the sdk creation is not necessarily early enough in the application lifecycle to handle this.
=> Allow events to be emitted with timestamp

sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/TestSdk.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/state/SynchronousMetricStorageTest.java
@asafm has identified a rather nefarious concurrency bug in the DefaultSynchronousMetricStorage for delta aggregation temporality.
This PR introduces a test which recreates almost always, and a fix utilizing a read-write lock. The idea is that while recording we take a relatively cheap read lock, and while collecting we take the more expensive write lock. 
This results in a modest reduction in performance, but it seems to be the best way to solve the problem and correctness should trump performance. Here's the [before](https://gist.github.com/jack-berg/8d96e5459805582bc14ff5877fb5740d) and [after](https://gist.github.com/jack-berg/9636f25b0c9e474e0ca496e2c7f519d3) of [MetricsBenchmark](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/jmh/java/io/opentelemetry/ …
=> Fix delta metric storage concurrency bug

exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java, exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java
@mikelaspina has been running a modified version of JdkHttpSender in production and has found some sharp edges with respect to which exceptions are considered retryable.
This PR expands the set to include all IOExceptions which are not instances of SSLException. Based off his experience running this in prod, all the IOExceptions we ran into qualify as retryable. They're also difficult to identify by their message so  this PR opts out of specific exceptions instead of the existing behavior of opting in.
=> Expand the set of retryable exceptions in JdkHttpSender

docs/apidiffs/current_vs_latest/opentelemetry-extension-kotlin.txt, extensions/kotlin/build.gradle.kts
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/5903
1.4 should be the earliest supported version for 1.9 compiler, probably we'll have to bump this with the next kotlin version
=> Target kotlin 1.4 in kotlin extension

extensions/incubator/src/main/java/io/opentelemetry/extension/incubator/logs/AnyValueBytes.java, extensions/incubator/src/test/java/io/opentelemetry/extension/incubator/logs/AnyValueTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/AnyValueBodyTest.java
#5973 upgrades the desguaring version so that we have access to `Base64`. This produces a more compact / familiar encoding for AnyValue bytes than the hex encoding currently being used.
=> Base64 encode AnyValue bytes in string representation

exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsUtil.java
Fixes #4533. As demonstrated in #6003, android desugaring now supports `Base64`.
=> Remove exception handling in TlsUtil#decodePem

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/JsonSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Serializer.java, exporters/otlp/common/build.gradle.kts, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/AnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/ArrayAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/BoolAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/BytesAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/DoubleAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/InstrumentationScopeMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/IntAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/KeyValueListAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/KeyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/ResourceMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/StringAnyValueMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/logs/LogMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExemplarMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/HistogramDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/NumberDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/SummaryDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanEventMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanLinkMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/AnyValueMarshalerTest.java, integration-tests/otlp/build.gradle.kts, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilder.java
Followup to #5880 which updates OTLP log record marshaling to properly encode AnyValue log bodies.
Leaving as a draft until #5880 is resolved.
=> Serialize log body any value

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure-spi.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure.txt, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfiguration.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ConfigurableSpanExporterTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java
The goal of this PR is to start a discussion around enhancing the ability to modify spans before export.
The existing mechanism to do this are the following: 
* SpanProcessor for modifying spans on start
* wrapping `SpanExporters` for modifying spans before they are exported (= after they have ended)
These options only allow to modify the contents of spans, but they do not allow to efficiently perform the following changes:
* Filtering spans, so that they are not exported
* See for example [this slack discussion](https://cloud-native.slack.com/archives/C014L2KCTE3/p1671486545789789)
* Delaying spans
* E.g. in order to add profiling statistics to spans as attributes. Those statistics are likely not immediately available on span end.
* Adding artificial spans
* Example use-case: Generating …
=> Improve autoconfiguration capabilities for adding, delaying or dropping spans

settings.gradle.kts
I can't build locally after merging #6050. Reverting so we can get through the release and I have time to investigate.
=> Revert com.gradle.enterprise 3.16 upgrade

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/AbstractPointAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/MetricAssertionsTest.java
=> add hasAttributesSatisfying overload to AbstractPointAssert

api/all/src/main/resources/META-INF/native-image/io.opentelemetry/opentelemetry-api/reflect-config.json
The `opentelemetry-api` jar has a `version.properties` files. The PR allows access to this file with a GraalVM native execution.
=> Ability to access version.properties API file with GraalVM native

all/build.gradle.kts, buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts, context/build.gradle.kts, sdk/metrics/build.gradle.kts
Fix the [owasp dependency check task](https://github.com/open-telemetry/opentelemetry-java/actions/workflows/owasp-dependency-check-daily.yml), which has been failing due to changes from gradle upgrades and dependency upgrades shifting around gradle configurations we need to exclude.
=> Fix owasp dependency check

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/FileConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FileConfigurationTest.java
Right now its impossible to trigger file configuration in autoconfigure. 
Whether you set an environment variable `OTEL_CONFIG_FILE` or system property `otel.config.file`, we're reading the `OTEL_CONFIG_FILE`, which never matches the normalized environment variable or system property 🤦. This fixes the bug.
=> Read normalized otel.config.file property

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java
The javadoc is incorrect, as noted in https://github.com/open-telemetry/opentelemetry-java/pull/4489#discussion_r1440180355
=> Fix autoconfigure javadoc explaining behavior when disabled

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
=> Only call SpanProcessor onStart / onEnd if required

sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/AggregationFactoryTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/Base2ExponentialHistogramAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/AggregationTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/Base2ExponentialHistogramAggregationTest.java
=> Base2ExponentialHistogramAggregation maxBuckets must be >= 2

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/ExemplarReservoir.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/LongToDoubleExemplarReservoir.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/Base2ExponentialHistogramAggregation.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ExplicitBucketHistogramAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkLongHistogramTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/exemplar/LongToDoubleExemplarReservoirTest.java
=> Convert histogram measurements to double before passing recording exemplar reservoir

docs/apidiffs/current_vs_latest/opentelemetry-exporter-otlp.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
Adds an option to the `SimpleSpanProcessor` and `BatchSpanProcessor` which allows unsampled spans to be exported.
```cs
SpanExporter spanExporter = ...;
SimpleSpanProcessor simpleSpanProcessor = SimpleSpanProcessor.builder(spanExporter)
.setExportUnsampledSpans(true)
.build();
BatchSpanProcessor batchSpanProcessor = BatchSpanProcessor.builder(spanExporter)
.setExportUnsampledSpans(true)
.build();
```
=> Add option to export unsampled spans from span processors

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusUnitsHelper.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusUnitsHelperTest.java
Addressing post-merge comments on #6015.
Fixing a few things that might qualify as regressions:
- After #6015, we don't ensure that the metric name is sanitized after appending the unit. This means that disallowed characters in the unit can cause errors.
- We stopped converting unit `1` to `ratio` in the simple case. I.e. we convert `1{foo}` to `ratio`, but `1` result in `null`. Not sure why but I think that's wrong.
=> Restore prometheus metric name mapper tests, fix regressions

dependencyManagement/build.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-exporter-zipkin.txt, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/BytesEncoderAdapter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/BytesEncoderAdapterTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterEndToEndHttpTest.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
Once merged, this will unlock spring-boot and micrometer tracing from zipkin reporter 2
=> Update dependency io.zipkin.reporter2:zipkin-reporter-bom to 3.1.1

sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/InstrumentGarbageCollectionBenchmarkTest.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/TestInstrumentType.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/tester/DoubleSumTester.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/tester/LongSumTester.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleSumAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongSumAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/MutableDoublePointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/MutableExponentialHistogramBuckets.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/MutableExponentialHistogramPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/data/MutableLongPointData.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/SumAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleSumAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongSumAggregatorTest.java
This is one of many PRs that implement #5105. See the complete plan [here](https://github.com/open-telemetry/opentelemetry-java/issues/5105#issuecomment-1739237240).
Specifically, this PR adds the implementation of `MemoryMode` for the synchronous instrument: counter.
This PR, relative to Exponential and Explicit Histogram PR, is rather trivial. It contains:
* Using a reusable point for returning the result on `doAggregateThenMaybeReset` for both `LongSumAggregator.Handle` and `DoubleSumAggregator.Handle`.
* Adding matching garbage collection benchmark tests
* Adjusting and adding tests for `LongSumAggregator` and `DoubleSumAggregator`
* Allowed to set the normalized allocate rate reduction percentage since, for both those aggregations, there was only a single allocation per Attributes, …
=> Memory mode: Adding support for synchronous instruments - Counter

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpSpanExporterProviderTest.java
Blocked by https://github.com/open-telemetry/opentelemetry-specification/issues/3832
=> header values are be expected to be W3C baggage encoded

.github/workflows/build.yml, RELEASING.md
See @trask's comment here: https://github.com/open-telemetry/opentelemetry-java/pull/6183#issuecomment-1922296811
As of [codecov 4.0.0](https://github.com/codecov/codecov-action/releases/tag/v4.0.0): 
> Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token). This [doc](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) shows instructions on how to add the Codecov token.
My read of this is that builds for this repo will need the token to upload, but PRs from forks don't need it.
=> Define CODECOV token

sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/ProfileBenchmark.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/TestInstrumentType.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/tester/DoubleLastValueTester.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/tester/LongLastValueTester.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleLastValueAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongLastValueAggregator.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/LastValueAggregation.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleLastValueAggregatorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongLastValueAggregatorTest.java
This is one of many PRs that implement #5105. See the complete plan [here](https://github.com/open-telemetry/opentelemetry-java/issues/5105#issuecomment-1739237240).
Specifically, this PR adds the implementation of `MemoryMode` for the synchronous instrument: counter.
This PR adds support for Memory mode for Last Value Aggregation. It contains:
* Using a reusable point for returning the result on `doAggregateThenMaybeReset` for both `LongLastValueAggregator.Handle` and `DoubleLastValueAggregator.Handle`.
* Adding matching garbage collection benchmark tests
* Adjusting and adding tests for `LongLastValueAggregator` and `DoubleLastValueAggregator`
=> Memory mode: Adding support for synchronous instruments - Last Value aggregation

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Add a check to ensure that calling `Span.setStatus()` will do nothing if StatusCode.OK has previously been set on the Span.
Add a unit test to ensure this functionality is/remains correct.
Should fix #6207
=> #6207 Ensure Span Status Cannot Be Updated After StatusCode.OK Is Set

.github/workflows/build.yml, docs/apidiffs/current_vs_latest/opentelemetry-exporter-zipkin.txt, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/InstrumentGarbageCollectionBenchmarkTest.java, sdk/metrics/src/jmhBasedTest/java/io/opentelemetry/sdk/metrics/internal/state/TestInstrumentType.java
Fixes #6211
- Adds more leniency towards tests, has fewer options to "mess" them and lower the allocation rate, and is more prone to have a variable allocation rate.
- Constraints the InstrumentGarbageCollectionBenchmarkTest to run only in one specific environment out of the entire matrix
=> Fix flaky InstrumentGarbageCollectionBenchmarkTest

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Most spans don't have events [citation needed].  So, fault it in like `attributes` and `links` rather than waste time/GC thrash allocating the storage for them.
=> Fault in SdkSpan.events

CHANGELOG.md, buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts, docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure.txt, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java
Nit: `AutoConfiguredOpenTelemetrySdkBuilder.addLogRecordProcessorCustomizer` returned base type `AutoConfigurationCustomizer` instead of impl one breaking the return chaining.
```java
sdkBuilder
.addLogRecordProcessorCustomizer((processor, props) -> ...)
.build() // not found :(
```
This PR fixes the return type.
=> Return AutoConfiguredOpenTelemetrySdkBuilder instead of the base type

api/events/src/main/java/io/opentelemetry/api/events/DefaultEventEmitterProvider.java, api/events/src/main/java/io/opentelemetry/api/events/EventEmitter.java, api/events/src/main/java/io/opentelemetry/api/events/EventEmitterBuilder.java, api/events/src/test/java/io/opentelemetry/api/events/DefaultEventEmitterProviderTest.java, api/events/src/test/java/io/opentelemetry/api/events/DefaultEventEmitterTest.java, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventEmitterProvider.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventEmitterProviderTest.java
See https://github.com/open-telemetry/semantic-conventions/pull/473 for details. The events working group has combined the `event.name` and `event.domain` by just having dot-separated prefixes on event names. This updates the API to match that expectation.
=> Remove domain from event api.

RELEASING.md
An organization wide `CODECOV_TOKEN` [was added](https://github.com/open-telemetry/community/issues/1926) removing the need for us to use my personal token.
I've removed the secret from the repository settings and this PR removes references to it from our docs.
=> Use shared CODECOV_TOKEN

exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingMetricExporter.java
Was looking over some code with a user, and we noticed that this word was wrong, probably just copypasta from the tracing version.
=> Fix copypasta artifact

sdk-extensions/autoconfigure/README.md
=> Update jaeger autoconfigure docs to point to OTLP

buildSrc/build.gradle.kts
You cannot build unless java17 is installed, see https://github.com/open-telemetry/opentelemetry-java/blob/main/buildSrc/build.gradle.kts#L69
=> Check for Java 17 toolchain and fail if not found

docs/apidiffs/current_vs_latest/opentelemetry-sdk-logs.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessor.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessor.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessorTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessorTest.java
Originally discussed in this [comment](https://github.com/open-telemetry/opentelemetry-java/pull/5986#discussion_r1412295799), the idea is to make `AutoConfigurationCustomizer#addSpanProcessorCustomizer` more useful by allowing you to extract the configured SpanExporter/LogRecordExporter from the processor, and plug it into your own processor.
```
autoConfiguration.addSpanProcessorCustomizer(
(spanProcessor, configProperties) -> {
if (spanProcessor instanceof BatchSpanProcessor) {
SpanExporter exporter = ((BatchSpanProcessor) spanProcessor).getExporter();
return new MyCustomProcessor(exporter);
}
return spanProcessor;
});
```
=> Add get{Signal}Exporter methods to Simple{Signal}Processor, Batch{Signal}Processor

.github/workflows/benchmark-tags.yml, .github/workflows/benchmark.yml, .github/workflows/build.yml, .github/workflows/codeql-daily.yml, .github/workflows/owasp-dependency-check-daily.yml, .github/workflows/release.yml
See <https://github.com/gradle/gradle-build-action/blob/main/README.md>:
> As of `v3` this action has been superceded by `gradle/actions/setup-gradle`.
> Any workflow that uses `gradle/gradle-build-action@v3` will transparently delegate to `gradle/actions/setup-gradle@v3`.
>
> Users are encouraged to update their workflows, replacing:
> ```
> uses: gradle/gradle-build-action@v3
> ```
>
> with
> ```
> uses: gradle/actions/setup-gradle@v3
> ```
>
> See the [setup-gradle documentation](https://github.com/gradle/actions/tree/main/setup-gradle) for up-to-date documentation for `gradle/actions/setup-gradle`.
=> migrate gradle/gradle-build-action to gradle/actions/setup-gradle

api/incubator/src/main/java/io/opentelemetry/api/incubator/events/DefaultEventLogger.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/events/EventBuilder.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/events/EventLogger.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/logs/AnyValue.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/logs/AnyValueArray.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/events/DefaultEventLoggerProviderTest.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/events/DefaultEventLoggerTest.java, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FullConfigTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventLoggerProvider.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventBuilderTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventLoggerProviderTest.java
Reflects changes in https://github.com/open-telemetry/opentelemetry-specification/pull/3772 and https://github.com/open-telemetry/opentelemetry-specification/pull/3749.
Previously attempted in #6001.
Summary of changes:
- Restructure API to put payload into log record AnyValue body. There are now a series of `put(String key, ? value)` types added which add information to the body. The spec currently [seems to be thinking](https://github.com/open-telemetry/semantic-conventions/issues/505) that fields in an event body are _not_ attributes. Because of this, there are not overloads for put which accept the attributes.
- You can still set attributes on an event via `setAttributes`. 
- You can now explicitly set the timestamp, context, and severity. Severity defaults to `INFO=9`.
Usage example …
=> Refactor Event API to reflect spec changes

CONTRIBUTING.md, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleExplicitBucketHistogramAggregator.java
Was doing some analysis and noticed a small amount of allocations occurring when recording to explicit bucket histogram.
Tracked it down and determine that ReentrantLock actually performs some small amount of allocations for synchronization. See the screenshot below from my profiler. Replaced it with the `synchronized` keyword and the allocations went away. Also noticed a modest increase in performance.
Before
```
Benchmark                                                            (aggregation)                (valueGen)  Mode  Cnt      Score       Error   Units
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10  36837.809 ± 14387.103   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate …
```
=> Use synchronized instead of reentrant lock in explicit bucket histogram

.github/repository-settings.md, settings.gradle.kts
Notes on migration from gradle enterprise to develocity: https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration
Updated secrets to include current value of `GRADLE_ENTERPRISE_ACCESS_KEY` in `DEVELOCITY_ACCESS_KEY`
=> Move away from deprecated gradle enterprise APIs

api/all/src/main/java/io/opentelemetry/api/metrics/Meter.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/SdkMeterTest.java
This came up in a real-world situation where the instrument name was failing for a different reason, but contained a forward slash, leading us to believe that was the cause. This adds the forward slash as an allowable character to the log message, and is in keeping with [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-name-syntax).
=> Add forward slash to InstrumentName log message

docs/apidiffs/current_vs_latest/opentelemetry-sdk-trace.txt, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
=> Add ReadableSpan#getAttributes

sdk-extensions/autoconfigure/README.md, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/FileConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/FileConfigurationTest.java, sdk-extensions/incubator/README.md
Reflects naming in spec PR: https://github.com/open-telemetry/opentelemetry-specification/pull/3948
The `experimental` prefix in the name makes it clear to users that the behavior of how file configuration is subject to breaking changes.
This PR removes support for `otel.config.file`. If it is set, we log a warning.
=> Rename otel.config.file to otel.experimental.config.file

api/incubator/src/main/java/io/opentelemetry/api/incubator/events/EventBuilder.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/events/DefaultEventLoggerTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/internal/SdkEventLoggerProviderTest.java
Event payload fields seem to be different than attributes: https://github.com/open-telemetry/semantic-conventions/issues/505
That's expected to some degree, since attribute types are limited to primitives and arrays of primitives, and event payloads are intended to be able to encode complex structured data, like bytes, object arrays, and maps of maps. But excluding `Attributes` / `AttributesKey<?>` from the event payload API surface area seems odd, given how prevalent Attributes are in the other APIs.
What happens if I want to include an attribute generated from [semantic-conventions-java](https://github.com/open-telemetry/semantic-conventions-java) in my payload? Am I prohibited from doing that? Do I need to call `put(AttributeKey.getKey(), value)` to extract the string attribute key and …
=> Add put(AttributeKey<T>, T) overload to EventBuilder

docs/apidiffs/current_vs_latest/opentelemetry-sdk-metrics.txt, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterOkHttpSenderTest.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/all/src/testJdkHttpSender/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterJdkSenderTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MetricExporterFactoryTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/AggregationTemporalitySelector.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/DefaultAggregationSelector.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/AggregationTemporalitySelectorTest.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/DefaultAggregationSelectorTest.java
Add missing metric-specific fields to the OtlpHttpMetricExporter and OtlpGrpcMetricExporter toString():
- AggregationTemporalitySelector
- DefaultAggregationSelector
- MemoryMode
=> Add missing fields to OTLP metric exporters

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
Followup to #6304. PeriodicMetricReader already has locks in place which prevent concurrent reads and ensure safe access when memory mode is reusable, but PrometheusHttpServer needs an equivalent mechanism.
=> PrometheusHttpServer prevent concurrent reads when reusable memory mode

exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpHttpSender.java, sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java
Even though plain HTTP protocol is used for exporting, still security components (SSLContext, TrustManager, KeyManager) are initialized. Most of the time, this is not a problem other than adding some minor startup overhead. 
But there might be some cases that security components should not be initialized initially by OTEL Java agent. Here is a case which effects one of our customers:
- They have their own custom `KeyStoreSpi` implementation.
- They bundle their Spring application as executable jar, so artifact layout is customized for Spring's custom Launcher classloader.
- OTEL Java agent is initialized at startup and so creates exporters. But even though traces are sent to OTEL collector over plain HTTP, still some security components are initialized by OTEL Java agent at system …
=> Ignore TLS components (SSLContext, TrustManager, KeyManager) if plain HTTP protocol is used for exporting

opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/SpanConverter.java, opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/InteroperabilityTest.java
Fixes #5475.
The behavior of `spanBuilderWithRemoteParent` seems wrong right now. It adds a span link instead but does not set the span represented by the context argument to be the parent. Not sure why this is, but I can't find anything in the [opencensus compatibility spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md) which states that this is intended, so I'm going to assume its just a bug in the implementation.
=> Fix opencensus shim spanBuilderWithRemoteParent behavior

docs/apidiffs/current_vs_latest/opentelemetry-sdk-common.txt, sdk/all/src/test/java/io/opentelemetry/sdk/common/SystemClockTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/Clock.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/SystemClock.java, sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/ExemplarClockBenchmarks.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/ReservoirCell.java
Resolves #6403.
Introduces a new `Clock#now(boolean highPrecision)` overload, which uses a performance optimized millisecond precision when `highPrecision=false`. Updates `ReservoirCell` to obtain measurement times using `Clock#now(false)`, which shaves a good chunk of time off the time to record each exemplar (~50ns on my machine).
This has a greater impact the more frequent measurements are candidates to be stored in ReservoirCell. The savings are especially impactful for the histogram exemplar reservoir, where the algorithm requires us to take the last measurement for each bucket. This means we compute the time for every measurement recorded. 
Here's a benchmark output comparing the high precision and low precision `Clock#now` implementations. Benchmark run using `OpenJDK Runtime …
=> Use low precision Clock#now when computing timestamp for exemplars

exporters/otlp/common/src/jmh/java/io/opentelemetry/exporter/internal/otlp/MetricsRequestMarshalerBenchmark.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExemplarMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExemplarStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramBucketsMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramBucketsStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramDataPointStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ExponentialHistogramStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/GaugeStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/HistogramDataPointStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/HistogramStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/InstrumentationScopeMetricsStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/LowAllocationMetricsRequestMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/NumberDataPointMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/NumberDataPointStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ResourceMetricsStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/SumStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/SummaryDataPointStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/SummaryStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ValueAtQuantileMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/metrics/ValueAtQuantileStatelessMarshaler.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/LowAllocationMetricsRequestMarshalerTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/metrics/MetricsRequestMarshalerTest.java, exporters/otlp/common/src/test/java/io/opentelemetry/exporter/internal/otlp/traces/TraceRequestMarshalerTest.java
Continuation of https://github.com/open-telemetry/opentelemetry-java/pull/6410
```
Benchmark                                                                 Mode  Cnt     Score    Error   Units
MetricsRequestMarshalerBenchmark.marshalStateful                          avgt   10     1.013 ±  0.021   us/op
MetricsRequestMarshalerBenchmark.marshalStateful:gc.alloc.rate            avgt   10  3080.843 ± 62.442  MB/sec
MetricsRequestMarshalerBenchmark.marshalStateful:gc.alloc.rate.norm       avgt   10  3272.006 ±  0.001    B/op
MetricsRequestMarshalerBenchmark.marshalStateful:gc.count                 avgt   10    92.000           counts
MetricsRequestMarshalerBenchmark.marshalStateful:gc.time                  avgt   10    32.000               ms …
```
=> Low allocation OTLP metrics marshaler

exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/BoolAnyValueStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/DoubleAnyValueStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/IntAnyValueStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/StringAnyValueStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/InstrumentationScopeSpansStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/ResourceSpansStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanEventStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanLinkStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanStatelessMarshaler.java, exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/traces/SpanStatusStatelessMarshaler.java
Skipped the ones that are modified in https://github.com/open-telemetry/opentelemetry-java/pull/6429
=> Add private constructors for stateless marshalers

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java
=> change variable name

api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/all/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java
Resolves #2948 
> Someone will need to validate what the specification currently says about baggage keys and create a PR if we're not currently in compliance.
I confirmed it. (Thanks to some commenters.) Written [here](https://www.w3.org/TR/baggage/#key). This page is linked from [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#overview).
> Leading and trailing whitespaces (OWS) are allowed and are not considered to be a part of the key.
So if key consists of space-only, we should treat as null.
=> Restrict space-only keys

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Fixes #4488 
The changes I added to the Java convention plugin will remove the common sources of non-determinism from the project's jar files, namely file creation/modification dates stored in zip catalog metadata.
The net result is that for future releases, a user would be able to checkout a specific tag, rebuild the code locally and produce jars that are bitwise identical (matching checksums) to those releases available on Maven Central.
As for testing: I was able to test this by building the project twice in distinct folders, then spot-checking about ten of the jars (`sdk`, `api`, and `context` libraries plus their `-javadoc` and `-source` jars), and the `opentelemetry-sdk-trace-shaded-deps-1.39.0-SNAPSHOT-all.jar`. All had identical SHA1 checksums, which is the goal.
Please let me …
=> Normalize timestamps and file ordering in jars, making the outputs reproducible

dependencyManagement/build.gradle.kts, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverter.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusUnitsHelper.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverterTest.java
The Prometheus metrics library 1.3.x introduced stricter checks for Prometheus `UNIT` names, and it also added a new helper method `PrometheusNaming.sanitizeUnitName(name)` for creating compliant `UNIT` names.
This PR updates the dependency version of the Prometheus metrics library, and also calls the new sanitize method to make sure we don't create illegal Prometheus UNIT names.
=> Update the Prometetheus metrics library

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
Currently, the `PrometheusHttpServer` serves Prometheus metrics on _any_ endpoint:
* `/metrics`
* `/liveness`
* `/my/pets/123`
* `/`
* ...
This leads to issues (see #6071), and is uncommon in the Prometheus ecosystem.
For reference, I tested the default behavior of a couple of popular official Prometheus exporters:
* [node_exporter](https://github.com/prometheus/node_exporter)
* [blackbox_exporter](https://github.com/prometheus/blackbox_exporter)
* [mysqld_exporter](https://github.com/prometheus/mysqld_exporter)
The behavior of all of them is:
* The default handler `/*` serves a static HTML page with some info on the exporter, and with a link to `/metrics`
* The `/metrics` handler serves the metrics.
This is also the default behavior of the …
=> Make /metrics the only Prometheus metrics endpoint

api/incubator/src/main/java/io/opentelemetry/api/incubator/trace/ExtendedSpanBuilder.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/trace/ExtendedTraceApiUsageTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java
Ran into this when updating https://github.com/open-telemetry/opentelemetry-java-examples/pull/421
=> Narrow ExtendedSpanBuilder return types for chaining

exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java
Build on main is [broken](https://github.com/open-telemetry/opentelemetry-java/actions/runs/9651727315/job/26620265627) right now due to a change in the collector prometheus receiver logic from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32829
=> Fix CollectorIntegrationTest

exporters/prometheus/src/test/resources/otel-config.yaml, integration-tests/otlp/src/main/resources/otel-config.yaml
Build is currently broken. Example here: https://github.com/open-telemetry/opentelemetry-java/actions/runs/9765156950/job/26955207437
The [0.104.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.104.0) release of collector contrib remove support for the `$ENV_VAR` syntax, and removes exposing health check on `0.0.0.0` by default. This PR updates the few places we use the collector in testing to reflect those changes.
=> Fix build after recent collector release

.github/workflows/build.yml
This is to hopefully address issues that our release workflow PRs fail due to the diff file transitions: https://github.com/open-telemetry/opentelemetry-java/pull/655
=> Ignore the japicmp diff check for bot PRs

exporters/otlp/profiles/build.gradle.kts, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableAttributeUnitData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableFunctionData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableLabelData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableLineData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableLinkData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableLocationData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableMappingData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableProfileContainerData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableProfileData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableSampleData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableValueTypeData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LocationData.java
Second step towards supporting the new experimental signal type for profiling...
Following on from the interfaces in https://github.com/open-telemetry/opentelemetry-java/pull/6374 this adds the AutoValue generated implementation classes.  Less to discuss here, it's much more straightforward than the interfaces!
- Still no test coverage, since most of the code is auto generated anyhow. For other similar classes the test coverage is indirect via the Marshaler tests, which for these classes won't be along until the next PR. Meanwhile codecov will probably continue to sulk.
- The ByteBuffer use in ProfileContainerData presents a challenge. For other similar cases, the mutable object could be wrapped during the static create(...) call with e.g. Collections.unmodifiableList, such that the …
=> Add exporter data model impl for profiling signal type.

exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/logs/OtlpHttpLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/logs/OtlpGrpcLogRecordExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpLogRecordExporterProviderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpMetricExporterProviderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpSpanExporterProviderTest.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterOkHttpSenderTest.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterOkHttpSenderTest.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterTest.java, exporters/otlp/all/src/testDefaultSender/java/io/opentelemetry/exporter/otlp/traces/OtlpGrpcSpanExporterTest.java, exporters/otlp/all/src/testJdkHttpSender/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterJdkSenderTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcLogRecordExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcMetricExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/GrpcSpanExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpLogRecordExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpMetricExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/HttpSpanExporterBuilderWrapper.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/ManagedChannelTelemetryExporterBuilder.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/TelemetryExporterBuilder.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanImpl.java
Resolves #5641.
- Changes all `OtlpHttp{Signal}Exporter`s and `OtlpGrpc{Signal}Exporter`s to enable retry by default.
- Adds new `otel.java.exporter.otlp.retry.disabled` (defaults to false) property to superseed `otel.experimental.java.exporter.otlp.retry.enabled` (defaults to true). The old property will be retained for some time for backwards compatibility.
Context:
- OTLP retry has been around years in this project and the programmatic configuration has been stable since july 2023.
- My employer (New Relic) has recommended it for production use for that entire time without any reports of issues
- The [spec mandates](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#retry) retrying transient errors with a retry strategy. By …
=> Enable retry by default for OTLP exporters

exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsUtil.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/TlsUtilTest.java
fixes #6572
Instead of parsing the inputStream ourselves, we should let the underlying CertificateFactory implementation process it and return list of certificates.
=> Use generateCertificates() of CertificateFactory to process certificates

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/JsonSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/MarshalerUtil.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Serializer.java, exporters/otlp/common/build.gradle.kts, exporters/otlp/profiles/build.gradle.kts, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/AttributeUnitMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/FunctionMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LineMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LinkMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LocationMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/MappingMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ProfileMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/SampleMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ValueTypeMarshaler.java, exporters/otlp/profiles/src/test/java/io/opentelemetry/exporter/otlp/profiles/ProfilesRequestMarshalerTest.java
The third step towards support for the new experimental profiling OTLP signal type, following on from the data model interfaces and implementation.
These marshaler classes are somewhat verbose and very boilerplatey, but should not contain any surprises, being patterned largely on the existing marshalers for other signal types. The code is tedious to review, particularly to check the field names and data types correspond correctly to the proto file. I think I got all the cut and paste errors out, but then again I thought that on two previous occasions whilst checking it and proved myself wrong both times. Should probably have written a codegen tool instead, but hey, hindsight...
The classes here cover the payload,  pprofextended.proto  The PR is already a bit big, so the ones for the …
=> Add Marshalers for profiling signal type

CONTRIBUTING.md, README.md
Build is currently [broken](https://github.com/open-telemetry/opentelemetry-java/actions/runs/10206034704/job/28238079974?pr=6615) after https://github.com/open-telemetry/community/pull/2051 moved the community contributor guide.
=> Fix broken link to community contributing guide

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AdviceAttributesProcessor.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/view/AdviceAttributesProcessorTest.java
=> Avoid allocations when advice doesn't remove any attributes

exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java, exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptor.java, exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptorTest.java
Fixes #6587.
I figured out how to reliably reproduce the `java.net.ConnectException` from the issue by connecting an unused port on `localhost`. JdkHttpSender was already retrying on these, but OkHttpSender and OkGrpcSender were not.
Also added some overdue debug logging for the intermediate retry requests so users have a way of determining what is going on.
=> Retry ConnectException, add retry logging

CHANGELOG.md, sdk/common/src/main/java/io/opentelemetry/sdk/common/CompletableResultCode.java
Would like to get #6614 in for this release as well.
=> Prepare 1.41.0

exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java
=> supress zipkin exporters instrumentations

sdk-extensions/incubator/README.md
Fixes few broken markdown links that prevent jobs from executing properly in CI now that markdown lint has been enabled.
The targeted file was removed in https://github.com/open-telemetry/opentelemetry-specification/pull/4128.
Command to validate (copy-paste from what is executed in CI).
```
find . -type f \                                                                                                                                                                                                                                                                   git:(fix-broken-links)
-name '*.md' \
-not -path './CHANGELOG.md' \
| xargs .github/scripts/markdown-link-check-with-retry.sh
```
=> Fix broken markdown links

api/incubator/src/main/java/io/opentelemetry/api/incubator/trace/ExtendedSpanBuilder.java
Incubator API usage is demonstrated via java snippets, linked in the incubator readme: https://github.com/open-telemetry/opentelemetry-java/tree/main/api/incubator#api-incubator
This helps ensure the usage snippets continue to be correct as the experimental APIs evolve.
Generally, I'm not a fan of embedding usage examples in javadoc. I'd rather have standalone docs with embedded snippets which have good formatting and are properly contextualized, as I propose in this PR: https://github.com/open-telemetry/opentelemetry.io/pull/4966
=> Remove outdated ExtendedSpanBuilder javadoc example

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/internal/SpiHelper.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ResourceFactory.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ResourceFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/component/ResourceComponentProvider.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/component/ResourceOrderedFirstComponentProvider.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/component/ResourceOrderedSecondComponentProvider.java, sdk-extensions/incubator/src/test/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.internal.ComponentProvider
Related to #6574.
In the issue, I said this about resources:
> For resources, should likely add support for ResourceProvider instead of loading via ComponentProvider since ResourceDeteector is already a first class concept in the specification, and ResourceProvider is the java implementation of ResourceDetector.
I had a change of heart in the implementation. Implementations of ResourceProvider expect to be participating in a configuration scenario which is based on the env var / system property configuration scheme. They receive a ConfigProperties instead of the StructuredConfigProperties used in file config, and look for things in it like `otel.resource.attributes` and `otel.service.name` to influence their behavior. 
Instead, in this PR I use `ComponentProvider` to provide resource …
=> Add file configuration ComponentProvider support for resources

docs/apidiffs/current_vs_latest/opentelemetry-sdk-testing.txt, sdk/testing/build.gradle.kts, sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj/LogRecordDataAssert.java, sdk/testing/src/test/java/io/opentelemetry/sdk/testing/assertj/LogAssertionsTest.java
I couldn't find a great way (without casting to `AnyValueBody`) for users to do assertions around `LogRecordData` bodies, specifically for writing tests involving Events. This seemed like a pretty low-impact way to add some testability.
=> Add asserts for event body fields

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java
This allows the tracer to become enabled and disabled dynamically (though only by reflection at this stage). Doing just this change allows downstream agent distros to play around with APIs that would best work while not yet changing anything public in the SDK
Without this change, testing downstream is still possible but much more effortful
=> make SdkTracer.tracerEnabled mutable

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/ComponentProvider.java, sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/FileConfiguration.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlStructuredConfigProperties.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlStructuredConfigPropertiesTest.java
Resolves #6574.
Little things discovered implementing https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1440.
=> Declarative configuration missing pieces

api/all/build.gradle.kts, api/all/src/test/java/io/opentelemetry/api/OpenTelemetryTest.java, api/all/src/test/java/io/opentelemetry/api/logs/DefaultLoggerTest.java, api/all/src/test/java/io/opentelemetry/api/metrics/DefaultMeterTest.java, api/all/src/test/java/io/opentelemetry/api/trace/DefaultTracerTest.java, api/incubator/build.gradle.kts, api/incubator/src/test/java/io/opentelemetry/api/incubator/ExtendedOpenTelemetryTest.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/logs/ExtendedDefaultLoggerTest.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/metrics/ExtendedDefaultMeterTest.java, api/incubator/src/test/java/io/opentelemetry/api/incubator/trace/ExtendedDefaultTracerTest.java, api/testing-internal/build.gradle.kts, api/testing-internal/src/main/java/io/opentelemetry/api/testing/internal/AbstractDefaultLoggerTest.java, api/testing-internal/src/main/java/io/opentelemetry/api/testing/internal/AbstractDefaultMeterTest.java, api/testing-internal/src/main/java/io/opentelemetry/api/testing/internal/AbstractDefaultTracerTest.java, api/testing-internal/src/main/java/io/opentelemetry/api/testing/internal/AbstractOpenTelemetryTest.java, settings.gradle.kts
Resolves #6693.
Will need to publish in 1.42.1 patch release.
=> Stop publishing test fixtures with opentelemetry-api

exporters/prometheus/src/test/resources/otel-config.yaml, integration-tests/otlp/src/main/resources/otel-config.yaml, perf-harness/src/test/resources/otel-collector-config-perf.yaml, sdk/trace/src/jmh/resources/otel.yaml
This exporter has been replaced by the debug exporter and will be removed soon
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037
=> tests: update references to logging exporter

extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/Common.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java, extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/OtTracePropagatorTest.java
OtTracePropagator drops the parent context if spanId is shorter than 16 bytes while checking [spanContext.isValid()](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java#L57) . There can be cases when the spanId is 15 bytes and these id's should be padded with 0's to avoid losing parent trace/span. The pr applies this fix.
Example screenshot
=> Fix ottracepropagation for short span ids

sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/EmptyStructuredConfigProperties.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/StructuredConfigProperties.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlStructuredConfigPropertiesTest.java
Add `StructuredConfigProperties.getStructured(String, StructuredConfigProperties)` method to assist with walking trees without null checking. Originated from this [conversation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12265#discussion_r1771964764).
=> Add getStructured default method, add empty StructuredConfigProperties

api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java, api/all/src/main/java/io/opentelemetry/api/baggage/ImmutableBaggage.java, api/all/src/main/java/io/opentelemetry/api/baggage/propagation/Parser.java, api/all/src/test/java/io/opentelemetry/api/baggage/BaggageTest.java, api/all/src/test/java/io/opentelemetry/api/baggage/ImmutableBaggageTest.java, docs/apidiffs/current_vs_latest/opentelemetry-api.txt
Resolves #6729.
This prevents users from having to go through `asMap()` in order to fetch the metadata for a given `BaggageEntry`.
=> Adds Baggage.getEntry(String key)

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/FileConfigurationCreateTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogRecordExporterFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogRecordProcessorFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LoggerProviderFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MeterProviderFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MetricExporterFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MetricReaderFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanExporterFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanProcessorFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/TracerProviderFactoryTest.java
This comment from the code explains the motivation behind this:
>  NOTE: The default OTLP protocol is different for declarative config than for env var / system property based config. This is intentional. OpenTelemetry changed the default protocol recommendation from grpc to http/protobuf, but the autoconfigure's env var / system property based config did not update to reflect this before stabilizing, and changing is a breaking change requiring a major version bump. Declarative config is not yet stable and therefore can switch to the current default recommendation, which aligns also aligns with the behavior of the OpenTelemetry Java Agent 2.x+.
=> Set declarative config default OTLP protocol to http/protobuf

RELEASING.md
Per conversations in #6799 and #6809, add reminders in release notes about updating opentelemetry.io website.
cc @breedx-splk, @jaydeluca
=> Add note about updating autoconfigure docs when releasing

exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/logs/OtlpStdoutLogRecordExporterComponentProvider.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/metrics/OtlpStdoutMetricExporterComponentProvider.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/traces/OtlpStdoutSpanExporterComponentProvider.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/ConsoleLogRecordExporterComponentProvider.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/ConsoleMetricExporterComponentProvider.java, exporters/logging/src/main/java/io/opentelemetry/exporter/logging/internal/ConsoleSpanExporterComponentProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpLogRecordExporterComponentProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpMetricExporterComponentProvider.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpSpanExporterComponentProvider.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/internal/PrometheusComponentProvider.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/internal/ZipkinSpanExporterComponentProvider.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/internal/B3ComponentProvider.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/internal/B3MultiComponentProvider.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/internal/JaegerComponentProvider.java, extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/internal/OtTraceComponentProvider.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/ComponentProvider.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java, sdk-extensions/incubator/README.md, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ResourceFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlStructuredConfigProperties.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlStructuredConfigPropertiesTest.java
Reflects the naming of this project in the spec: https://opentelemetry.io/docs/specs/otel/configuration/#declarative-configuration
=> Rebrand file configuration to declarative configuration in documentation

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtilTest.java
The OpenTelemetry java agent switched the default OTLP protocol from `grpc` to `http/protobuf` in the 2.0 release. This is misaligned with the autoconfigure default, which is stuck with the protocol being `grpc` until a major version bump, which there are no plans for.
This causes confusion for users.
To relieve some of the confusion, this PR adds logging when the the endpoint port is not aligned with version of the protocol. I.e. log when port is 4318 and protocol is grpc, or when port is 43117 and protocol is http/protobuf.
Thanks to @laurit for the recommendation.
=> Log a warning if OTLP endpoint port is likely incorrect given the protocol

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
I kept `otel.experimental.resource.disabled.keys` for backwards compatibility and promoted them to a newer stabilized version as `otel.resource.disabled.keys`. Please take a look and let me know if this looks good. This resolves [6777](https://github.com/open-telemetry/opentelemetry-java/issues/6777)
=> Stabilizing `otel.experimental.resource.disabled.keys`

exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java, exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java
- #6780
Changes:
- Added a condition to trigger retries based on retryable gRPC status codes, even when the HTTP status is not 200.
Impact:
This fix ensures that gRPC requests are retried according to policy when encountering transient 503 errors, enhancing resilience in case of temporary unavailability.
=> Fix gRPC Retry Mechanism for Unsuccessful HTTP Responses

api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java, api/all/src/test/java/io/opentelemetry/api/internal/ConfigUtilTest.java, sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/DefaultConfigProperties.java
Resolves #6732.
Builds on #6746.
=> Fix ConfigUtil#getString ConcurrentModificationException

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/CodedOutputStream.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/JsonSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/MarshalerUtil.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Serializer.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ProfileContainerMarshaler.java
The marshaling utility code has not previously needed to support encoding of ByteBuffer type fields, as they are not used by any existing protocol. With the creation of the new experimental profiling signal type, that changes.
https://github.com/open-telemetry/opentelemetry-java/pull/6680 adds support for marshaling the new signal, but converts the ByteBuffer field into byte[] first, which is not ideal. To allow the ByteBuffer to be passed directly to the serialization code, we add support through Serializer and MarshalerUtil. The bulk of the change is in CodedOutputStream, the upstream protobuf version of which has ByteBuffer support already, so this is really just reinstating it in the fork.
In so doing, I've opted to keep the data handling behaviour based on 'buffer capacity, not …
=> Add ByteBuffer field type marshaling support to exporter.

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Marshaler.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/writer/StreamJsonWriter.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/AbstractOtlpStdoutExporterTest.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/internal/writer/StreamJsonWriterTest.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusMetricReaderTest.java
fixes https://github.com/open-telemetry/opentelemetry-java/issues/6836
=> bugfix: add newline in stdout exporter

custom-checks/src/main/java/io/opentelemetry/gradle/customchecks/OtelInternalJavadoc.java, custom-checks/src/test/resources/io/opentelemetry/gradle/customchecks/internal/InternalJavadocPositiveCases.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/LoggerConfig.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/internal/SdkEventLoggerProvider.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/MeterConfig.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/SdkMeterProviderUtil.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/SdkTracerProviderUtil.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/TracerConfig.java
Added the javadoc boilerplate internal comment v2 for experimental classes for the issue below.
https://github.com/open-telemetry/opentelemetry-java/issues/6662
=> Add javadoc boilerplate internal comment v2 for experimental classes

sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessor.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java
=> Add synchronization to SimpleLogRecordProcessor and SimpleSpanProcessor to ensure thread-safe export of logs and spans respectively

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Marshaler.java, exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/internal/writer/LoggerJsonWriter.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/internal/writer/LoggerJsonWriterTest.java
See this comment for explanation: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1551#discussion_r1849064365
=> Rename Marshaler#writeJsonToGenerator to allow jackson runtimeOnly dependency

buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts
Not sure why this was needed, but javadoc links seems to be fine
=> Remove outdated commented out code

exporters/common/build.gradle.kts, exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/UnsafeString.java, exporters/common/src/testWithoutUnsafe/java/io/opentelemetry/exporter/internal/marshal/StatelessMarshalerUtilTest.java
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/6913
=> Fix missing unsafe available check

buildSrc/src/main/kotlin/otel.japicmp-conventions.gradle.kts
Was supposed to delete this after 1.36.0 😬
=> Remove japicmp special case

api/all/src/main/java/io/opentelemetry/api/baggage/package-info.java, api/all/src/main/java/io/opentelemetry/api/trace/package-info.java
We have no plans to add code examples to our `package-info.java` files.
=> Remove outdated TODOs

sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/AggregationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/AttributeListFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/FileConfiguration.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/LogRecordProcessorFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MeterProviderFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/MetricReaderFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ResourceFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanLimitsFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SpanProcessorFactory.java
Improving readability by replacing FQCN with qualified imports after #6721.
=> Declarative config: more qualified imports

exporters/otlp/common/build.gradle.kts, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/ValueBodyTest.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java, sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/IdentityTest.java, sdk/testing/build.gradle.kts
Low hanging fruit I noticed working #6944.
=> Remove unused dependencies, cleanup code after stability

sdk/common/src/main/java/io/opentelemetry/sdk/common/CompletableResultCode.java, sdk/common/src/test/java/io/opentelemetry/sdk/common/CompletableResultCodeTest.java
Relates to this comment: https://github.com/open-telemetry/opentelemetry-android/pull/709#discussion_r1887250785
This is useful when chaining result codes and wanting to not lose an existing throwable. It was completely valid before, but it wasn't documented.
=> Explicitly allow null into CompletableResultCode.failExceptionally()

docs/apidiffs/current_vs_latest/opentelemetry-api.txt, docs/apidiffs/current_vs_latest/opentelemetry-sdk-logs.txt, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ReadWriteLogRecord.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkReadWriteLogRecord.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/ReadWriteLogRecordTest.java
Resolves #6895.
To maintain binary compatibility, default implementations were provided.
=> Add getters/accessors for readable fields in ReadWriteLogRecord.

exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/Serializer.java, exporters/common/src/test/java/io/opentelemetry/exporter/internal/marshal/MarshalerTest.java
Resolves #6946, #6916.
@laurit interested in your thoughts on this as well, since its about the stateless marshalers.
=> Ensure Serializer runtime exceptions are rethrown as IOException

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Resolves #6797.
Supersedes #6808.
=> Fix span setStatus

exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractGrpcTelemetryExporterTest.java, exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpHttpSender.java, exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterBuilder.java, exporters/zipkin/src/test/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporterTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java
Implementation of spec PR: https://github.com/open-telemetry/opentelemetry-specification/pull/4331
Supersedes #6850.
=> Interpret timeout zero value as no limit

exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/internal/data/ImmutableProfileData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LocationData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LocationMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ProfileData.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ProfileMarshaler.java, exporters/otlp/profiles/src/test/java/io/opentelemetry/exporter/otlp/profiles/ProfilesRequestMarshalerTest.java
Use List<AttributeKeyValue<?>> rather than Attributes, as the latter's map semantics are not appropriate for all use cases of the Profile.attribute_table field in the wire message.
=> Improve profiles attribute table handling

exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptor.java, exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptorTest.java, sdk/common/src/main/java/io/opentelemetry/sdk/common/export/RetryPolicy.java
Reflects discussion [here](https://github.com/open-telemetry/opentelemetry-java/pull/6991#issuecomment-2578647610).
- Expand to retry on all SocketTimeoutExceptions, instead of looking for specific messages.
- Expand to retry on UnknownHostException
This brings OkHttp more in line with JdkHttpSender, which retries [on any IOException except SSLException](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java#L306).
=> Expand OkHttp retry exception predicate

sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfigurationTest.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/LogLimitsBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorBuilder.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/LogLimitsTest.java, sdk/logs/src/test/java/io/opentelemetry/sdk/logs/export/BatchLogRecordProcessorTest.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanLimitsBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/config/SpanLimitsTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorTest.java
Addresses the issue mentioned #7024.
=> Follow spec on span limits, batch processors

sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ExtendedSdkTracer.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/SdkTracerProviderUtil.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerProviderTest.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkTracerTest.java, sdk/trace/src/testIncubating/java/io/opentelemetry/sdk/trace/TracerConfigTest.java
per discussion [here](https://github.com/open-telemetry/opentelemetry-java/pull/6899#issuecomment-2518772100) from [PR](https://github.com/open-telemetry/opentelemetry-java/pull/6899)
=> add SdkTracerProvider.setScopeConfigurator() and support

exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptor.java, exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptorTest.java
Extended the default predicate as mentioned here https://github.com/open-telemetry/opentelemetry-java/pull/6991#issuecomment-2585209126
=> Expand OkHttp default retry exception predicate with SocketException

docs/apidiffs/current_vs_latest/opentelemetry-sdk-extension-autoconfigure.txt, sdk-extensions/autoconfigure/build.gradle.kts, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/EnvironmentResourceProvider.java, sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
Based on this [comment](https://github.com/open-telemetry/opentelemetry.io/pull/6100#discussion_r1932881125).
Users need to reference the FQCN when setting `otel.java.enabled.resource.provider` and `otel.java.disabled.resource.provider`. Having `.internal.` in the package name of such a prominent resource provider isn't a good look, so let's promote `EnvironmentResourceProvider` to part of the public API.
=> Promote EnvironmentResourceProvider to public API

.github/workflows/ossf-scorecard.yml
It looks like OSSF Scorecard code scanning is already being run externally (I didn't realize they were doing this): https://securityscorecards.dev/viewer/?uri=github.com/open-telemetry/opentelemetry-java
But this PR will make it run from this repo and also report individual issues under the Security tab in GitHub.
Related to #7068
=> Add OSSF Scorecard code scanning

.github/workflows/gradle-wrapper-validation.yml
This is why OSSF Scorecard Binary-Artifacts score is only 9/10.
Related to #7068
=> Always run gradle wrapper validation

.github/renovate.json5
After this, Renovate should send a PR to start pinning github actions and docker images.
Because of the resulting increase in Renovate PRs for ever github action minor version, I followed the instrumentation repo where we group the updates and limit them to once a week.
Related to https://github.com/open-telemetry/opentelemetry-java/issues/7068
Marked as draft for now because it's better to merge #7074 first.
=> Renovate best practices

.github/repository-settings.md
I will implement if you approve
=> Convert branch protections to rule sets

.github/repository-settings.md, .github/workflows/owasp-dependency-check-daily.yml, .github/workflows/reusable-workflow-notification.yml
Resolves #7075
Please merge #7095 first, I'll need to rebase this and resolve a merge conflict between the two afterwards.
=> Fix OWASP dependency check workflow

custom-checks/build.gradle.kts
Resolves #7125.
See another example of where we disable `dependencyCheck` on test code: https://github.com/open-telemetry/opentelemetry-java/blob/main/integration-tests/otlp/build.gradle.kts#L46-L49
=> Disable owasp dependency check on :custom-checks

exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterBuilderUtil.java, exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/AbstractOtlpStdoutExporterTest.java
The new `otel.java.exporter.memory_mode` has been available sine 1.44.0, and there have been 3 minor releases since.
=> Remove support for otel.java.experimental.exporter.memory_mode

sdk/common/src/main/java/io/opentelemetry/sdk/internal/AttributesMap.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java, sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanTest.java
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/7135
=> Fix bug preventing accurate reporting of dropped attribute count

sdk/common/src/main/java/io/opentelemetry/sdk/internal/ThrottlingLogger.java, sdk/common/src/test/java/io/opentelemetry/sdk/internal/ThrottlingLoggerTest.java
After I stopped the otel collector, the program injected with agnet logged errors. The error logs were printed very frequently. I saw that the source code had already limited the flow of printing logs, but it was not as expected once a minute, but still five times a minute. Then I checked the code and found that there was an error in the parameter assignment. After changing it, it ran OK.
Thanks for reviewing the PR! I appreciate your time and any feedback you can provide.
[application-log.txt](https://github.com/user-attachments/files/19006768/application-log.txt)
=> fix bug: throttledRateLimiter is not once per minute, but five times

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/SdkMeterProviderUtil.java
This API was promoted to the stable API in 1.44.0 but I forgot to remove the experimental method for setting: https://github.com/open-telemetry/opentelemetry-java/blob/3c71b798a5dc50d87e00698acfafc8d88f9e14fd/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/ViewBuilder.java#L110-L125
=> Remove obsolete SdkMeterProviderUtil#setCardinalitylimit API

exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcSenderConfig.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcSenderProvider.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporterBuilder.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpSenderConfig.java, exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpSenderProvider.java, exporters/sender/grpc-managed-channel/src/main/java/io/opentelemetry/exporter/sender/grpc/managedchannel/internal/UpstreamGrpcSenderProvider.java, exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderProvider.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderProvider.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpHttpSenderProvider.java
Related to #6718.
Reduces churn of the GrpcSenderProvider, HttpSenderProvider interfaces by extracting all config parameters into a carrier class, which can be extended with default implementations when new options are added.
#7152 would need to churn the API contract in order to accommodate the new `ExecutorService` parameter. Instead, because its built off of this PR, it can be done as a non-breaking change.
This will be important if we want to promote sender API to public as discussed in #6781.
=> Extract sender parameters to config carrier class

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java
The new property `otel.java.exporter.otlp.retry.disabled` was added in #6588 in 7/2024, so we're well past our ordinary timeline for supporting deprecated experimental properties, which is typically just 3 releases.
=> Remove support for otel.experimental.exporter.otlp.retry.enabled

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfigurationTest.java
Declarative config now has a [more expressive mechanism](https://github.com/open-telemetry/opentelemetry-configuration/pull/) for configuring cardinality limits, and there is no standard env var for this defined in the specification. Still, I don't think we should get rid of support for specifying cardinality limits via env vars / system properties. So let's stabilize `otel.experimental.metrics.cardinality.limit` as a java-specific property with name `otel.java.metrics.cardinality.limit`.
=> Stable cardinality limit property otel.java.metrics.cardinality.limit

exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java, exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptor.java, exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/RetryInterceptorTest.java
Adjusted the jitter calculation to improve the randomness and distribution of delays in the exponential backoff logic.
current implementation is not based on exponential backoff but more uses randomly generated numbers in range **(0, upperBound)** and only **upperBound** exponentially grows, so in some cases we generate relatively low delays for retries 
Also there was an existing link 
https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exponential-backoff in code to implementation of exponential backoff but actual source code was different
=> Refine delay jitter for exponential backoff

exporters/otlp/testing-internal/src/main/java/io/opentelemetry/exporter/otlp/testing/internal/AbstractHttpTelemetryExporterTest.java
Clean up noisy logs like https://github.com/open-telemetry/opentelemetry-java/actions/runs/14160997041/job/39666396016?pr=7229#step:6:1457, which started after a recent armeria version bump.
=> Remove armeria log decorator to clean up build logs

exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java, exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerTest.java
Resolve the issue mentioned https://github.com/open-telemetry/opentelemetry-java/issues/6013.
=> Authenticator added for PrometheusHttpServer

context/src/main/java/io/opentelemetry/context/Context.java, context/src/test/java/io/opentelemetry/context/ContextTest.java
Resolves the issue https://github.com/open-telemetry/opentelemetry-java/issues/6955.
=> Fix duplicated ExecutorService wrap

api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java, api/all/src/test/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagatorTest.java, context/src/main/java/io/opentelemetry/context/propagation/TextMapGetter.java, context/src/main/java/io/opentelemetry/context/propagation/internal/ExtendedTextMapGetter.java, context/src/test/java/io/opentelemetry/context/propagation/TextMapGetterTest.java, docs/apidiffs/current_vs_latest/opentelemetry-context.txt
Operation is now stable in the spec: https://github.com/open-telemetry/opentelemetry-specification/pull/4472
=> Promote getAll to TextMapGetter stable API

api/all/src/main/java/io/opentelemetry/api/common/ArrayBackedAttributesBuilder.java, api/all/src/main/java/io/opentelemetry/api/common/AttributesBuilder.java, api/all/src/main/java/io/opentelemetry/api/logs/DefaultLogger.java, api/all/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java, api/all/src/main/java/io/opentelemetry/api/trace/PropagatedSpan.java, api/all/src/main/java/io/opentelemetry/api/trace/Span.java, api/all/src/test/java/io/opentelemetry/api/common/AttributesTest.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/logs/ExtendedDefaultLogger.java, api/incubator/src/main/java/io/opentelemetry/api/incubator/logs/ExtendedLogRecordBuilder.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/DelegatingSpan.java, opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetryNoRecordEventsSpanImpl.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ExtendedSdkLogRecordBuilder.java, sdk/logs/src/main/java/io/opentelemetry/sdk/logs/SdkLogRecordBuilder.java, sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java
The underlying implementation already does a null check on both key and value.
I think it's useful to publicly allow nulls on values since they are often null and it's helpful if callers know they don't need to null check.
(I could see an argument to not allow nulls for keys, so I didn't add Nullable there.)
Fixes #4336
=> Clarify that AttributesBuilder.put allows nulls

README.md
Build link checking frequently fails on this link with a 403 ([example](https://github.com/open-telemetry/opentelemetry-java/actions/runs/14499462708/job/40675416367)). Hoping a change to the new host [documented here](https://github.com/softwaremill/maven-badges?tab=readme-ov-file#a-new-dns-address) resolves it.
Also considering: 
1. Removing the maven badge, but I like having a quick link to get to maven central
2. Excluding the link from build link checking
=> Update maven badge to new host

exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java, exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilderTest.java
=> Fix OTLP metric exporter toBuilder() loosing temporality

exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java, exporters/otlp/all/build.gradle.kts, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java, exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilderTest.java
I ran the build locally for the first time after merging #7255 and noticed a variety of issues:
- Instances where GlobalOpenTelemetry is not reset
- Tests export real data via OTLP without setting up an OTLP receiver, causing error logs
- Test mocks don't account for all the code paths, causing NPEs
Fixing things up here.
=> Fix Otlp*MetricExporterBuilderTests

javadoc-crawler/src/main/java/io/opentelemetry/javadocs/Artifact.java, javadoc-crawler/src/main/java/io/opentelemetry/javadocs/JavaDocsCrawler.java, javadoc-crawler/src/test/java/io/opentelemetry/javadocs/JavaDocsCrawlerTest.java
Expanding on @jaydeluca's javadoc crawler work from #7300 to crawl all groups we publish artifacts to:
- io.opentelemetry
- io.opentelemetry.instrumentation
- io.opentelemetry.contrib
- io.opentelemetry.semconv
- io.opentelemetry.proto
=> Update cralwer to crawl all io.opentelemetry.* groups

.github/workflows/reusable-markdown-link-check.yml
Fixes #7327 
* Add retry-wait-time to potentially help these errors too (10s backoff instead of 1s).
* Add max-concurrency 1 to follow what opentelemetry-java-instrumentation does to avoid these issues.
=> Avoid HTTP 429 errors

context/src/test/java/io/opentelemetry/context/ContextTest.java
I hate this, but I think it serves to clarify the current state of the context implementation. [See also](https://github.com/open-telemetry/opentelemetry-java/pull/2191#discussion_r535400360)...
=> Add test that shows how context keys are special

context/src/main/java/io/opentelemetry/context/LazyStorage.java
This change makes error messages use the existing `CONTEXT_STORAGE_PROVIDER_PROPERTY` constant to fix the name of the system property being slightly different.
This solves issue #7318
=> Fix context storage provider property name (#7318)

api/incubator/src/test/java/io/opentelemetry/api/incubator/config/InstrumentationConfigUtilTest.java, sdk-extensions/autoconfigure/src/testIncubating/java/io/opentelemetry/sdk/autoconfigure/DeclarativeConfigurationTest.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SdkConfigProvider.java
Related to https://github.com/open-telemetry/opentelemetry-configuration/pull/179
`SdkConfigProvider` class update is necessary to handle breaking change for `instrumentation` yaml node. This change was introduced in declarative config file format version 0.4
=> Handle instrumentation node changes in yaml config file format 0.4

build.gradle.kts
See this announcement: https://central.sonatype.org/news/20250326_ossrh_sunset/
and see this for the docs on this change https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central
The org has already been migrated, but a new user token will need to be generated and put into GH repo variables.
=> Update repos for sonatype central

sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGauge.java, sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongGauge.java
closes https://github.com/open-telemetry/opentelemetry-java/issues/7402
Rename argument from `increment` to `value` for set methods in `SdkLongGauge` and `SdkDoubleGauge`.
=> Update argument name for set(long value)

.github/workflows/benchmark-tags.yml, .github/workflows/benchmark.yml
TIL you can't target by runner name, only by labels, so I created a new label for this runner...
Follow-up to #7399
Related to https://github.com/open-telemetry/community/issues/2801
=> Fix benchmark workflows

.github/workflows/issue-management-feedback-label.yml
I tested this and "pull-request: write" is needed when the "issue" is a pull request
=> Fix workflow permission

README.md
Following @laurit's lead in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/14005
=> Update sonatype snapshot repo location

sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/DeclarativeConfigurationTest.java, sdk-extensions/autoconfigure/src/testIncubating/java/io/opentelemetry/sdk/autoconfigure/DeclarativeConfigurationTest.java, sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactory.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ServiceResourceDetector.java, sdk-extensions/incubator/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.internal.ComponentProvider, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/DeclarativeConfigurationCreateTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/DeclarativeConfigurationParseTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/OpenTelemetryConfigurationFactoryTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/ServiceResourceDetectorTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/fileconfig/YamlDeclarativeConfigPropertiesTest.java
Release notes here: https://github.com/open-telemetry/opentelemetry-configuration/releases/tag/v1.0.0-rc.1
Users of 0.4 _should not_ be impacted as this release consists of only a small set of backwards compatible changes.
=> Update to declarative config 1.0-rc.1

exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/AttributeUnitMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/FunctionMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LineMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LinkMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/LocationMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/MappingMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/SampleMarshaler.java, exporters/otlp/profiles/src/main/java/io/opentelemetry/exporter/otlp/profiles/ValueTypeMarshaler.java, exporters/otlp/profiles/src/test/java/io/opentelemetry/exporter/otlp/profiles/ProfilesRequestMarshalerTest.java
Fix 'repeated' (i.e. array of) element encoding on profile OTLP Marshalers and add test coverage.
=> profile exporters fix and test improvements

dependencyManagement/build.gradle.kts, exporters/otlp/all/build.gradle.kts, exporters/otlp/testing-internal/build.gradle.kts, exporters/sender/okhttp/build.gradle.kts, sdk-extensions/jaeger-remote-sampler/build.gradle.kts
This hopefully resolves #7491 
I ended up having to change `dependencyManagement/build.gradle.kts` because I was getting errors seeming to indicate the BOM wasn't working for the okhttp-jvm package.
I was getting:
```
* What went wrong:
Execution failed for task ':exporters:sender:okhttp:compileJava'.
> Could not resolve all files for configuration ':exporters:sender:okhttp:compileClasspath'.
> Could not find com.squareup.okhttp3:okhttp-jvm:.
Required by:
project :exporters:sender:okhttp
```
If there's a different way to handle that so we don't have to list out the bom and the okhttp-jvm dependencies in `dependencyManagement/build.gradle.kts` separately, let me know
=> Update okhttp dependency to okhttp-jvm

.github/workflows/benchmark.yml
I had a typo leading to:
```
/usr/bin/docker pull ubuntu-24.04
Using default tag: latest
Error response from daemon: pull access denied for ubuntu-24.04, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Docker pull failed with exit code 1
```
=> Fix benchmark container image

.github/renovate.json5, .github/workflows/build.yml, exporters/prometheus/src/test/java/io/opentelemetry/exporter/prometheus/CollectorIntegrationTest.java, integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java, perf-harness/src/test/java/io/opentelemetry/perf/OtlpPipelineStressTest.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/ExporterBenchmark.java, sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java
Pros:
- running tests locally use the same version as CI
- version is collocated in the test file
- easily extendable to other images (one extra line in the renovate configuration)
Cons:
- complex renovate rule
- requires scanning test files which are normally ignored by renovate
cc @zeitlinger
=> Alternate strategy for pinning collector images

animal-sniffer-signature/build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts, custom-checks/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, sdk-extensions/jaeger-remote-sampler/build.gradle.kts
=> Update to gradle v9

sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java, sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/ResourceConfigurationTest.java
8 months ago #7052 added backward compatibility support for the old `internal` fully qualified package class name of the `EnvironmentResourceProvider`. The comments indicated that we would remove this after 1.49.0, but it looks like that was overlooked.
The old full class name: `io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider`.
The current full class name going forward: `io.opentelemetry.sdk.autoconfigure.EnvironmentResourceProvider`.
=> Remove support for old EnvironmentResourceProvider package name.

.github/workflows/survey-on-merged-pr.yml
The Contributor Experience group created a survey to help understand challenges and feedback from new contributors. We have this survey running for a few months on opentelemetry.io and the JS repo, with helpful feedback, so now adding to more repos.
Example of message: https://github.com/open-telemetry/opentelemetry-js/pull/5884#issuecomment-3237568813
=> chore: add workflow for surveys of non-members

sdk-extensions/incubator/build.gradle.kts, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableAlwaysOffSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableAlwaysOnSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableParentThresholdSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableTraceIdRatioBasedSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/CompositeSampler.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ImmutableSamplingIntent.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/OtelTraceState.java, sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/SamplingIntent.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableAlwaysOffSamplerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableAlwaysOnSamplerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableParentThresholdSamplerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/ComposableTraceIdRatioBasedSamplerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/CompositeSamplerTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/OtelTraceStateFuzzTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/OtelTraceStateTest.java, sdk-extensions/incubator/src/test/java/io/opentelemetry/sdk/extension/incubator/trace/samplers/TestUtil.java
Fixes #7615 
This implements composite samplers as in the development spec
https://opentelemetry.io/docs/specs/otel/trace/sdk/#built-in-composablesamplers
https://opentelemetry.io/docs/specs/otel/trace/tracestate-probability-sampling/
The implementation is quite similar to the contrib one that was used to drive the OTEP, though the naming is updated to match what made it to the spec
https://github.com/open-telemetry/opentelemetry-java-contrib/tree/fc6507e5e24473fc4a131e3bda1d4b1156fe18c9/consistent-sampling/src/main/java/io/opentelemetry/contrib/sampler/consistent56
For reference, implementations for JS and Python
https://github.com/open-telemetry/opentelemetry-js/pull/5839
https://github.com/open-telemetry/opentelemetry-python/pull/4714
=> Add incubator implementation of composite sampling spec

.github/workflows/build.yml, sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/SunMiscProhibitedSecurityManagerTest.java
Java 25 should be available in our matrix soon, but in the meantime, looks like we missed Java 24 b/c Renovate auto-update isn't working (I'm looking into this separately, but wanted to get this updated in the meantime).
=> Add Java 24 to test matrix

settings.gradle.kts
This is same as instrumentation repo uses.
=> Add Gradle toolchain support so -PtestJavaVersion will automatically download Java version

sdk-extensions/autoconfigure/src/testFullConfig/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfigurationTest.java, sdk/trace-shaded-deps/src/main/java/io/opentelemetry/sdk/trace/internal/JcTools.java, sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/JcToolsSecurityManagerTest.java, sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/JcToolsTest.java
The `delayMs=0` tests seem to have a lot of variance, I've seen them fluctuate in both directions.
| Test Configuration | Main Branch (ops/s) | PR Branch (ops/s) | Difference | % Change |
|--------------------|--------------------|--------------------|------------|----------|
| delayMs=0, spanCount=1000 | 2,902.557 ±659.449 | 2,677.476 ±481.106 | -225.081 | **-7.8%** |
| delayMs=0, spanCount=2000 | 1,180.198 ±153.058 | 1,487.399 ±446.232 | +307.202 | **+26.0%** |
| delayMs=0, spanCount=5000 | 459.718 ±26.793 | 495.353 ±157.615 | +35.635 | **+7.8%** |
| delayMs=1, spanCount=1000 | 852.660 ±16.069 | 840.142 ±9.107 | -12.519 | **-1.5%** |
| delayMs=1, spanCount=2000 | 848.187 ±14.081 | 860.653 ±5.051 | +12.466 | **+1.5%** |
| delayMs=1, spanCount=5000 | 844.831 ±6.976 | 842.294 ±8.436 | …
=> Proactively avoid Unsafe on Java 23+

sdk/metrics/build.gradle.kts, sdk/trace/build.gradle.kts
@open-telemetry/android-approvers is this worrisome that removing these doesn't cause any failures?
=> Remove unnecessary(?) animalsniffer exclusions

sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/JcToolsSecurityManagerTest.java, sdk/trace-shaded-deps/src/test/java/io/opentelemetry/sdk/trace/internal/SunMiscProhibitedSecurityManagerTest.java
=> Better fix for security manager test on Java 24
